### ISSUE TITLE
Audio upload isn't working?

### ISSUE THREAD

**Issue by samohovets** [negezor/vk-io#102]
#### What version of `vk-io` are you using?
4.0.0-rc.1

#### What version of Node.js are you using?
10.6

#### What did you do?
Пытаюсь заливать аудио по ссылке таким образом:
```js
vk.upload.audio({source: { 
  value: '*моя_ссылка*.mp3',
  filename: 'audio.mp3',
  contentType: 'audio/mpeg'
 }, title: 'jebat', artist: 'opa'});
```
#### What was the actual result?
(node:4139) UnhandledPromiseRejectionWarning: APIError: Code №15 - Access denied: filename is incorrect
    at API.callMethod (/Users/igor/Projects/langbots/node_modules/vk-io/lib/index.js:1256:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)

В чём может быть проблема? Скачивал отдельно уже буфер и пробовал таким образом - та же ошибка.

**Comment by negezor** [comment]
Странно, у меня всё работает, попробуйте мой вариант:
```js
const audio = await vk.upload.audio({
	source: 'http://ronsen.org/purrfectsounds/purrs/chicken.mp3'
});

console.log('Audio', audio);
```

**Comment by samohovets** [comment]
У меня ваш вариант тоже работает!

Кажется всё ясно: **ВК не позволяет заливать слишком короткие файлы** (длительностью 0 секунд)

![image](https://user-images.githubusercontent.com/24735429/43481656-38b21972-950f-11e8-8198-d78f848696b4.png)

Закрыто, спасибо.
