### ISSUE TITLE
Ошибка двухэтапной авторизации

### ISSUE THREAD

**Issue by PetrKlassen** [negezor/vk-io#105]
После длительных повторов двухэтапной авторизации она перестала работать (Incorrect two-factor code). С другого аккаунта все так же работает. При учете, что ни разу не вылезла при этом капча, я подумал, что возможно ошибка на вашей стороне и во время двухэтапной аутентификации не обрабатывается капча (метод установлен). Вы не могли бы это проверить?

**Comment by negezor** [comment]
Есть вероятность что это со стороны ВКонтакте, можете запустить приложение с env `DEBUG=vk-io:auth`, тогда в ошибке будет не пустое свойство pageHtml, и отправьте HTML сюда или мне в [личные сообщения](https://vk.com/id195624402).
