### ISSUE TITLE
context.forwards возвращает неверные значения.

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#106]
Когда я отвечаю или пересылаю сообщения данные в массиве всегда пустые.

Code:
```
vk.updates.on('message', async(context, next) => {
	if (context.hasForwards) console.log(context.forwards);
});
```
Retun:
`[ { from_id: 0, fwd_messages: [] } ]`

И еще я нашел опечатку в документации
`Возвращает пересланные сообщение`

**Comment by negezor** [comment]
Всё по тому что нужно загружать полное сообщение, так как ВКонтакте для User Long Poll не отправляет нужный набор данных. Сделать это можно через `context.loadMessagePayload()`. И в чём именно опечатка?

**Comment by T1MOXA** [comment]
Спасибо попробую.
На счет опечатки - я полагаю что правильнее было написать пересланные сообщени**я**

**Comment by T1MOXA** [comment]
Кстати было бы не плохо добавить предупреждения при использовании методов требующих loadMessagePayload без вызова этого метода.

**Comment by T1MOXA** [comment]
UPD
Не помогло.
Теперь при проверке любого сообщения `context.hasForwards` возвращает `true`

Code:
```
vk.updates.on('message', async(context, next) => {
	context.loadMessagePayload().then(() => {
		console.log(`context.hasForwards = ${context.hasForwards}`);
		if (context.hasForwards) console.log(context.payload.fwd_messages);
	});
});
```
Return:
```
 context.hasForwards = true
 []

```

**Comment by negezor** [comment]
Какая версия библиотеки? Потому что у меня всё правильно отрабатывет.
```js
vk.updates.on('message', async (context, next) => {
	console.log('Before', context.payload.fwd_messages);
	console.log('hasForwards', context.hasForwards);
	console.log('forwards', context.forwards);

	await context.loadMessagePayload();

	console.log('After', context.payload.fwd_messages);
	console.log('hasForwards', context.hasForwards);
	console.log('forwards', context.forwards);

	await next();
});
```

**Comment by T1MOXA** [comment]
У меня немного устаревшая версия vk-io@4.0.0-rc.0
Сейчас обновлю и на новой проверю.

**Comment by T1MOXA** [comment]
Да, на новой версии все ок.
Спасибо.

Еще возник вопрос, как получить id пересланного сообщения ?

**Comment by T1MOXA** [comment]
Еще возник вопрос, как получить id пересланного сообщения ?

**Comment by negezor** [comment]
Никак, всё потому что эти сообщения отсутствуют в локальной копии.

**Comment by negezor** [comment]
А зачем для этого ID? Достаточно `from_id` и `text`. Насчёт локальной копии, у каждого пользователя ID чата начинается с 1 не просто так)
