### ISSUE TITLE
Можно ли проверить есть ли закрепленные посты в вк?

### ISSUE THREAD

**Issue by Jengas** [negezor/vk-io#107]
Здравствуйте! У меня назрел вопрос, возможно ли проверить есть ли у определенной группы закрепленный пост, чтобы при использовании

`
    const response = await vk.api.wall.get({
      owner_id: -151886840,
      count: 1,
      offset: 1
    });
`

можно было указывать offset 1 или 0 (Если нету закрепа)?

**Comment by negezor** [comment]
А что именно требуется? Если для проверки то можно просто указать `count: 1` и проверить на `is_pinned`.

**Comment by Jengas** [comment]
@negezor просто я не понимаю где получить параметр is_pinned к примеру у https://vk.com/dev/wall.get ничего нету

**Comment by negezor** [comment]
Вот так вполне можно:
```js
const response = await vk.api.wall.get({
	domain: 'mlbots',
	count: 1
});

const [post] = response.items;

console.log('isPonned', post.is_pinned === 1);
console.log('Post', post);
```
