### ISSUE TITLE
Updates.isGroup

### ISSUE THREAD

**Issue by alienvspredator** [negezor/vk-io#108]
В вашем коде вы выполняете подключение к Bots Long Poll API или к User Long Poll API отталкиваясь от параметров, установленных при инициализации.
```
const {
  pollingGroupId
} = this.vk.options;
const isGroup = pollingGroupId !== null;
```
Но можно сделать иначе. Метод `groups.getById?` без параметров, с ключом доступа сообщества, возвращает объект этого же сообщества, тогда как этот же метод с ключом доступа пользователя возвращает ошибку о пропущенном параметре group_ids.

**Comment by negezor** [comment]
А что мешает вам так поступить?)

**Comment by alienvspredator** [comment]
Ничего, это лишь предложение по улучшению.

**Comment by negezor** [comment]
Дело в том что это больше "магическое" API которое может позже перестать работать.

**Comment by alienvspredator** [comment]
Понял.

**Comment by alienvspredator** [comment]
Это не магическое API, об этом указано в документации к методу:
https://vk.com/dev/groups.getById
Описание метода следующее:
"Возвращает информацию о заданном сообществе или о нескольких сообществах."
Так же в описании параметров к методу ни один из параметров не является обязательным.
Это задокументированная возможность данного метода, просто описана немного не чётко.

**Comment by negezor** [comment]
Но это и называется "магическим" API.
