### ISSUE TITLE
bots longpoll

### ISSUE THREAD

**Issue by Jengas** [negezor/vk-io#109]
Здравствуйте! Поддерживает ли ваша библиотека bots longpoll? https://vk.com/dev/bots_longpoll
Если да, то есть ли на неё документация? (Желательно с примером кода)

**Comment by negezor** [comment]
Да поддерживает, примеры в examples, достаточно в опция просто установить [pollingGroupId](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/vk.md#%D0%9E%D0%BF%D1%86%D0%B8%D0%B8-polling-long-poll).

**Comment by negezor** [comment]
ID должен быть положительным числом. Мне кажется у токена нету доступа к сообщениям.

**Comment by Jengas** [comment]
Без указания id, бот спокойно работает

**Comment by negezor** [comment]
Какие у токена права?

**Comment by Jengas** [comment]
![image](https://user-images.githubusercontent.com/14033756/44534681-a54a2480-a6f8-11e8-91a2-18e139bedfaa.png)

**Comment by negezor** [comment]
Токен
![image](https://user-images.githubusercontent.com/9392723/44535179-2b8c5800-a745-11e8-921d-067f0dbb7cc2.png)
![image](https://user-images.githubusercontent.com/9392723/44535102-039cf480-a745-11e8-840c-44cc17bb8d2e.png)
В настройках включено так
![image](https://user-images.githubusercontent.com/9392723/44535251-4c54ad80-a745-11e8-9960-1d77876b48a1.png)
![image](https://user-images.githubusercontent.com/9392723/44535237-465ecc80-a745-11e8-95f4-7f6759413706.png)
И в итоге всё запускается и отвечает
![image](https://user-images.githubusercontent.com/9392723/44535314-6d1d0300-a745-11e8-8c5a-e0aedcd66a43.png)

**Comment by Jengas** [comment]
![image](https://user-images.githubusercontent.com/14033756/44535478-5dc49800-a6fa-11e8-8100-01204cea864f.png)
![image](https://user-images.githubusercontent.com/14033756/44535491-63ba7900-a6fa-11e8-8f5d-5fe1f146dcc3.png)
![image](https://user-images.githubusercontent.com/14033756/44535510-72a12b80-a6fa-11e8-8564-b1f9a47ee596.png)
![image](https://user-images.githubusercontent.com/14033756/44535518-7765df80-a6fa-11e8-993a-61e7f0c3191f.png)

**Comment by negezor** [comment]
Похоже требуется право управление сообществом
![image](https://user-images.githubusercontent.com/9392723/44535739-6c38a100-a746-11e8-9e45-acc33a5f8921.png)

**Comment by Jengas** [comment]
Хм, и в правду. Сработало. Спасибо! Кстати, я пытаюсь сейчас понять как используя VK-IO добавить Клавиатуру для ботов https://vk.com/dev/bots_docs_3. Я буду рад если будет решение от этого API

**Comment by negezor** [comment]
Уже давно [есть](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/buttons/keyboard.md), а так же [пример](https://github.com/negezor/vk-io/blob/master/examples/simple-keyboard-bot.js) :)

**Comment by Jengas** [comment]
Отлично! Спасибо большое за помощь!
