### ISSUE TITLE
Планируемые изменения в работе с сервисным ключом доступа.

### ISSUE THREAD

**Issue by fidlow** [negezor/vk-io#11]
Подробнее https://vk.com/dev/service_token

Как использовать сервисный ключ доступа?

**Comment by negezor** [comment]
В связи со скорым изменениями во ВКонтакте API, работа с ним будет примерно таким образом.
```javascript
'use strict';

const vk = new (require('vk-io'));

vk.setting({
	app: <appId>,
	key: <serverKey>
});

// Новая авторизация сменит предыдущий токен
vk.appAuth()
.then((token) => {
	// Токен можно сохранить, он вечный
	vk.setToken(token);

	// Теперь можно использовать методы secure.
	// Или с обновлением открытые методы
});
```

**Comment by fidlow** [comment]
Сейчас я в <serverKey> пишу Защищённый ключ приложения, я его меняю на Сервисный ключ доступа и все работает? Сервисный ключ доступа я так понимаю нельзя получить через OAuth, его можно лишь задать в настройках.

**Comment by negezor** [comment]
Я в примере выше показал как получить серверный ключ доступа или можно просто взять его в настройках приложения. Для получение сервисного ключа(токена) доступа необходимо `ID приложения` и `Защищённый ключ`. Сервисный ключ доступа который можно получить в настройках приложения, его нужно вставлять в токен.
