### ISSUE TITLE
TypeError: this.isBlock is not a function at GroupUserContext.get isExpired

### ISSUE THREAD

**Issue by Wixty** [negezor/vk-io#112]
#### What version of `vk-io` are you using?
npm 4.0.0-rc.1

#### What version of Node.js are you using?
v10.9.0

#### What did you do?
/** GroupUserContext */ context
context.isExpired ? ... : ...

#### What did you expect to happen?
true / false

#### What was the actual result?
TypeError: this.isBlock is not a function at GroupUserContext.get isExpired

**Comment by Wixty** [comment]
Фикс #111

**Comment by negezor** [comment]
Там ещё не всё исправлено, остальное я доделаю.
