### ISSUE TITLE
Субтип обновления группы

### ISSUE THREAD

**Issue by Wixty** [negezor/vk-io#113]
#### What version of `vk-io` are you using?
v4.0.0-rc.2

#### What version of Node.js are you using?
v10.10.0

#### What did you do?
```
/* @type GroupUpdateContext */
// context.subTypes === [ 'group_update_photo' ]
context.isChangePhoto ? ...
```

#### What did you expect to happen?
true

#### What was the actual result?
false

---

В `GroupUpdateContext` геттеры `isChange*` проверяют `subType` на наличие `group_change_*`
https://github.com/negezor/vk-io/blob/c3ef6b7e34401e06dc284cd156d7cee3770ffc7e/src/structures/contexts/group-update.mjs#L41-L43

Но в конструкторе `subType` устанавливается, как `group_update_*`
https://github.com/negezor/vk-io/blob/c3ef6b7e34401e06dc284cd156d7cee3770ffc7e/src/structures/contexts/group-update.mjs#L26-L33

**Comment by negezor** [comment]
Исправил, https://github.com/negezor/vk-io/commit/a313f1fe64c588e7e4b2bb81bb6f3b9bf3ab23e8.
Стоит пока установить с репозитория.
