### ISSUE TITLE
Проблема с long polling при получение отправленного сообщения в группу

### ISSUE THREAD

**Issue by spb-web** [negezor/vk-io#114]
При получение через long polling отправленного сообщения в группу сообщение помечается как полученное, а не отправленное. 
Проблема в файле src/updates/transform-message.mjs, в этом куске кода
![vk io transform message mjs at master negezor vk io](https://user-images.githubusercontent.com/17136981/45586229-35e4e080-b904-11e8-93e7-700fc48bda93.png)
Если его убрать, то все работает. Для чего этот фрагмент кода?

**Comment by negezor** [comment]
Я унифицирую сообщение Long Poll к его главному [объекту](https://vk.com/dev/objects/message). Для пользователя приходит вот такой [набор флагов](https://vk.com/dev/using_longpoll_2?f=4.%20%D0%A4%D0%BB%D0%B0%D0%B3%D0%B8%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9), а для группы [такой набор](https://vk.com/dev/using_longpoll_2?f=5.%20%D0%A4%D0%BB%D0%B0%D0%B3%D0%B8%20%D0%B4%D0%B8%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2).

**Comment by spb-web** [comment]
Да, в коде используется `context.isOutbox`. Использовался аккаунт пользователя. `context.isOutbox` возвращает всегда `false`, а  `context.isInbox` всегда возвращает `true` если сообщение было отправлено в диалог группы. Это [флаги диалогов группы](https://vk.com/dev/using_longpoll_2?f=5.%20%D0%A4%D0%BB%D0%B0%D0%B3%D0%B8%20%D0%B4%D0%B8%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2). Диалог группы может быть помечен админом группы как важный или может быть помеченным как не имеющим ответа на последнее входящее сообщение, а это [флаги сообщений](https://vk.com/dev/using_longpoll_2?f=4.%20%D0%A4%D0%BB%D0%B0%D0%B3%D0%B8%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9), совсем другая сущность, как мне кажется.

**Comment by negezor** [comment]
Опубликовано с фиксом https://github.com/negezor/vk-io/commit/4c4f4ebf21193837ce2b9b19ad8a455bfeb079c4
