### ISSUE TITLE
Сохранение и восстановление контекста события

### ISSUE THREAD

**Issue by Wixty** [negezor/vk-io#117]
Добрый вечер.

В проекте, над которым сейчас работаю, есть необходимость сохранения и восстановления событий, т.е. контекста события определённого типа. Так как нативных путей сохранения нет, провёл некоторые исследования либы.

Для создания экземпляра контекста любого типа необходимы `vk`, `payload`, `source`, `updateType` и `groupId`. Всё, кроме `updateType`, можно получить из существующего экземпляра контекста.

Поле `updateType` - как понял, это название события, которое присылает ВК. Используется только в конструкторе, не сохраняется. По нему добавляются как минимум субтипы и аттачи.

Одно из возможных решений - сохранять json, который присылает вк, в поле объекта (которое потом можно сохранить куда угодно), и добавить в либу функцию создания контекста из этого json'а.

Могу попробовать сделать PR, но у меня не очень большой опыт работы с нодой.

---
Ещё немного смутило, что при `polling` обновлениях группы контекст создаётся с помощью функции `handleWebhookUpdate`, но это видимо из-за того, что там названия типов событий такие же, как при коллбек обновлениях.

**Comment by Wixty** [comment]
Более простой вариант - добавить поле `vkUpdateType` и сохранять в него оригинальный `updateType`. Это позволит сохранять/восстанавливать событий, пусть и не самым удобным способом.

**Comment by negezor** [comment]
Я думаю будет проще сделать свою обёртку, а контекст использовать в качестве отправной точки.

**Comment by Wixty** [comment]
Благодарю за наводку, разобрался.

Правда вместо обёртки пришлось полностью переопределить handleWebhookUpdate, т.к. создание контекста и запуск промежуточных обработчиков не разделены по фукциям (а сохранение события - в одном из обработчиков):
https://github.com/negezor/vk-io/blob/149b6f86100fe893df8465189816fb5883b46c0a/src/updates/index.mjs#L366-L371

Возможно есть какой-то более простой способ?

---
Если кто столкнётся с такой же проблемой, примерное решение
```
/**
 * Декоратор экземпляра VK, добавляет в контекст события поле json
 * @param vk {VK}
 */
const decorateVK = vk => {
  vk.updates.handleWebhookUpdate = async (update) => {
    const ctx = createContext(update, vk)
    return vk.updates.dispatchMiddleware(ctx)
  }
}

/**
 * Создание контекста события из json'а события
 * @param json {Object}
 * @param vk {VK}
 * @return {Context|Object}
 */
const createContext = (json, vk) => {
  const ContextType = webhookContexts[json.type]
  if (!ContextType) {
    log.error(`Unsupported webhook context type ${json.type}`)
    return null
  }
  const ctx = new ContextType(vk, json.object, {
    source: 'WEBHOOK',
    updateType: json.type,
    groupId: json.group_id
  })
  ctx.json = json
  return ctx
}
```
Константа `webhookContexts` - копипаста из библиотеки.
После применения декоратора к экземпляру VK в контексте появится поле json.
Для восстановления контекста из json'а использовать функцию`createContext`.
