### ISSUE TITLE
Check for upload_url

### ISSUE THREAD

**Issue by DQvsRA** [negezor/vk-io#12]
Hi
Thank for your library it's very useful!
Could you please add check for upload_url in vk.upload.[something] method to remove additional request for getting this url.

Peace,
VM

**Comment by negezor** [comment]
Hi!
Implemented, used like this:
```javascript
vk.upload.[something]({
   uploadUrl: 'Upload server',
   source: <file>
})
.then(handler);
```
[Upload files](https://github.com/negezor/vk-io#Загрузка-файлов)
