### ISSUE TITLE
Можно ли в context.send передать в качестве аргумента сам объект сообщения?

### ISSUE THREAD

**Issue by feh-wallpapers** [negezor/vk-io#120]
Допустим, я получаю сам message context другого сообщения. И мне нужно будет потом позже отправить это же сообщение в чат. Со всеми прикреплениями и прочим. Чтобы не запоминать по отдельности и attachments и текст и прочее. Как это реализовать?

**Comment by negezor** [comment]
Нет смысла в реализации подобного в самом контексте, вам в любом случае стоит сериализовать данные.
