### ISSUE TITLE
Как запостить картинку на страницу сообщества

### ISSUE THREAD

**Issue by BeaRRRRR** [negezor/vk-io#121]
#### Версия node - 8.11.1

Я хотел сделать приложение которое постит на страницу сообщества картинки
```
const {VK} = require('vk-io');

const vk = new VK({token : 'токен, который я сгенерировал в своей группе,в вкладке работа с Api'});

vk.upload.wallPhoto({
    group_id : 173918804,
    source : 'C:\\Users\\misha\\WebstormProjects\\vkbot\\doge.jpg'
});
```

Вылетает ошибка
```
(node:14388) UnhandledPromiseRejectionWarning: APIError: Code №5 - User authorization failed: method is unavailable with group auth.
    at API.callMethod (C:\Users\misha\WebstormProjects\vkbot\node_modules\vk-io\lib\index.js:1229:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by qwertyuiopasdfsde** [comment]
Попробуй вот так

<code>
vk.setOptions({
'token': токен,
'pollingGroupId': ид группы
}); 
</code>

**Comment by negezor** [comment]
Дело в том что ВКонтакте не разрешает от токена сообщества загружать изображения на стенку. Так как метод [photos.getWallUploadServer](https://vk.com/dev/photos.getWallUploadServer) доступен только с токена пользователя.

**Comment by BeaRRRRR** [comment]
> 
> 
> Дело в том что ВКонтакте не разрешает от токена сообщества загружать изображения на стенку. Так как метод [photos.getWallUploadServer](https://vk.com/dev/photos.getWallUploadServer) доступен только с токена пользователя.

Поменял токен на токен пользователя,программа отрабатывает без ошибок , но не загружает фото на страницу сообщетсва.

**Comment by negezor** [comment]
Потому что этот метод загрузки не постит изображение, из него возвращается `PhotoAttachment`, который нужно приложить в методе API `wall.post`.

**Comment by BeaRRRRR** [comment]
```
const {VK} = require('vk-io');

const vk = new VK({
    token: 'f19414246c584212e485c11e012b2c9ad426c17c34b9f4076e9cc02c90fb3ad17618bfa94d1888de788f4',
    pollingGroupId: 173918804
});

const {api} = vk;


api.call('wall.post', {
    owner_id: 173918804,
    friends_only : 0,
    form_group : 1,
    attachments: vk.upload.wallPhoto({
        owner_id: 173918804,
        source: 'C:\\Users\\misha\\WebstormProjects\\vkbot\\doge.jpg'
    })
});
```
Ошибка
```
(node:3808) UnhandledPromiseRejectionWarning: APIError: Code №100 - One of the parameters specified was missing or invalid: invalid message param
    at API.callMethod (C:\Users\misha\WebstormProjects\vkbot\node_modules\vk-io\lib\index.js:1229:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by Bapen1k** [comment]
Потому что vk.upload.wallPhoto возвращает промис...
https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/upload.md

**Comment by negezor** [comment]
```js
const {VK} = require('vk-io');

const vk = new VK({
    token: 'токен',
    pollingGroupId: 173918804
});

async function run() {
  const photo = await vk.upload.wallPhoto({
    owner_id: 173918804,
    source: <...>
  });

  await vk.api.wall.post({
    owner_id: 173918804,
    friends_only: 0,
    form_group: 1,
    attachments: photo
  });
}
```

**Comment by negezor** [comment]
Я закрою этот issue, если что-то понадобится не стесняйтесь открыть новый.

**Comment by BeaRRRRR** [comment]
Спасибо, заработало с вашим кодом,только в owner_id число нужно было с минусом указать)
