### ISSUE TITLE
AudioMessage: TypeError: (intermediate value) is not iterable

### ISSUE THREAD

**Issue by AliceCyber** [negezor/vk-io#125]
#### What version of `vk-io` are you using?

vk-io@4.0.0-rc.9

#### What version of Node.js are you using?
v11.3.0

#### What did you do?
Run the simple-updates-bot.js

#### What did you expect to happen?
Expect AudioMessage sending to work.

#### What was the actual result?
Error:
```
  vk-io:api http --> execute +26s
  vk-io:api http <-- execute 89ms +89ms
  vk-io:api http --> docs.getMessagesUploadServer +292ms
  vk-io:api http <-- docs.getMessagesUploadServer 60ms +60ms
  vk-io:api http --> docs.save +3s
  vk-io:api http <-- docs.save 80ms +82ms
Error: TypeError: (intermediate value) is not iterable
    at Upload.messageDocument (/home/tim/Documents/bot/node_modules/vk-io/lib/index.js:3984:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

```

vk-io/lib/index.js:3984
```
async messageDocument(params, {
    attachmentType = null
  } = {}) {
    const [document] = await this.conduct({ //<-- this is line 3984
      field: 'file',
      params,
      getServer: this.vk.api.docs.getMessagesUploadServer,
      serverParams: ['type', 'peer_id'],
      saveFiles: this.vk.api.docs.save, //<-- this is a source of error(???)
                                        //    'cuz conduit() returns it's call result?
      saveParams: ['title', 'tags'],
      maxFiles: 1,
      attachmentType: attachmentType || 'doc'
    });
    return new DocumentAttachment(document, this.vk);
  }
```
Also please change `http://lorempixel.com/400/200/cats/` in simple-updates-bot.js to something like `https://placekitten.com/400/300/` or `https://loremflickr.com/400/300/` because LoremPixel is dead.

З.Ы. права боту стоят практически все, включая права на аудиозаписи. Но не похоже что в этом дело. К сожалению, я не очень умею в современный джаваскрипт с промисами и асинхронностью (я уж молчу про деконструирующее присваивание!), так что моя не понимать что там происходит :(

**Comment by negezor** [comment]
Проблема исправлена в `4.0.0-rc.10`, а так же обновлены примеры. Причина была в том что ВКонтакте изменила ответ загрузки документов, было обращение к объекту как к массиву (по старому формату Object[]). Если есть ещё проблемы, смело открывайте новый issue.

**Comment by AliceCyber** [comment]
О - Оперативность. Без шуток, огромное спасибо!
