### ISSUE TITLE
проблема с npm i версии 4.0.0-rc.12, 4.0.0-rc.13

### ISSUE THREAD

**Issue by stasionok** [negezor/vk-io#130]
-bash-4.2$ node -v
v8.15.0
-bash-4.2$ npm -v
6.4.1

node_modules/vk-io/typings/methods.d.ts:37:2 - error TS1036: Statements are not allowed in ambient contexts.

37 };
    ~

node_modules/vk-io/typings/objects.d.ts:43:2 - error TS1036: Statements are not allowed in ambient contexts.

43 };
    ~

node_modules/vk-io/typings/params.d.ts:9:2 - error TS1036: Statements are not allowed in ambient contexts.

9 };
   ~

node_modules/vk-io/typings/params.d.ts:2081:5 - error TS2300: Duplicate identifier 'post_id'.

2081     post_id: number;
         ~~~~~~~

node_modules/vk-io/typings/params.d.ts:2081:5 - error TS2687: All declarations of 'post_id' must have identical modifiers.

2081     post_id: number;
         ~~~~~~~

node_modules/vk-io/typings/params.d.ts:2105:5 - error TS2300: Duplicate identifier 'post_id'.

2105     post_id?: number;
         ~~~~~~~

node_modules/vk-io/typings/params.d.ts:2105:5 - error TS2687: All declarations of 'post_id' must have identical modifiers.

2105     post_id?: number;
         ~~~~~~~

node_modules/vk-io/typings/responses.d.ts:17:2 - error TS1036: Statements are not allowed in ambient contexts.

17 };

**Comment by negezor** [comment]
Используется typescript?

**Comment by stasionok** [comment]
Да.

**Comment by negezor** [comment]
А где именно вызывается ошибка?

**Comment by negezor** [comment]
Вроде исправил, вы можете загрузить библиотеку с git для проверки?

**Comment by stasionok** [comment]
Да взлетело, но только после того как я установил yarn
Без него естественно не фачит.

**Comment by negezor** [comment]
Хорошо, тогда я опубликую свежую версию.
