### ISSUE TITLE
Проблема с forwards

### ISSUE THREAD

**Issue by zombieserv** [negezor/vk-io#132]
На текущей версии (vk-io@4.0.0-rc.15) вновь актуальна данная проблема: https://github.com/negezor/vk-io/issues/106
Даже на примере от разработчика информация о пересланных сообщениях не отдаётся.
Работаю в беседе через бота в сообществе (токен сообщества).
Что делать?

![image](https://user-images.githubusercontent.com/32253362/53064149-dce32f00-34d7-11e9-9acb-45164dfb812c.png)

**Comment by zombieserv** [comment]
Решилось переустановкой.
Плюс имейте в виду: пересланные и те, что отмечены как "ответить" - отображаются в API по-разному.

**Comment by negezor** [comment]
Они доступны через `replyMessage`.
