### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by ProgrammingLife** [negezor/vk-io#133]
I have "node v11.10.0" + MacOS 10.14. 
Unfortunately I can't start VK-io because of these errors:

```
import VK from 'vk-io';
       ^^
SyntaxError: Unexpected identifier

...

import { VK } from 'vk-io';
       ^
SyntaxError: Unexpected token {
```

So I tried something else but again I've not succeed with that approach:

```
const vk = require('vk-io');
vk.token = "asdfasdfadsf";
const collectStream = vk.collect.wall.get({ owner_id: -86529522 });

// Error:
const collectStream = vk.collect.wall.get({
                                 ^
TypeError: Cannot read property 'wall' of undefined
```

What do I do wrong?

**Comment by negezor** [comment]
The import works only with MJS and TypeScript or Babel preprocessing. Here you need to use Common JS:
```js
const { VK } = require('vk-io');

const vk = new VK();
vk.token = 'asdfasdfadsf';

const collectStream = vk.collect.wall.get({ owner_id: -86529522 });
```

**Comment by ProgrammingLife** [comment]
negezor, thanks! It works!
Do you happen to know why am I have such error?

```
vk.collectStream.on('error', console.error);
                 ^
TypeError: Cannot read property 'on' of undefined
```

**Comment by negezor** [comment]
Maybe the fact is that the vk object is used at the beginning?
Example for usage.
```js
const collectStream = vk.collect.wall.get({ owner_id: -86529522 });

collectStream.on('error', console.error);

collectStream.on('data', payload => {
  console.log('Data', payload.items);
});
collectStream.on('end', () => {
	console.log('Data received');
});
```

**Comment by ProgrammingLife** [comment]
Is there any little example on how to get messages from a wall of a group?
I'm new to VK service so it looks little bit confusing to me.
Which authorization method should I choose? What is the appId and the appSecret? I need to access to a group not to an application. Where can I pass my group's private Key?
I have a login/password data and the privateKey to the group. What should I do next?

**Comment by negezor** [comment]
You can get posts from a group using the [wall.get](https://vk.com/dev/wall.get) method, but it is not available for the group token. If there is a token, you need to using it only in the options.
```js
const group = new VK({
  token: 'GROUP_TOKEN'
});

const app = new VK({
  token: 'APP_TOKEN_OR_USER_TOKEN'
});

// Method
app.api.wall.get({
  owner_id: -86529522 // Group ID
}); // => Promise

// Or collect all
app.collect.wall.get({
  owner_id: -86529522
}); // => CollectStream
```
The collection works with a user or application token. But only if the method supports.

**Comment by ProgrammingLife** [comment]
Thanks!
What is the AppToken and where I get UserToken?

**Comment by negezor** [comment]
[Application token (Service Token)](https://vk.com/apps?act=manage). User token available via standalone or direct authorization. These are all tokens, have their permissions to call methods.

**Comment by ProgrammingLife** [comment]
What token (and auth method) do I need to make wall.get requests?

My sample code now is:
```
const { VK } = require("vk-io");
const vk = new VK({ token: "...a long group API token placed here..." });
vk.api.wall.get({ owner_id: -86529522 });
```

But everytime I get a following message:
`Code №5 - User authorization failed: method is unavailable with group auth.`

Looks I can't just make simple wall.get request :)

**Comment by negezor** [comment]
The method documentation indicates that it is not available for the group token. Need a service or user token, I already wrote about this above.
![image](https://user-images.githubusercontent.com/9392723/53468552-cd9f4b00-3aae-11e9-8357-c2d49c1358c8.png)
