### ISSUE TITLE
Failed to compile.  ./node_modules/sandwich-stream/dist/sandwich-stream.mjs Can't import the named export 'Readable' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by zavx0z** [negezor/vk-io#134]
Хочу использовать в коде React Create App прилжения, но столкнулся с данной ошибкой. Как быть?

**Comment by negezor** [comment]
Проблема скорее в сборщике, так как она не берёт module из package.json. Да и библиотека серверная.

**Comment by zavx0z** [comment]
Да. Проблема в Webpack4. Жаль. Пишу теперь свой async API для ReactJs.

**Comment by negezor** [comment]
Хорошо, я тогда закрою данный вопрос.
