### ISSUE TITLE
Вконтач с недавних пор ограничил доступ к API сообщений

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#135]
https://vk.com/dev/messages_api

В связи с чем поломались все боты которые используют аккаунт пользователя (как я понял)
И у меня возникает вопрос что можно с этим сделать помимо обращения в поддержку ?
Возможно поможет другой способ авторизации ?

В поддержку уже написал, но чувствую это на долго.

**Comment by Bapen1k** [comment]
Я использую клиент авторизации официального Android  приложения (его поддержка есть в библиотеке) и проблем, пока что, не испытываю.

**Comment by negezor** [comment]
Используя токены от официальных приложения, можно использовать User Long Poll.
