### ISSUE TITLE
Документ загружается в профиль, несмотря на параметр group_id

### ISSUE THREAD

**Issue by zombieserv** [negezor/vk-io#136]
Приветствую.
Имеется код:

```
var urlILink = "https://..";
var GroupID = 1234;

vkUser.upload.graffiti({
	source: urlILink,
	group_id: GroupID,
	title:'title'
}).then(async function (r) {
	console.log(r)
})
```

Проблема в том, что несмотря на переменную GroupID граффити сохраняется к пользователю в документы.
Пробовал идентификатор сообщества и с "-" начинать, не помогает.
Либо баг, либо я что-то не так делаю, подскажите, пожалуйста.

**Comment by negezor** [comment]
Дело в том что граффити грузятся сейчас в сообщения. У меня сейчас не имеется возможности протестировать, но так работает?
```js
const { graffiti } = await vk.upload.conductDocument(
	{
		source: urlILink,
		group_id: GroupID,

		type: 'graffiti'
	},
	{
		attachmentType: 'graffiti'
	}
);

console.log('Graffity', graffiti);
```

**Comment by zombieserv** [comment]
Да, это работает, огромное спасибо!
Но почему-то в случае смены имени переменной graffiti уже не работает, магия какая-то.
Но главное, что работает. А в чём разница upload.document и upload.conductDocument?

**Comment by negezor** [comment]
В том что это внутренняя реализация. Дело в том что по умолчанию граффити грузятся в диалог, но думаю можно добавить 2 отдельных метода.

**Comment by negezor** [comment]
Решено в 4.0.0-rc.16, добавлен новый метод [documentGraffiti](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/upload.md#documentgraffiti).
