### ISSUE TITLE
Отправка фотографий в беседе

### ISSUE THREAD

**Issue by 0ArturkA** [negezor/vk-io#142]
#### What version of `vk-io` are you using?

4.0.0-rc.16

#### What version of Node.js are you using?
v10.13.0

#### What did you do?
Если пользователь в нашей беседе не разу не писал боту в ЛС и он допустим выполнил команду  и мы попытаемся через MessageContext отправить фотографию используя функцию `sendPhoto()` то мы получим ошибку `901 - Can't send messages for users without permission`.
Это происходит из за установки параметра `peer_id` в функции `sendPhoto()`:
https://github.com/negezor/vk-io/blob/e5cd5f33a793fb42bf9f7717912785c362f8c37e/src/structures/contexts/message.mjs#L575-L581
ВК считает что пользователь не дал нам ещё права писать ему, для этого он должен написать хоть что то в ЛС бота.
Может стоит ввести проверку на `isChat`? И не добавлять `peer_id` для сообщений с фотографией в беседе.

**Comment by negezor** [comment]
Раньше без этого параметра невозможно было загрузить, я думаю может его стоит вовсе убрать.

**Comment by 0ArturkA** [comment]
Попробовал удалить совсем `peer_id` для фото, отправлял фото в лс и в беседе. Вроде всё норм. Обновил pull request.
