### ISSUE TITLE
Не приходят фотографии, когда бот работает в беседе

### ISSUE THREAD

**Issue by AndreiBelokopytov** [negezor/vk-io#146]
#### What version of `vk-io` are you using?
4.0.0-rc.16

#### What version of Node.js are you using?
10.14.2

#### What did you do?
Подключил бота, созданного с помощью vk-io в беседу. Бот должен отправлять фотографии в ответ на сообщения пользователей. Для некоторых участников беседы  это работает, но для некоторых – нет, при этом текстовые сообщения приходят всем одинаково.

Код, который отправляет фотографии

```
        const { text, photo } = hints[hintIndex - 1];
        await context.send(`Подсказка №${hintIndex}: ${text ? text : ""}.`);
        if (photo) {
          const localPhoto = fs.createReadStream(path.join(__dirname, `../../img/${photo}`));
          await context.sendPhoto(localPhoto);
        }

        if (hintIndex < hints.length) {
          const count = hints.length - hintIndex;
          await context.send(`Осталось ${count} ${pluralizeMessage(count)}.`);
        } else {
          await context.send("Это последняя подсказка");
        }
```

#### What did you expect to happen?
Фотографии приходят в ответ на сообщение от любого пользователя

#### What was the actual result?
Фотографии приходят в ответ на сообщения только некоторых пользователей

**Comment by negezor** [comment]
А какие ошибки?

**Comment by AndreiBelokopytov** [comment]
В консоли ошибок нет, сейчас включил DEBUG=*, надеюсь получить более подробный лог. Бот по задумке должен работать в беседе. Соответственно, мы видим, что когда один человек отправляет команду, приходит сообщение без фотографии, а для другого человека приходит то же сообщение, но с фотографией. Спасибо за совет насчет установки из репозитория, попробую так сделать.

**Comment by AndreiBelokopytov** [comment]
Проблема исчезла после:
* установки vk-io из репозитория
* изменения версии API в настройках группы на 5.92 (было 5.80)

**Comment by negezor** [comment]
Хорошо, тогда я закончу обновление быстрее и опубликую.
