### ISSUE TITLE
Implement request timeout

### ISSUE THREAD

**Issue by spb-web** [negezor/vk-io#147]
Как на счет того что бы сделать выбрасывание ошибки если запрос выполняется дольше n секунд? Актуально если барахлят проки.

**Comment by spb-web** [comment]
Есть таймаут на выполнение методов апи, нашел. Может добавим таймаут и на ImplicitFlow?

**Comment by negezor** [comment]
Думаю можно добавить, отпишусь когда посмотрю.

**Comment by negezor** [comment]
Реализовано https://github.com/negezor/vk-io/commit/08314a31c68db05fb789d3118894d61f284d50b4
