### ISSUE TITLE
Обновить документацию

### ISSUE THREAD

**Issue by Saiv46** [negezor/vk-io#148]
Несмотря на _100% coverage of the VKontakte API_, документация скудная и безполезна для создания более сложных ботов чем "Команда -> Ответ".

**Comment by xTCry** [comment]
Гайды по написанию различных ботов, думаю, надо смотреть не в документациях по работе с API VK

**Comment by negezor** [comment]
Привет! Прошу прощение за долгий ответ, но какие именно есть предложения? Есть пример бота со сценами. Примеры должны быть простыми и понятными.

**Comment by Saiv46** [comment]
Одно слово - контексты.
Пришлось неоднократно лезть в исходники чтобы не обращаться к `context.payload` за незнанием тех геттеров что каждый тип контекста имеет.

**Comment by negezor** [comment]
Подсветка типов от TS используется?

**Comment by Saiv46** [comment]
Используется, но работает только с Context и Message. Остальные геттеры тупо не видны.

**Comment by artmove27** [comment]
Привет.
Объясните чайнику, как сделать запросы к api через прокси, используя вашу библиотеку?
Если можно то лучше всего пример.

**Comment by xTCry** [comment]
> Если можно, то лучше всего пример.

На примере прокси через Tor

```js
const { VK } = require('vk-io');
const Agent = require('socks5-https-client/lib/Agent');
const HttpProxyAgent = require('http-proxy-agent');

let vk = new VK();
const agent = new Agent({ socksPort: 9050, socksHost: "127.0.0.1" });
// const agent = new HttpProxyAgent("http://127.0.0.1:8119");
vk.setOptions({ agent });

(() => {
  try {
    let [user] = await vk.api.users.get();
    console.log('User:', user);
  } catch(e) { console.log(e); }
})();
```

**Comment by artmove27** [comment]
> 
> 
> > Если можно, то лучше всего пример.
> 
> На примере прокси через Tor
> 
> ```js
> const { VK } = require('vk-io');
> const Agent = require('socks5-https-client/lib/Agent');
> const HttpProxyAgent = require('http-proxy-agent');
> 
> let vk = new VK();
> const agent = new Agent({ socksPort: 9050, socksHost: "127.0.0.1" });
> // const agent = new HttpProxyAgent("http://127.0.0.1:8119");
> vk.setOptions({ agent });
> 
> (() => {
>   try {
>     let [user] = await vk.api.users.get();
>     console.log('User:', user);
>   } catch(e) { console.log(e); }
> })();
> ```

Спасибо

**Comment by negezor** [comment]
Я закрою этот вопрос в пользу этого https://github.com/negezor/vk-io/issues/255
