### ISSUE TITLE
Флуд сообщений

### ISSUE THREAD

**Issue by shakidev** [negezor/vk-io#15]
if (message.text === null) {
    return;
  }else if(ismember == 0){
   message.send('Вы должны вступить в группу!');
 }else{
  const text = message.text.split(" ")[0];
        message.send("Сохранить");
      }

идет флуд бесконечный, из-за чего такое поведение может быть?  логи чисты.

**Comment by negezor** [comment]
Можно привести полный пример кода?

**Comment by shakidev** [comment]
![image](https://cloud.githubusercontent.com/assets/15838110/24834461/eda2ac42-1d07-11e7-9fd8-6c7764cd06d4.png)

**Comment by shakidev** [comment]
код из examples работает хорошо) вот только начинаю чуть своё и начинается флуд)

**Comment by negezor** [comment]
Из кода не совсем понятно как именно подключается обработчик? Просто тут возможно где то закралась рекурсия.

**Comment by shakidev** [comment]
Полный код 
'use strict';

const vk = new (require('vk-io'));
const config = require("./config.json");
const bot = require('./controllers/bot');

vk.setToken(config.secret_key);

vk.setOptions({
  call: 'api'
});

vk.longpoll.start()
.then(() => {
  console.log('Long Poll started');
});

vk.longpoll.on('message',(message) => {
  vk.api.groups.isMember({
    "group_id": config.group_id,
    "user_id": message.user
  }).then((ismember) => {
   if (message.text === null) {
    return;
  }else if(ismember == 0){
   message.send('Вы должны вступить в группу!');
 }else{
  const text = message.text.split(" ")[0];
  switch (text){
    case "Сохранить":{
      message.send("Сохранить");
      break;
    }

  }

}
});
});

**Comment by negezor** [comment]
Кажется я всё понял, когда пользователь пишет сообщение "Сохранить", потом идёт ответ от группу с текстом "Сохранить" и так он снова и снова по кругу гоняет. Тут нужно сделать проверку что пишет именно пользователь, хотя у самого частенько возникают проблемы как лучше это реализовать так как флаги группы сломаны (фича ВКонтакте).

**Comment by shakidev** [comment]
Все понял) спасибо)
