### ISSUE TITLE
После обновления в updates on message не подгружаются полезная нагрузка

### ISSUE THREAD

**Issue by xTCry** [negezor/vk-io#150]
Месяц назад до обновления все работало как надо.
А теперь...
```js
vk.updates.on([ 'new_message', 'edit_message' ], async (context, next) => {
// ...
	console.log("M_Before", context);
	await context.loadMessagePayload();
	console.log("M_After", context);
```
вложенные фотографии не подгружают информацию
![image](https://user-images.githubusercontent.com/5994290/56096246-628ac600-5eee-11e9-8dac-2b7b524fbe36.png)

Также будет если переслать это сообщение
![image](https://user-images.githubusercontent.com/5994290/56096314-45a2c280-5eef-11e9-821b-0ddb3864fb3b.png)

Однако, если выполнить `reply` на сообщение выше (не переслать, а именно ответить), то вложения сообщения с ответом подгружают информацию
![image](https://user-images.githubusercontent.com/5994290/56096264-b09fc980-5eee-11e9-9ca9-a4ad053efebe.png)
и еще `forwards` не пустой. И из-за этого получатся, что `context.hasReplyMessage` и `context.hasForwards` истины
Хотя на самом деле должно быть истинно только `context.hasReplyMessage`

![image](https://user-images.githubusercontent.com/5994290/56096270-beede580-5eee-11e9-90b3-3699d84a43fb.png)

Может это связано с поднятием версии API, но так и не понял толком причины

**Comment by negezor** [comment]
Исправлено https://github.com/negezor/vk-io/commit/49b0415902da3bf66a95e7dcc1ffb4bd9a52e750
