### ISSUE TITLE
Ошибка с typescript

### ISSUE THREAD

**Issue by SneakBug8** [negezor/vk-io#152]
![](https://imgur.com/wr6WIFg.png)
Ошибка возникает сразу после установки пакета.
Использую typescript Version 2.9.2
"vk-io": "^4.0.0-rc.17"

**Comment by negezor** [comment]
Любые изменения?

**Comment by negezor** [comment]
Я закрою эту проблему, так как не удалось повторить поведение. Не стесняйтесь открыть вопрос снова.
