### ISSUE TITLE
User authorization failed в примере

### ISSUE THREAD

**Issue by apepenkov** [negezor/vk-io#153]
в примере https://github.com/negezor/vk-io/blob/master/docs/examples/simple-keyboard-bot.js при вставке токена сообщества я получаю:
 node test.js
{ APIError: Code №5 - User authorization failed: invalid access_token (4).
    at API.callMethod (/root/vkoin/node_modules/vk-io/lib/index.js:1084:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  code: 5,
  name: 'APIError',
  params:
   [ { key: 'oauth', value: '1' },
     { key: 'method', value: 'groups.getById' },
     { key: 'v', value: '5.92' } ] }

**Comment by iNPGT** [comment]
тоже самое
