### ISSUE TITLE
Возникла проблема!

### ISSUE THREAD

**Issue by MrProLopstar** [negezor/vk-io#154]
Я делаю бота для vk. Но у меня вылазит данная ошибка:
(node:9920) UnhandledPromiseRejectionWarning: ExecuteError: Code №100 - One of t 
he parameters specified was missing or invalid: message is empty or invalid 
at request.resolve.errors.map.error (C:\Users\Ярослав\Desktop\Версии BotRikl 
\BotRikl\node_modules\vk-io\lib\index.js:1240:62) 
at Array.map (<anonymous>) 
at API.callMethod (C:\Users\Ярослав\Desktop\Версии BotRikl\BotRikl\node_modu 
les\vk-io\lib\index.js:1240:49) 
at processTicksAndRejections (internal/process/next_tick.js:81:5) 
(node:9920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This 
error originated either by throwing inside of an async function without a catch 
block, or by rejecting a promise which was not handled with .catch(). (rejection 
id: 1) 
(node:9920) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre 
cated. In the future, promise rejections that are not handled will terminate the 
Node.js process with a non-zero exit code.
Что делать?

**Comment by negezor** [comment]
Без кода, я не смогу понять в чём дело.

**Comment by negezor** [comment]
Я закрою проблему, так как не было никакого ответа. Не стесняйтесь открыть вновь.
