### ISSUE TITLE
Некорректно работающий pooling от группы.

### ISSUE THREAD

**Issue by aeonixlegit** [negezor/vk-io#156]
По каким-то непонятным для меня причинам, если в options присутствует pollingGroupId, то он перестает работать совсем, ни сообщения, ни вступления в группу, ни новые посты, не получает данные абсолютно ни о чем, однако, если данного параметра нет, или он равен null, то всё спокойно работает и обрабатывает (по крайней мере сообщения, остальное не тестировал) с чем это может быть связано?

node version: v10.15.3
vk.io version: 4.0.0-rc.17
platform: win64

**Comment by negezor** [comment]
Дело в том, что настройках должен быть включен Bots Long Poll, нужные события и указана актуальная версия API `5.95`. Без Bots Long Poll, будет использоваться User Long Poll. Который получает только неполный сообщения.

**Comment by aeonixlegit** [comment]
прошу прощения за свой тупизм, вкладку с типами событий не заметил.
