### ISSUE TITLE
Во вложениях перестал подгружаться audio_playlist

### ISSUE THREAD

**Issue by xTCry** [negezor/vk-io#157]
Во вложениях перестал подгружаться **audio_playlist**

![image](https://user-images.githubusercontent.com/5994290/57178902-3ffe2400-6e80-11e9-812c-87365a9092f8.png)

**Comment by xTCry** [comment]
Это было на версии __4.0.0-rc.15__

На версии __4.0.0-rc.17__ вообще пусто
![image](https://user-images.githubusercontent.com/5994290/57179337-9752c300-6e85-11e9-9649-1b3c11565890.png)

**Comment by negezor** [comment]
Дело в том что в https://github.com/negezor/vk-io/commit/d5427068ffd9bfc56469ca333965394fe963c634 передача типов в `subTypes` была убрана. Связанно это с неочевидным поведением, так как при появлении новых типов появляются в контексте, что может привести к последствиям. Так что сейчас в `subTypes` хранится только событие объекта.

**Comment by xTCry** [comment]
Дело в том, что там не приходит вложение плейлиста

**Comment by xTCry** [comment]
Формат файла аудиозаписи стал приходить __m3u8__
![image](https://user-images.githubusercontent.com/5994290/57198288-adda4680-6f79-11e9-8ce7-a4f7cd393791.png)

В самой веб версии ВК аудио тоже стали такого формата

Но в API vk.com/dev/messages.getById формат файла по прежнему __mp3__
![image](https://user-images.githubusercontent.com/5994290/57198318-f265e200-6f79-11e9-8343-10430a0ec65a.png)
![image](https://user-images.githubusercontent.com/5994290/57198321-f98cf000-6f79-11e9-992b-f4a0ab6c5a47.png)

**Comment by xTCry** [comment]
К сообщению был прикреплен playlist, но во вложениях его нету
`console.log("\n-----------", context.hasAttachments('audio_playlist'))`
 =>
`----------- false`

![image](https://user-images.githubusercontent.com/5994290/57198360-6902df80-6f7a-11e9-86b0-dcb66b0d1830.png)
Нету вложений ни с ссылкой, ни с плейлистом

Запрос через тот же messages.getBId
![image](https://user-images.githubusercontent.com/5994290/57198397-e2023700-6f7a-11e9-9134-81682d106601.png)
