### ISSUE TITLE
Можно ли авторизоваться при помощи логина и пароля?

### ISSUE THREAD

**Issue by scientistnik** [negezor/vk-io#158]
Хочу от своего имени постить сообщения на стене. По идее нужно создавать application, указывать на какой сайт будет редирект, получать временный токен, затем запросом получить постоянные токен.

А можно просто по логину и паролю?
В примерах используются только токены.
Спасибо!

**Comment by negezor** [comment]
Можно, для этого есть работа [авторизацией](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/auth.md). Можно выбрать на нужную потребность.
