### ISSUE TITLE
При загрузке аудио ошибка — Internal server error

### ISSUE THREAD

**Issue by voodee** [negezor/vk-io#159]
#### What version of `vk-io` are you using?
4.0.0-rc.15

#### What version of Node.js are you using?
v11.14.0

#### What did you do?
Хочу отправить аудио в сообщение пользователю, перед этим загружаю его:
```js
const { VK } = require('vk-io');

const vkIo = new VK();
vkIo.setOptions({
	token: '...',
});

await vkIo.upload.audioMessage({
	peer_id: '..',
	source: 'http://ronsen.org/purrfectsounds/purrs/trip.mp3'
});
```

#### What did you expect to happen?
Ожидаю получить сообщение об успешной загрузки.

#### What was the actual result?
Получаю сообщение об ошибке:
```js
{ APIError: Code №10 - Internal server error
     at API.callMethod (/node_modules/vk-io/lib/index.js:1120:33)
     at processTicksAndRejections (internal/process/task_queues.js:86:5)
   code: 10,
   name: 'APIError',
   params:
    [ { key: 'oauth', value: '1' },
      { key: 'method', value: 'docs.save' },
      { key: 'v', value: '5.92' },
      { key: 'file',
        value:
         '317108901|0|-1|852728|6c66d0c759|ogg|915004|file0.dat|3c17f465ad6940229e70a4bf9c33cd44|d99deca65b1fcaba7d3e188d736c5c9e||||eyJkaXNrIjoiOCIsImF1ZGlvX21zZyI6eyJkdXJhdGlvbiI6MjguNTU5OTk5OTk5OTk5OTk4LCJ3YXZlZm9ybSI6IjMyOjAwMDAwMDAwMDAwMDAxMTEyMjMzNDQ1NDQzMzQ1Njc5YWNmaGprbG1ubm9vb25vcHFxcnN0dXZ2dnZ2dnV1dHFvbm1sbWxqaGdmZWRiOTUzMjI1NTdiZGNjZGVkZWVmZmZnaGhpaWtra2tqaWhnZmVlZGNjYmJjYiJ9LCJwZWVyX3NlbmRlciI6Ii0xNjgyNjg4NTgifQ==' } ] }

```

**Comment by negezor** [comment]
Это проблема связанная с ВК, судя по значению сервера, аудио сообщение было загружено, но не обработано в методе `docs.save`. Я бы рекомендовал поднять версию API до 5.95 и обновить библиотеку до последней версии.

**Comment by voodee** [comment]
Обновил пакет (4.0.0-rc.17) и поднял версию (5.95), не помогло:
```js
{ APIError: Code №10 - Internal server error
     at API.callMethod (/node_modules/vk-io/lib/index.js:1084:33)
     at processTicksAndRejections (internal/process/task_queues.js:86:5)
   code: 10,
   name: 'APIError',
   params:
    [ { key: 'oauth', value: '1' },
      { key: 'method', value: 'docs.save' },
      { key: 'v', value: '5.95' },
      { key: 'file',
        value:
         '317108901|0|-1|852436|97d27f2e89|ogg|915004|file0.dat|3c17f465ad69402194e70a4bf9c33cd44|9fca4c8670d6ec4e51b557a8d10398789||||eyJkaXNrIjoiMTAiL4CJhdWRpb19tc2ciOnsiZHVyYXRpb24iOjI4LjU1OTk5OTk5OTk5OTk5OSwid2F2ZWZvcm0iOiIzMjowMDAwMDAwMDAwMDtAwMTExMjIzMzQ0NTQ0MzM0NTY3OWFjZmhqa2xtbm5vb29ub3BxcXJzdHV2dnZ32dnZ1dXRxb25tbG1samhnZmVkYjk1MzIyNTU3YmRjY2RlZGVlZmZmZ2hoaWlra2tramloZ2ZlZWRjY2JiY2IifSwicGVlcl9zZW5kZXIiOiItMTY4MjY4NzU4In0=' } ] }
```

**Comment by negezor** [comment]
Я сейчас пробовал загрузить аудио сообщение ogg/mp3, у меня ничего не вышло. Файл на сервер загружен, но метод `docs.save` падает с ошибкой. До этого это работало, возможно это как-то связанно с этой [новостью](https://tjournal.ru/tech/96063-v-rabote-vkontakte-po-vsey-rossii-voznikli-problemy).

**Comment by voodee** [comment]
У меня загрузилось `ogg` http://ia800700.us.archive.org/18/items/antony_raijekov-views/antony_raijekov_views_track_01_lightin.ogg

Но это такое себе решение, раньше и mp3 работало.

**Comment by negezor** [comment]
Хотя изначально указано было OGG, но с MP3 работало. Но видать это прекратили.
![image](https://user-images.githubusercontent.com/9392723/57569249-e37da480-743d-11e9-8b0b-6e991d6f5257.png)

**Comment by negezor** [comment]
Возможно это было исправлено в `4.0.0-rc.18`, проверьте.
