### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by shakidev** [negezor/vk-io#16]
Unhandled rejection TypeError: Cannot read property 'replace' of undefined
при вызове
message.flag.replace({
              'id': message.user,
              'flags': ['date']
          });
Как правильно использовать флаги и можно ли их использовать для состояний ?

**Comment by negezor** [comment]
Можно узнать присутсвуют ли в сообщении флаги или взять полный список messages.flags
https://github.com/negezor/vk-io#messagehasflag
Все свойства в объекте Message -- read-only
Замена флагов производится через методы ВКонтакте, например:
https://vk.com/dev/messages.markAsRead
https://vk.com/dev/messages.markAsImportantDialog
