### ISSUE TITLE
Несколько месяцев не работает что-то, APIERROR 15

### ISSUE THREAD

**Issue by kungermu** [negezor/vk-io#161]
Уже несколько месяцев мучаюсь с ошибкой при запуске скрипта, просьба помочь.

(node:22376) UnhandledPromiseRejectionWarning: APIError: Code №15 - Access denied: no access to call this method
    at API.callMethod (/home/dima/TestBot/node_modules/vk-io/lib/index.js:1084:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by negezor** [comment]
А что в коде? Так как эта ошибка символизирует, что у вас в токене нет прав на выполнение действия.

**Comment by negezor** [comment]
Я закрою этот вопрос, так как нет дальнейшей информации.
