### ISSUE TITLE
@vk-io/scenes Выход из сцены с помощью кнопок или других команд

### ISSUE THREAD

**Issue by xTCry** [negezor/vk-io#162]
Понадобился способ выхода из сцены  с помощью кнопок или других команд

Сейчас использую ``enterHandler``
![image](https://user-images.githubusercontent.com/5994290/57721157-26cd5280-768c-11e9-931d-ffadafb329c5.png)

Но при деструкторе (``context.scene.leave()``) сцены все равно продолжается выполнение ``context.scene.step.reenter()``

scenes/step.ts
![image](https://user-images.githubusercontent.com/5994290/57721177-364c9b80-768c-11e9-82f1-11cdf0175696.png)

по этому пришлось сделать проверку, что сцена уже была покинута
![image](https://user-images.githubusercontent.com/5994290/57721363-a824e500-768c-11e9-94e1-2f91193b4b79.png)

## Предложение
Сделать проверку, что сцена была завершена из ``enterHandler``
Возможность прослушивания ``updates.hear``

**Comment by negezor** [comment]
Правильным вариантом было бы вовсе отделить middleware установки в контекст и его логику (у меня реализовано так). Думаю будет мажорное исправление.
