### ISSUE TITLE
Что такое StepScene и как его едят?

### ISSUE THREAD

**Issue by tailsjs** [negezor/vk-io#163]
#### What version of `vk-io` are you using?
4.0

#### What version of Node.js are you using?
12.2.0

#### What did you do?
Подгружаю загрузку сцен и StepScene нет

#### What did you expect to happen?
Появление сцены

#### What was the actual result?
ReferenceError: StepScene is not defined

**Comment by negezor** [comment]
Мне нужен код для того что-бы сказать что не так.

**Comment by negezor** [comment]
Возможно это поможет https://github.com/negezor/vk-io/issues/167
