### ISSUE TITLE
Как пользоваться get.user?

### ISSUE THREAD

**Issue by RomanJarckov** [negezor/vk-io#165]
Можно ли более подробное описание использования этой функции?
Заранее спасибо!

**Comment by negezor** [comment]
Какой именно функции? Речь идёт про `vk.api.users.get({ ... })`? Если да, то достаточно заглянуть в [документацию](https://vk.com/dev/users.get).

**Comment by negezor** [comment]
Я закрою вопрос, так как нет дополнительной информации, не стесняйтесь снова открыть.
