### ISSUE TITLE
Как реализовать выход из сцены с переходом в context.state.command?

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#168]
Как только я не пытался реализовать выход из сцены и переход к любой команде через  `context.state.command`, ничего не вышло.

Сцена завершается, но `state.command` не выполняется.

**Comment by negezor** [comment]
Можно код?

**Comment by MrZillaGold** [comment]
`sceneManager.addScene(new StepScene('names', [
    (context) => {
        if (context.scene.step.firstTime || !context.text) {
            return context.send('💡 Введите никнейм игрока, историю которого вы хотите посмотреть.');
        }

        context.scene.state.name = context.text;

        return context.scene.step.next();
    },
    async (context) => {
        const { name } = context.scene.state;

        axios.get(`https://api.ashcon.app/mojang/v2/user/${name}`).then(res => {
            return res.data;
        }).then(data => {
            let username = data.username;
            let names = '';
            data.username_history.forEach(item => {
                names += item.username + ' \n ';
            })
            return context.send(`[public175914098|💬 История никнейма ${username}]:\n\n${names}`);
        }).catch(err => context.send(`⚠ Никнейм ${name} не существует!`));

        await context.scene.leave();
    }
]));`

**Comment by negezor** [comment]
Этот код совсем не ждёт же результата, вот и выходит из сцены так как нет ожидающих операций. Так как тут смешение Promise API и async/await.
