### ISSUE TITLE
messages.getConversations

### ISSUE THREAD

**Issue by Revalto** [negezor/vk-io#169]
Здравствуйте, хотел получить user_id администратора беседы, в итоге столкнулся с проблемой...
![image](https://user-images.githubusercontent.com/43722954/58982460-2b91ac00-87dd-11e9-83fb-5f65d7737700.png)
Ответ постоянно - { count: 0, items: [] }

**Comment by negezor** [comment]
Вызов сообщения идёт в чате? Можно полный код с отладкой переменных.

**Comment by Revalto** [comment]
Выявил проблему, если у группы нету административных прав в беседе, то он не сможет получить информацию о ней...
![image](https://user-images.githubusercontent.com/43722954/59053297-c0f27600-8899-11e9-9348-60c9ce309e90.png)

**Comment by negezor** [comment]
По идеи он должен выдавать ошибку:
```
917 | You don't have access to this chat
```
Но в таком случае я закрою проблему.
