### ISSUE TITLE
Ошибка использования upload.groupCover

### ISSUE THREAD

**Issue by nitreojs** [negezor/vk-io#171]
При `apiMode: 'parallel'` использование `vk.upload.groupCover(...)` приводит к ошибке. При переключении на `apiMode: 'sequential'` и попытке выложить обложку снова всё проходит нормально.

**Comment by vitalyavolyn** [comment]
Используете токен сообщества?
parallel собирает все в execute, который нельзя вызывать от группы

**Comment by negezor** [comment]
Проблема остаётся на стороне ВКонтакте, честно пока не знаю как её лучше решить.

**Comment by nitreojs** [comment]
> 
> 
> Используете токен сообщества?
> parallel собирает все в execute, который нельзя вызывать от группы

> [execute](https://vk.com/dev/execute)
> Универсальный метод, который позволяет запускать последовательность других методов, сохраняя и фильтруя промежуточные результаты.
> Этот метод можно вызвать с ключом доступа пользователя.
> **Этот метод можно вызвать с ключом доступа сообщества**.

**Comment by vitalyavolyn** [comment]
@nitreojs упс. извиняюсь

перепутал, это с сервисным токеном нельзя
я так недавно пытался разослать пользователям приложения vk mini apps пуш, хотел использовать parallel, а нельзя

**Comment by isinkin** [comment]
Предлагаю сделать массив, в котором хранятся методы, которые не работают в execute и вызывать их напрямую

**Comment by nitreojs** [comment]
есть какие-нибудь идеи/продвижения по этому issue?

**Comment by negezor** [comment]
Реализовано https://github.com/negezor/vk-io/commit/315e4fbb554f0e580b8b2bea1eccce4c62991168
