### ISSUE TITLE
Nodejs v12

### ISSUE THREAD

**Issue by AndreiSoroka** [negezor/vk-io#175]
#### What version of `vk-io` are you using?
"vk-io": "^4.0.0-rc.19"

#### What version of Node.js are you using?
node -v
v12.4.0

#### What happened. Why are you write this issue?
```
import VK from 'vk-io';

// Nodejs v => 12
const vk = new VK.VK({ token: process.env.VK_TOKEN });
// Nodejs v < 12
const vk = new VK({ token: process.env.VK_TOKEN });
```
Давно хотел опубликовать, но руки не доходили.
В nodejs 12 версии `VK` не является конструктором, но является объектом
Поэтому приходится делать `VK.VK`
Соответственно, если у вашего коллеги другая версия nodejs, то возникают казусы

Запуск приложения происходит с флагом `experimental modules`

**Comment by negezor** [comment]
Это связано с обновлением спецификации ESM. Насколько я понял, он теперь требует указание полного пути до .mjs файла.
```js
import VK from 'vk-io/lib/index.mjs';
```
Я немного позже проведу тестирование.

**Comment by AndreiSoroka** [comment]
Сегодня добрались руки.
```
import VK from 'vk-io/lib/index.mjs';
```
Результат
```
> node --experimental-modules -r dotenv/config bin/www.mjs

(node:19028) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/andreisoroka/git/vk-users-service/node_modules/vk-io/lib/index.mjs:12
import { noopNext, getOptionalMiddleware, compose } from 'middleware-io';
                                          ^^^^^^^
SyntaxError: The requested module 'middleware-io' does not provide an export named 'compose'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:93:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:108:20)
    at async Loader.import (internal/modules/esm/loader.js:128:24)
```

**Comment by negezor** [comment]
В целом это не совсем точно является костылём. Я поступаю абсолютно так же в самом модуле. Так как по умолчанию весь экспорт **CJS** находится в `default` для **MJS** модулей.

https://github.com/negezor/vk-io/blob/master/packages/vk-io/src/upload/index.js#L3-L5
https://github.com/negezor/vk-io/blob/master/packages/vk-io/src/upload/index.js#L21-L23

На текущий момент единственное что остаётся, это ждать пока стандарт **MJS** станет более популярным. Следуя из того что описано в [документации](https://nodejs.org/docs/latest/api/esm.html#esm_package_entry_points) насчёт входных точек:

> The `"main"` field can point to exactly one file, regardless of whether the
package is referenced via `require` (in a CommonJS context) or `import` (in an
ES module context). Package authors who want to publish a package to be used in
both contexts can do so by setting `"main"` to point to the CommonJS entry point
and informing the package’s users of the path to the ES module entry point. Such
a package would be accessible like `require('pkg')` and `import
'pkg/module.mjs'`. Alternatively the package `"main"` could point to the ES
module entry point and legacy users could be informed of the CommonJS entry
point path, e.g. `require('pkg/commonjs')`.

Более или менее требует явного определение файлов библиотеки, что для кодовой базы не позволительная порой роскошь. Так как библиотека может менять своё внутреннее строение.

Так что я повременю с полным переходом на **MJS**. Так как стандарт **MJS** на текущий момент очень неудобен без всяких транспайлеров Babel, TypeScript, бандлеров Rollup, Webpack. Я закрою этот вопрос, пока не будет других деталей реализации стандартного импорта.

А ещё так наверное будет более приглядно выглядеть.
```js
import vkIo from 'vk-io';

const { VK } = vkIo;

const vk = new VK();
```

**Comment by testnamefuckgithub** [comment]
www.npmjs.com/package/esm
вам в помощь.
