### ISSUE TITLE
Ошибка метода wall.getById

### ISSUE THREAD

**Issue by RomanJarckov** [negezor/vk-io#177]
При вызове данного метода выдает ошибку, хотя токен задан: 
UnhandledPromiseRejectionWarning: APIError: Code №27 - Group authorization failed: method is unavailable with group auth.
====
var data = await vk.api.wall.getById({
		posts: '-170730674_1082',
		extended: 1
});    
=====

**Comment by negezor** [comment]
В ошибке же написано, данный [метод](https://vk.com/dev/wall.getById) недоступен для токена сообщества. Его можно вызвать только с перечисленных типов токена:
![image](https://user-images.githubusercontent.com/9392723/60903882-db1adc00-a2bd-11e9-8f35-6563e9de8100.png)

**Comment by RomanJarckov** [comment]
Могу ли задать сервисный ключ?

**Comment by negezor** [comment]
Да, он в настройках приложения есть.

**Comment by negezor** [comment]
Я закрою этот вопрос, поскольку нет ответа. Не стесняйтесь открыть его вновь.
