### ISSUE TITLE
Использование .editMessage

### ISSUE THREAD

**Issue by Hypuxxx** [negezor/vk-io#179]
Не очень понятно как использовать .editMessage
Получаю ошибку 15 Access denied при попытке отредактировать сообщение
```js
context.send(text);
context.editMessageText(`test`);
```

**Comment by negezor** [comment]
Если говорить про беседу, то там невозможно отредактировать сообщение, ввиду того что отсутствует идентификатор сообщения `(context.id === 0)`. Но это должно работать для личных сообщений.

**Comment by Hypuxxx** [comment]
```js
hearCommand('test', async (context) => {
    context.send(`test`);
    context.editMessageText(`testdsdasds`);
})
```
Получаю ошибку 15, хотя все права в LongPoll установлены.
С использованием await, ошибки нет но сообщение не редактируется.
```js
hearCommand('test', async (context) => {
    await context.send("test");
    await context.editMessageText(`testdsdasds`);
});
```

**Comment by negezor** [comment]
А можно полную ошибку?

**Comment by Hypuxxx** [comment]
(node:27680) UnhandledPromiseRejectionWarning: ExecuteError: Code №15 - Access denied

**Comment by negezor** [comment]
А куда именно боту пишешь, в ЛС или в беседе? Какая версия API включена для Bots Long Poll?

**Comment by Hypuxxx** [comment]
Пишу в лс, версия 5.101 (последняя)

**Comment by negezor** [comment]
Я забыл сказать о самом главном, редактируется текущее сообщение, а не новое. Если взять исходящее сообщение бота, то оно будет отредактировано. Демонстрационный пример:
```js
vk.updates.on('message', async (context) => {
	if (context.isOutbox) {
		await context.editMessageText('World!');

		return;
	}

	await context.send('Hello');
});
```

**Comment by DZ8540** [comment]
На сегодняшний день, этот пример, к сожалению, не работает :(
