### ISSUE TITLE
Ошибка метода wall.get при call:'execute'

### ISSUE THREAD

**Issue by HaselLoyance** [negezor/vk-io#18]
Имеется такой код, где `<token>` - токен со страницы  приложения:

```
let VKService = new VK({
	token: <token>,
	call: 'execute'
});
```

Вызов метода wall.get через 
`VKService.api.wall.get({ owner_id: 1 })`
Возвращает ошибку доступа `28 Application authorization failed: method is unavailable with service token.
`
Если же сменить call на api, то всё работает без ошибок

**Comment by Lisennk** [comment]
+

Ещё такая ошибка была у нас:
```
code: 28,
params: 
[ { key: 'oauth', value: '1' },
{ key: 'method', value: 'execute' },
{ key: 'lang', value: '' },
{ key: 'v', value: '5.63' },
{ key: 'code',
value: 'return [API.wall.get({"owner_id":-144252945,"count":3})];' } ] }
```

**Comment by negezor** [comment]
Подозреваю что проблема в самом ограничение ВКонтакте API на метод execute, там указано:
```
Этот метод можно вызвать с ключом доступа пользователя.
Этот метод можно вызвать с ключом доступа сообщества.
```
Так как с `call: api` вызов `wall.get` единичен.
