### ISSUE TITLE
[Бот не видит сообщения из беседы]

### ISSUE THREAD

**Issue by PetrenkoNotValid** [negezor/vk-io#183]
[Бот не видит сообщения из беседы] Использую самый простой пример в лс группы с ботом, все работает, а в попытке проверить в беседе бот просто не видит сообщений.

![image](https://user-images.githubusercontent.com/52258477/62519694-4e305780-b856-11e9-8d0c-fae95c3febb5.png)

**Comment by negezor** [comment]
Должно быть что-то одно `updates.start()` или `updates.startPolling()`. В первом варианте запустится User Long Poll так как не указан `pollingGroupId`, во втором случае он будет поставлен автоматический и запустится Bots Long Poll.

**Comment by PetrenkoNotValid** [comment]
То-есть нужно убрать updates.start?

**Comment by PetrenkoNotValid** [comment]
Сделал вот так но проблема осталась

![image](https://user-images.githubusercontent.com/52258477/62522523-11675f00-b85c-11e9-8d07-ac8d1d46ca12.png)

**Comment by negezor** [comment]
![image](https://user-images.githubusercontent.com/9392723/62524869-1dfeae00-b882-11e9-8410-8d177e033499.png)

**Comment by PetrenkoNotValid** [comment]
Убрал но проблема осталась, в лс бот работает, а в беседе не хочет

**Comment by PetrenkoNotValid** [comment]
Тип вот так бот вообще не работает даже в лс

![image](https://user-images.githubusercontent.com/52258477/62525441-9dc85080-b861-11e9-9a35-d4e401dd6e56.png)

**Comment by PetrenkoNotValid** [comment]
А если в конце заменяю vk.updates.start на vk.updates.startPolling то снова работает в лс, а в беседе по прежнему ничего

**Comment by PetrenkoNotValid** [comment]
А все я тупой не увидел в группе в вк в настройках вкладку с событиями, теперь все работает. Спасибо за помощь
