### ISSUE TITLE
Какой синтаксис настройки Standalone-приложения?

### ISSUE THREAD

**Issue by VovaDDOS** [negezor/vk-io#184]

**Comment by negezor** [comment]
[Опции авторизация](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/vk.md#%D0%BE%D0%BF%D1%86%D0%B8%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8), [пример авторизации](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/auth.md#implicit-flow-user).
