### ISSUE TITLE
Как вытащить тип прикрепления из сообщения

### ISSUE THREAD

**Issue by PetrenkoNotValid** [negezor/vk-io#185]
При отправке голосового сообщения боту хочу вытащить тип этого прикрепления

`vk.updates.on('message', (context, next) => {
	console.log(context.attachments)
	return next();
});`

При отправке голосового сообщения боту мне приходит в console.log(context.attachments) следующее -> 

![image](https://user-images.githubusercontent.com/52258477/62688105-6b019200-b9f2-11e9-9721-d8551e96b906.png)

Как можно вытащить этот тип прикрепления AudioMessageAttachment из этого json?

Сначала пробовал вытащить его context.type но он выводит просто message, т.е это не то
Т.е простыми словами мне нужно вытащить название типа прикрепления из этого json
Реализуемо?

**Comment by negezor** [comment]
```
vk.updates.on('message', (context, next) => {
  console.log(audioMessage); // Возвращает массив такого типа

  return next();
});
```

**Comment by PetrenkoNotValid** [comment]
negezor спасибо большое
