### ISSUE TITLE
Обработка ивента app_payload

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#189]
При попытке обработки ивента app_payload ничего не происходит.

`
vk.updates.on('app_payload', async (context) => {
console.log(context)
});
`

В дебаге получаю: `Unsupported webhook context type app_payload`

В библиотеке есть возможность обработки этого ивента?

**Comment by negezor** [comment]
Скоро будет опубликовано https://github.com/negezor/vk-io/commit/28e5ae4521d8baafddd5abf3e7769860c1743435
