### ISSUE TITLE
Как узнать событие?

### ISSUE THREAD

**Issue by PetrenkoNotValid** [negezor/vk-io#190]
Как можно отловить события вк?
Попробовал много способов но не получилось

**Comment by PetrenkoNotValid** [comment]
Точнее как отловить так называемый source_act

**Comment by negezor** [comment]
Используется source_act только в User Long Poll, а в объекте сообщения [action](https://vk.com/dev/objects/message). А событие это обычный `message`, в контексте есть геттер `context.isEvent` и соответственно с ним события.

**Comment by negezor** [comment]
Я закрою issue так как нет активности.
