### ISSUE TITLE
Ошибки с WebPack

### ISSUE THREAD

**Issue by xTCry** [negezor/vk-io#191]
### При упаковке WebPack'ом вылазят ошибки...

__build.js__
```js

const webpack = require('webpack');
const webpackConfig = require("./webpack.config.js");

(async () => {
    // WebPack src
    try {
        console.log("[WebPack] Start");
        await new Promise((resolve, reject) => {
            webpack(webpackConfig, async (err, stats) => {
                if (err || stats.hasErrors()) {
                    reject(err || stats.compilation.errors || stats)
                }
                resolve()
            })
        });
    } catch (e) {
        console.error("[WebPack] Error\n", e);
        process.exit()
    }
    console.log("[WebPack] Done");
})();
```

__index.js__
```js
import { VK } from "vk-io";
VK.token = false;
```

__webpack.config.js__
```js
const path = require('path');

module.exports = {
	mode: 'production',
	entry: './index.js',
	target: 'node',
	output: {
		filename: 'index.js',
		path: path.resolve(__dirname, 'dist/'),
	},
}
```

> ModuleDependencyError: Can't import the named export '`Agent`' from non EcmaScript module (only default export is available)
> ModuleDependencyError: Can't import the named export '`PassThrough`' from non EcmaScript module (only default export is available)
> ModuleDependencyError: Can't import the named export '`Readable`' from non EcmaScript module (only default export is available)
> ModuleDependencyError: Can't import the named export '`URLSearchParams`' from non EcmaScript module (only default export is available)
> ModuleDependencyError: Can't import the named export '`inspect`' from non EcmaScript module (only default export is available)

![image](https://user-images.githubusercontent.com/5994290/63215216-28dffb00-c12c-11e9-923c-9e5268769609.png)

**Comment by isinkin** [comment]
Тебе вебпак пишет в чём проблема, да и зачем вообще собирать VK-IO через вебпак?

**Comment by xTCry** [comment]
> Тебе вебпак пишет в чём проблема, да и зачем вообще собирать VK-IO через вебпак?

Собирал большой проект через WebPack. Была куча ошибок при сборке в других модулях.
Пока фиксил другие, не мог толком понять какая тут ошибка и думал тут быстрее решение получу

**Comment by Nekonyx** [comment]
@xTCry попробуйте собрать ещё раз. Проблема решена?

**Comment by negezor** [comment]
Стоит попробовать сбилдить на v4.0.0

**Comment by isinkin** [comment]
@negezor, предлагаю закрыть issue.
