### ISSUE TITLE
Getting default AuthError. Wrong default auth scope

### ISSUE THREAD

**Issue by npyramid** [negezor/vk-io#192]
#### What version of `vk-io` are you using?
4.0.0-rc.20

Доброго времени суток. Просидел около часа прежде чем поставить брейкпоинт в пакете.

Суть:
Использую ImplicitFlowUser.
В процессе авторизации упала ошибка VK.

```
{"error":"invalid_request","error_description":"This application has no right to use messages"}
```
Вместо того чтобы отдать полученный от vk ответ с ошибкой о том, что права на messages имеют только избранные приложения, отдает дефолтную ошибку "Could not log in".

Что ожидалось:
Упадет обернутая ошибка vk с настоящим мессаджем проблемы;
По дефолту не должно быть authScope === 'all'  (https://vk.com/faq13567)

Спасибо.

**Comment by negezor** [comment]
А какие есть предположения для стандартного scope?

**Comment by isinkin** [comment]
> А какие есть предположения для стандартного scope?

бросать ошибку, если юзер не указал необходимый скоп

**Comment by npyramid** [comment]
> А какие есть предположения для стандартного scope?
Судя по документации должен быть `all!messages` что-то вроде такого

**Comment by negezor** [comment]
Реализовано https://github.com/negezor/vk-io/commit/a8ebc240c8f81f0eb59b725847856298b93d2164
