### ISSUE TITLE
Ошибка: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by Bezlepkin** [negezor/vk-io#194]
#### What version of `vk-io` are you using?
vk-io: 4.0.0-rc.20

#### What version of Node.js are you using?
10.16.3

#### What did you do?
Пытаюсь импортировать библиотеку в Vue

#### What was the actual result?
`in ./node_modules/vk-io/lib/index.mjs

Module parse failed: Unexpected token (167:18)
You may need an appropriate loader to handle this file type.
| 	constructor(method, params = {}) {
| 		this.method = method;
| 		this.params = { ...params };
| 
| 		this.attempts = 0;
`

**Comment by negezor** [comment]
Библиотека работает только в среде Node.js, не для браузеров.
