### ISSUE TITLE
.deleteMessage

### ISSUE THREAD

**Issue by sugatsky** [negezor/vk-io#198]
Привет!
Можно подробнее о deleteMessage?

Мне нужно, чтобы по определенной команде (допустим, clear) бот удалял все свои сообщения в чате.
Наглядный пример будет очень кстати.

**Comment by negezor** [comment]
Невозможно, так как для ботов не хранится переписка. Возможно в будущем будет возможно.

**Comment by sugatsky** [comment]
Окей, спасибо
