### ISSUE TITLE
hasForwards

### ISSUE THREAD

**Issue by sugatsky** [negezor/vk-io#199]
Можно подробнее о hasForwards, пожалуйста?
Пытался научить бота закреплять сообщения, но получал ошибку (он должен был закреплять то сообщение, которое ему переслали)
![DshhuPG_ryM](https://user-images.githubusercontent.com/55203801/64984788-93738a80-d8d4-11e9-8de7-50fa6de2192e.jpg)
Или тут так же, как с deleteMessage в чатах?

**Comment by negezor** [comment]
Для ботов не хранится переписка, а соответственно id будет равено `0`. По этому сделать всё что использует id - не получится.

**Comment by sugatsky** [comment]
Тогда зачем оно прописано в документации?

**Comment by sugatsky** [comment]
Почему ВКонтакте говорит, что этот метод юзать от сообщества, если сообщения для него не хранятся?
![i-GcBxiY0BE](https://user-images.githubusercontent.com/55203801/65055577-7d230880-d980-11e9-903b-0b59d68aa2dd.jpg)

**Comment by jarvis394** [comment]
У ВК много проблем с документацией; напиши им в поддержку.

**Comment by negezor** [comment]
Нам только остаётся ждать введения аналогов для использования этих методов.
