### ISSUE TITLE
MessageForward doesn't have an 'id' field

### ISSUE THREAD

**Issue by jarvis394** [negezor/vk-io#200]
#### What version of `vk-io` are you using?
latest v4.0.0-rc.20

#### What version of Node.js are you using?
v10.x.x

У `MessageForward` отсутствует поле `id`, свойственное для сообщений. Если смотреть через `context.payload`, все на месте.

**Comment by negezor** [comment]
Этого поля не должно быть, когда ВКонтакте начала перерабатывать пересланные сообщения. Там стали хранить только копию сообщения, и вместо ID приходит `0`. Но для `ReplyMessage` должен быть `conversationMessageId`.
