### ISSUE TITLE
Получить group_id инста

### ISSUE THREAD

**Issue by Aleksey-Danchin** [negezor/vk-io#201]
Как получить id инста VK? Я создаю `vk`

```
const vk = new VK({ token: "..." })
```

А как потом мне получить `group_id` из `vk`?

**Comment by negezor** [comment]
Как вариант вызвать метод:
```js
const [group] = await this.vk.api.groups.getById();

const groupId = group.id;
```

**Comment by Aleksey-Danchin** [comment]
Ну да, в целом работает, спасибо. Может есть метод очевиднее? Или этот метод гарантированно при авторизации через токен группы будет всегда возвращать массив с 1 элементом?

**Comment by Aleksey-Danchin** [comment]
И на будущее, такие вещи не в issues надо задать, а на каком-нибудь stackoverflow или мессенджере, где лучше? Где есть живое сообщество?

**Comment by isinkin** [comment]
> Ну да, в целом работает, спасибо. Может есть метод очевиднее? Или этот метод гарантированно при авторизации через токен группы будет всегда возвращать массив с 1 элементом?

Если метод будет вызван от токена группы, то да

**Comment by negezor** [comment]
В целом это пока единственный способ который я знаю, что-бы получить ID сообщества с токена. А вопрос в целом можно писать тут, или на toster.
