### ISSUE TITLE
Авторизация от имени пользователя

### ISSUE THREAD

**Issue by Aleksey-Danchin** [negezor/vk-io#202]
Пытаюсь авторизоваться от имени пользователя. В принципе в [опции авторизации](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/vk.md#%D0%BE%D0%BF%D1%86%D0%B8%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8) есть возможность по `login/password` или `phone/password` авторизоваться. Но что-то не срабатывает.

```
new VK({
	phone: config.get('phone'),
	password: config.get('password')
})
```

```
(node:32655) UnhandledPromiseRejectionWarning: APIError: Code №5 - User authorization failed: invalid access_token (4).
    at API.callMethod (/home/old/Desktop/Porka/backend/node_modules/vk-io/lib/index.js:1764:30)
```

`access_token` нужно запросить у vk отдельно? И как тогда его передать? Вместе с `token` полем?

P.S. `config` правильный, перепроверял.

**Comment by negezor** [comment]
Нужно авторизоваться через [Direct](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/auth.md#direct) или [Implicit Flow User](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/auth.md#implicit-flow) и потом передать токен в экземпляр класса.

**Comment by negezor** [comment]
Я закрой вопрос из-за не активности.
