### ISSUE TITLE
Как правильно сделать выход из сцены?

### ISSUE THREAD

**Issue by wnull** [negezor/vk-io#203]
Есть следующая сцена, на первом шаге посылается клавиатура с отменой (команда `cancel`. Как правильно реализовать данную команду?). Нужно, чтобы при нажатии на кнопку произошел выход из сцены и послано другое меню (команда `update`). Буду признателен за помощь.

```javascript
sceneManager.addScene(new StepScene('createProfile', [
	(context) => {
		if (context.scene.step.firstTime || !context.text) {
			context.send({
				message: 'Укажи идентификатор значка',
				keyboard: Keyboard.keyboard([
					[
						Keyboard.textButton({
							label: 'Отменить',
							payload: {
								command: 'cancel',
							},
							color: Keyboard.NEGATIVE_COLOR
						})
					]
				])
			});
		}

		context.scene.state.mark = context.text;

		return context.scene.step.next();

	},
	async (context) => {
		const { mark } = context.scene.state;
		await context.send({
			message: `Ваш значок (${mark})!`,
			keyboard: Keyboard.keyboard([
				[
					Keyboard.textButton({
						label: 'Вернуться в главное меню',
						payload: {
							command: 'update',
						},
						color: Keyboard.NEGATIVE_COLOR
					})
				]
			])
		});

		await context.scene.leave();
	}
]));
```

**Comment by negezor** [comment]
В примере есть глобальный обработчик отмены.
```js
vk.updates.on('message', (context, next) => {
	if (!context.scene.current) {
		return next();
	}

	const cancel =  context.messagePayload && context.messagePayload.command === 'cancel';

	if (cancel) {
		return context.scene.leave({
			canceled: true
		});
	}

	return context.scene.reenter();
});

// вместо
// vk.updates.on('message', sceneManager.middlewareIntercept);
```
Ещё у сцен есть leaveHandler который можно передать в качестве опций:
```js
sceneManager.addScene(new StepScene('signup', {
  steps: [ /* Обработчики */ ],
  leaveHandler(context) {
    if (context.scene.canceled) {
      // Сцена отмена
   } else {
      // Сцена полностью завершила сценарий
   }
  }
});
```
К тому же в коде ошибка и там сразу вызывается следующая сцена, поправить можно так:
```diff
sceneManager.addScene(new StepScene('createProfile', [
	(context) => {
		if (context.scene.step.firstTime || !context.text) {
-			context.send({
+			return context.send({
				message: 'Укажи идентификатор значка',
				keyboard: Keyboard.keyboard([
```

**Comment by wnull** [comment]
@negezor, спасибо за поправку сцены, но у меня возникает следующая ошибка, когда заменяю обработчик отмены. С чем это может быть связано?
```
Handle polling update error: TypeError: Cannot read property 'reenter' of undefined
```

**Comment by wnull** [comment]
@negezor, спасибо за поправку сцены, заменив обработчик, и после вызова кнопки отмены (команда `cancel`) вообще ничего не происходит.  В чем причина? Вот на случай [полный код](https://vk.cc/9QxC4Z).
![Безымянный](https://user-images.githubusercontent.com/33278849/65666387-3e5b1580-e046-11e9-8938-09a1ad84b84b.png)

**Comment by negezor** [comment]
Ну так фактический сцена отменяется и ничего больше она и не должна делать. Как я уже сказал, для дополнительной логики можно дополнить сам вход в сцену глобальный или использовать `leaveHandler()`.

**Comment by wnull** [comment]
@negezor, пойду разбираться, благодарю за консультацию.
