### ISSUE TITLE
Сообщение не отправляется при использовании intent параметра к сообщению 

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#204]
Пытаемся передать в .send() параметр **intent**
Сообщение не отправляется.
https://vk.com/dev/bots_docs_4?f=5.%2B%D0%98%D0%BD%D1%82%D0%B5%D0%BD%D1%82%D1%8B
![](https://user-images.githubusercontent.com/42776347/65683325-52336580-e0a0-11e9-9f24-967c77097196.png)
https://vk.com/dev/bot_rules?f=%D0%9C%D0%BE%D0%BD%D0%B5%D1%82%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F+%D0%B1%D0%BE%D1%82%D0%BE%D0%B2
![Аннотация 2019-09-26 210039](https://user-images.githubusercontent.com/42776347/65683525-bf46fb00-e0a0-11e9-8a9d-db3f208b7aa0.png)
```js
context.send({
        message: `123`,
        intent: "promo_newsletter"
    });

**Comment by negezor** [comment]
ВКонтакте криво косо сейчас с этим работает, по этому это не касается библиотеки на данный момент.
