### ISSUE TITLE
APIError: file is undefined при отправки аудиосообщения с диска

### ISSUE THREAD

**Issue by Salaron** [negezor/vk-io#205]
#### What version of `vk-io` are you using?

4.0.0-rc.20

#### What version of Node.js are you using?
10.16.3

При попытке отправить аудио с диска возвращает ошибку *APIError: Code №100 - One of the parameters specified was missing or invalid: file is undefined*
```js
await context.sendAudioMessage({
     value: readFileSync("./temp.ogg")
})
```
При использовании *vk.upload.audioMessage* та же история получается.

Причём если использовать ссылку, то никаких проблем нет.
```js
await context.sendAudioMessage({
      value: "http://ronsen.org/purrfectsounds/purrs/chicken.mp3"
})
```

Или я что-то делаю не так?

**Comment by negezor** [comment]
Есть вероятность что файл битый.

**Comment by Salaron** [comment]
Действительно, в этом вся проблема. Я был уверен, что с файлом всё ок, но это оказалось не так.
Спасибо!
