### ISSUE TITLE
setHearFallbackHandler

### ISSUE THREAD

**Issue by sugatsky** [negezor/vk-io#206]
Можно наглядный пример использования setHearFallbackHandler?
У меня он реагирует на все сообщения :(

**Comment by negezor** [comment]
Обработчик в `setHearFallbackHandler` вызывается в конце цепочки hear если не один обработчик в `.hear()` не был перехвачена. Это фактический всё что нужно о нём знать.

**Comment by sugatsky** [comment]
Если вставлять его в конец - он не работает вообще.
Если в самом начале - реагирует на любое сообщение, кроме команды.

**Comment by negezor** [comment]
Но вы ведь владеете основами JS? Можно например в чате отключить отправку:
```js
vk.updates.setHearFallbackHandler(async (context, next) => {
	if (context.isChat) {
		return;
	}       

	await context.send('Такой команды нет :(');
});
```

**Comment by negezor** [comment]
Я закрою этот вопрос из-за не активности, не стесняйтесь открыть его снова.

**Comment by keyzt** [comment]
На самом деле достаточно в настройках longpoll отключить пункт "Исходящие сообщения".
