### ISSUE TITLE
context.send не возвращает идентификатор сообщения?

### ISSUE THREAD

**Issue by fipnooone** [negezor/vk-io#208]
> Отправляет сообщение в текущий диалог
> `context.send(text [, params]); // => Promise<number>`

Мне кажется, что логично было бы возвращать то, что описано в vk.com/docs/messages.send

`updates.hear(/.*/, (msg) => {
  msg.send('1').then(x => console.log(x))
});`

На выходе получаем, как я могу предположить, id сообщения в диалоге. Но зачем? Как тогда, например, изменить сообщение после его отправки?

**Comment by isinkin** [comment]
Вы гений мысли. 
1) Не vk.com/docs/messages.send, а https://vk.com/dev/messages.send
2) Метод после успешного выполнения возвращает идентификатор отправленного сообщения.
3) Вы можете изменять сообщение после отправки:
```js
await context.send('hello!');

await delay(10000);

await context.editMessageText('world!');
```

**Comment by fipnooone** [comment]
> Вы гений мысли.
Да, подумал немного у другом, когда писал ссылку.  

> Метод после успешного выполнения возвращает идентификатор отправленного сообщения.
Идентификатор вида, например: "160", который прибавляет каждый раз то количество сообщений, которое было отправлено в диалог? По-моему это id сообщения в беседе, а не id сообщения в вк, который выглядит как "552885".

**Comment by negezor** [comment]
Для каждого нового бота ID истории будет начинаться с 1, а на текущий момент в чатах возвращается `0`. Это специфика ВКонтакте, по этому на неё сложно будет как-то повлиять.
