### ISSUE TITLE
upload.video для сторонних сервисов

### ISSUE THREAD

**Issue by Antosik** [negezor/vk-io#21]
При использовании upload.video для видео с Youtube, Rutube, Vimeo метод при удачной загрузке возвращает лишь `1`, а не всю информацию.

Например:
 ```
vk.upload.video({
      group_id,
      source: link,
      name,
      description,
      album_id,
      link,
      no_comments: 1,
})
```
вернет `1`, а в логах: `vk-io:api Request video.save took 157ms of time +4s`

Данная фича не предусмотрена? Или мой запрос построен некорректно?

**Comment by negezor** [comment]
В таком случае думаю это было не предусмотрено, так как это результат удачной загрузки, но дело в том при указание свойства "link" идёт сохранение напрямую со внешнего сервиса.

**Comment by negezor** [comment]
Исправлено в версии 3.1.6, обновитесь.
