### ISSUE TITLE
vk.collect.groups.getById is not a function

### ISSUE THREAD

**Issue by avalsoff** [negezor/vk-io#210]
Добрый день, подскажите пожалуйста, тайпинги не соответствуют коду или у меня что-то не установилось?
[
<img width="410" alt="Screenshot 2019-10-04 at 23 09 51" src="https://user-images.githubusercontent.com/37933607/66236869-4416c200-e6fc-11e9-986c-aad644cf8f3f.png">
](url)

**Comment by negezor** [comment]
Добрый, типы методов наследуются от `API` (что не совсем верно). Коллекции нужно использовать с методами которые поддерживают offset/limit, для всего остального просто `vk.api`

**Comment by avalsoff** [comment]
Спасибо, разобрался
