### ISSUE TITLE
Невозможно отправить определенный файл документом.

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#211]
Пытаюсь отправить документом файл, при это получаю ошибку. Другие файлы идентичного формата и размера отправляются нормально.

Также он нормально загружается через upload.messageDocument.

Рабочий файл: http://textures.minecraft.net/texture/dc1c77ce8e54925ab58125446ec53b0cdd3d0ca3db273eb908d5482787ef4016

Ломаный файл: http://textures.minecraft.net/texture/c4bbd505227b2a2ddc1aa803da327d4784e004c4b4087ef88ba3102d2e24b504

vk-io 4.0.0 rc-21
```js
return context.sendDocument({
                    value: ("http://textures.minecraft.net/texture/c4bbd505227b2a2ddc1aa803da327d4784e004c4b4087ef88ba3102d2e24b504"),
                    filename: `${res.data.username}.png`,
                }, {
                    message: `[public175914098|📸 Скин ${name}]`
                });
TypeError: Cannot read property 'owner_id' of undefined
    at new DocumentAttachment (C:\Users\Пронин Егор\Desktop\steve\node_modules\vk-io\lib\index.js:3716:33)
    at Upload.messageDocument (C:\Users\Пронин Егор\Desktop\steve\node_modules\vk-io\lib\index.js:4370:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by negezor** [comment]
Я протестировал и по непонятным причинам возвращается `graffiti` вместо документа.
![image](https://user-images.githubusercontent.com/9392723/66371495-044b2580-e9ef-11e9-8160-82ceea09fba9.png)
