### ISSUE TITLE
После обновления перестал работать LP

### ISSUE THREAD

**Issue by zombieserv** [negezor/vk-io#216]
Добрый вечер.
Ситуация следующая: обновил модуль (для работы с inline), и после обновления при получении сообщений имею это:

> Handle polling update error: TypeError: Cannot read property 'text' of undefined
    at MessageContext.applyPayload (C:\Users\BuTaMuH\Desktop\VKBots\node_modules\vk-io\lib\index.js:6776:37)
    at new MessageContext (C:\Users\BuTaMuH\Desktop\VKBots\node_modules\vk-io\lib\index.js:6200:14)
    at Updates.handleWebhookUpdate (C:\Users\BuTaMuH\Desktop\VKBots\node_modules\vk-io\lib\index.js:8965:40)
    at response.updates.forEach (C:\Users\BuTaMuH\Desktop\VKBots\node_modules\vk-io\lib\index.js:8476:28)
    at Array.forEach (<anonymous>)
    at PollingTransport.fetchUpdates (C:\Users\BuTaMuH\Desktop\VKBots\node_modules\vk-io\lib\index.js:8474:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Подумал, быть может, у меня в коде что-то неактуальное и/или нерабочее (давно не обновлял версию), попробовал шаблон [отсюда](https://github.com/negezor/vk-io/blob/65299de5bd4eeb1dccf088f788cd0d022301ab12/docs/examples/simple-updates-bot.js), аналогично.
В чём может быть проблема?

Единственные изменения, которые видно невооруженным взглядом:
await vk.updates.startPolling();
=>
await vk.updates.start().catch(console.error);

Извиняюсь, если вопрос глупый, но решения пока не вижу.
Заранее благодарю.

**Comment by xTCry** [comment]
При запуске через `vk.updates.start()` автоматически определяется чей токен был отправлен ( группы или пользователя) и, если был токен группы, то модуль сам получает ID этой группы.

При запуске через `vk.updates.startPolling()`, если ID группы (`pollingGroupId`) не был передан в опции, то модуль считает, что это токен пользователя...

Проблема в том, что если модуль запущен для группы, то `pollingTransport` подписывается на событие `handleWebhookUpdate`, а в нем событие `message_new` приносит объект payload  который `applyPayload` не ожидал.

Поэтому пока что запускаем через `startPolling` без передачи `pollingGroupId`.

_И ждем фикс для `handleWebhookUpdate`._

**Comment by zombieserv** [comment]
Спасибо за ответ, это действительно решило проблему, но только для ЛС с сообществом.
LP сообщества в беседах в этом случае не работает.
И как быть?

**Comment by negezor** [comment]
На самом деле нужно установить версию API в Bots Long Poll на v5.103. Я сделаю обратную совместимость.

**Comment by xTCry** [comment]
@zombieserv, в самом сообществе ВКонтакте надо не забыть поменять версию API на `5.103` и будет все отлично
![image](https://user-images.githubusercontent.com/5994290/67929190-cb593780-fbcd-11e9-8ce6-e441cd54ab5c.png)

**Comment by zombieserv** [comment]
Спасибо большое, решено!
