### ISSUE TITLE
Не работает LongPoll (почти все возвращается null)

### ISSUE THREAD

**Issue by TheNevikatYT** [negezor/vk-io#219]
#### Я пытаюсь слушать события LongPoll.
`vk.updates.on(['new_message'], async (context, next) => {
  if (Number(context.senderId) <= 0) return;
  console.log(context);
  next();
});`

pollingGroupId я указываю.

В консоли:
`MessageContext {
  id: undefined,
  conversationMessageId: null,
  peerId: undefined,
  peerType: 'user',
  senderId: undefined,
  senderType: 'user',
  createdAt: undefined,
  text: null,
  forwards: MessageForwardsCollection [],
  attachments: [],
  isOutbox: false,
  type: 'message',
  subTypes: [
    'new_message'
  ],
  state: {}
}`

Если не указывать `pollingGroupId` и изменить событие на `message`, то работает, но другие события Bots LongPoll не работают.

**Comment by TheNevikatYT** [comment]
Решилось выбором версии vkapi 5.101 вместо 5.103.

**Comment by xTCry** [comment]
Запуская функцией 
`updates.start()` можно не указывать id группы, т. к. он получается автоматически

И поставь версию обратно на 5.103
