### ISSUE TITLE
Авторизация. Документация.

### ISSUE THREAD

**Issue by alexmww** [negezor/vk-io#220]
Интересный модуль, замечательная архитектура, но...
Я потратил час на то, чтобы запустить hello world. В первую очередь это кончено связано с моими когнитивными способностями, но давайте взглянем на документацию.

Первое, что мы видим:
```
const vk = new VK({
	token: process.env.TOKEN
});
```
Отлично. Что такое токен? Где его взять?
Смотрим документацию. Страницу Auth. Замечаем интересную строчку `Так же присутствуют заданные приложения по умолчанию для прямой авторизации` - где они заданы непонятно.

Находим реализацию Implicit Flow Отлично, теперь токен нам не нужен
```
vk.setOptions({
	appId: process.env.APP,
	login: process.env.LOGIN,
	password: process.env.PASSWORD
});
```
Запускаем. Deprecated. Ладно. Подключаем новый модуль.
Запускаем. Ошибка. authScope не указан. Ладно. Указываем.
Запускаем. Токен выводится в консоль, но мы получаем ошибку авторизации. Проверяем:

```
const vk = new vk_io.VK({
    appId: '***',
    login: '***',
    password: '***',
    authScope: 'offline,wall'
});

const auth = new vk_io_auth.Authorization(vk);
const implicitFlow = auth.implicitFlowUser();

implicitFlow.run()
    .then((response) => {
        console.log(response.token); // выводится, все супер
    })
    .then(r => {
        console.log(vk.token); // null !!!
    })
    .catch(error => console.log(error)); 
```

То есть, предполагается, что сохранять токен я буду руками? Это есть хоть в одном примере? Ладно, сохраняем
```
        vk.token =  response.token;
```
Работает.

В общем, я считаю, что как минимум Example usage надо подправить, чтобы сразу показать авторизацию по номеру и паролю. Посмотрите как выглядит readme у аналогичной библиотеки для питона: https://github.com/python273/vk_api
Одна минута и все завелось.

**Comment by xTCry** [comment]
Никаких проблем не возникало.

**Comment by negezor** [comment]
Библиотека в первую очередь рассчитана на сообщества, но так же поддерживает работу с пользователем. Работа с авторизацией вынесена в отдельный модуль для библиотеки [@vk-io/authorization](https://github.com/negezor/vk-io/tree/master/packages/authorization) что бы уменьшить размер основной библиотеки.

У меня сейчас не так много времени что бы обновить документацию. Но библиотека не предполагает внутренние реализации сессий.

**Comment by negezor** [comment]
Я закрою этот вопрос в пользу https://github.com/negezor/vk-io/issues/255
