### ISSUE TITLE
Документация по Модулю API

### ISSUE THREAD

**Issue by Pahanovskill** [negezor/vk-io#221]
Доброго дня. 
Начал разбираться с библиотекой и у меня возникла проблема, не понимаю как именно работать с API модулем. 
В [документации](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/api.md) я нашел описание, но не нашел примеры. Возможно это легко и не требует объяснения ( я недавно начал изучать node js и скорей всего не понимаю что-то) Но можно привести пример. Интересует как именно получить информацию с помощью методов VK

	const { VK, Keyboard, api } = require('vk-io');
	function ap(){
		api.call("messages.getConversations", {			
			count: 200,
			filter: 'unread',
			group_id: 'xxx',
			access_token: 'xxx'
		}).then(( {result} ) => {
			console.log(result);
		})
	}

**Comment by isinkin** [comment]
```js
const vk = new VK({
  token: 'XXX'
});

vk.api.messages.getConversations({}).then(console.log).catch(console.error);
```

**Comment by negezor** [comment]
Я закрою этот вопрос из-за не активности. Не стесняйтесь открыть снова.
