### ISSUE TITLE
AuthorizationError: Unsupported type validation

### ISSUE THREAD

**Issue by cyperdark** [negezor/vk-io#224]
#### Что ты сделал?
Скопировал код из примера

#### Чего ты ожидал?
Входа в аккаунт

#### Каков был фактический результат?
Ошибка: https://i.imgur.com/vCeRxb4.png

#### Дополнительная информация
const express = require("express"),
      app = express(),
      { VK } = require("vk-io"),
      { Authorization } = require("@vk-io/authorization");
app.use(express.static("public"));
app.listen(process.env.PORT, () => {console.log('Запущено');});
const vk = new VK({
	appId: process.env.APP_ID,
	appSecret: process.env.APP_SECRET,
	login: process.env.LOGIN,
	password: process.env.PASSWORD,
        authScope: 'offline,wall'
});
const authorization = new Authorization(vk);
async function run() {
	const direct = authorization.direct();
	const response = await direct.run();
	console.log('Token:', response.token);
	console.log('Expires:', response.expires);
	console.log('Email:', response.email);
	console.log('User ID:', response.user);
}
run().catch(console.error);

#### Versions
package.json
{
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.17.1",
    "vk-io": "4.0.0-rc.20",
    "@vk-io/authorization": "^0.0.0-alpha.1"
  },
  "engines": {
    "node": "10.x"
  }
}

**Comment by negezor** [comment]
Прямая авторизация доступна только для проверенных приложений, нужно использовать `authorization.ImplicitFlowUser()`.
