### ISSUE TITLE
Добавляя setHearFallbackHandler на неизвестную команду бот отвечает бесконечным числом сообщений, как исправить?

### ISSUE THREAD

**Issue by LegionLex** [negezor/vk-io#225]
Добавляя:
updates.setHearFallbackHandler(async (context, next) => {
await context.send('Такой команды нет :(');
});

Результат:
Такой команды нет :(
Такой команды нет :(
Такой команды нет :(
Такой команды нет :(
Такой команды нет :(
...
Такой команды нет :(

Как сделать так, чтобы ответ был только один раз?
Желательно на простом примере, спасибо...

**Comment by LegionLex** [comment]
Нашел простое решение...

vk.updates.setHearFallbackHandler(async (context, next) => {
	if (context.isOutbox) {
		return;
	}       

	await context.send('Такой команды нет :(');

**Comment by LegionLex** [comment]
Простое решение...

vk.updates.setHearFallbackHandler(async (context, next) => {
	if (context.isOutbox) {
		return;
	}       

	await context.send('Такой команды нет :(');

**Comment by negezor** [comment]
Варианты решения:
- отключить исходящие сообщения
- добавить это в начало, так как бот может реагировать не только на setHearFallbackHandler()
```js
vk.updates.on('message', async (context, next) => {
  if (context.isOutbox) {
    return;
  }

  return next();
});
````

**Comment by keyzt** [comment]
Самый простой вариант:

- Выключить исходящие сообщения в настройках лп
