### ISSUE TITLE
Ошибка с Longpoll

### ISSUE THREAD

**Issue by fgRuslan** [negezor/vk-io#226]
Время от времени вылезает такая ошибка:

```
Handle polling update error: { ExecuteError: Code â
                                                   113 - Invalid user id
    at request.resolve.errors.map (/root/node_modules/vk-io/lib/index.js:837:73)
    at Array.map (<anonymous>)
    at API.callMethod (/root/node_modules/vk-io/lib/index.js:837:57)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 113, name: 'ExecuteError', method: 'users.get' }
```

Что это значит? Также, тут видно, что ошибка в коде vk-io, а не в моём коде, потому что node не пишет название файла, который выполняется, а пишет названия файлов библиотеки.

**Comment by negezor** [comment]
Ошибка не библиотеке, а не в отловленном исключении на методе `users.get`. В функцию передается значение отличное от INT. Это можно понять по тексту ошибки `113 - Invalid user id`

**Comment by fgRuslan** [comment]
Как понять в какой строке кода произошло исключение?

**Comment by negezor** [comment]
В данном случае сложно сказать, так как вызов происходит уже в следующей итерации `Event Loop`. Стоит глянуть на всё вызываемые `users.get`, и проверить наличие ожидания их обещания.

**Comment by fgRuslan** [comment]
Спасибо <3
