### ISSUE TITLE
forward messages problem

### ISSUE THREAD

**Issue by Pacmard** [negezor/vk-io#227]
#### What did you do?
Логгировал информацию что приходит при получении сообщения (код) 
`vk.updates.on('message', async (data) => {
    console.log(data)
})`

#### What did you expect to happen?
В forwards информация о сообщениях на которые я ответил

#### What was the actual result?
В forwards информация о сообщении появляется, но все значения - 0
    `  forwards: MessageForwardsCollection [
    MessageForward {
      senderId: 0,
      createdAt: 0,
      updatedAt: 0,
      text: null,
      attachments: [],
      forwards: []
    }
  ],`

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `12.13.0` |
| `yarn` or `npm`                    | `npm 6.12.0` |

**Comment by jarvis394** [comment]
@Pacmard, как вы решили проблему? Я тоже с этим столкнулся, стал брал информацию из поля `payload` контекста сообщения (хотя так делать не очень хорошо)

**Comment by negezor** [comment]
@jarvis394, такое поведение свойственно только User Long Poll. Нужно перезагружать сообщения для того чтобы получить полное сообщение.
```js
await context.loadMessagePayload();
```
И если это бот для группы, установить опцию `pollingGroupId` или использовать 
```js
vk.updates.start();
```
Он установит ID группы по умолчанию.

**Comment by Pacmard** [comment]
@negezor <3
