### ISSUE TITLE
middleware-io@2.3.0-2.5.0 breaks package compilation

### ISSUE THREAD

**Issue by daniluk4000** [negezor/vk-io#228]
#### What did you do?
`npm update` to check dependencies update

#### What did you expect to happen?
`middleware-io`@2.3.0 does not break vk-io package

#### What was the actual result?
`node_modules/vk-io/lib/structures/shared/composer.d.ts:2:22 - error TS2417: Class static side 'typeof import("/builds/package/node_modules/vk-io/lib/structures/shared/composer").default' incorrectly extends base class static side 'typeof import("/builds/package/node_modules/middleware-io/lib/composer").Composer'.
  The types of 'builder().middlewares' are incompatible between these types.
    Type 'Middleware<object>[]' is not assignable to type 'Middleware<Context>[]'.
      Type 'Middleware<object>' is not assignable to type 'Middleware<Context>'.
        Type 'object' is not assignable to type 'Context'.
          'object' is assignable to the constraint of type 'Context', but 'Context' could be instantiated with a different subtype of constraint '{}'.
2 export default class Composer extends MiddlewareComposer {`

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `13 or 12` |
| `TypeScript`                       | `3.7.5` |
| `yarn` or `npm`                    | `npm 6.13.4` |

**Comment by negezor** [comment]
Now the library does not support middleware-io@2.3.0. It will only be on release.

**Comment by daniluk4000** [comment]
Temp workaround: freeze middleware-io on version 2.1.0 in your package.json

**Comment by negezor** [comment]
I will close this question in favor of this https://github.com/negezor/vk-io/issues/234
