### ISSUE TITLE
loadMessagePayload не работает

### ISSUE THREAD

**Issue by D0G-HaCk** [negezor/vk-io#229]
При вызове функции loadMessagePayload объект сообщения остаётся неизменным.
Может конечно я что-то не так делаю, но у меня данная функция не работает.

**Comment by negezor** [comment]
Если объект уже полный - он ничего делать и не должен. Как временный вариант подхода можно использовать:
```js
context.$filled = false;

await context.loadMessagePayload();
```
На релизе будет:
```js
await context.loadMessagePayload({
  force: true
});
```

**Comment by negezor** [comment]
Я закрою этот вопрос из-за неактивности, не стесняйтесь открыть его снова.
