### ISSUE TITLE
import error 'vk-io' does not provide VK

### ISSUE THREAD

**Issue by protectedsnow** [negezor/vk-io#231]
Запускал пример с главного readme. На require всё работает, с es6 что-то не так.

```
import {VK} from 'vk-io';
        ^^
SyntaxError: The requested module 'vk-io' does not provide an export named 'VK'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:164:24)
```

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `13.7.0` |
| `TypeScript`                       | `3.7.5` |
| `yarn`                    | `1.21.1` |

**Comment by TheEVolk** [comment]
Добро пожаловать в "стабильный" es6. Лично я юзаю модуль esm на 1.12 версии Node. Это плохо, но не вижу другого выхода.

**Comment by negezor** [comment]
Всё дело в ESM сборке, из-за вноса правок в стандарт - библиотека его уже не поддерживает. Варианты решения, использовать TypeScript/Babel или CJS:
```js
const { VK } = require('vk-io');
```
@TheEVolk но с ES2015 всё в порядке :)

**Comment by TheEVolk** [comment]
Так или иначе, убили.

**Comment by dvadvaa** [comment]
Да, сам использую у себя
`const { VK } = require('vk-io');`
Сейчас, к сожалению, только так.

**Comment by negezor** [comment]
Я закрою этот issue, так как это зависит от окружения в котором пишется код.

**Comment by MrZillaGold** [comment]
@negezor Я думаю тот вариант который используют в **discord.js** можно использовать и в **vk-io**
https://github.com/discordjs/discord.js/blob/master/esm/discord.mjs

**Comment by negezor** [comment]
Для этого нужно что бы и импортируемые модули соответствовали импорту ESM.

**Comment by MrZillaGold** [comment]
Подкинув такой способ на уже собранном модуле все работает.
![image](https://user-images.githubusercontent.com/42776347/103861228-d16b7200-5108-11eb-92b1-d73e047635e1.png)
