### ISSUE TITLE
Ошибка  Generic type 'Composer<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by AlexXanderGrib** [negezor/vk-io#234]
#### What did you do?
Я скомпилировать проект на typescript с vk-io.

#### What did you expect to happen?
Он скомпилируется без ошибок.

#### What was the actual result?
```
node_modules/vk-io/lib/structures/shared/composer.d.ts:2:39 - error TS2314: Generic type 'Composer<T>' requires 1 type argument(s).

2 export default class Composer extends MiddlewareComposer {
                                        ~~~~~~~~~~~~~~~~~~
```

#### Additional Info
Всевозможные Strict Type-Checking Options в tsconfig.json отключил

#### Versions

| package                            | version |
| ----------------------------| -------- |
| `vk-io`                               | `4.0.0`   |
| `node`                               | `13.6.0` |
| `TypeScript`                      | `3.7.5` |
| `yarn` or `npm`                 | `yarn 1.21.1` |
| `vk api`                             | `5.103` |

**Comment by negezor** [comment]
Временное решение что и у https://github.com/negezor/vk-io/issues/228

**Comment by AlexXanderGrib** [comment]
Что-то теперь и деградация до middleware-io@2.1.0 не помогла
```
$ npm run compile

> project@1.0.0 compile /home/alexxgrib/Projects/a
> tsc --build tsconfig.json

node_modules/vk-io/lib/structures/shared/composer.d.ts:2:39 - error TS2314: Generic type 'Composer<T>' requires 1 type argument(s).

2 export default class Composer extends MiddlewareComposer {
                                        ~~~~~~~~~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elevation-mine-market-update@1.0.0 compile: `tsc --build tsconfig.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elevation-mine-market-update@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexxgrib/.npm/_logs/2020-02-12T15_56_05_194Z-debug.log
$ cat node_modules/middleware-io/package.json | grep version
        "version": "2.1.0",

```

package.json
```JSON
"dependencies": {
    "aws-sdk": "^2.614.0",
    "middleware-io": "2.1.0",
    "vk-io": "^4.0.0-rc.30"
  }
```

**Comment by negezor** [comment]
Другой вариант решения добавить в `compilerOptions` свойство `"skipLibCheck": true`

**Comment by AlexXanderGrib** [comment]
Помогло, спасибо, но решение о закрытие Issue остаётся  на вас, так-как я думаю это не прямое решение проблемы и вам надо внести правки в код vk-io, чтобы у других пользователей такой проблемы не возникало

**Comment by negezor** [comment]
Они уже давно внесены, но до релиза `4.0.0` я не выпущу их.

**Comment by negezor** [comment]
Исправлено в v4.0.0.
