### ISSUE TITLE
Приватные фото не присоединяются к сообщениям

### ISSUE THREAD

**Issue by TheSimplyOwl** [negezor/vk-io#237]
#### What did you do?

Я присоединяю фотографию к сообщеню у бота
```
context.send({
		message: `msg`,
		keyboard: simpleKeyboard,
		attachment: `photo${photo_id}`'
	});
```

#### What did you expect to happen?

Ожидается, что вместе с текстовым сообщением "msg" отправится фотография

#### What was the actual result?

Отправляются публичные фото. Приватные фото не приклепляются

#### Additional Info

`photo_id` -- является строкой вида `ownerId_photoId_accessKey`

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `v8.10.0` |
| `npm`                    | `3.5.2` |

**Comment by negezor** [comment]
\- Каким образом получен идентификатор фотографии?
\- Если прикреплении из сообщения, было ли оно перезагружено?
\- Отправляется в чат или личное сообщение?

**Comment by TheSimplyOwl** [comment]
> Каким образом получен идентификатор фотографии?

Получен через context (метод `getAttachments('photo')`)

> Если прикреплении из сообщения, было ли оно перезагружено?

Не понял. Было ли обновлено сообщение? (edit?)

> Отправляется в чат или личное сообщение?

Личные сообщения

**Comment by negezor** [comment]
Сообщение из которого получена фотография, это чат? Сообщение не присоединяется скорее всего потому, что сообщения приходящие из Polling/Webhook присылаются с неверным access_key. Если нужно отправить из диалога в диалог, то можно перезагрузить сообщение через:
```js
context.$filled = false; // Временный вариант

await context.loadMessagePayload();
```
Если же в чате, придётся загружать заново.

**Comment by TheSimplyOwl** [comment]
> _Вы наверно колдун?_

Огромное спасибо, это конечно же сработало

**_НО... Как?_** Можно пожалуйста пояснить, почему именно так? (или я просто полез без мат. части?)

**Comment by negezor** [comment]
> Сообщение не присоединяется скорее всего потому, что сообщения приходящие из Polling/Webhook присылаются с неверным access_key.

Всё дело именно в этом. Возможно в будущем будет исправлено.

**Comment by TheSimplyOwl** [comment]
> > Сообщение не присоединяется скорее всего потому, что сообщения приходящие из Polling/Webhook присылаются с неверным access_key.
> 
> Всё дело именно в этом. Возможно в будущем будет исправлено. В чате этот обход с `loadMessagePayload()` не будет работать.

Получается в чате только с бубном танцевать?

**Comment by negezor** [comment]
В чате нужно будет загрузить фотографию от имени сообщества.
