### ISSUE TITLE
Вывод информации await

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#239]
Как правильно вывести информацию из api, при попытке выводить через await скрипт прекращает свою работу.

**Comment by negezor** [comment]
А что в самом коде?

**Comment by el9in** [comment]
К примеру:
const { test } = await api.messages.removeChatUser({chat_id: 4, member_id: 93743})
api.messages.send({peer_id: 2000000004, message: '☢️  был дизактивирован!'});
api.messages.send - не срабатывает при не удаче.

**Comment by el9in** [comment]
Так тоже код не срабатывает:
var test;
test = await api.messages.removeChatUser({chat_id: 4, member_id: 93743});
api.messages.send({peer_id: 2000000004, message: '☢️  был дизактивирован!'});

**Comment by negezor** [comment]
Логично что при ошибке дальше выполнение не пойдёт. Нужно использовать try catch, это уже касается основ JS.
```js
try {
    await api.messages.removeChatUser({
        chat_id: 4,
        member_id: 93743
    });

    await api.messages.send({
        peer_id: 2000000004,
        message: '☢️ был дизактивирован!'
    });
} catch (error) {
    console.log('Error', error);
    
    await api.messages.send({
        peer_id: 2000000004,
        message: 'Произошла ошибка при удалении участника беседы'
    });
}
```

**Comment by el9in** [comment]
Благодарю! А можно ли ещё как то отключить ошибки от ВК, именно вывод её в логи.

**Comment by negezor** [comment]
Ошибки игнорировать не стоит, их нужно обрабатывать.

**Comment by el9in** [comment]
Есть такие ошибки как (не могу отправить сообщение юзеру) но эта ошибка из за того что лагает vk api.

**Comment by negezor** [comment]
[Здесь](https://github.com/negezor/vk-io/blob/master/docs/examples/advanced/middleware-error-fallback.js) есть пример как можно наверху сделать общий обработчик.

**Comment by el9in** [comment]
Последний вопрос, я использую: " vk.updates.on('message', async (context, next) => ", бот обрабатывает запросы постепенно, можно ли как то сделать что бы он мог обрабатывать сразу несколько запросов одновременно?

**Comment by el9in** [comment]
Точнее как я понял, он их отправляет с задержкой в 200 мс, можно ли это отключить?

**Comment by el9in** [comment]
Закрываю, нашёл нужное в документации. Довольно сложно там что то найти(
