### ISSUE TITLE
Прокси сервер для авторизации

### ISSUE THREAD

**Issue by Orland25565** [negezor/vk-io#240]
#### What did you do?
Попытка авторизоваться через Implicit Flow из Украины

#### What did you expect to happen?
Я не ожидал что это сработает. 

#### What was the actual result?
Ошибка, превышено время ожидания.

#### Additional Info
Просьба к автору библиотеки внести возможность в опциях устанавливать не только прокси сервер для API но и для авторизации. А такой есть. https://xtrafrancyz.net/unblock-vk
и он хорошо работает.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `X.Y.Z` |
| `@vk-io/authorization`             | `X.Y.Z` |
| `node`                             | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `X.Y.Z` |

**Comment by negezor** [comment]
В библиотеке можно использовать прокси, для этого нужно передать HTTPS Agent, например [этим](https://www.npmjs.com/package/https-proxy-agent) модулем.
```js
const { VK } = require('vk-io');
const HttpsProxyAgent = require('https-proxy-agent');

const agent = new HttpsProxyAgent('you_proxy_address');

const vk = new VK({
  agent 
});
```

**Comment by negezor** [comment]
Я закрою этот вопрос, из-за неактивности, не стесняйтесь открыто его снова.
