### ISSUE TITLE
Отличие, и что лучше использовать. 

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#241]
В чем отличие context.send и api.message.send, или это одно и тоже?
Если нет, что предпочтительнее использовать?

**Comment by negezor** [comment]
Разница в том, что `context.send({ message: 'Hello!' })` алиас от:
```ts
const options = { message: 'Hello!' }; // Аргумент метода

vk.api.messages.send({
  peer_id: context.peerId,
  random_id: getRandomId(),
  ...options
});
```
Напрямую отправит в нужный диалог сообщение.

**Comment by el9in** [comment]
Благодарю за информацию.
