### ISSUE TITLE
Можно ли добавить ещё 1 отлов событий в текущий.

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#243]
Можно ли добавить ещё 1 отлов событий в текущий.
К примеру у меня есть

`vkp.updates.on('message', async (context, next) => {
	console.log(parseInt(context.text)+' '+context.senderId);
	if(parseInt(context.text) == context.senderId) context.send('вот какой то ID: '+context.senderId);
});`

Я хочу добавить к этому vkp ещё 1 отлов событий к этому отлову, что бы все команды были одинаковыми.

**Comment by negezor** [comment]
Какое например событие ещё нужно отлавливать? Или имеется ввиду установить несколько `vkp.updates.on(...)`?

**Comment by el9in** [comment]
Несколько в одном и том же vkp.updates.on

**Comment by negezor** [comment]
А какие ещё события понадобились? В `vkp.updates.on(['message', 'you_event'])` можно передать массив событий которые он будет слушать.

**Comment by el9in** [comment]
Я хочу отлавливать события сразу из двух или больше групп в одном vkp.updates.on - с событиями всё нормально)

**Comment by negezor** [comment]
Библиотека придерживается правила: 1 группа - 1 инстанция класса.
Так как все методы пойдут через определённый токен. Конечно никто не запрещает вручную скармливать эвенты других групп через webhook, так:
```js
vk.updates.handleWebhookUpdate(youUpdate);
```
Ну или вешать callback на express/http[s] так:
```js
app.post('/secret-callback-api-1', vk.updates.getWebhookCallback());
app.post('/secret-callback-api-2', vk.updates.getWebhookCallback());
```

**Comment by el9in** [comment]
А если я создам например 100-200 классов с другими группами через for(.., будет ли какая-то нагрузка при таком количестве?

**Comment by negezor** [comment]
Не сказал бы, объекты мало весят в памяти.

**Comment by el9in** [comment]
Спасибо за ответы)
