### ISSUE TITLE
Проблема с кнопкой "VKPay"

### ISSUE THREAD

**Issue by lowkeypriority** [negezor/vk-io#244]
#### What did you do?

Отправляю кнопку 'Оплата через VKPay' с методом `pay-to-group`, указывая amount, description и data

#### What did you expect to happen?

Пользователь успешно оплачивает услугу через VKPay, нажав на кнопку

#### What was the actual result?

При оплате возникает ошибка:
*Невозможно совершить операцию. Повторите позже*

#### Additional Info

В кнопке я ещё отправляю свою дату `data: { item: itemId }`

Отправляя эту же кнопку через request и переводя деньги снова всё проходит успешно

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `v8.10.0` |
| `npm`                    | `3.5.2` |

**Comment by negezor** [comment]
Можно исходный код?

**Comment by TheSimplyOwl** [comment]
```
require('dotenv').config();

const { VK, Keyboard } = require('vk-io');
const { SceneManager, StepScene } = require('@vk-io/scenes');
const { SessionManager } = require('@vk-io/session');

const sessionManager = new SessionManager();
const sceneManager = new SceneManager();

const vk = new VK({
	token: process.env.TOKEN
});
const { api } = vk;

vk.updates.on('message', (context, next) => {
	const { messagePayload } = context;

	context.state.command = messagePayload && messagePayload.command ? messagePayload.command : null;

	return next();
});

vk.updates.on('message', sessionManager.middleware);
vk.updates.on('message', sceneManager.middleware);
vk.updates.on('message', sceneManager.middlewareIntercept);

// Simple wrapper for commands
const hearCommand = (name, conditions, handle) => {
	if (typeof handle !== 'function') {
		handle = conditions;
		conditions = [];
	}

	if (!Array.isArray(conditions)) {
		conditions = [conditions];
	}
	if (!Array.isArray(handle)) {
		handle = [handle];
	}

	sceneManager.addScene(new StepScene(name, handle))

	vk.updates.hear(
		[
			(text, { state }) => (
				state.command === name
			),
			...conditions
		],
		async (context) => {
			await context.scene.enter(`${name}`)
		}
	);
};

vk.updates.on('vkpay_transaction', async (context) => {
		await context.loadMessagePayload();

		console.log(context)
		console.log(context.message)
		console.log(context.type)
	}
);

hearCommand('start', [/start/i],
	async (context) => {
		await context.send({
			message: 'VKPay test',
			keyboard: Keyboard.builder()
				.payButton({
					hash: {
						action: 'pay-to-group',
						group_id: process.env.GROUP_ID,
						aid: 10,
						amount: 1,
						data: {
							sender: context.peerId
						},
						description: 'test payament'
					}
				})
		})
	}
)

vk.updates.start().catch(console.error);
```

**Comment by TheSimplyOwl** [comment]
*@negezor, в чём проблема и как её решить?*

**Comment by negezor** [comment]
А какой запрос в чистом request передаётся? Ну и к тому же `data` должен быть строкой.

**Comment by TheSimplyOwl** [comment]
Запрос делал через `requests` на Пайтон *(Конечно странно, ведь работаю на ноде...)* Запрос также имел "не валидное" поле `data`, но всё проходило. (Сам код ниже)

Также я попытался опять отправить кнопку через **vk-io**, но без `data`. Всё прошло успешно
Решив, что пробелма была всё-так в не валидном формате `data` решил отправить, так как пишется в офф. документации -- словарём с произвольными данными. Не вышло.  `Data` же была такого вида -- ```data: `{sender:${209377620}}` ```

И имеется ещё один вопрос по поводу VKPay: Как "прослушивать" собыития о переводе в группу (или пользователю)? Также, через `updates.on`? Если да, то в каком виде? Я пытался сделать, но без успешно:
```js
vk.updates.on('vkpay_transaction', async (context) => {
		await context.loadMessagePayload();

		console.log(context)
		console.log(context.message)
		console.log(context.type)
	}
);
```
P.S. Можно дополнить документацию подобными ньюансами (типы, схемы и т.д)?

*Код запроса на Python к первому вопросу:*

```py
import requests
import json
from random import randint

payload = {
        "v": "5.102",
        "access_token": "64d2ccfb6b9319de58606ac7cbc59cc763d35887b6342d59d42845d9e7ef7d97c9f685e19078baf9fe7f7",
        "random_id": randint(0, 18446744073709551616),
		"user_id": 209377620,
		"message": 'VKPay test',
		"keyboard": json.dumps({
			"one_time": False,
			"buttons": [
				[{
					"action": {
						"type": "vkpay",
						"hash": {
							"action": 'pay-to-group',
							"group_id": 170835296,
							"aid": 10,
							"amount": 1,
							"data": {
								"sender": 209377620
							},
							"description": 'test payment'
						}
					}
				}]
        	]
    	})
    }

r = requests.post("https://api.vk.com/method/messages.send", data=payload)
```

**Comment by TheSimplyOwl** [comment]
Запрос делал через `requests` на Python *(Конечно странно, ведь работаю на node...)* Запрос также имел "не валидное" поле `data`, но всё проходило. (Сам код ниже)

<details><summary>Код запроса на Python:</summary>

```python

import requests
import json
from random import randint

payload = {
        "v": "5.102",
        "access_token": "token",
        "random_id": randint(0, 18446744073709551616),
		"user_id": user_id,
		"message": 'VKPay test',
		"keyboard": json.dumps({
			"one_time": False,
			"buttons": [
				[{
					"action": {
						"type": "vkpay",
						"hash": {
							"action": 'pay-to-group',
							"group_id": group_id,
							"aid": 10,
							"amount": 1,
							"data": {
								"sender": user_id
							},
							"description": 'test payment'
						}
					}
				}]
        	]
    	})
    }

r = requests.post("https://api.vk.com/method/messages.send", data=payload)
```

</details>

Также я попытался опять отправить кнопку через **vk-io**, но без `data`. Всё прошло успешно
Решив, что пробелма была всё-так в не валидном формате `data` решил отправить, так как пишется в офф. документации -- словарём с произвольными данными. Не вышло.  `Data` же была такого вида -- ```data: `{sender:${209377620}}` ```

И имеется ещё один вопрос по поводу VKPay: Как "прослушивать" собыития о переводе в группу (или пользователю)? Также, через `updates.on`? Если да, то в каком виде? Я пытался сделать, но без успешно:
```js
vk.updates.on('vkpay_transaction', async (context) => {
		await context.loadMessagePayload();

		console.log(context)
		console.log(context.message)
		console.log(context.type)
	}
);
```
P.S. Можно дополнить документацию подобными ньюансами (типы, схемы и т.д)?

**Comment by negezor** [comment]
Свойства `data` должно быть произвольной строкой, но честно не знаю что разрешено или наоборот запрещено. Но учитывая что он передаётся в `URL`, то скорее всего на него накладываются именно его ограничения. Что если попробовать так:
```js
Keyboard.builder()
    .payButton({
        hash: {
            action: 'pay-to-group',
            group_id: process.env.GROUP_ID,
            aid: 10,
            amount: 1,
            data: encodeURIComponent(`sender:${context.senderId}`),
            description: 'test payament'
        }
    })
```

А описание контекста тут: [VKPayTransactionContext](https://github.com/negezor/vk-io/blob/master/packages/vk-io/src/structures/contexts/vk-pay-transaction.ts)
```js
vk.updates.on('vk_pay_transaction', async (context) => {
	console.log(context);
});
```

**Comment by TheSimplyOwl** [comment]
Так, информацию о переводе я получаю: **спасибо**, что показали правильный пример. Ошибку заметил 

Однако, из-за `data` все также платеж не проходит -- даже использовав `encodeURIComponent`
