### ISSUE TITLE
Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by fax1ty** [negezor/vk-io#245]
#### What did you do?
```typescript
vk.updates.on('new_wall_post', data => {
eventEmitter.emit('newPost', [data.wall]);
});
```

#### What did you expect to happen?
Хотелось бы передавать объект без ошибки

#### What was the actual result?
```
Handle polling update error: TypeError: Cannot read property 'url' of undefined
    at PhotoAttachment.get smallPhoto [as smallPhoto] ([REDACTED]\node_modules\vk-io\lib\index.js:1851:21)
    at copyParams ([REDACTED]\node_modules\vk-io\lib\index.js:324:34)
    at PhotoAttachment.[inspectCustomData] ([REDACTED]\node_modules\vk-io\lib\index.js:1898:16)
    at PhotoAttachment.toJSON ([REDACTED]\node_modules\vk-io\lib\index.js:1084:39)
    at PhotoAttachment.[nodejs.util.inspect.custom] ([REDACTED]\node_modules\vk-io\lib\index.js:1100:43)
```

#### Additional Info
Почему-то коллстек идёт только из библиотеки, а все мои действия после работы с объектом `data` прерываются. Поэтому не смог нормально задебагать

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `13.8.0` |
| `TypeScript`                       | `3.8.2` |
| `yarn` or `npm`                    | `yarn 1.21.1` |

**Comment by negezor** [comment]
Какая версия VK API в группе (Bots Long Poll/Callback API)?

**Comment by fax1ty** [comment]
@negezor, 5.50

**Comment by negezor** [comment]
А что именно используется для получения событий? Библиотека рассчитана на сейчас на самую последнюю версию `5.103`.

**Comment by fax1ty** [comment]
Использую Long Poll. То есть просто нужно поставить версию повыше? Сейчас проверю

**Comment by negezor** [comment]
А запускается обновления через `startPolling()` или `start()`? Если с первым вариантом, то для получения полных событий в группе должен быть установлен `pollingGroupId`. Иначе будет запущен по умолчанию User Long Poll. Метод `start()` автоматический установит эту опцию по необходимости.

**Comment by fax1ty** [comment]
Через startPolling. В объекте указан `pollingGroupId`. Он даже возвращает новые посты. Дело именно в url картинки. Я ещё как понял через эвент возвращается не оригинальный объект. Как получить голый объект, который передаёт ВК?

**Comment by negezor** [comment]
У меня не получается воспроизвести ошибку.

**Comment by fax1ty** [comment]
@negezor Скорее-всего ошибка была из-за другой версии Long Poll сервера. Но второй вопрос всё ещё остался. Если верить документации ВК, то в `wall_post_new` они возвращают обычный объект стены
![image](https://user-images.githubusercontent.com/26363214/75106563-8901ad80-5637-11ea-8829-88266b0d4477.png) с обычными `attachments` 
![image](https://user-images.githubusercontent.com/26363214/75106571-a0d93180-5637-11ea-9f62-4575b6cd601c.png)
в формате
```typescript
{
type: 'mediaType';
[mediaType: string]: MediaTypeInterface;
}
```
Но вместо этого библиотека возвращает это 
![image](https://user-images.githubusercontent.com/26363214/75106634-180ec580-5638-11ea-8d2e-72e19d8dff43.png)
Как можно получить голый ответ?

**Comment by fax1ty** [comment]
Блин, ответ всё время лежал на поверхности. `toJSON()`. Это где-то описано?

**Comment by negezor** [comment]
Этот метод по умолчанию вызывается для `JSON.stringify()`.

**Comment by fax1ty** [comment]
Не знаю была ли та ошибка багом или просто это случилось из-за старой версии, но спасибо в любом случае

**Comment by fax1ty** [comment]
А, я понял рановато я закрыл. Он возвращает тоже самое, но с постом. А есть всё-таки какой-то способ получить голый ответ?

**Comment by negezor** [comment]
Если нужно прямо совсем оригинальный ответ, то можно получить через:
```js
context.payload
```
Но лучше так не делать.

**Comment by fax1ty** [comment]
@negezor Оно сработало с кастингом к `any`. У Вас в типах оно помечено как `protected`. Поэтому и не отображалась в объекте. А какие могут быть отрицательные последствия? Почему "лучше так не делать"?

**Comment by negezor** [comment]
В будущем формат может меняться, как было с message_new. А контекст представляет абстракцию.
