### ISSUE TITLE
Как узнать что в сообщении фото

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#246]
Пытаюсь узнать таким образом context.isPhoto() и context.attachments[0].isPhoto - выдаёт что это не функция. либо undefined isPhoto | isPhoto()

**Comment by aeonixlegit** [comment]
`context.hasAttachments(['photo']) // => Boolean` - если нужно узнать, есть
ли фото в сообщении вообще.

`context.attachments[0].type === 'photo' // => Boolean` - если нужно
узнать, является ли конкретный аттач фото.

вт, 25 февр. 2020 г., 2:11 AM el9in <notifications@github.com>:

**Comment by negezor** [comment]
Все объекты будут `PhotoAttachment`
```js
const photos = context.getAttachments('photo');

if (photos.length !== 0) {
  // В сообщении есть фото
}
```
Ну или альтернативный одиночный вариант:
```js
const [photo] = context.getAttachments('photo');

if (photo) {
  // Фотография
}
```
> `context.attachments[0].type === 'photo' // => Boolean` - если нужно
узнать, является ли конкретный аттач фото.

Такой вариант не стоит использовать ввиду его костыльности. Допустим нам прислали фотографию и документ (случайно), то первым аттачментом может быть документ, и мы скажем пользователю что не прикрепили фото?
