### ISSUE TITLE
Как получить id определенных сообщений?

### ISSUE THREAD

**Issue by Jl1mbo** [negezor/vk-io#247]
Я пишу вот так:

vk.updates.hear(/^(?:Ред)\s(.*)\s(.*)$/i, async (message) => {
vk.api.messages.edit({
  peer_id: message.peerId,
  message_id: message.id,
  message: `Тест`,
  apiVersion: '5.80'
})
})
Когда я пишу "ред 123 тест" то он должен изменить сообщение 123, но когда я пишу он изменяет мое сообщение для редактирования, я пишу "ред 123 тест" и он мое вот это сообщение редачит на "тест" а мне надо чтобы он редачил 123, подскажите как это сделать.

**Comment by MagaBro0** [comment]
@negezor помоги плз

**Comment by negezor** [comment]
Зачем это понадобилось?

**Comment by MagaBro0** [comment]
Чтобы можно было быстро удалять сообщения

**Comment by negezor** [comment]
А при чём тут ручной ввод `ID` и редактирование?

**Comment by tailsjs** [comment]
если группа и при этом ты не в беседе этой группы - то не пойдёт

**Comment by tailsjs** [comment]
а, ещё, зачем apiVersion: '5.80' в messages.edit

**Comment by MagaBro0** [comment]
@tailsjs хз

**Comment by negezor** [comment]
Я закрою этот вопрос из-за неясности, не стесняйтесь открыть его снова.
