### ISSUE TITLE
Typescript lint Error

### ISSUE THREAD

**Issue by Laboratory** [negezor/vk-io#249]
#### What did you do?
Run app
#### What did you expect to happen?
Compile project
#### What was the actual result?
`````bash
node_modules/vk-io/lib/structures/shared/composer.d.ts:2:39 - error TS2707: Generic type 'Composer<T, R>' requires between 1 and 2 type arguments.

2 export default class Composer extends MiddlewareComposer {
                                        ~~~~~~~~~~~~~~~~~~

Found 1 error.
`````
#### Additional Info

Need to fix ti

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | ^4.0.0-rc.30|
| `node`                             | v13.10.1 |
| `TypeScript`                       | ^3.8.3 |
| `yarn` or `npm`                    | 1.10.1|

I've added "skipLibCheck": true to ts lint config, but need to fix MiddlewareComposer type declaration like <any, any>

Thx, V

**Comment by negezor** [comment]
Duplicate #234
