### ISSUE TITLE
Кириллица в пароле при standalone auth

### ISSUE THREAD

**Issue by kurl-off** [negezor/vk-io#25]
Возникает ошибка `AuthError: Auth form error: Указан неверный логин или пароль.` при попытке авторизоваться с кириллическим паролем

**Comment by negezor** [comment]
Это уже специфичность ВКонтакте, так как все экранизируется.

**Comment by kurl-off** [comment]
а делать-то что?

**Comment by TrueLecter** [comment]
Пароль сменить на не кирилицу

**Comment by zaets-pobegaec** [comment]
https://vk.com/page-2158488_47181319
