### ISSUE TITLE
Некорректно отображаются вложения в context.

### ISSUE THREAD

**Issue by nik9play** [negezor/vk-io#251]
#### What did you do?
Пытаюсь получить список вложений для сообщения в боте.

#### What did you expect to happen?
Получаю список всех 10 изображений при помощи context.getAttachments("photo")

#### What was the actual result?
Получаю либо только первое изображение либо ничего. 

#### Additional Info
Когда изображений меньше 9 то все работает.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `12.16.1` |
| `yarn` or `npm`                    | `yarn` |

**Comment by negezor** [comment]
А изображения именно в самом сообщении? Ну и можно привести код?

**Comment by nik9play** [comment]
```javasceipt
vk.updates.hear(/п(е)?р(е)?к(и)?нь/i, async (context) => {
  context.setActivity()
  const sendPhotos = async () => {
    if (context.hasAttachments("photo")) {
      let photoArray = []
      for (const element of context.getAttachments("photo")) {
        await vk.upload.messagePhoto({
          source: element.largePhoto,
        })
        .then(attachment => {
          photoArray.push(attachment.toString())
        })
      }
      await vk.api.messages.send({
        peer_id: context.peerId,
        attachment: photoArray.join(",")
      })
    } else {
      context.send("Я не вижу фотографий. Попробуй ещё раз.")
    }
  }

  await Promise.all([
    context.send({
      message: 'Жди...'
    }),
    sendPhotos()
  ])
})
```
 
Собственно проблемы с вложениями сообщения которое принимает бот.

**Comment by negezor** [comment]
Какая версия API в группе? Если запустить с `DEBUG=vk-io:updates` будут ли все аттачменты? Если нет, то это приходит с ВК так.

**Comment by nik9play** [comment]
С `DEBUG=vk-io:updates` ничего не изменилось. Апи версия 5.103.

**Comment by negezor** [comment]
Нужно посмотреть результат приходящих событий в консоли, возможно это ВКонтакте что-то не до конца присылает.

**Comment by nik9play** [comment]
Вот что приходит, только непонятно как заглянуть в массив attachments

![изображение](https://user-images.githubusercontent.com/13693620/77235092-06cbc100-6bc4-11ea-998e-ddae15cc8296.png)

**Comment by negezor** [comment]
Можно установить вложенность ещё `DEBUG_DEPTH=20`

**Comment by nik9play** [comment]
В общем, `DEBUG_DEPTH=20` не сработал, но немного пошаманив, понял что именно с сервера приходит только одно вложение:
![изображение](https://user-images.githubusercontent.com/13693620/77249263-e39b2300-6c50-11ea-8438-53037b44881b.png)
Также я проверил поведение на другой [библиотеке](https://github.com/node-vk-bot-api/node-vk-bot-api) в которой можно создавать ботов, и там происходит тоже самое.

Считаю, что можно закрыть проблему, так как виноваты ВК.
