### ISSUE TITLE
Можно ли пользователя отправить на сцену по его Id

### ISSUE THREAD

**Issue by idev-hub** [negezor/vk-io#254]
Пишу бота и по функционалу нужно перекидывать двух пользователей на новую сцену. 
Если первого я могу перекинуть по context.scene.enter('nameScene'). То второго уже так не могу. Существует ли какой либо функционал для этого? Насколько верно я понял сцены пользователей хранятся в сессиях. Но тот же вопрос не могу переписать сессию по id пользователя. И верно ли что я пишу суда подобные вопросы?

**Comment by negezor** [comment]
Сцену предполагают одного пользователя, можно по подробней узнать решаемую задачу?

**Comment by idev-hub** [comment]
> Сцены предполагают одного пользователя, можно по подробней узнать решаемую задачу?

Делаю что-то вроде локального анонимного чата. Делаю через бд, записываю id пользователей которые общаются и их статус. В целом я реализовал весь необходимый функционал, но есть неприятная особенность.

Допустим пользователь Алексей нажал поиск собеседника. Идёт запрос в базу. Если собеседника сейчас нету, то Алексея ставят на пассивный поиск, то есть как только другой собеседник начнет поиск, пусть будет Ваня. Алексей стоит на ожидании, Ваня жмёт поиск. Ваня нашёл Алексея. Ване пришло сообщение что был найден пользователь для общения и Ваню кидает на сцену с чатом (Сцена просто ретранслирует сообщения Вани, Алексею), но вот Алексею приходит сообщение через api.message.send что его нашли, но на сцену я его перекинуть не могу, он так же остается в сцене ожидания. Ведь Алексей просто ожидал, он не совершал действия. 

Сейчас эту задачу решил так, что когда оба нашли друг друга им кидает кнопки, они оба их нажимают тем самым вручную себя кидают на сцену с чатом. Но это лишнее неприятное действие, хотелось бы сразу кидать Алексея на сцену чата.

Надеюсь понятно расписал задачу

**Comment by negezor** [comment]
Я думаю сцены в данном случае излишни, здесь можно поступить так:
- Сделать middleware в котором будет обращается например к Redis или другому быстрому хранилищу.
- Если есть информация о собеседнике, мы просто перехватываем события и общаемся с собеседником. (не забывая про кнопки отмены).
- Если нет, ничего не делаем.
Набросал простой пример:
```js
const memoryStore = new Map();

const getInterlocutor = async ({ senderId }) => {
	return memoryStore.get(senderId);
};

const createInterlocutor = async ({ senderId, targetId }) => {
	return memoryStore.set(senderId, {
		userId: targetId
	});
};

const deleteInterlocutor = async ({ senderId }) => {
	memoryStore.delete(senderId);
};

vk.updates.on('message', async (context, next) => {
	const interlocutor = await getInterlocutor({
		senderId: context.senderId
	});

	// Идём дальше по цепочки middleware
	if (!interlocutor) {
		return next();
	}

	const { messagePayload } = context;

	// Выход из диалога
	if (messagePayload && messagePayload.command === 'cancel') {
		return Promise.all([
			deleteInterlocutor({
				senderId: context.senderId
			}),
			vk.api.messages.send({
				peer_id: interlocutor.userId,
				message: 'Собеседник вышел'
			})
		]);
	}

	await vk.api.messages.send({
		peer_id: interlocutor.userId,
		message: context.text
	})ж
});
```
