### ISSUE TITLE
Feature Request: События новых товаров

### ISSUE THREAD

**Issue by AlexXanderGrib** [negezor/vk-io#256]
Сегодня ВК добавил новые события для связанные с товарами и заказами. Просьба запилить для них поддержку.

![image](https://user-images.githubusercontent.com/29816814/77984979-cd115d80-731b-11ea-82aa-97fb74f1c688.png)

**Comment by negezor** [comment]
В документации пока не появилось описание событий.

**Comment by AlexXanderGrib** [comment]
Появилась https://vk.com/dev/groups_events

**Comment by negezor** [comment]
Займусь в ближайшее время.

**Comment by negezor** [comment]
Реализовано https://github.com/negezor/vk-io/commit/5070f669fb8dc465da9294043ad7c786228b23c8
