### ISSUE TITLE
Таймер.

### ISSUE THREAD

**Issue by Jl1mbo** [negezor/vk-io#257]
У меня есть команда /пригласить <id>, мне надо сделать чтобы ее можно было вводить раз в 2 минуты, как это сделать?

**Comment by idev-hub** [comment]
Я вижу только одну реализацию в вашем случае. Записывать в сессию последнюю дату когда выполнялась команда /пригласить и при повторном ее выполнении сравнивать текущую дату с датой в сессии. В помощь придет модуль Luxor в котором есть возможность сравнивать даты и время.

Либо заместо сессии использовать базу данных что будет немного надёжнее но в вашем случае это не критично

**Comment by negezor** [comment]
Обычная задача для Rate Limit, выше её уже описал @idev-hub. В принципе ничего сложного, простая реализация:
```js
const { VK } = require('vk-io');

const { SessionManager } = require('@vk-io/session');

const vk = new VK({
	token: process.env.TOKEN
});

const sessionManager = new SessionManager();

vk.updates.on('message', sessionManager.middleware);

const RATE_LIMIT_COMMAND = 60e3 * 2; // two mins

vk.updates.hear(/^hello/i, async (context) => {
    const now = Date.now();
    
    const { lastCommandUsageAt = 0 } = context.session;
    
    if (lastCommandUsageAt > (now - RATE_LIMIT_COMMAND)) {
        await context.send('Вы не можете вызывать эту команду чаще одного раза в две минуты.');
        
        return;
    }

    context.session.lastCommandUsageAt = now;

    // something logic
});
```

**Comment by Jl1mbo** [comment]
Спасибо.
