### ISSUE TITLE
Команды

### ISSUE THREAD

**Issue by Jl1mbo** [negezor/vk-io#258]
Возможно тупой вопрос, но все равно спрошу, как делать команды? Вот например у меня есть

`vk.api.status.set({
  text: 'тест'
});`
Мне надо чтобы стату менялся по команде тест1 например, как это сделать?

**Comment by negezor** [comment]
Есть примеры на `vk.updates.hear()` https://github.com/negezor/vk-io/blob/master/docs/examples/simple-updates-bot.js

**Comment by Jl1mbo** [comment]
Спасибо.
