### ISSUE TITLE
Комментирование поста.

### ISSUE THREAD

**Issue by Jl1mbo** [negezor/vk-io#259]
Мне надо чтобы мой бот, комментировал пост, но каким методом это сделать? Просто в вк апи в wall я не нашел

**Comment by negezor** [comment]
http://vk.com/dev/wall.createComment

**Comment by Jl1mbo** [comment]
@negezor `node test
(node:24850) UnhandledPromiseRejectionWarning: APIError: Code №100 - One of the parameters specified was missing or invalid: incorrect post_id`

**Comment by Jl1mbo** [comment]
Простите, моя ошибка, там id надо с 

> - 
Делать
