### ISSUE TITLE
Как сделать кд?

### ISSUE THREAD

**Issue by Jl1mbo** [negezor/vk-io#260]
Как сделать кд? Типо мне надо чтобы статус обновлялся каждую минуту а он обновляется до того, пока ему капчу не выдаст

**Comment by negezor** [comment]
Без кода сложно сказать что именно делается.

**Comment by Jl1mbo** [comment]
@negezor 
`const { VK } = require('vk-io');
const vk = new VK({
  token: 'token'
});

vk.api.status.set({
  text: NewDate()
});
vk.updates.start().catch(console.error);`

**Comment by idev-hub** [comment]
Вв серьезно? Не удивительно что он обновляется пока капчу не выдаст. Почитай про cron и используте модуль node-cron

**Comment by Jl1mbo** [comment]
В смысле?

**Comment by idev-hub** [comment]
vk startPolling проще говоря запускает бесконечный цикл. И обновление статуса идёт в бесконечном потоке пока что то в виде капчи не помешает. Cron позволяет запускать один раз в определенные промежутки времени или в точно указанное время.

**Comment by negezor** [comment]
@Jl1mbo в данном коде метод `vk.api.status.set()` будет вызван только один раз при старте бота.

@idev-hub `vk.updates.start()` запускает только получение события со стороны ВК. И никак не зацикливает вызов метода `vk.api.status.set()`.

**Comment by Jl1mbo** [comment]
Мне нудно просто, чтобы у меня статус обновлялся каждую минуту, как это сделать?
