### ISSUE TITLE
Id коментария

### ISSUE THREAD

**Issue by Jl1mbo** [negezor/vk-io#263]
Как получить ID коментария? Я хочу удалить все свои комментарии с группы, 
`vk.api.wall.deleteComment({
  owner_id: -10875831,
  comment_id: messageId
});`
Но когда я пытаюсь получить id таким образом, то мне выдает ошибку, можете сказать как правильно?

**Comment by negezor** [comment]
Откуда взялась переменная `messageId`? Что бы удалить свои комментарии с группы, нужно получить все посты и с ним получать все комментарии, фильтруя по своему ID.

**Comment by Jl1mbo** [comment]
Можно пример?

**Comment by negezor** [comment]
Никаких конкретных примеров, но в vk-io есть работа с коллекциями.
https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/collect-stream.md
