### ISSUE TITLE
Переменные.

### ISSUE THREAD

**Issue by Jl1mbo** [negezor/vk-io#265]
Где можно больше узнать о переменных? Просто когда я хочу получить id чела который мне написал, то мне приходится id его сообщения вводить, мне что-то говорили про переменные но я никакой инфы о них не нашел, можете помочь?

**Comment by negezor** [comment]
У библиотеки есть API Reference, касательно MessageContext, можно узнать [тут](http://negezor.github.io/vk-io/references/vk-io/classes/_structures_contexts_message_.messagecontext.html).
