### ISSUE TITLE
Ошибка в README

### ISSUE THREAD

**Issue by kirillzver** [negezor/vk-io#268]
В документации указано:
`
sceneManager.addScenes(...
`
На деле же:
`
sceneManager.addScene(...
`

**Comment by negezor** [comment]
Это не ошибка, готовятся мажорные изменения в библиотеке.

**Comment by kirillzver** [comment]
Хотелось бы верить, ибо в доках это, как минимум, два месяца..

**Comment by negezor** [comment]
Нехватка времени что бы всё завершить.
