### ISSUE TITLE
Клавиатура в беседе

### ISSUE THREAD

**Issue by shketov** [negezor/vk-io#269]
Как заставить работать клавиатуры в беседах? 
Все доки перерыл, ничего не нашёл

**Comment by negezor** [comment]
А что в самом коде? По умолчанию нет разницы куда отправляется клавиатура.

**Comment by shketov** [comment]
Наверное, не так выразился. Сама клавиатура отправляется, но на нажатия не реагирует

**Comment by negezor** [comment]
Так снова, что в коде?

**Comment by shketov** [comment]
```
vk.updates.hear(/^(?:test)/i, (message) => {
 		return message.send({
			message:`test`,
			keyboard: Keyboard.keyboard([  
			[ 
				Keyboard.textButton({ 
					label: 'Помощь', 
					color: Keyboard.POSITIVE_COLOR,
					payload: {
						"command": "help"
					}
				})         
            ]
		])
	});
});
```

**Comment by negezor** [comment]
Я имел ввиду код обработчика который пытается поймать событие клавиатуры?

**Comment by shketov** [comment]
Беда, а такого и нет. Подскажи, как сделать?

**Comment by negezor** [comment]
Простой бота с клавиатурой https://github.com/negezor/vk-io/blob/master/docs/examples/simple-keyboard-bot.js
