### ISSUE TITLE
 sceneManager.addScenes is not a function

### ISSUE THREAD

**Issue by alras63** [negezor/vk-io#271]
C:\projects\vk-io-test\dist\js\app.js:24
sceneManager.addScenes([new _scenes.StepScene('signup', [context => {
             ^

TypeError: sceneManager.addScenes is not a function
    at Object.<anonymous> (C:\projects\vk-io-test\dist\js\app.js:24:14)

**Comment by alras63** [comment]
Handle polling update error: TypeError: scene.enterHandler is not a function

**Comment by negezor** [comment]
Метод `sceneManager.addScenes()` будет только в следующем мажоре, сейчас нужно:
```js
sceneManager.addScene(new StepScene(...));
```
