### ISSUE TITLE
Проблема с клавиатурой с payload

### ISSUE THREAD

**Issue by Bonya77** [negezor/vk-io#272]
Здравствуйте! Помогите пожалуйста, пишу бота и надо делать бота который полностью управляется клавиатурой и без команд. Но недавно столкнулся с проблемой в том что не работает payload. То есть в консоль ошибок не отправляет и на кнопку не отвечает... Вот собственно скрипт 1го сообщения с кнопкой:

```
updates.hear(/^(привет)/ui, async (mes) => {
return mes.send({
message: 'Привет!',
keyboard: Keyboard.keyboard([
Keyboard.textButton({
label: "Пока", 
payload: {
text: "привет"
},
color: 'primary'
])
})
});
});
```

_Не судите строго что в тексте могут быть ошибки т.к. писал эту команду вручную, но в скрипте нету ошибок... Помогите пожалуйста!_

**Comment by isinkin** [comment]
А в чём ошибка? Вы отправляете кнопку с payload-ом, но не обрабатываете нажатия на кнопку, а просто юзаете затычку в виде updates.hear, которая работает только с ТЕКСТОМ СООБЩЕНИЯ

**Comment by Bonya77** [comment]
> А в чём ошибка? Вы отправляете кнопку с payload-ом, но не обрабатываете нажатия на кнопку, а просто юзаете затычку в виде updates.hear, которая работает только с ТЕКСТОМ СООБЩЕНИЯ

Окей, тогда подскажите как сделать чтобы с payload-ом кнопка отвечала? Мне подсказали что так должна работать с пайлоадом. Без пайлоада работает но мне нужна скрытая, без участия сообщений.

**Comment by isinkin** [comment]
> > А в чём ошибка? Вы отправляете кнопку с payload-ом, но не обрабатываете нажатия на кнопку, а просто юзаете затычку в виде updates.hear, которая работает только с ТЕКСТОМ СООБЩЕНИЯ
> 
> Окей, тогда подскажите как сделать чтобы с payload-ом кнопка отвечала? Мне подсказали что так должна работать с пайлоадом. Без пайлоада работает но мне нужна скрытая, без участия сообщений.

https://github.com/negezor/vk-io/blob/master/docs/examples/simple-keyboard-bot.js

**Comment by Bonya77** [comment]
> > > А в чём ошибка? Вы отправляете кнопку с payload-ом, но не обрабатываете нажатия на кнопку, а просто юзаете затычку в виде updates.hear, которая работает только с ТЕКСТОМ СООБЩЕНИЯ
> > 
> > 
> > Окей, тогда подскажите как сделать чтобы с payload-ом кнопка отвечала? Мне подсказали что так должна работать с пайлоадом. Без пайлоада работает но мне нужна скрытая, без участия сообщений.
> 
> https://github.com/negezor/vk-io/blob/master/docs/examples/simple-keyboard-bot.js

![2020-05-11_10-20-59](https://user-images.githubusercontent.com/64512104/81521360-29cb5380-9371-11ea-868e-d66385152e83.png)
 Даёт ошибку с токеном.. Попробовал через vk.SetOptions() ошибку давать перестал но не отвечает на сообщение. Вроде все правильно но ответа нет. 

```
async function polling() {
	vk.setOptions({
		token: 'bea0dca8f313b1805b88113bc468707ef6727729c5d7f1f7be50ad861cac7da8a6687e024eb3290655e7e',
		apiMode: 'parallel',
		pollingGroupId: 191736935
	});
	console.log('LongPoll Started...');
	await vk.updates.startPolling();
	console.log('LongPoll actived')
}
polling().catch(console.error);
}
});
```

**Comment by Bonya77** [comment]
```
const { VK, Keyboard } = require('vk-io');

const vk = new VK({
	token: process.env.bea0dca8f313b17db3290655e7e
});

vk.updates.on('message', (context, next) => {
	const { messagePayload } = context;

	context.state.command = messagePayload && messagePayload.command
		? messagePayload.command
		: null;

	return next();
});

// Simple wrapper for commands
const hearCommand = (name, conditions, handle) => {
	if (typeof handle !== 'function') {
		handle = conditions;
		conditions = [`/${name}`];
	}

	if (!Array.isArray(conditions)) {
		conditions = [conditions];
	}

	vk.updates.hear(
		[
			(text, { state }) => (
				state.command === name
			),
			...conditions
		],
		handle
	);
};

// Handle start button
hearCommand('start', (context, next) => {
	context.state.command = 'help';

	return Promise.all([
		context.send('Hello!'),

		next()
	]);
});

hearCommand('help', async (context) => {
	await context.send({
		message: `
			My commands list
			/help - The help
			/time - The current date
			/cat - Cat photo
			/purr - Cat purring
		`,
		keyboard: Keyboard.builder()
			.textButton({
				label: 'The help',
				payload: {
					command: 'help'
				}
			})
			.row()
			.textButton({
				label: 'The current date',
				payload: {
					command: 'time'
				}
			})
			.row()
			.textButton({
				label: 'Cat photo',
				payload: {
					command: 'cat'
				},
				color: Keyboard.PRIMARY_COLOR
			})
			.textButton({
				label: 'Cat purring',
				payload: {
					command: 'purr'
				},
				color: Keyboard.PRIMARY_COLOR
			})
	});
});

hearCommand('cat', async (context) => {
	await Promise.all([
		context.send('Wait for the uploads awesome 😻'),

		context.sendPhotos('https://loremflickr.com/400/300/')
	]);
});

hearCommand('time', ['/time', '/date'], async (context) => {
	await context.send(String(new Date()));
});

const catsPurring = [
	'http://ronsen.org/purrfectsounds/purrs/trip.mp3',
	'http://ronsen.org/purrfectsounds/purrs/maja.mp3',
	'http://ronsen.org/purrfectsounds/purrs/chicken.mp3'
];

hearCommand('purr', async (context) => {
	const link = catsPurring[Math.floor(Math.random() * catsPurring.length)];

	await Promise.all([
		context.send('Wait for the uploads purring 😻'),

		context.sendAudioMessage(link)
	]);
});

vk.updates.start().catch(console.error);
```

> Возможно сделал ошибку при вставке токена в поле, но я хз..
