### ISSUE TITLE
captchahandler

### ISSUE THREAD

**Issue by notz448** [negezor/vk-io#273]
Проблема с обработкой капчи, все ниже
`vk.captchaHandler(async ({ src }, retry) => {`
  ` ^`
`TypeError: vk.captchaHandler is not a function`

код

> vk.captchaHandler(async ({ src }, retry) => {

	const response = await fetch(src);

	const buffer = await response.buffer();

	const base64Captcha = `data:${response.headers.get('content-type')};base64,${buffer.toString('base64')}`;

	const key = await captchahandler;

	try {
		await retry(key);

		console.log('Капча успешно решена');
	} catch (error) {
		console.log('Капча неверная');
	}});

**Comment by negezor** [comment]
Обработчик `vk.captchaHandler` не метод, нужно его присваивать:
```js
vk.captchaHandler = async ({ src }, retry) => {
	const response = await fetch(src);

	const buffer = await response.buffer();

	const base64Captcha = `data:${response.headers.get('content-type')};base64,${buffer.toString('base64')}`;

	const key = await captchahandler;

	try {
		await retry(key);

		console.log('Капча успешно решена');
	} catch (error) {
		console.log('Капча неверная');
    }
};
```
