### ISSUE TITLE
Как отлавливать события? 

### ISSUE THREAD

**Issue by hos1n** [negezor/vk-io#276]
Привет, мне нужно отловить событие group_join. Но в силу недостатка моего опыта сделать это не получилось.

**Comment by nitreojs** [comment]
исходя из https://github.com/negezor/vk-io/blob/master/packages/vk-io/src/updates/updates.ts#L93, метод **group_join** присутствует в библиотеке и должен работать. выставлена ли галочка **Вступление в сообщество** в _Работа с API -> Long Poll API_?

![изображение](https://user-images.githubusercontent.com/40319427/81500892-b75d6380-92dd-11ea-9c9a-aad82934777f.png)

**Comment by hos1n** [comment]
> исходя из https://github.com/negezor/vk-io/blob/master/packages/vk-io/src/updates/updates.ts#L93, метод **group_join** присутствует в библиотеке и должен работать. выставлена ли галочка **Вступление в сообщество** в _Работа с API -> Long Poll API_?
> 
> ![изображение](https://user-images.githubusercontent.com/40319427/81500892-b75d6380-92dd-11ea-9c9a-aad82934777f.png)

Да, включено.

**Comment by negezor** [comment]
Как именно запускается получение событий? Если через Polling, то необходимо убедится что запускается через `updates.start()` или указан `pollingGroupId`.
