### ISSUE TITLE
Как ввести 2 пользователей в 1 сцену?

### ISSUE THREAD

**Issue by RomanJarckov** [negezor/vk-io#277]
Как добавить 2 человека в 1 сцену?
Чтобы 1 сцена отлавливала события от 2 пользователей?

**Comment by isinkin** [comment]
То есть? Можно пример? И для чего это вам надо?

**Comment by RomanJarckov** [comment]
> То есть? Можно пример? И для чего это вам надо?

Ну, допустим хочу отлавливать ник пользователя из чужого бота.

Пример:
Пользователь: Профиль
Чужой бот: Ник, профиль:

Мне нужно достать ник

**Comment by negezor** [comment]
Сцены сделаны немного не для этого. По хорошему тут лучше построить свою схему на перехвате сообщений.
