### ISSUE TITLE
Как можно сделать ответ на не созданное сообщение?

### ISSUE THREAD

**Issue by Boniuss** [negezor/vk-io#278]
#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `X.Y.Z` |
| `node`                             | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `X.Y.Z` |

Как можно сделать ответ на неверное сообщение? То есть как бы бот отвечал на неправильное сообщение, которого не существует?

**Comment by negezor** [comment]
https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/updates.md#sethearfallbackhandler
