### ISSUE TITLE
Сбор вызовов методов в очередь для предотвращения 6-ой ошибки

### ISSUE THREAD

**Issue by RedFoxCode** [negezor/vk-io#28]
Если вызвать много методов за раз, например как

```javascript
let api = vk.api.call
api("friends.getRequests")
api("wall.get")
api("friends.get")
```

То оно выпадет в 6-ю ошибку (too many requests). Через vk.chain не получится, ибо когда вызовутся методы непредсказуемо, при том могут наложится еще. Так вот, запилить чтоб методы собирались в массив (очередь) и они постепенно вызывались, каждый по 334 миллисекунды. Тогда 6-ой ошибки не будет.

**Comment by negezor** [comment]
Ну так это давно реализовано, разве появились баги? Можно stack trace получить?
