### ISSUE TITLE
Generic type 'Composer<T, R>' requires between 1 and 2 type arguments

### ISSUE THREAD

**Issue by Baalaandaa** [negezor/vk-io#282]
#### What did you do?
Installed lib, tried to run sample

#### What did you expect to happen?
TS compiles ok

#### What was the actual result?
Compile error http://prntscr.com/sl8efh

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `v12.16.0` |
| `TypeScript`                       | `3.8.3` |
| `yarn` or `npm`                    | `npm 6.13.4` |

**Comment by negezor** [comment]
Duplicate https://github.com/negezor/vk-io/issues/234
