### ISSUE TITLE
Передача контекста отправленного сообщения после успешной отправки

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#283]
В данный момент, после успешной отправки сообщения нам возвращается его id в диалоге.
Хотелось бы получать его контекст, например это будет полезно для моментального редактирования сообщения или его удаления, без отлавливания его контекста в updates.

Конечно, можно брать нужные параметры для api-метода редактирования сообщения из контекста отправленного сообщения пользователем и потом подставлять id отправленного сообщения и мы получим тот же самый результат, но хочется простоты и красоты кода.

**Comment by nitreojs** [comment]
Это всё конечно прекрасно будет видеть контекст отправленного сообщения, но это тебе не Telegram API и тут API "на уровень выше". Само API после отправки сообщения отдает `{ response: number }`, то есть для того, чтобы реализовать твою идею, придётся делать лишний запрос, а это **в 2 раза дольше** (из-за пинга до сервера ВК и обратно), чем просто получить ID сообщения после выполнения метода messages.send; к тому же, я видел довольно мало (практически ноль) случаев использования отправленного контекста (в отличие от Telegram, здесь он не нужен, так как нет хороших и удобных методов для работы с отправленным сообщением)

**Comment by negezor** [comment]
Реализовано в v4.0.0. Работает пока только в беседах созданных для сообщества и в ЛС.
