### ISSUE TITLE
подписка на события группы

### ISSUE THREAD

**Issue by MEGA72** [negezor/vk-io#285]
```
const { VK } = require("vk-io");
const vk = new VK();
const config = require("./config/config");
vk.token = config.token;

vk.updates.on(["wall_comment"], async context => {
  console.log(context);
})

vk.updates.on(["new_wall_repost"], async context => {
  console.log(context);
}) 

vk.updates.on(["new_wall_post"], async WallPostContext => {
  console.log(WallPostContext);
})

vk.updates.on(["new_message"], async context => {
  console.log(context);
})

vk.updates.start(console.log("bot up")).catch(console.error);
```

сделал подписку на события, новый пост в группе и репост записи из группы. 
постоянно выпадают сообщения в логах 

>  Deprecated: context.userId deperecated, use context.fromId

как бороться или не бороться?:) 
#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                        |     4.0.0-rc.30 
| `node`                        |      v14.3.0

**Comment by negezor** [comment]
Заменить `context.userId` на `context.fromId` :)

**Comment by negezor** [comment]
Я закрою этот вопрос, так как здесь отсутсвует активность.
