### ISSUE TITLE
Методы не передают параметр attachment при отправке

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#286]
При использовании **.sendDocuments()** **.sendPhotos()** **.sendAudioMessage()** при этом передавая дополнительные параметры к сообщению такие как attachment и тд, **attachment** передаваемый к сообщению не передается.

Другие методы не тестировал.

https://github.com/negezor/vk-io/blob/63a20ce512ef9e88e7c6981bab39487910633be8/packages/vk-io/src/structures/contexts/message.ts#L585-L597
```js
return context.sendDocuments({
                                value,
                                filename
                            },
                            {
                                message: "message",
                                attachment: "photo233731786_457263782"
                            });

**Comment by negezor** [comment]
Он не передаётся потому что соотвественно его переопределяет результат вызванной загрузки. Это всего лишь алиас, если нужно добавить свои и загрузить, то лучше сделать это отдельно. Так-как непонятно как это должно мерджиться.

**Comment by MrZillaGold** [comment]
В чем проблема, допустим, у нас загрузилось это вложение нормально и мы готовы отправит сообщение, почему бы не добавлять ещё и те вложение которые мы передаём?

**Comment by negezor** [comment]
Какой именно параметр? Если `source` то соотсветсвенно его значение передаётся в `vk.upload.messageDocument(...)`. Если `params` - он не обязательный.

**Comment by MrZillaGold** [comment]
attachment

**Comment by negezor** [comment]
Ну так это свойство, а не параметр. Он переопредяется результатом загрузки, что собственно понятно из названия метода. Как я и сказал, если нужно передать вручную прикрипления, стоит использовать связку `vk.upload.messagePhoto()` и `context.send()`.

**Comment by MrZillaGold** [comment]
Я понимаю, что оно предопределяется результатом, в чем проблема **после успешного результата** добавлять в результат **attachment** который мы передаем перед выполнение?

https://github.com/negezor/vk-io/blob/63a20ce512ef9e88e7c6981bab39487910633be8/packages/vk-io/src/structures/contexts/message.ts#L593-L597
В этом месте происходит отправка вложения после успешной загрузки, если при выполнения метода в параметрах присутствует **attachment**, мы добавляем к нему результат загрузки.

```
const response = await this.send({
			...params,

			attachment: uploadedAttachment + attachment
		});
```

По такой логике метод **.send()** вообще не нужен в библиотеке, можно же использовать одно api, мне кажется та конструкция которую описываю я намного удобнее, тем более после использования **.send()** у многих пользователей будет складываться впечатление, я уверен так и происходит, что все остальные методы для отправки работают точно также.

**Comment by negezor** [comment]
Проблема тут в том что непонятно, куда именно он будет добавляться. Если ставить его первым прикреплением, то что тогда делать если мне нужно что бы он был последним?

**Comment by MrZillaGold** [comment]
Если смотреть по иерархии , если мы передаем уже загруженные вложения, то они так и так старея чем те которые мы только будем загружать. По цепочке, как я считаю, их нужно ставить первыми.
А вот, что делать если необходимо наоборот - непонятно.

**Comment by negezor** [comment]
Придётся всё так же использовать методы загрузки вручную. Я думаю это идеальное поведение в данной ситуации. В целом можно рассмотреть поведение из Telegram.
