### ISSUE TITLE
Бот не видит инфо о сообщении.

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#287]
Бот не реагирует если люди с именами (пример Имя' Фамил'ия) пересылают какие-то записи.
Например я выделил сообщение, и отправил, context нет ответа.

**Comment by nitreojs** [comment]
Может быть, это проблема со стороны API?
Есть ли какие-нибудь доказательства? Фотографии приходящих респонсов или сами приходящие респонсы?

**Comment by el9in** [comment]
Сомневаюсь что со стороны API, хотя всё может быть.
В логах не выводит даже пустую строку. Вывод из console.log(context);, с другими именами всё хорошо. Так же данная ошибка связана только с аудио / постами и видео при именах И'мя Фа'милия с символами.

**Comment by negezor** [comment]
Запустите бота с env `DEBUG=vk-io:updates` и посмотрите какие события приходят во время того как пишет человек с символами в имени и фамилии. Если события не приходят — проблема со стороны ВК.

**Comment by el9in** [comment]
Куда это нужно вписать?

**Comment by negezor** [comment]
В консоль, пример:
```sh
DEBUG=vk-io:updates node bot.js
```
Для Windows будет что-то вроде:
```sh
set DEBUG=vk-io:updates
node bot.js
```

**Comment by el9in** [comment]
Не выводит результат. (Не работает только если переслать сообщение без текста (только запись человека с таким именем))
![image](https://user-images.githubusercontent.com/46536746/85576225-e6872480-b640-11ea-8fb7-64c6b4314f13.png)

**Comment by el9in** [comment]
![image](https://user-images.githubusercontent.com/46536746/85576364-04ed2000-b641-11ea-8ffc-dcb71b1850b8.png)

**Comment by el9in** [comment]
А вот нормальное имя
![image](https://user-images.githubusercontent.com/46536746/85577112-a5dbdb00-b641-11ea-82e0-61910d9f3a9b.png)

**Comment by negezor** [comment]
Нужно смотреть в консоль, а не в диалог. Именно там будут показаны события.

**Comment by el9in** [comment]
Я смотрел, вывод был только 1 сообщения с моим идом 232356, второй ID вообще не вывелся, даже номер диалога.

**Comment by negezor** [comment]
Значит проблема на стороне ВКонтакте, здесь я уже ничем не помогу.

**Comment by el9in** [comment]
Я уже написал об этой проблеме в поддержку, отпишу тут если её решат.

**Comment by dndrheadof** [comment]
Могут ли вложения в сообщении как-нибудь влиять на это? Сейчас проверили на последней версии vk-io и на версии апи 5.110 сообщения спокойно консолятся

**Comment by el9in** [comment]
Можете добавить меня в беседу? Я посмотрю при таких ли условиях они консолятся как у меня.
vk.com/thev1p

**Comment by el9in** [comment]
Проблема в 10 вложениях в записях.
ТП ответила что знает про проблему уже довольно давно.
