### ISSUE TITLE
Async iterator in method collect.wall.get works incorrectly

### ISSUE THREAD

**Issue by Mreddi1** [negezor/vk-io#289]
#### What did you do?
I called method `collect.wall.get` and used result in `for await` statement

#### What did you expect to happen?
ICollectChunkData

#### What was the actual result?
But got an error:
`
RangeError: Maximum call stack size exceeded
    at CollectStream.[Symbol.asyncIterator] (/PATH_TO_PROJECT_FOLDER/node_modules/vk-io/lib/index.js:3876:27)
`
#### Additional Info
I looked at the source (index.js) and noticed that in class CollectStream in body method [Symbol.asyncIterator]: `return this[Symbol.asyncIterator]();`
But there must be: `return super[Symbol.asyncIterator]();`
If I change the keyword from **this** to **super** everything works as it should.

Perhaps the problem is in the typescript build. I will do  investigate and tests about this.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `13.9.0` |
| `TypeScript`                       | `3.9.5` |
| `npm`                    | `6.13.7` |

**Comment by Mreddi1** [comment]
I compiled locally on scripts from https://travis-ci.org/github/negezor/vk-io/builds/702839222. And everything works as it should.

**Comment by Mreddi1** [comment]
I installed vk-io v.4.0.0-rc.27 and everything works as it should, because inherited methods are used from stream.Readable

**Comment by negezor** [comment]
Fixed in https://github.com/negezor/vk-io/commit/21921361d6f04cf5426227b4099285d3987fe715, but not released

**Comment by negezor** [comment]
Fixed in v4.0.0.
