### ISSUE TITLE
Не работает updates.on

### ISSUE THREAD

**Issue by MrLeecs** [negezor/vk-io#290]
Приветствую. Не работают никакие события кроме message и wall_post_new в группе. В настройках группы все права и события включены. Последняя версия api.

**Comment by negezor** [comment]
Покажите пример кода которым пытаетесь поймать события, потому как `updates.on(type, callback)` предназначен для фильтрования до необходимых.

**Comment by MrLeecs** [comment]
const config = require('./config');
const {VK, Keyboard} = require('vk-io');
const vk = new VK({token: config.vk.token, apiMode: 'parallel'});
vk.updates.on('message', async (context, next) => {
console.log(context)
}
vk.updates.on('like_add', async (context, next) => {
console.log(context)
}
vk.updates.on('wall_reply_new', async (context, next) => {
console.log(context)
}
vk.updates.start().catch(console.error);

**Comment by MrLeecs** [comment]
`const config = require('./config');
const {VK, Keyboard} = require('vk-io');
const vk = new VK({token: config.vk.token, apiMode: 'parallel'});
vk.updates.on('message', async (context, next) => {
console.log(context)
}
vk.updates.on('like_add', async (context, next) => {
console.log(context)
}
vk.updates.on('wall_reply_new', async (context, next) => {
console.log(context)
}
vk.updates.start().catch(console.error);`

**Comment by negezor** [comment]
События лайков ещё не реализованы, да и в текущей версии получать посты можно так:
```js
vk.updates.on('new_wall_reply', async (context, next) => {
    console.log(context)
}
```

**Comment by negezor** [comment]
Я закрою этот issue из-за неактивности.
