### ISSUE TITLE
callback

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#292]
Как получить событие callback с помощью vk io?

**Comment by negezor** [comment]
Дубликат, отслеживается здесь https://github.com/negezor/vk-io/issues/291

**Comment by el9in** [comment]
Не совсем ответ на мой вопрос.
Я спросил, можно ли как то получить callback события, например как в php, вставляешь адрес. Только с помощью модуля vk-io?

**Comment by negezor** [comment]
Да можно, это называется `webhook`.
