### ISSUE TITLE
Отсутствует важный евент

### ISSUE THREAD

**Issue by keyfqsY** [negezor/vk-io#294]
Очень удивился когда увидел, что отсутствует например, евент лайка или репоста, когда завезут поддержку этих евентов? (с другими модулми на той-же группе всё работает)

**Comment by isinkin** [comment]
репост реализован и доступен в текущей версии, лайк реализован но не выпущен

**Comment by negezor** [comment]
Всё как и сказал @isinkin.

**Comment by tailsjs** [comment]
согласен с @isinkin.

**Comment by negezor** [comment]
Реализовано в v4.0.0.
