### ISSUE TITLE
Добавил поле deactivated в Objects.UsersFields

### ISSUE THREAD

**Issue by b-ponomarenko** [negezor/vk-io#295]
При вызове метода vk.api.users TS ругается Type '"deactivated"' is not assignable to type 'UsersFields'., хотя по доке я могу вызвать метод с этим параметром (https://vk.com/dev/users.get)
![image](https://user-images.githubusercontent.com/9141542/87644195-7c9bff80-c754-11ea-9d69-90dc21036ae0.png)

**Comment by negezor** [comment]
Не нужно указывать поле `deactivated`, оно в любом случае вернётся если пользователь заморожен/забанен.
![image](https://user-images.githubusercontent.com/9392723/87653990-0d4cfc80-c7a2-11ea-8d79-81673042d2ca.png)
