### ISSUE TITLE
access_token 

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#296]
Как сделать вызов через другой токен, пример кода который не работает и вызов происходит через токен основной группы.
```
await vkcb.api.messages.getConversationMembers({ 
					peer_id: 'беседа',
					access_token: 'токен'
				})
```

**Comment by negezor** [comment]
Какая версия vk-io?

**Comment by el9in** [comment]
4.0.0-rc.30

**Comment by el9in** [comment]
Странно что 
await vkcb.api.messages.send
Работает с access_token, а вот await vkcb.api.messages.getConversationMembers нет.

**Comment by el9in** [comment]
Такс, ошибка в обработчике
```
try {
await vkcb.api.messages.getConversationMembers({ 
					peer_id: 'беседа',
					access_token: 'токен'
				})
} catch (error) {
...
}
```
vk-io почему то выдаёт ошибку 7, что сообщества нет в беседе, но если установить .catch(console.error) т.е.
```
await vkcb.api.messages.getConversationMembers({ 
					peer_id: 'беседа',
					access_token: 'токен'
				}).catch(console.error)
```
vk-io выдаёт ошибку 917 (именно ту ошибку которая должна выходить. (у пользователя нет доступа к чату)

**Comment by el9in** [comment]
Нашёл подмену токена, это из за 
```
vk.setOptions({
	apiMode: 'parallel_selected',
	apiExecuteMethods: ['messages.send'],
	apiLimit: 25
});
```
Видимо оно привязывает токен.

**Comment by negezor** [comment]
А ну в принципе логично что в `execute` игнорирует другие токены.
