### ISSUE TITLE
Как вернуть все старые названия

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#298]
У вас в модуле возврат идёт senderId, а мне нужно from_id, можно ли как то изменить возврат данных по умолчанию?

**Comment by Noop1** [comment]
Так в чем сложность поменять в вашем коде с from_id на senderId?

**Comment by negezor** [comment]
```js
vk.updates.on('message', (context, next) => {
  context.from_id = context.senderId;

  return next();
});
```

**Comment by el9in** [comment]
Как бы да, но не то. Мне нужно изменить все названия, в attachment, authorId на обычные и прочие названия которые возвращаются не по дефолту.

**Comment by negezor** [comment]
Если нужны необработанные данные, то они лежат в `context.payload`
