### ISSUE TITLE
не работает context.replyMessage

### ISSUE THREAD

**Issue by Nikt-OS** [negezor/vk-io#299]
перестала работать обработка ответов на сообщения
```
  context.loadMessagePayload();
  console.log(context.replyMessage)
  console.log(context.replyMessage.senderId)
```
 при попытке получить данные `context.replyMessage` выдает **null**, а при `context.replyMessage.senderId` -- ошибку

![изображение](https://user-images.githubusercontent.com/24947331/88793557-a538e600-d1a5-11ea-8023-5d62e51a0bf9.png)

**Comment by isinkin** [comment]
а может 

```js
await context.loadMessagePayload();
```

**Comment by Nikt-OS** [comment]
работает, спасибо за указание ошибки))
