### ISSUE TITLE
Как отправить сообщение только единожды?

### ISSUE THREAD

**Issue by F1ks3r** [negezor/vk-io#30]
Сейчас такой код выдает сообщение за сообщением, каким образом отправить сообщение только 1 раз?
```
const vk_io = require('vk-io')
const vk = new vk_io({token: dev_token})
vk.longpoll.start().then(() => {
    console.log('Long Poll запущен');
})
.catch((error) => {
    console.error(error)
})

vk.longpoll.on('message', (message) => {
    message.send('hi')
})
```

**Comment by negezor** [comment]
Если нужно проверить что бы бот не отвечал сам на своии сообщения можно сделать [так](https://github.com/castery/caster-vk/blob/22ed8bc94206aff8eb0787706925c462eeb871e9/src/platform.js#L351-L355)
Но если нужно запустить цепочку диалога тут я могу посоветовать только создания сессии и уже по ней вести диалог, абстрактный код:
```javascript
const topics = new Map;

vk.longpoll.on('message', async (message) => {
    /* Пропускает своё сообщение в группе */
    if (message.hasFlag('answered')) {
        return;
    }

    if (topics.has(message.peer)) {
       topics.set(message.peer, 'start');

       return await message.send('hi');
    }

   /* Тут уже ввести дальше что не связанно с приветсвием  */
})
```
Так же не стоит игнорировать ошибки, я использовал тут async/await потому что это удобно.
