### ISSUE TITLE
Поддержка Inline keyboard

### ISSUE THREAD

**Issue by murka** [negezor/vk-io#300]
Когда планируется поддержка [Inline](https://vk.com/dev/bots_docs_3?f=4.%2B%D0%9A%D0%BB%D0%B0%D0%B2%D0%B8%D0%B0%D1%82%D1%83%D1%80%D1%8B%2B%D0%B4%D0%BB%D1%8F%2B%D0%B1%D0%BE%D1%82%D0%BE%D0%B2) режима для клавиатуры?

**Comment by vitalyavolyn** [comment]
Прошлой осенью: https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/buttons/keyboard.md#inline
