### ISSUE TITLE
[question] Отправка изображений из Buffer

### ISSUE THREAD

**Issue by inoyakaigor** [negezor/vk-io#301]
Насколько я понял для отправки изображений методом `sendPhotos` нужно, чтобы они присутствовали на диске физически, но беглая отладка этого метода говорит о том, что под капотом там так или иначе используются внутренние методы Node, а значит в, теории можно использовать [Buffer](https://nodejs.org/api/buffer.html#buffer_class_buffer). Посему вопрос: как это можно сделать?

**Comment by negezor** [comment]
https://github.com/negezor/vk-io/blob/master/docs/examples/uploads.js#L47

**Comment by negezor** [comment]
В итоге используем так:
```js
context.sendPhotos({
  value: youBuffer
});
```

**Comment by negezor** [comment]
Я закрою этот вопрос из-за отсутсвия активности.
