### ISSUE TITLE
Cannot read property 'enter' of undefined

### ISSUE THREAD

**Issue by tenwiq** [negezor/vk-io#303]
#### What did you do?

Написал команду 
```js
sceneManager.addScene(new StepScene('money', [
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Я готов к выдачи денег, подтвердите действие, напишите "подтверждаю"');
        }
        if (message.text == 'подтверждаю' || message.text == 'Подтверждаю') return message.scene.step.next();
        if (!message.text == 'подтверждаю' || message.text == 'Подтверждаю') return message.send(`Подтвердите действие, напишите "подтверждаю"`)
    },
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Сколько вам нужно?');
        }
        if (message.text == 'выйти') return message.scene.leave();

        a.balance += Number(message.text);

        return message.scene.step.next();
    },
    async (message) => {
        const {
            firstName,
            age
        } = message.scene.state;

        await message.send(`Готово, я выдал вам запрошенные деньги!`);

        await message.scene.leave();
    }
]));

vk.updates.on('message', sessionManager.middleware);
vk.updates.on('message', sceneManager.middleware);
vk.updates.on('message', (message, next) => {
    if (!message.scene.current) {
        return next();
    }
    const cancel = message.messagePayload && message.messagePayload.command === 'cancel';
    if (cancel) {
        return message.scene.leave({
            canceled: true
        });
    }
    return message.scene.reenter();
});


vk.updates.hear(/^(?:money)/i, (message) => {
    if (message.user.settings.adm < 1) return;
    return message.scene.enter('money');
});
```

#### What did you expect to happen?

Бот должен ответит на сообщение  "money"

#### What was the actual result?

Cannot read property 'enter' of undefined

Получаю вот такую ошибку
![Screenshot_1](https://user-images.githubusercontent.com/31911410/89369480-e457c180-d6e6-11ea-9b46-e574502c69f4.png)

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0` |
| `@vk-io/scenes`                    | `0.0.0-alpha.5` |
| `node`                             | `14.4.0` |
| `TypeScript`                       | `no use` |
| `yarn` or `npm`                    | `6.14.7` |

**Comment by Noop1** [comment]
Пришлите строчки 6482 и 971.

**Comment by negezor** [comment]
Должен быть только один обработчик, из этих двух:
```js
vk.updates.on('message', sceneManager.middleware);
```
Или
```js
vk.updates.on('message', (message, next) => {
    if (!message.scene.current) {
        return next();
    }
    const cancel = message.messagePayload && message.messagePayload.command === 'cancel';
    if (cancel) {
        return message.scene.leave({
            canceled: true
        });
    }
    return message.scene.reenter();
});
```

**Comment by tenwiq** [comment]
negezor,  все равно  Cannot read property 'enter' of undefined

**Comment by tenwiq** [comment]
Noop1, 971  строка - 	message.args = message.text.match(command[0]);
	await command[1](message, bot);

а 6482 указывает, где произошла ошибка, там как раз enter

**Comment by negezor** [comment]
У вас используется своя реализация `.hear()`? Если да, то она должна обрабатываться позже установки сцены в контекст.

**Comment by tenwiq** [comment]
Да, я пользуюсь реализации `.hear()`. 

Пробовал без реализации, там такая же ситуация с undenfined "enter"

**Comment by negezor** [comment]
Можно привести полный код? Ведь `undefined` будет только в случае того что в контекст не установлен scene.

**Comment by tenwiq** [comment]
const { VK, Keyboard } = require('vk-io');
const vk = new VK();
const commands = [];
const request = require('prequest');
const fs = require("fs");
const format = require('node.date-time');
const googleTTS = require('google-tts-api'); 
let user = new VK();
const https = require('https');
const requests = require('request');
const rq = require("prequest");
const tcpp = require('tcp-ping');
const http = require('http'); 
const chalk = require('chalk');
const request = require('prequest');
const { SceneManager, StepScene } = require('@vk-io/scenes')
const { SessionManager } = require('@vk-io/session')
const sessionManager = new SessionManager();
const sceneManager = new SceneManager();

Manager.addScene(new StepScene('signup', [
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Как тебя зовут?');
        }
        a.nick = message.text;
        return message.scene.step.next();
    },
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Сколько тебе лет?');
        }
        a.age = Number(message.text);
        return message.scene.step.next();
    },
    async (message) => {
        const { firstName, age } = message.scene.state;
 
        await message.send(`👤 Вы ${a.nick}, Вам ${a.age} лет`);
 
        await message.scene.leave();
    }
]));

cmd.hear(/^(?:тест)/i, (message) => {
    return message.scene.enter('signup');
});

**Comment by tenwiq** [comment]
`const { VK, Keyboard } = require('vk-io');
const vk = new VK();
const commands = [];
const request = require('prequest');
const fs = require("fs");
const format = require('node.date-time');
const googleTTS = require('google-tts-api'); 
let user = new VK();
const https = require('https');
const requests = require('request');
const rq = require("prequest");
const tcpp = require('tcp-ping');
const http = require('http'); 
const chalk = require('chalk');
const fortyn = '';
let giving = false;
let ownerid = 301165464;
const request = require('prequest');
const { SceneManager, StepScene } = require('@vk-io/scenes')
const { SessionManager } = require('@vk-io/session')
const sessionManager = new SessionManager();
const sceneManager = new SceneManager();

sceneManager.addScene(new StepScene('signup', [
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Как тебя зовут?');
        }
        a.nick = message.text;
        return message.scene.step.next();
    },
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Сколько тебе лет?');
        }
        a.age = Number(message.text);
        return message.scene.step.next();
    },
    async (message) => {
        const { firstName, age } = message.scene.state;
 
        await message.send(`👤 Вы ${a.nick}, Вам ${a.age} лет`);
 
        await message.scene.leave();
    }
]));

vk.updates.on('message', sessionManager.middleware);
vk.updates.on('message', sceneManager.middleware);
vk.updates.on('message', (message, next) => {
    if (!message.scene.current) {
        return next();
    }
    const cancel =  message.messagePayload && message.messagePayload.command === 'cancel';
    if (cancel) {
        return message.scene.leave({
            canceled: true
        });
    }
    return message.scene.reenter();
});
 
cmd.hear(/^(?:тест)/i, (message) => {
    return message.scene.enter('signup');
});`

**Comment by tenwiq** [comment]
`const { VK, Keyboard } = require('vk-io');
const vk = new VK();
const commands = [];
const request = require('prequest');
const fs = require("fs");
const format = require('node.date-time');
const googleTTS = require('google-tts-api'); 
let user = new VK();
const https = require('https');
const requests = require('request');
const rq = require("prequest");
const tcpp = require('tcp-ping');
const http = require('http'); 
const chalk = require('chalk');
const fortyn = '';
let giving = false;
const request = require('prequest');
const { SceneManager, StepScene } = require('@vk-io/scenes')
const { SessionManager } = require('@vk-io/session')
const sessionManager = new SessionManager();
const sceneManager = new SceneManager();

sceneManager.addScene(new StepScene('signup', [
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Как тебя зовут?');
        }
        a.nick = message.text;
        return message.scene.step.next();
    },
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Сколько тебе лет?');
        }
        a.age = Number(message.text);
        return message.scene.step.next();
    },
    async (message) => {
        const { firstName, age } = message.scene.state;
 
        await message.send(`👤 Вы ${a.nick}, Вам ${a.age} лет`);
 
        await message.scene.leave();
    }
]));

vk.updates.on('message', sessionManager.middleware);
vk.updates.on('message', sceneManager.middleware);
vk.updates.on('message', (message, next) => {
    if (!message.scene.current) {
        return next();
    }
    const cancel =  message.messagePayload && message.messagePayload.command === 'cancel';
    if (cancel) {
        return message.scene.leave({
            canceled: true
        });
    }
    return message.scene.reenter();
});
 
cmd.hear(/^(?:тест)/i, (message) => {
    return message.scene.enter('signup');
});`

**Comment by tenwiq** [comment]
пришлось заново переписать код без реализации.


` const { VK } = require("vk-io");
const vk = new VK();
const { updates } = vk;
const fs = require("fs");
const admins = [1];
const users= require("./users.json");
const { SceneManager, StepScene } = require('@vk-io/scenes')
const { SessionManager } = require('@vk-io/session')
const sessionManager = new SessionManager();
const sceneManager = new SceneManager();

 
vk.setOptions({
    token: "",
    apiMode: "parallel",
    pollingGroupId: 
});

async function saveAll()
{
    require('fs').writeFileSync('./users.json', JSON.stringify(users, null, '\t'));
    return true;
}

updates.startPolling();
updates.on('message', async (message, next) => {
    if(message.is("message") && message.isOutbox) return;
    message.user = message.senderId;
    if (message.user < 1) return;
    if (message.text) {
    console.log(`@id${message.senderId} ${ message.isChat ? "#" + message.chatId : "" }, text: ${ message.text.slice(0, 36) }`);
    }
    if (!users[message.senderId]) {
        users[message.senderId] = {
            permission: 0,
            balance: 1000,
            ban: false
        };
    }
    message.user = users[message.senderId];
    if (message.user.ban) return;
    try {
    await next();
    saveAll();
    } catch (err) { console.error(err) }
});
 

updates.hear(/(тест)/i, async (message) => {
    await message.send(`Работаю`)
});

updates.hear("up", async (message) => {
    if (!~admins.indexOf(message.senderId)) { return message.send('Ты не администратор');
    }
    message.user.permission = 2;
    await message.send(`Вам выданы права администратора`);
});
 
updates.hear(/(balance|баланс)/i, async (message) => {
    await message.send(`Твой баланс: ${ message.user.balance } $`)
});
 

sceneManager.addScene(new StepScene('signup', [
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Как тебя зовут?');
        }
        a.nick = message.text;
        return message.scene.step.next();
    },
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Сколько тебе лет?');
        }
        a.age = Number(message.text);
        return message.scene.step.next();
    },
    async (message) => {
        const { firstName, age } = message.scene.state;
 
        await message.send(`👤 Вы ${a.nick}, Вам ${a.age} лет`);
 
        await message.scene.leave();
    }
]));

vk.updates.on('message', sessionManager.middleware);
vk.updates.on('message', sceneManager.middleware);
vk.updates.on('message', (message, next) => {
    if (!message.scene.current) {
        return next();
    }
    const cancel =  message.messagePayload && message.messagePayload.command === 'cancel';
    if (cancel) {
        return message.scene.leave({
            canceled: true
        });
    }
    return message.scene.reenter();
});
 
vk.updates.hear(/^(?:проверь меня)/i, (message) => {
    return message.scene.enter('signup');
}); `

Именно с этого момента заработало Scene и без undenfined enter

**Comment by negezor** [comment]
В первом примере отсутсвует реализация `cmd.hear()`

**Comment by tenwiq** [comment]
реализация - 
const cmd = {
hear: (p, f) => {
commands.push([p, f]);
}
}

**Comment by negezor** [comment]
Имелось ввиду обработка комманд.

**Comment by tenwiq** [comment]
`const command = commands.find(x=> x[0].test(message.text));
message.args = message.text.match(command[0]);
await command[1](message, bot);`

**Comment by negezor** [comment]
Так снова не показан где именно вызывается этот код, где именно этот обработчик? Выше или ниже к этим?
```js
vk.updates.on('message', sessionManager.middleware);
vk.updates.on('message', sceneManager.middleware);
```

**Comment by tenwiq** [comment]
Эти коды находится в самом внизу, а если точнее последние коды

`
const cmd = { hear: (p, f) => { commands.push([p, f]); } }

const command = commands.find(x=> x[0].test(message.text)); message.args = message.text.match(command[0]); await command[1](message, bot);

Manager.addScene(new StepScene('signup', [
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Как тебя зовут?');
        }
        a.nick = message.text;
        return message.scene.step.next();
    },
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Сколько тебе лет?');
        }
        a.age = Number(message.text);
        return message.scene.step.next();
    },
    async (message) => {
        const { firstName, age } = message.scene.state;
 
        await message.send(`👤 Вы ${a.nick}, Вам ${a.age} лет`);
 
        await message.scene.leave();
    }
]));

sceneManager.addScene(new StepScene('money', [
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Я готов к выдачи денег, подтвердите действие, напишите "подтверждаю"');
        }
 if(message.text == 'подтверждаю' || message.text == 'Подтверждаю') return message.scene.step.next();
 if(!message.text == 'подтверждаю' || message.text == 'Подтверждаю') return message.send(`Подтвердите действие, напишите "подтверждаю"`)
    },
    (message) => {
        if (message.scene.step.firstTime || !message.text) {
            return message.send('Сколько вам нужно?');
        }
        if(message.text == 'выйти') return message.scene.leave();
 
        a.balance += Number(message.text);
 
        return message.scene.step.next();
    },
    async (message) => {
        const { firstName, age } = message.scene.state;
 
        await message.send(`Готово, я выдал вам запрошенные деньги!`);
 
        await message.scene.leave();
    }
]));
 
vk.updates.on('message', sessionManager.middleware);
vk.updates.on('message', sceneManager.middleware);
vk.updates.on('message', (message, next) => {
    if (!message.scene.current) {
        return next();
    }
    const cancel =  message.messagePayload && message.messagePayload.command === 'cancel';
    if (cancel) {
        return message.scene.leave({
            canceled: true
        });
    }
    return message.scene.reenter();
});
 
vk.updates.hear(/^(?:тест)/i, (message) => {
    return message.scene.enter('signup');
});
 
 vk.updates.hear(/^(?:money)/i, (message) => {
    if(a.adm < 1) return;
    return message.scene.enter('money');
});`

**Comment by tenwiq** [comment]
До меня только что дошло, что `vk.updates.on('message', sessionManager.middleware);
vk.updates.on('message', sceneManager.middleware);`
Должен находится перед комманд
