### ISSUE TITLE
Событие wall_post ссылка на источник.

### ISSUE THREAD

**Issue by raziEiL** [negezor/vk-io#305]
Подскажите пожалуйста как взять ссылку на источник видео (youtube) из поста группы. P.S. Имеется ли группа в вк по данному API или обсуждение на другом ресурсе?
```js
import { VK, AttachmentType } from "vk-io";

const vk = new VK({
    token: process.env.TOKEN,
    pollingGroupId: Number.parseInt(process.env.GROUP_ID)
});

vk.updates.on("wall_post", async (context, next) => {

    const video = context.wall.getAttachments(AttachmentType.VIDEO);
    for (const i of video) {
        console.log(i);
    }
});
```

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `v12.18.3` |
| `TypeScript`                       | `3.9.7` |
| `yarn` or `npm`                    | `6.14.6` |

**Comment by negezor** [comment]
Геттер
```js
video.platformName
```
В офицальной документации `platform`

**Comment by raziEiL** [comment]
`video.platformName` возвращает платформу , например `"YouTube"`, а мне нужно получить ссылку на само видео в youtube.

**Comment by negezor** [comment]
Нужно использовать `context.player`, при `video.platformName === 'YouTube'` будет ссылка на embed плеера, формат [https://www.youtube.com/embed/dQw4w9WgXcQ?__ref=vk.api](https://www.youtube.com/embed/dQw4w9WgXcQ?__ref=vk.api)

**Comment by negezor** [comment]
Я закрою этот вопрос из-за отсутствия активности.
