### ISSUE TITLE
undenfined message.payload.action.member_id

### ISSUE THREAD

**Issue by tenwiq** [negezor/vk-io#306]
Хочу сделать так, чтобы бот после приглашение проверил игрока, в бане он или нет. И вот, получить айди игрока с помощью метода message.payload.action.member_id

написал код:

`vk.updates.on(['chat_invite_user'],async (message, next) => {
		if(message.payload.action.member_id == message.senderId) return;
		let user = await vk.api.users.get({user_id: message.payload.action.member_id})
let chatid = message.chatId;	
			if(chats[message.chatId].users[message.payload.action.member_id].isBanned && chats[message.chatId].users[message.payload.action.member_id].permanently){
		    vk.api.call("messages.removeChatUser", {chat_id: chatid, user_id: message.payload.action.member_id});
		    return message.send('@id' + message.payload.action.member_id + ' - находится в бане.');}
		message.send(`${smilesuccess} Добро пожаловать в беседу. Напиши команду "!Помощь", что бы узнать мои команды`);
		await next();
	});`

получаю вот такой undenfined: 
![Screenshot_1](https://user-images.githubusercontent.com/31911410/89758168-d98a9b80-daef-11ea-89de-d032aa77d542.png)

И как мне вывести айди игрока?

**Comment by negezor** [comment]
Вместо того что бы лезть внутрь `payload`, лучше использовать геттер `context.eventMemberId`.
