### ISSUE TITLE
Не передается идентификатор сообщения при работе с longpoll

### ISSUE THREAD

**Issue by mrqiz** [negezor/vk-io#308]
#### What did you do?
Получаю сообщения через `vk.updates` и пытаюсь считать `id`.

#### What did you expect to happen?
`id` указывает идентификатор сообщения.

#### What was the actual result?
`id` всегда равен нулю.

#### Additional Info
Данные, которые прилетают после нового события:
```
MessageContext {
  id: 0,
  conversationMessageId: 128,
  peerId: 2000000001,
  peerType: 'chat',
  senderId: 424919130,
  senderType: 'user',
  createdAt: 1597173814,
  text: 'badword1',
  forwards: MessageForwardsCollection(0) [],
  attachments: [],
  isOutbox: false,
  type: 'message',
  subTypes: [
    'new_message'
  ],
  state: {}
}
```

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `12.16.3` |
| `TypeScript`                       | `none` |
| `yarn` or `npm`                    | `1.22.4` |

**Comment by negezor** [comment]
Для ботов идентификатор не передаётся в чатах.

**Comment by mrqiz** [comment]
Точно, забыл об этом изменении. Обидно, что его убрали. Но всё же, спасибо!
