### ISSUE TITLE
бот страничный спамит одинаковые сообщение за 1 сообщение

### ISSUE THREAD

**Issue by tenwiq** [negezor/vk-io#309]
```const vk = new VK();
const rq = require("prequest");
const { api } = vk;
const fs = require("fs");


vk.setOptions({ token: 'token'});
const { updates, snippets } = vk;

updates.startPolling();

console.log(`Хелло Ворлд`)

updates.on('message', async (message) => {
	return message.reply(`приветиккк`);

});
});
```

Напишу ему одно сообщение, а в ответ получаю вот так:

![image](https://user-images.githubusercontent.com/31911410/90122349-d39df000-dd65-11ea-8683-1a827fcd2ccc.png)

**Comment by tenwiq** [comment]
я понял в чем проблема :0. Извините за мой тупизм

**Comment by tenwiq** [comment]
способ не помог(

Добавил туда в updates.on(message)

if(message.senderId == id страничного бота) return;

----
он все равно спамит

**Comment by negezor** [comment]
Тут есть 3 варианта решения проблемы:
1. Отключить исходящие сообщения в группе
2. Использовать событие `message_new` (для версии `rc.30` событие `new_message`)
3. Использовать геттер `context.isOutbox`, он будет `true` если сообщение исходящее.

**Comment by tenwiq** [comment]
использовал геттер ```context.isOutbox```. Сработало. Благодарю
