### ISSUE TITLE
Как реализовать проверку отсутствия администратора в Беседе?

### ISSUE THREAD

**Issue by YeaOs** [negezor/vk-io#310]
Написал код вот так 

```JS
updates.hear(/^(?:проверка)$/i, async (message, bot) => {
   if (message.adminId)  return('Ты не админ, обмануть меня хотел?');
message.user.admin = 1;
return message.send('Ваши данные успешно обновлены');
  });
```

Он мне ничего не выдает, только фразу получаю "Ваши данные успешно обновлены"

**Comment by tailsjs** [comment]
Получать данные о том, что юзер админ или бот?

**Comment by YeaOs** [comment]
получить даннные о том, что юзер админ

**Comment by negezor** [comment]
В сообщении нет возможности узнать кто администратор. Для этого нужно получить список пользователей беседы. Но для этого бот должен быть администратором.

**Comment by tailsjs** [comment]
согласен с негезором.
