### ISSUE TITLE
wall_reply_new событие

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#313]
Пытаюсь отловить событие, но не успешно.
vk.updates.on('wall_reply_new', (context) => {
  console.log("тест");
});
updates.start();

**Comment by negezor** [comment]
В текущей версии вот так:
```js
vk.updates.on('new_wall_reply', (context) => {
console.log("тест");
});
```

**Comment by el9in** [comment]
Аналогично new_wall_reply тоже не работает, но вот new_wall_post работает.

**Comment by negezor** [comment]
Я немного ошибся, сейчас так:
```js
vk.updates.on('new_wall_comment', (context) => {
  console.log("тест");
});
```

**Comment by el9in** [comment]
А где можно посмотреть все изменения? Потому что они отличаются от https://vk.com/dev.php?method=groups_events

**Comment by negezor** [comment]
С выпуском 4.0.0 будут использованы оригинальные названия.

**Comment by el9in** [comment]
Спасибо за ответы.
