### ISSUE TITLE
Ошибка при загрузке фотографии пользователю

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#314]
#### What did you do?

При попытке отправить фотографию через **context.sendPhotos();** получаем ошибку.
Такая же ситуация наблюдается с **upload.messagePhoto();**.
Для теста используем [пример из документации](https://github.com/negezor/vk-io/blob/master/docs/examples/simple-keyboard-bot.js)

#### What was the actual result?
![image](https://user-images.githubusercontent.com/42776347/90552261-e4bb8680-e1d5-11ea-9566-ba34e4d7dd02.png)

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0` |
| `TypeScript`                   | `-.-.-` |
| `node`                             | `14.7.0` |
| `yarn` or `npm`                    | `6.14.5` |

**Comment by tenwiq** [comment]
У меня тоже самое все sendPhoto поломались

**Comment by negezor** [comment]
В v4.0.0 теперь стало обязательно использовать объект в свойствах отправки:

Было:
```ts
context.sendPhotos('./cat.png');
```

Стало:
```ts
context.sendPhotos({
	value: './cat.png',
	// filename: 'cat.png',
	// contentType: 'image/png',
	// contentLength: ...
});

// Или

context.sendPhotos({
	values: [{
		value: './cat.png'
		// filename: 'cat.png',
		// contentType: 'image/png'
		// contentLength: ...
	}],
	// timeout: 30_000,
	// uploadUrl: '...'
});
```

**Comment by MrZillaGold** [comment]
@negezor с **contex.sendPhotos();** все хорошо, но если использовать **upload.messagePhoto();** при этом передавая url, то получаем ошибку:
![image](https://user-images.githubusercontent.com/42776347/90613159-559d8580-e24c-11ea-977c-2d8f53ddb951.png)

Причем это происходит не со всеми ресурсами, пример проблемного ресурса:
https://mc-heads.net/body/mrzillagold

Такая же ошибка встречается и в другой issue:
https://github.com/negezor/vk-io/issues/302#issuecomment-670629538

```js
upload.messagePhoto({
   source: {
      value: "https://mc-heads.net/body/mrzillagold"
   },
   peer_id: context.peerId
})
.then(({ownerId, id, accessKey}) =>
   resolve(`photo${ownerId}_${id}_${accessKey}`)
)
```

В данный момент, чтобы решить эту проблему приходится извращаться с буффером.

**Comment by negezor** [comment]
Проблема в том что сервер не возвращает `content-length` и по этому ничего не загружается. Я думаю можно сделать force buffer режим для таких файлов.

P.S. Не нужно вручную описывать attachment, достаточно сделать так:
```ts
upload.messagePhoto({
   source: {
      value: "https://mc-heads.net/body/mrzillagold"
   },
   peer_id: context.peerId
})
.then((attachment) => String(attachment))
```

**Comment by negezor** [comment]
Должно работать правильно в v4.0.1
