### ISSUE TITLE
for await (const chunk of stream$1) {

### ISSUE THREAD

**Issue by YeaOs** [negezor/vk-io#316]
Раньше работало, а вот уже чет перестал работать
![image](https://user-images.githubusercontent.com/69641099/90636487-570e8400-e233-11ea-8315-a3dc4bb3607b.png)
до обновления 4.0.1 все работало, а вот после обновы теперь выдает мне такую ошибку

**Comment by YeaOs** [comment]
до обновления 4.0.1 все работало, а вот после обновы теперь выдает мне такую ошибку

**Comment by negezor** [comment]
Минимальная версия Node.js 12 или новее.

**Comment by YeaOs** [comment]
после этого получаю вот это 
![image](https://user-images.githubusercontent.com/69641099/90672816-6277a480-e25f-11ea-8558-b885df532550.png)

**Comment by MrZillaGold** [comment]
[Почитайте про изменения в 4 версии библиотеки](https://negezor.github.io/vk-io/ru/guide/migration-to-v4.html#breaking-%D1%81hanges), там написано про то, что теперь **setOptions()** метода не существует, нужно при инициализации класса VK передавать нужные данные в конструктор - из-за этого и ошибка .

**Comment by YeaOs** [comment]
С этим я разобрался. Теперь как подключить hearManager? Не очень точная информация, пытался подключить и выдает вот такое: 
![image](https://user-images.githubusercontent.com/69641099/90713609-6383f280-e2ae-11ea-82c6-a1cd07ff2494.png)

**Comment by negezor** [comment]
Пример для TypeScript, нужно убрать `<MessageContext>`.

**Comment by YeaOs** [comment]
Не отвечает бот на сообщение. В чем проблема?

```JS
const { VK, keyboard } = require("vk-io");
const { HearManager } = require('@vk-io/hear');
const vk = new VK({
	token: 
	pollingGroupId: 
});
const { updates, snippets } = vk;
const hearManager = new HearManager();

vk.updates.on('message_new', hearManager.middleware);

updates.on('message_new', async (context) => {
	const { text = 'default text' } = context;

	if (text === 'default text') {
		return context.send('Вы ничего не написали');
	}
	
	await context.send('Hello!');
});


hearManager.hear(/^hello$/, async (context) => {
	await context.send('Hello!');
});

vk.updates.start().catch(console.error);

console.log(`Работаю`);
```

**Comment by YeaOs** [comment]
Решил проблему. Я не обновился до 4.0.1. Благодарю.
