### ISSUE TITLE
Не прослушивается событие с vkpay: vkpay_transaction

### ISSUE THREAD

**Issue by nikitafloy** [negezor/vk-io#319]
Пытаюсь прослушать событие "Платёж через VK Pay", использую Long Poll.
Текущая проблема - оплата прошла, событие не ловится.

С 'transfer-to-group' vk pay отклоняет оплату (оплата проводится с другого аккаунта)

Как его прослушать уже?) Что я делаю не так? Сижу с документацией третий день

```
const { VK, Keyboard } = require('vk-io');
const vk = new VK({
	token: process.env.TOKEN,
});

vk.updates.hear('Начать', async context => {
		vk.api.messages.send({
			user_id: context.senderId,
			random_id: Math.random() * 100 + 1,
			message: 'VKPay test',
			keyboard: Keyboard.builder()
				.payButton({
					hash: {
						action: 'pay-to-group',
						group_id: GROUP_ID,
						amount: 1,
					}
				})
		});
	}
);

vk.updates.startPolling({
	pollingGroupId: GROUP_ID,
});

vk.updates.on('vk_pay_transaction', async (context) => {
	console.log(context);
});
```

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `14.8.0` |
| `TypeScript`                       | `3.9.7` |
| `yarn`                    | `1.22.4` |

**Comment by lowkeypriority** [comment]
@nikitafloy Заметил, что в `hash` вы не передаёте `aid` приложения для оплаты. Это указано в [документации](https://vk.com/dev/bots_docs_3?f=4.2.%2B%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%2B%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85)
<details><summary>Выдержка из документации</summary>
<b>Кнопка VK Pay</b>

открывает  окно оплаты VK Pay с предопределёнными параметрами. Кнопка называется  “Оплатить через VK pay”, VK pay отображается как логотип. Эта кнопка  всегда занимает всю ширину клавиатуры.

Поля:   

- type (string) — для кнопки вызова платежного окна имеет значение vkpay
- payload (string) — дополнительная информация.  В кнопках, не отправляющих текст, передается для совместимости со старыми клиентами.  
- **hash (string) — строка, содержащая параметры платежа VK Pay и идентификатор приложения в параметре aid , разделенные &. Пример: `action=transfer-to-group&group_id=1&aid=10`.**
</details>

Там конечно не указано, обязателен ли этот параметр, но скорее всего так и есть

**Comment by nikitafloy** [comment]
> @nikitafloy Заметил, что в `hash` вы не передаёте `aid` приложения для оплаты. Хотя этот параметр указан в [документации](https://vk.com/dev/bots_docs_3?f=4.2.%2B%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%2B%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85)
> 
> Выдержка из документации
> Кнопка VK Pay
> открывает окно оплаты VK Pay с предопределёнными параметрами. Кнопка называется “Оплатить через VK pay”, VK pay отображается как логотип. Эта кнопка всегда занимает всю ширину клавиатуры.
> 
> Поля:
> 
> * type (string) — для кнопки вызова платежного окна имеет значение vkpay
> * payload (string) — дополнительная информация.  В кнопках, не отправляющих текст, передается для совместимости со старыми клиентами.
> * **hash (string) — строка, содержащая параметры платежа VK Pay и идентификатор приложения в параметре aid , разделенные &. Пример: `action=transfer-to-group&group_id=1&aid=10`.**
> 
> Там конечно не указано, обязателен ли этот параметр, но скорее всего так и есть
> 
> P.S. Опции для кнопки оплаты вы формируете полностью сами в пределах "схемы" для этой кнопки (собственно референс на [интерфейс, который за это отвечает](http://negezor.github.io/vk-io/references/vk-io/interfaces/ikeyboardvkpaybuttonoptions.html))

И aid тоже передавал - и строкой и объектом, несколько раз доки перечитывал - не ловится оповещение.

**Comment by lowkeypriority** [comment]
@nikitafloy А числом вы передавали?

**Comment by nikitafloy** [comment]
> @nikitafloy А числом вы передавали?
> 
> UPD: и константа `GROUP_ID` объявлена? А то в коде объявления и импорта не наблюдается, хотя есть извлечение токена из переменных окружения.

Значение aid - число, взято из примера - 10
Даже строкой передавал, как в примере было
Константа объявлена

**Comment by Antonzlo** [comment]
У вас в настройках ЛП включено событие?
