### ISSUE TITLE
[bug] vk.api отправляет параметры, равные undefined

### ISSUE THREAD

**Issue by zardoy** [negezor/vk-io#321]
Привет!
Если коротко, то вызов **любого** API с параметром, у которого **явно** указано значение `undefined` приводит к тому, что он передается ВК. Ниже привел пример.

#### What did you do?

```ts
await ctx.send("it'll fail", {
    keyboard: undefined
});
```
`ctx` – контекст события `message_new`

<img width="785" alt="Снимок экрана 2020-08-28 в 00 53 43" src="https://user-images.githubusercontent.com/46503702/91498892-3d231000-e8c9-11ea-94a3-d3c36dcf1afa.png">

#### What did you expect to happen?

Параметры со значением `undefined` не должны передаваться, ровно так же, как если бы они были опущены.

#### What was the actual result?

VK-IO переводит `undefined` в строку и отдает это серверу.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.1` |
| `node`                             | `12.17.0` |
| `TypeScript`                       | `4.0.2` |
| `yarn`                              | `1.22.4` |

**Comment by isinkin** [comment]
Нет, постой, это не так работает немножко. Тебе объяснить?

**Comment by zardoy** [comment]
Ну давай, что немножко не так?

**Comment by isinkin** [comment]
То, что параметры отправляются с помощью URLSearchParams

```js
const params = {
   message: 'hello',
   keyboard: undefined
};

console.log(new URLSearchParams(params));
// Выведет: URLSearchParams { 'message' => 'hello', 'keyboard' => 'undefined' }
```

**Comment by zardoy** [comment]
@isinkin Да, но я в PR уже написал, что это именно баг, тк TypeScript вообще без разницы параметр не указан или указан со значением `undefined`, а вот в runtime это уже приводит к ошибки API. Это прям подводный камень какой-то.

**Comment by talentumtuum** [comment]
@zardoy почему это баг?

```javascript
const obj = {
  key: undefined,
}

const properties = Object.getOwnPropertyNames(obj)

console.log(properties)
```

Свойство объявлено, его тип - undefined и при его преобразовании в строку получается строка 'undefined'.
То что у ts что-то там не так работает уже относится к ts, рантайм у нас на v8, как правило, и он поддерживает только javascript.

**Comment by zardoy** [comment]
> ```js
> const obj = {
>   key: undefined,
> }
> 
> const properties = Object.getOwnPropertyNames(obj)
> 
> console.log(properties)
> ```


Все верно, но только зачем это преобразование? Ведь если мы хотим явно передать строку с таким контентом, почему явно не передать строку в качестве параметра?
```ts
vk.api.messages.send({
    message: "undefined" // - так ок
});
```

Возможно ты прав, что это не баг, а просто подводный камень из-за того, что ts не выкидывает ошибку компиляции при явном указании `undefined`. Однако моё предложение в PR заключается в том, что бы поведение когда мы параметр опускаем полностью и указываем `undefined` было одинаковым, тк не всегда

**Comment by zardoy** [comment]
Сори, что закрыл, сейчас дополню.

**Comment by talentumtuum** [comment]
@zardoy я понимаю о чем ты. 

Наверняка ты пишешь что-то вроде

```javascript
let someVariable;

const query = {
  key: someVariable,
}

send(query)
```

Я считаю эта проблема на стороне пользователя, писать нужно по-другому, а этим pr-ом ты ломаешь обратную совместимость.

**Comment by zardoy** [comment]
> Я считаю эта проблема на стороне пользователя, писать нужно по-другому, а этим pr-ом ты ломаешь обратную совместимость.

Согласен.

Просто вот смотри где собака зарыта (более наглядный пример):

 - я не мог так прописать
<img width="921" alt="Снимок экрана 2020-08-28 в 13 39 24" src="https://user-images.githubusercontent.com/46503702/91552188-13530300-e934-11ea-8116-91c843153839.png">

 - я вот так уже могу
<img width="249" alt="Снимок экрана 2020-08-28 в 13 39 59" src="https://user-images.githubusercontent.com/46503702/91552237-24037900-e934-11ea-9cdb-cc25c8752b59.png">

ts ругаться ну будет, хотя запрос по факту будет таким же. Просто подводный камень для пользователя

**Comment by talentumtuum** [comment]
@zardoy так ты ничего не пиши если не хочешь передавать этот параметр,  будет работать так как ты хочешь 

```javascript
vk.api.messages.send()
```

**Comment by negezor** [comment]
Тут скорее несовпадение поведений, при `JSON.stringify()` будет упущен `undefined`. В то время когда `URLSearchParams` приводит всё к строке. Это не будет ломанием обратной совместимости, так как проверяется именно `undefined`, а не `"undefined"`.

**Comment by talentumtuum** [comment]
@negezor про такие сообщения я и имел ввиду, не исключено что кто-то использует тип undefined когда хочет напечатать такой текст)

**Comment by isinkin** [comment]
А зачем вы вообще указываете в параметрах undefined?

**Comment by zardoy** [comment]
Явно указание — упрощенный пример, лишь для понимания. В реальности же это значение может приходить из функции, при слиянии объектов, и много откуда еще. Вот пример из PR:
'''ts
await ctx.send("Hey there!", {
    keyboard: await getKeyboardToSend() //undefined | KeyboardBuilder - соответствие типов, но ошибка ругается API
});
'''
Здесь использую как резервной тип, который бы означал то, что не нужно показывать клавиатуру

**Comment by talentumtuum** [comment]
То что URLSearchParams собирает undefined наверное более гибко и правильно, но менее удобно.

Я плохо знаю vkapi и сурсы этой либы и не могу сказать есть ли проблема, но если проблема разных поведений в одной библиотеке действительно есть, то это надо решать.

Полагаю, что можно передать напрямую body запроса и оно преобразуется в JSON с помощью JSON.stringify, который усекает undefined в отличии от URLSearchParams, что может путать пользователей библиотеки.

**Comment by zardoy** [comment]
> То что URLSearchParams собирает undefined наверное более гибко и правильно, но менее удобно.

@talentumtuum не совсем согласен, могу даже пример из другой весьма крупной либы привести.
Есть такая библиотека prisma (через неё можно делать запросы к бд). И вот один из их примеров:

```ts
const hisNotes = await prisma.userNote.findMany({
    where: {
        userName: "Dmitriy" // вернет записки только дмитрия
    }
});
const allNotes = await prisma.userNote.findMany({
    where: {
        userName: undefined // не вернет записки пользователя "undefined"
    }
});
// это равносильно
allNotes = await prisma.userNote.findMany({ });
```

**Comment by zardoy** [comment]
> upd: ну, а вместо undefined будет вылетать exception в некоторых случаях, например когда сообщение пустое.

согласен, только вот представь если тебе бот на любую команду будет спамить "undefined". Лучше уж исключение чем silent бессмыслица

**Comment by negezor** [comment]
Всё же я думаю ошибка лучше, чем проблемный пост. В таких инструментах как [Sentry](sentry.io) сложно отследить то что не является ошибкой. Мажор 4 версии был нацелен на улучшенное взамодействие с библиотекой и явный `undefined` не является им.

Это так же исправляет неочевидное поведение между `URLSearamParams` и `JSON.stringify()`, исправлено в https://github.com/negezor/vk-io/commit/1026d333a07ff50423100f331e74a8041e2f567d, опубликовано в [4.0.2](https://www.npmjs.com/package/vk-io/v/4.0.2)
