### ISSUE TITLE
после обновления до последней версии при запуске скрипта получаю ошибку

### ISSUE THREAD

**Issue by natikkk1** [negezor/vk-io#323]
NodeJS - v12.18.3
VK-IO - 4.0.1

![YmUcL-jjsjM](https://user-images.githubusercontent.com/70379385/91563499-a2b5e180-e947-11ea-990e-2bce55fa974b.jpg)

**Comment by negezor** [comment]
Дубликат https://github.com/negezor/vk-io/issues/317
