### ISSUE TITLE
[HELP] не работает авторизация группы

### ISSUE THREAD

**Issue by qukallon1337** [negezor/vk-io#325]
Когда пишу токен группы - пишет
APIError: Code №5 - User authorization failed: invalid session.

Пишу токен свой - все ок..

const vk = new VK({
	token: "бла-бла-бла",
	pollingGroupId: 198364786
});

**Comment by isinkin** [comment]
Но токен от пользователя...

**Comment by GoodHood5** [comment]
Попробуй вот так 
const vk = new VK();
vk.setOptions({ token: 'Token Group', apiMode: 'parallel', pollingGroupId: IDGROUP  });

**Comment by negezor** [comment]
Я закрою этот вопрос из-за неактивности.

**Comment by negezor** [comment]
Такая проблема возникает в основном из-за нового токена. Это проблема со стороны ВКонтакте.
