### ISSUE TITLE
AuthorizationError: Unsupported type validation

### ISSUE THREAD

**Issue by cyperdark** [negezor/vk-io#326]
#### What did you do?
скопировал код из примера
https://i.imgur.com/oyZFjah.jpg

#### What did you expect to happen?
авторизацию

#### What was the actual result?
https://i.imgur.com/JdzwOTN.jpeg

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.2` |
| `@vk-io/authorization`             | `1.0.0` |
| `node`                             | `v12.18.0` |
| `yarn` or `npm`                    | `npm` |

**Comment by negezor** [comment]
Если использовать официальные ID приложений — ситуация сохраняется?

**Comment by negezor** [comment]
В модуле экспортируется `officialAppCredentials`.
https://github.com/negezor/vk-io/blob/48e085752c2ef854744b16c6f8d20763e28bf89c/packages/authorization/src/constants.ts#L59-L84

**Comment by cyperdark** [comment]
Как я понимаю, пока что с не офф. приложениями работать не будет?

**Comment by negezor** [comment]
Прямая авторизация работает только для разрешённых приложений. По умолчанию это все официальные клиенты. Можно использовать `ImplicitFlowUser`, можно получить весь доступ кроме `messages` секции. Тут нужно использовать данные официальных приложений.

**Comment by cyperdark** [comment]
`ImplicitFlowUser` а где его именно использовать?

**Comment by negezor** [comment]
Для авторизации в Standalone приложениях. Но я всё же считаю что будет достаточно авторизоваться как официальное приложение, так как ограничений будет меньше.
