### ISSUE TITLE
Как вернуть ответ callback кнопки?

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#327]
https://vk.com/dev/bots_docs_5?f=4.4.+Callback-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8
Иду вроде по документации, пытаюсь получить message_event путём:
```
updates.on('message_event', (context) => {
	console.log(context);
});
```
Но ничего не приходит после нажатия
Версия 4.0.1 nodejs 12

**Comment by negezor** [comment]
Бот подключен через Bots Long Poll/Webhook? Какая версия в сообществе для выбранного подключения? Включено ли событие в группе?

**Comment by el9in** [comment]
Bots Long Poll но в логах пишет webhook update
5.122
DEBUG=vk-io:updates node bot.js: Не присылает этого события.

**Comment by negezor** [comment]
Значит событие в группе не включено.

**Comment by el9in** [comment]
А как называется событие?

**Comment by el9in** [comment]
![image](https://user-images.githubusercontent.com/46536746/92324523-450e4d00-f04b-11ea-9207-f8ff1da8043c.png)
В Callback к примеру тоже установлен только
![image](https://user-images.githubusercontent.com/46536746/92324542-5bb4a400-f04b-11ea-8385-49b888df5b53.png)
Но событие приходит.

**Comment by el9in** [comment]
Спасибо, потыкал по событиям начало приходить.

**Comment by Jelle02** [comment]
el9in, можешь прислать как ты сделала callback кнопки?
