### ISSUE TITLE
Как снять ограничение на отправку запросов в секунду.

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#330]
У меня к callback подключено много групп, но вот отправка запросов на них происходит очень медленно, пока в одной группе обработаются 500 запросов, потом в другой.
Можно ли как то снять это ограничение?

**Comment by negezor** [comment]
Как именно реализуется обработка множества групп? Указана ли опция`apiLimit: 20` для групп?

**Comment by el9in** [comment]
Мне нужно вообще убрать этот лимит, чтобы он не ограничивал отправку запросов. Можно ли это сделать?

**Comment by negezor** [comment]
Ну в таком случае тут же можно попасть под rate limit ВК. Достаточно указать большое число для `apiLimit`.

**Comment by el9in** [comment]
Там получается к серверу подключаются большое количество групп, т.е. люди подключают и из за этого лимита, беседа в которой не было не единого запроса просто начинает игнорить пока выполнятся запросы из другой группы.
Будет ли добавлено apiLimit: 0 (для того чтобы снять ограничения?)

**Comment by negezor** [comment]
Уточню, для каждой группы используется своя инстанция VK?

**Comment by el9in** [comment]
Только одна, вывод через access_token, нет возможности делать под каждую.

**Comment by negezor** [comment]
Что значит нет возможности? На каждую группу должна быть своя инстанция класса VK.

**Comment by el9in** [comment]
Каждый человек может сам подключиться к моему серверу и начать получать запросы, по этому было решено создать всего одну и через неё всё обрабатывать.

**Comment by negezor** [comment]
Это неправильный подход, как выше указал — следует на каждую группу создавать свою инстанцию `VK`. Если проблема в дублировании кода, достаточно создать [фабричный метод](https://refactoring.guru/ru/design-patterns/factory-method).
