### ISSUE TITLE
Проблемы с updates.setHearFallbackHandler

### ISSUE THREAD

**Issue by GoodHood5** [negezor/vk-io#332]
#### What did you do?
Беда с updates.setHearFallbackHandler(async (message) => 

Сначала работает нормально, а потом когда много людей начинают юзать бота, то данная функция перестает работать и выдает ошибки в консоле

| RangeError: Maximum call stack size exceeded
 | Exception in PromiseRejectCallback:
 | /root/botanypay/node_modules/vk-io/node_modules/middleware-io/lib/index.js:57
|                 Promise.reject(error);
|                         ^
| RangeError: Maximum call stack size exceeded

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `X.Y.Z` |
| `node`                             | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `X.Y.Z` |

**Comment by negezor** [comment]
Я более чем уверен что дело в `updates.on()` или `updates.use()`, учитывая что бот сначала работает означает что вы сделали вложенный обработчик. Т.е. на каждое сообщение вы ставите ещё один, в итоге получаем `Maximum call stack size exceeded`.

**Comment by negezor** [comment]
Я закрою этот вопрос из-за неактивности.
