### ISSUE TITLE
VK - это не конструктор

### ISSUE THREAD

**Issue by SergeyMC9730** [negezor/vk-io#334]
#### What did you do?
Я создал новую переменную:
`const vk = new VK({
        token: 'токен (если что, я его ввёл)'
});`
Но получил ошибку:
`TypeError: VK is not a constructor`

Можно ли эту проблему как-нибудь решить?
#### Additional Info
Я тестировал и на ESM и на CJS - получился тот же результат
#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `Последняя` |
| `node`                             | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `6.14.4` |

**Comment by negezor** [comment]
Каким образом импортируется? Библиотека не имеет экспорта по умолчанию.

**Comment by negezor** [comment]
Я закрою этот вопрос из-за неактивности.
