### ISSUE TITLE
code№925 - You are not admin of this chat | messages.pin

### ISSUE THREAD

**Issue by tenwiq** [negezor/vk-io#335]
```JS   
 vk.updates.on(['chat_unpin_message'], async (message, next) => { // Реакция на закрепленное сообщение.
const [user_info] = await vk.api.users.get({ user_id: message.senderId });
  vk.api.call('messages.pin', {peer_id: message.peerId, message_id: `${chats[message.chatId].messages_pin}`});

        message.send(`В этой беседе запрещено откреплять сообщение.`);
        await next()
    });
```
При закрепление сообщение, консоль ругается (вк), что якобы бот не админ или я не админ [code№925 - You are not admin of this chat], хотя бот отвечает на определенную команду, редактирует сообщение и т.д. Абсолютно без проблем. Еще в беседе он как полноценный админ.

В чем же проблема?

**Comment by tenwiq** [comment]
Ещё заметил такой странный баг вк, бот отправляет фотографии в беседу, а это фотография отправляется почему то от имени какого-то человека, а не от бота как обычно бывает ://

**Comment by negezor** [comment]
Потому что `message_id` это только для ЛС группы или страницы пользователя. Нужно отправлять `conversation_message_id`, но он доступен с `5.124`. Версию нужно установить в опциях модуля через `apiVersion: '5.124'` до следующего релиза.

**Comment by negezor** [comment]
Я закрою этот вопрос из-за неактивности.
