### ISSUE TITLE
Глобальная реализация перехода на следующий шаг

### ISSUE THREAD

**Issue by Meqy** [negezor/vk-io#336]
Есть ли возможность перейти на следующий шаг сцены из глобального обработчика(который заменяет middlewareIntercept)?
Предположим, как-нибудь так: context.scene.current.step.next()

**Comment by negezor** [comment]
Такой возможности нет, но зачем это понадобилось?

**Comment by Meqy** [comment]
ну, предположим, переключать этапы через кнопку

**Comment by negezor** [comment]
Это по хорошему должно быть в обработчике сцены. Как вариант можно внутри `onEnterHandler`:
```ts
sceneManager.addScenes([
  new StepScene('signup', {
    steps: [...],
    async onEnterHandler(context) {
      const { messagePayload = {} } = context;

      if (messagePayload.command === 'prev') {
        await context.scene.step.previous({
          silent: true
        });
      } else if (messagePayload.command === 'next') {
        await context.scene.step.next({
          silent: true
        });
      }
    }
  })
]);
```

**Comment by Meqy** [comment]
Спасибо 👍
