### ISSUE TITLE
Не могу сделать пост с помощью wall.post() 

### ISSUE THREAD

**Issue by KnightDark-loli** [negezor/vk-io#337]
Что бы сделать пост на странице сообщества нужна авторизация, а как делать ее я не пойму. Перерыл кучу статей, но полных примеров не нашел. Можете пожалуйста написать подробный пример с этим методом? Я серьезно не понимаю.

**Comment by tenwiq** [comment]
В интернете много таких сервисов, чтобы получить токен. Например сайт: vkhost github io

**Comment by negezor** [comment]
Метод `wall.post` доступен сейчас только для пользовательского токена
> This method can be called with a user token received in Standalone-app via Implicit Flow or by using the confirmation window. Access rights required: wall.

Нужно авторизоваться через официальное приложение например, у библиотеки есть модуль отвечающий за это [@vk-io/authorization](https://www.npmjs.com/package/@vk-io/authorization).
```ts
import { CallbackService } from 'vk-io';
import { DirectAuthorization, officialAppCredentials } from '@vk-io/authorization';

const callbackService = new CallbackService();

const direct = new DirectAuthorization({
	callbackService,

	...officialAppCredentials.android,

	login: process.env.LOGIN,
	password: process.env.PASSWORD
});

async function run() {
	const response = await direct.run();

	console.log('Token:', response.token);
	console.log('Expires:', response.expires);

	console.log('Email:', response.email);
	console.log('User ID:', response.user);
}

run().catch(console.error);
```

**Comment by negezor** [comment]
Я закрою этот вопрос из-за неактивности.
