### ISSUE TITLE
Объедени снова все в 1 модуль!

### ISSUE THREAD

**Issue by Zharckov** [negezor/vk-io#338]
**Я просто не понимаю, зачем 1 модуль раскидывать на 100 частей?
Обновил я зависимости и тут бот не работает.**

**Comment by tenwiq** [comment]
Где именно не работает? Какую ошибку выдает?

**Comment by Zharckov** [comment]
> Где именно не работает? Какую ошибку выдает?

Теперь чтобы работала нужно ещё и HearManager

**Comment by tenwiq** [comment]
Так, вы же можете создать свою реализацию HearManager без модуля.

**Comment by Zharckov** [comment]
> Так, вы же можете создать свою реализацию HearManager без модуля.

Это да, но узнать "Зачем и Почему?" разбили все на модули хочется!)

**Comment by tenwiq** [comment]
> > Так, вы же можете создать свою реализацию HearManager без модуля.
> 
> Это да, но узнать "Зачем и Почему?" разбили все на модули хочется!)

Возможно для удобства и чтоб быстро работало 👍 . Хотя все же есть минусы у модели.

**Comment by Zharckov** [comment]
> > > Так, вы же можете создать свою реализацию HearManager без модуля.
> > 
> > 
> > Это да, но узнать "Зачем и Почему?" разбили все на модули хочется!)
> 
> Возможно для удобства и чтоб быстро работало 👍 . Хотя все же есть минусы у модели.

Быстрее от этого не станет, как мне кажется

**Comment by tenwiq** [comment]
> > > > Так, вы же можете создать свою реализацию HearManager без модуля.
> > > 
> > > 
> > > Это да, но узнать "Зачем и Почему?" разбили все на модули хочется!)
> > 
> > 
> > Возможно для удобства и чтоб быстро работало 👍 . Хотя все же есть минусы у модели.
> 
> Быстрее от этого не станет, как мне кажется

Но все же, лучше использовать свою реализацию )) Там меньше проблем

**Comment by nitreojs** [comment]
> > > > Так, вы же можете создать свою реализацию HearManager без модуля.
> 
> > > 
> 
> > > 
> 
> > > Это да, но узнать "Зачем и Почему?" разбили все на модули хочется!)
> 
> > 
> 
> > Возможно для удобства и чтоб быстро работало 👍 . Хотя все же есть минусы у модели.
> 
> 
> 
> Быстрее от этого не станет, как мне кажется

естественно станет, модуль не будет подгружать те вещи, которые начальному юзеру будут ненужны и не будет обрабатывать мидлвари, которые в итоге будут проигнорированы = буст в скорости, думайте о чем пишете

**Comment by Zharckov** [comment]
> > > > > Так, вы же можете создать свою реализацию HearManager без модуля.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Это да, но узнать "Зачем и Почему?" разбили все на модули хочется!)
> > 
> > 
> > > 
> > 
> > 
> > > Возможно для удобства и чтоб быстро работало 👍 . Хотя все же есть минусы у модели.
> > 
> > 
> > Быстрее от этого не станет, как мне кажется
> 
> естественно станет, модуль не будет подгружать те вещи, которые начальному юзеру будут ненужны и не будет обрабатывать мидлвари, которые в итоге будут проигнорированы = буст в скорости, думайте о чем пишете

Да, но основной хендлер - сообщения, зачем его то выпиливать?

**Comment by Nekonyx** [comment]
Давай я постараюсь объяснить тебе всё на понятном языке - языке мемов.

![image](https://user-images.githubusercontent.com/16444061/93468539-f39a7380-f910-11ea-8fdd-5b64b4b5eaae.png)

**Comment by Saiv46** [comment]
> В защиту @Zharckov могу сказать что нарушение обратной совместимости - не есть хорошо.
> Разъединение модулей повысило порог вхождения, да и сложность кода лишь увеличилась со временем.

![Phoenix Wright](https://gammalaw.com/wp-content/uploads/2013/11/phoenix-ready-1.jpg)

**Comment by Nekonyx** [comment]
> > В защиту @Zharckov могу сказать что нарушение обратной совместимости - не есть хорошо.

Поэтому это **Breaking Change**.

![image](https://user-images.githubusercontent.com/16444061/93512606-5a864f80-f946-11ea-8e64-32ff8d80d2ee.png)

**Comment by negezor** [comment]
Основная библиотека это `vk-io`, которая предоставляет базовое взаимодействие с ВКонтакте, она тянет за собой минимальное количество зависимостей. Модуль `@vk-io/hear` это такой же [middleware](https://en.wikipedia.org/wiki/Middleware) как `@vk-io/session` и `@vk-io/scenes`. Так как это только альтернативная реализация возможного взаимодействия с сообщениями. Когда модуль находился в `Updates` это не позволяло переиспользовать его и добавляла лишнюю сложность и бесконтрольность, к тому же это нарушало принцип [SOLID](https://en.wikipedia.org/wiki/SOLID).

В самом деле я бы всё разделил на отдельные модули `@vk-io/api`, `@vk-io/upload`, `@vk-io/updates`, `@vk-io/collect` и `@vk-io/structures` а в `vk-io` всё бы это экпортировалось по умолчанию, ввиду того что каждый модуль лишь реализация своей отвественности. Но прямо сейчас внутри `vk-io` каждый модуль уже готов перасадки в своё пространство имён.

У этого подхода есть большее преимущество, вы устанавливаете только то — что вам нужно. А так же вы не путаетесь в огромном количестве экспорта из всего модуля. За примером далеко ходить не нужно, стоит посмотреть инструменты по типу: [apollo-server](https://github.com/apollographql/apollo-server), [apollo-tooling](https://github.com/apollographql/apollo-tooling) и [apollo-client](https://github.com/apollographql/apollo-client).

![image](https://user-images.githubusercontent.com/9392723/93555248-2a2fc700-f9c1-11ea-8765-f5c8100236f3.png)
