### ISSUE TITLE
MessageContext<S>::loadMessagePayload() not loads properly

### ISSUE THREAD

**Issue by Saiv46** [negezor/vk-io#339]
#### What did you do?
I want to fetch message contents with `MessageContext<S>::loadMessagePayload()`

#### What did you expect to happen?
Have message payload fully loaded.

#### What was the actual result?
If using this method with group messages (using `pollingGroupId`) **and** userbot (user access token) - it just not loads properly (not exists or even loading user message contents instead).

#### Additional Info
Workaround:
```js
const { items: [msg] } = await this.api.messages.getByConversationMessageId({
  peer_id: ctx.peerId,
  group_id: this.groupId,
  conversation_message_ids: ctx.conversationMessageId
})
```

Yes, this is *very* specific case when you need to use both group messages API and userbot for things that groups can't do.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `12.16.1` |
| `TypeScript`                       | `Not installed` |
| `yarn` or `npm`                    | `6.14.8` |

**Comment by negezor** [comment]
This is not a specific case, you need to separate the bot and the user. The library does not assume the use of 1 instance for more than one entity.
