### ISSUE TITLE
Error on install and use

### ISSUE THREAD

**Issue by exdeniz** [negezor/vk-io#34]
* fs in ./node_modules/vk-io/upload/helpers.js, ./node_modules/request/lib/har.js

To install it, you can run: npm install --save fs

**Comment by negezor** [comment]
Can you provide a log npm? Since `fs` is the standard Node.js library

**Comment by exdeniz** [comment]
Install with yarn, yarn log without error

**Comment by negezor** [comment]
Specify exactly where the error is, I do not understand.
