### ISSUE TITLE
Не работает wall_post/wall_post_new

### ISSUE THREAD

**Issue by BlusteryS** [negezor/vk-io#340]
#### What did you do?
Хочу получить данные поста при его публикации.

#### What did you expect to happen?
updates.on('wall_post_new', async (wall) => {
    console.log(wall);
});

Использую "updates.on('message_new', async (message) => { console.log(message) });", всё работает.
В версии 3 "wall_post" работал, когда обновился до 4, то перестал.

#### What was the actual result?
Ничего не выводит в консоль.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.2` |
| `node`                             | `12.18.4` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `6.14.6` |

**Comment by negezor** [comment]
Событие включено в группе? Не перехватывается ли сообытие в middleware до этого?

**Comment by BlusteryS** [comment]
Включено

До этого только:
const { VK } = require(`vk-io`);
let config = require(`./database/settings.json`),
const vk = new VK({
	token: config.grouptoken
});
const { api } = vk;
const { updates } = vk;
updates.startPolling();
updates.on('message_new', async (message) => {
// код
});

**Comment by negezor** [comment]
Нужно через `updates.start()` запускать или указывать `pollingGroupId`.
