### ISSUE TITLE
Ошибка документации. Миграция до V4

### ISSUE THREAD

**Issue by Viiprogrammer** [negezor/vk-io#341]
#### What did you do?

```
hearManager.hear(/^\/test$/i, async (context, next) => {
	console.log(context.isInbox, context.isGroup, context.isFromWebChat);
});
```

#### What did you expect to happen?

true/false true/false true/false

#### What was the actual result?

true/false true/false undefined 

![Screenshot_1](https://user-images.githubusercontent.com/17622604/93687385-38b3d680-fac6-11ea-8a97-10641aa69a8c.png)

#### Additional Info

Геттер context.isFromWebChat не существует, но указан в миграции до v4. В место него нужно использовать context.isFromUser

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.2` |
| `node`                             | `12.16.1` |
| `yarn` or `npm`                    | `6.14.8` |

**Comment by negezor** [comment]
А теперь нужно внимательно прочитать что это `MessageFlagsContext`, а не `MessageContext`.
