### ISSUE TITLE
Callback Buttons

### ISSUE THREAD

**Issue by WDIlsb** [negezor/vk-io#344]
Уже несколько месяцев прошло с добавления callback кнопок в ВК, это удобная и интересная возможность, было бы здорово  работать с такими кнопками через эту библиотеку

**Comment by negezor** [comment]
Библиотека поддерживает callback кнопки.
https://negezor.github.io/vk-io/references/vk-io/classes/keyboardbuilder.html#callbackbutton
Ловля событий через:
```js
vk.updates.on('message_event', (context) => {
  // ...
});
```
