### ISSUE TITLE
UnhandledPromiseRejectionWarning: APIError: Code №5

### ISSUE THREAD

**Issue by Vanyla-Vvv** [negezor/vk-io#345]
#### What did you do?
const vktoken = "token";
const { VK } = require('vk-io');
const vk = new VK({token: vktoken});

#### What was the actual result?
(node:10204) UnhandledPromiseRejectionWarning: APIError: Code №5 - User authorization failed: invalid session.
    at SequentialWorker.execute (F:\nodejs\node_modules\vk-io\lib\index.js:1524:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `past` |
| `node`                             | `12` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `npm` |

**Comment by Vanyla-Vvv** [comment]
Please do not close.

**Comment by Vanyla-Vvv** [comment]
UPD: const vk = new VK({token: vktoken})

**Comment by negezor** [comment]
This happens for new VK tokens.

**Comment by Vanyla-Vvv** [comment]
> This happens for new VK tokens.

How to fix it?

**Comment by Keller18306** [comment]
> How to fix it?
Maybe re-create the token?

**Comment by negezor** [comment]
Try to create a new token, or make a request to VK support. These factors are not controlled by the library.
