### ISSUE TITLE
Прямая ссылка на аудио/видео

### ISSUE THREAD

**Issue by Nikt-OS** [negezor/vk-io#346]
Каким образом можно получить прямую ссылку на аудио/видео ВК для прямого скачивания.
При получении сообщения с аудио, получаю файл index.m3u8, а с видео - ссылку на плеер

аудио
`{
    id: 456239024,
ownerId: 536769586,
    accessKey: '599f63a5d10d1083e9',
    lyricsId: undefined,
    albumId: undefined,
    genreId: 18,
    title: 'Opr',
    artist: 'Gesaffelstein feat. УННВ',
    duration: 210,
    createdAt: 1601098581,
    url: 'https://sgi2.beltelecom-by-minsk.vkuseraudio.net/p10/64fe9bc5395/a26ef62d76161a/index.m3u8?extra=jk4DdWX62LHiMyu1hH9lTVKdfJLp2ZudilMnufCNH2SGUSLBpy63YbEKmAwuN_12jAmiOO9GN56HN89ivmZrDuaQ375zCUQlYYOvxcyLRMd6XYS3CBVmtEGhs56pG_rroOymnvcIXNWv6V9iYm3donoR8Xw&long_chunk=1'
  }`

видео
`{
  id: 456239657,
  ownerId: 173051940,
  accessKey: '23c7d58ad01304a8e6',
  title: 'Сэнко для ВП (Уворот от бана) (Озвучка iMiles)',
  description: 'https://www.youtube.com/channel/UCysmaAdKferbE31bMkCoFxQ',
  duration: 1,
  createdAt: 1578579279,
  addedAt: undefined,
  viewsCount: 8448,
  commentsCount: 1,
  player: 'https://vk.com/video_ext.php?oid=173051940&id=456239657&hash=3d9b00ff26caa423&__ref=vk.android_messenger&api_hash=16012833762fb157ba35cbb9b196_GUZTMNZWHE2TQNQ',
  platformName: undefined
}`

**Comment by negezor** [comment]
Насколько я знаю прямых ссылок получить нельзя, только использованием обходных путей. Каким именно образом я подсказать не могу.

**Comment by Nikt-OS** [comment]
лана, пасиб
