### ISSUE TITLE
hearManager: возвращение context в ide, не равного типу MessageContext

### ISSUE THREAD

**Issue by lunnaholy** [negezor/vk-io#348]
при использовании конструкции типа `hearManager.hear("hello", (ctx) => { ... });` в IDE (WebStorm, Visual Studio & Visual Studio Code) возвращается тип, не равный MessageContext. Во время исполнения всё нормально.

@vk-io/hear: 1.0.2
vk-io: 4.0.3

**Comment by negezor** [comment]
Это не ошибка, по умолчанию HearManager ссылается не базовый класс контекста, так как он может работать не только с сообщениями. Нужно передать в дженерик класса `MessageContext`, это только для TypeScript.
