### ISSUE TITLE
Авторизация приложения

### ISSUE THREAD

**Issue by raziEiL** [negezor/vk-io#349]
Доброго дня. В предшествующих версиях **vk-io** я авторизировал **vk app** с помощью ключей `appId`, `appSecret` класс `VK`. Обновил пакет до последней версии и вижу, что данные ключи теперь отсутствуют. Не совсем понятно как это сейчас делать. Не могли бы вы предоставить хоть какие-то примеры авторизации для vk app или получение [user token](https://vk.com/dev/access_token) через ваше API? Конкретно я хочу использовать метод [video.get](https://vk.com/dev/video.get), который требует авторизацию через user token. Спасибо. 

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.3` |
| `@vk-io/authorization`             | `1.0.0` |

**Comment by negezor** [comment]
https://github.com/negezor/vk-io/issues/337#issuecomment-694636476

**Comment by raziEiL** [comment]
Получил следующую ошибку. VKError: Missing two-factor handler. Каким образом вводится код подтверждения?

**Comment by isinkin** [comment]
Используйте `CallbackService` для этого

**Comment by raziEiL** [comment]
Не много изучил исходники и сообразил как все организовать. Всех благодарю, вот наглядный пример получение токена.
```js
import { CallbackService, ICallbackServiceTwoFactorPayload, CallbackServiceRetry } from "vk-io";
import { DirectAuthorization, officialAppCredentials } from "@vk-io/authorization";
import readline from "readline";
import { config } from "dotenv";
config();

const readLine = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const callbackService = new CallbackService();

callbackService.onTwoFactor((payload: ICallbackServiceTwoFactorPayload, retry: CallbackServiceRetry) => {
    readLine.question("Enter VK code:", answer => {
        retry(answer).then(console.log).catch(console.error);
    });
});

const app = new DirectAuthorization({
    callbackService,
    ...officialAppCredentials.windows,
    scope: ["video", "photos", "audio", "pages", "docs", "wall"],
    login: process.env.VK_LOGIN,
    password: process.env.VK_PASSWORD,
    apiVersion: "5.124"
});

app.run().then(console.log).catch(console.error);
```
