### ISSUE TITLE
ApiError: Application authorization failed: access_token has expired

### ISSUE THREAD

**Issue by nsklyarov** [negezor/vk-io#35]
Здравствуйте.
Столкнулся с ошибкой:
Application authorization failed: access_token has expired.

Как получил:
1. Делаю запрос серверной  авторизации для своего приложения;
2. Получаю token и пишу его в глобальный объект методом .setToken(access_token); 
3. После этого делаю запрос wall.get;

Ожидаемый результат: 
Объект соответствующий параметрам запроса.
Фактический результат:
```
{ ApiError: Application authorization failed: access_token has expired.
  name: 'ApiError',
  code: 28,
  params: 
   [ { key: 'oauth', value: '1' },
     { key: 'method', value: 'wall.get' },
     { key: 'lang', value: '' },
     { key: 'v', value: '5.68' },
     { key: 'owner_id', value: '-86529522' },
     { key: 'count', value: '1' },
     { key: 'filter', value: 'owner' },
     { key: 'extended', value: '1' } ] }
```

Такая ошибка повторяется и при использовании других методов, users.get, например, после использования метода .setToken(access_token);

```
const vkClient = new VK({
    app: vk.appId,
    key: vk.key
});

const auth = _ => vkClient.auth
    .server()
    .then(token => Promise.resolve(vkClient.setToken(token)));

auth()
    .then(client => {
        return client.api.wall.get({
            owner_id: '-86529522',
            count: 1,
            filter: 'owner',
            extended: 1
        })
    })
    .then(response => console.log(response))
    .catch((error) => {
        console.error(error);
    });
```

**Comment by negezor** [comment]
Это проблема уже скорее со стороны ВКонтакте, всё описано как у них в API. Но при этом это сейчас не работает, хоть в RoadMap было пройдено. Я по разбираюсь с этим, но пока лучше токен оставить пустым.

**Comment by nsklyarov** [comment]
отписал им в техпод;
продублирую ответ сюда.

**Comment by negezor** [comment]
Хорошо, жду.

**Comment by nsklyarov** [comment]
Неправильно использовал метод;
Для корректной работы wall.get:
- cгенерировал новый сервисный ключ в настройках приложения;
- используя ваш метод setToken, расширил поле класса апи значением access_token из настроек;

вот кусочек кода:

```
const vkClient = new VK({
    app: vk.appId,
    key: vk.key,
});

vkClient.setToken(vk.token)
    .api.wall.get({
    owner_id: '1',
    count: 1,
    filter: 'owner',
    extended: 1,
}).then(response => console.log(response))
```

**Comment by negezor** [comment]
Как именно был расширен класс API? Ведь access_token передаётся со всеми запросами в не зависимости от типа.

**Comment by negezor** [comment]
![image](https://user-images.githubusercontent.com/9392723/31847254-889a4e62-b664-11e7-8c2b-d7d8ec526beb.png)
Вообщем это не баг, а фича.
