### ISSUE TITLE
(vk.upload.photoAlbum) APIError: Code №100 - One of the parameters specified was missing or invalid: photos_list is invalid

### ISSUE THREAD

**Issue by APA64IK** [negezor/vk-io#350]
#### What did you do?
```javascript
async function uploadPhoto(title, urlList) {

    const photoList = urlList.map(link=> {
        return {value: link};
    });
        
    const response = await vk.upload.photoAlbum({
        album_id: (await Album.getAlbums()).find(a=>a.title.startsWith(title)).id,
        source: {
            values: photoList
        }
    });
        
    return response;
};

uploadPhoto('albumName', ['img url'])
```

#### What did you expect to happen?
Загрузка фотографии в альбом

#### What was the actual result?
Пустое значение ```{ key: 'photos_list', value: '' }```
```javascript
APIError: Code №100 - One of the parameters specified was missing or invalid: photos_list is invalid
    at SequentialWorker.execute (D:\dev\vk\node_modules\vk-io\lib\index.js:1440:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 100,
  params: [
    { key: 'method', value: 'photos.save' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.122' },
    { key: 'album_id', value: '276855811' },
    { key: 'server', value: '856316' },
    { key: 'photos_list', value: '' },
    { key: 'aid', value: '276855811' },
    { key: 'hash', value: 'e00ad5dbaa6dbf172e4da706518ec17d' }
  ]
}
```
#### Additional Info
photoList содержит 
```javascript
[
  {
    value: 'https://sun9-59.userapi.com/impf/ПРАВИЛЬНУЮ__ССЫЛКУ.jpg'
  }
]
```
#### Versions

| package                          | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.2` |
| `node`                            | `12.18.3` |
| `npm`                             | `6.14.6` |

**Comment by negezor** [comment]
Эта ошибка может быть связана с использованием `apiMode: 'parallel'`
https://github.com/negezor/vk-io/issues/171

**Comment by APA64IK** [comment]
@negezor не использовал его и на всякий случай поставил ```apiMode: "sequential"```. Ошибка не менялась.

Пока писал ответ, решил посмотреть "а что если загрузить другое фото со стороннего сурса?" Загрузило. Но та фотография с сервера вконтакте, которую я спокойно открывал - терялась и возвращало ошибку с пустым значением ```photos_list: ""``` . Сейчас всё работает, а к той фотографии `уже` доступ закрыт, так что и проверять смысла нет. Спасибо.
