### ISSUE TITLE
Attachment помощь

### ISSUE THREAD

**Issue by GoodHood5** [negezor/vk-io#351]
Хелпаните пожалуйста.

Можете написать пример attachment type=link, у меня вообще не получается и отправляет просто сообщение, без закрепленный ссылки. Использую 4 версию VK IO

Буду очень сильно благодарен!

**Comment by Nikt-OS** [comment]
такого типа вложений в вк нету
![изображение](https://user-images.githubusercontent.com/24947331/95673490-94e3b500-0bb1-11eb-8dfe-18a073f10462.png)

**Comment by negezor** [comment]
Этот тип прикрепления невозможно отправить через параметр `attachment`. Он может быть прикриплён только как сниппет, и то самим ВК. Параметр который за это отвечает `dont_parse_links`.
