### ISSUE TITLE
Как правильно переназначить params.d.ts

### ISSUE THREAD

**Issue by idev-hub** [negezor/vk-io#352]
Взять к примеру строчку `filter?: "friends" | "unsure";`
Почему их всего два? И зачем так жестко ограниченно. Мне вот к примеру нужно получить managers и donut

Как я могу грамотно это сделать? Что бы при обновлении depences оно не слетело, возможно глупый вопрос, заранее извиняюсь

**Comment by isinkin** [comment]
Тайпинги для АПИ генерируются на основе схемы ВК, так что все претензии по этому поводу направляйте им.
