### ISSUE TITLE
 AbortError: The user aborted a request.

### ISSUE THREAD

**Issue by Nikt-OS** [negezor/vk-io#354]
При попытке загрузить видео через `vk.upload.document` короткие видео загружаются без проблем, а больше 100 мб почему-то выпадают в ошибку  **AbortError: The user aborted a request.**
![изображение](https://user-images.githubusercontent.com/24947331/95673616-dfb1fc80-0bb2-11eb-86ca-3a5084341ced.png)

**Comment by APA64IK** [comment]
Скорость соединения плохая, превышен таймаут ожидания загрузки. в source укажи таймаут повыше, а лучше и скрипт на какой нибудь хостинг залей
