### ISSUE TITLE
Midlewares для hear

### ISSUE THREAD

**Issue by idev-hub** [negezor/vk-io#356]
Немного порылся в исходном коде и понял что можно легко реализовать последовательность middleware для команд с одним именем. Но я не могу разобрать правильный ли мой подход, не дублирую ли я просто напросто команды, возможно можно это как-то оптимизировать?

```ts
public readonly newcommand: any = (name: string, conditions: Array<string | RegExp>, handles: any) => {
        if(typeof handles !== "function"){
            for (let i = 0; i < handles.length; i++) {
                console.log(i)
                const handle = handles[i]
                this.hearManager.hear(
                    [
                        (text, {state}) => (
                            state.command === name.toLowerCase().trim()
                        ),
                        ...conditions
                    ],
                    handle
                )
            }
        }
    }
```

Мне нужна цепочка команд в которой я мог бы проверять isChat, session или другие вещи которые вроде как описаны в документации, но не работают, в любом случае мне нужно обращаться к базе данных, а это можно сделать только в обработчике

**Comment by isinkin** [comment]
Можете показать пример того, как вы хотели бы использовать?

**Comment by idev-hub** [comment]
Визуально это express со своими middleware
isLogin, inOutbox промежуточные обработчики, точно такие же как и ниже `async(context, next)`
`
bot.command("test", ["/test"], isLogin, isOutbox,
    async (context, next) => {
        await context.send("test start"),
        return next()
    }, async (context, next) => {
       return context.send("test end"),
    })
`

**Comment by isinkin** [comment]
Вы можете использовать так:

```js
const { compose } = require('middleware-io');

hearManager.hear('/test', compose([
    isLogin,
    isOutbox,
    async (context, next) => {
        await context.send('hello!');

        await next();
    },
    async (context) => {
        await context.send('world');
    }
])); 
```
