### ISSUE TITLE
Некорректный resolveResource

### ISSUE THREAD

**Issue by WDIlsb** [negezor/vk-io#357]
```
foundUser = await resolveResource({
    api: new API({
      token: groupToken
    }),
    resource: "https://vk.com/bogdan3265705"
  })
console.log(foundUser); // {id: 3265705, type: "bogdan"}
```

Пользователь сделал себе короткое имя с цифрами после,

корректный ответ был бы `{id: 525189942, type: "user" }`

| `vk-io`                            | `4.0.3` |

**Comment by negezor** [comment]
Исправлено https://github.com/negezor/vk-io/commit/d203b0dbc935af7dad4cdd4f5e6361ba1e486dba в 4.0.4
