### ISSUE TITLE
Callback Buttons рекурсивный payload

### ISSUE THREAD

**Issue by idev-hub** [negezor/vk-io#358]
Что-то я не понимаю. Делаю callback кнопки, все работает, там где они могут работать. Но как дело касается браузера, где нет callback кнопок, то всё. Возвращает мне первый раз в `messagePayload`  вот это:
```js
{
  command: 'not_supported_button',
  button_type: 'callback',
  payload: '{"command":"other"}'
}

```
Во второй раз, это:
```js
{
  command: 'not_supported_button',
  button_type: 'callback',
  payload: '{"command":"not_supported_button","button_type":"callback","payload":"{\\"command\\":\\"other\\"}"}'
}

```

В третий раз payload увеличивается и так пока вк не станет игнорить отправляемые сообщения боту.
Что это? Как с этим бороться, мне ведь просто из payload нужно достать `command: "other"`, что бы выполнить запрашиваемую команду на стороне бота, раз callback не поддерживается.

Ошибка ли это вк, или все таки где-то у меня что-то не так. А может в vk-io дело, не знаю, потому обращаюсь за помощью.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.3` |
| `node`                             | `12.18.3` |
| `TypeScript`                       | `4.0.3` |
| `yarn`                   | `1.22.4` |

**Comment by isinkin** [comment]
Претензии к ВК, они реализовали как всегда через одно место

**Comment by negezor** [comment]
А можно пример обработчика?

**Comment by idev-hub** [comment]
Пример обработчика message_event? Или какой другой. Код большой просто, уже путаться начинаю

```ts
this.updates.on('message_event', async (context, next) => {
            if (context.eventPayload && context.eventPayload.command) {
                const {command} = context.eventPayload
                if (command === "other") {
                    await this.api.messages.sendMessageEventAnswer({
                        event_id: context.eventId,
                        user_id: context.userId,
                        peer_id: context.peerId,
                        event_data: JSON.stringify({
                            type: "show_snackbar",
                            text: "Покажи исчезающее сообщение на экране"
                        })
                    })
                }
            }
        });
```
