### ISSUE TITLE
Добавление модуля в README

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#359]
**[vk-io-pages](https://www.npmjs.com/package/vk-io-pages)** - Модуль vk-io для создания динамических страниц

Подробная документация, примеры и демонстрация работы доступны в [репозитории](https://github.com/MrZillaGold/vk-io-pages).

**Comment by Noop1** [comment]
для майнкрафта самое то, спс, ждём ответа от владлена

**Comment by WDIlsb** [comment]
Прекрасная идея, сам пробовал что-то подобное делать
Но насколько я помню у вк есть лимиты, на редактирование сообщения и на вызов действий от callback кнопок

**Comment by negezor** [comment]
Предлагаю сделать фабрику:
```diff
- const builder = new context.pageBuilder({
-     api: vk.api, // API нужен для отметки сообщений прочитанными, по желанию можете не передавать.
-     context // Контекст текущего сообщения
- });

+ const builder = context.pageBuilder({
+     // other options
+ });
```

Так как контекст можно передавать в pagesManager.middleware:
```ts
context.pageBuilder = (options = {}) => (
  new PageBuilder({
    context,

    api: this.api
  })
);
```

Инициализацию самого менеджера так:
```ts
new PagesManager({
  api: vk.api
});
```

**Comment by MrZillaGold** [comment]
Разбираясь с цепочками, совсем не обратил внимание на этот нюанс. 
Исправил это недоразумение. 

Спасибо!
