### ISSUE TITLE
Загрузка фотографии пользователя через upload.ownerPhoto

### ISSUE THREAD

**Issue by C0smoCat** [negezor/vk-io#364]
#### What did you do?
Меняю аватарку пользователя
```js
await vk.upload.ownerPhoto({
    owner_id: user.id,
    source: {
        value: <...>
    }
});
```

#### What did you expect to happen?
Аватар меняется, функция возвращает 6 полей:
```json
{
  "photo_hash": "<...>",
  "photo_src": "<...>",
  "photo_src_big": "<...>",
  "photo_src_small": "<...>",
  "saved": 1,
  "post_id": "<...>"
}
```

#### What was the actual result?
Аватар не меняется, функция возвращает 4 поля:
```json
{
  "photo_hash": "<...>",
  "photo_src": "<...>",
  "photo_src_big": "<...>",
  "photo_src_small": "<...>"
}
```

#### Additional Info
Если вызывать метод сохранения со [страницы документации](https://vk.com/dev/photos.saveOwnerPhoto), всё норм, но если вызывать через апи - новая аватарка не сохраняется, а в ответе отсутствуют поля `saved` и `post_id`

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.3` |
| `node`                             | `14.9.0` |
| `TypeScript`                       | `3.9.5` |
| `yarn` or `npm`                    | `6.14.8` |

**Comment by negezor** [comment]
Как именно инициализируется vk-io?

**Comment by C0smoCat** [comment]
> 
> 
> Как именно инициализируется vk-io?

```js
const { VK } = require("vk-io");

const vk = new VK({
    token: process.env.TOKEN,
    apiVersion: "5.22"
});

const [user] = await vk.api.users.get({});
```

Токен получен с помощью [User Implicit Flow](https://vk.com/dev/implicit_flow_user), `scope=offline,docs,photos,wall,status`

**Comment by negezor** [comment]
А почему версия такая старая?

**Comment by tailsjs** [comment]
Попробуй версию поставить повыше.

**Comment by C0smoCat** [comment]
Вот полный код, проверенный на последней версии апи

index.js
```js
const generator = require("./generator");

const { VK } = require("vk-io");
const vk = new VK({
    token: process.env.TOKEN, // User Implicit Flow, scope=offline,docs,photos,wall,status
    apiVersion: "5.124" // также пробовал 5.122, 5.110, 5.23 и 5.22, результат одинаковый
});

async function run() {
    const [user] = await vk.api.users.get({});

    const imageStream = generator.createAvatarStream({});

    const uploadImage = await vk.upload.ownerPhoto({
        source: {
            value: imageStream
        },
        owner_id: user.id
    });

    console.log(uploadImage); // { "photo_hash": "<...>", "photo_src": "<...>", "photo_src_big": "<...>", "photo_src_small": "<...>" }
}

run().catch(console.log);
```
generator.js
```js
const { createCanvas } = require("canvas"); // 2.6.1

function createAvatarStream({ width = 250, height = 250 }) {
    const hue = Math.random() * 360;
    const canvas = createCanvas(width, height);
    const ctx = canvas.getContext("2d");

    const background = ctx.createLinearGradient(0, 0, width, height);
    background.addColorStop(0, `hsl(${ hue },90%,70%)`);
    background.addColorStop(1, `hsl(${ (hue + 30) % 360 },90%,70%)`);

    ctx.fillStyle = background;

    ctx.fillRect(0, 0, width, height);

    return canvas.createPNGStream();
}

module.exports = {
    createAvatarStream
};
```

Пример создаваемой картинки:
![1](https://user-images.githubusercontent.com/50526934/98340734-44803b80-2027-11eb-92c9-0852ccb62bf4.png)

**Comment by tailsjs** [comment]
можно использовать buffer вместо stream

**Comment by negezor** [comment]
Если не указывать `user_id`, какой результат будет?

**Comment by C0smoCat** [comment]
> 
> 
> Если не указывать `user_id`, какой результат будет?

В смысле, вот так?
```js
const uploadImage = await vk.upload.ownerPhoto({
    source: {
        value: imageStream
    },
    // owner_id: user.id
});
```

Результат такой же. На сколько я понял, для пользователя этот параметр игнорируется.

**Comment by negezor** [comment]
Но как я понимаю ссылки загруженного аватара действительны?

**Comment by C0smoCat** [comment]
Да, все 3

**Comment by Antonzlo** [comment]
Если читать с файла, возвращается ошибка 129 - file is invalid

**Comment by C0smoCat** [comment]
Проверил на версии `canvas: 2.7.0`, `vk-io: 4.1.4`, сейчас всё работает как и должно.

```js
const generator = require("./generator");

const { VK } = require("vk-io");
const vk = new VK({
    token: process.env.TOKEN,
});

async function run() {
    const [ user ] = await vk.api.users.get({ });

    const imageStream = generator.createAvatarStream({ });

    const uploadImage = await vk.upload.ownerPhoto({
        source: {
            value: imageStream
        }
    });

    console.log(uploadImage);
}

run().catch(console.log);
```

Результат в `uploadImage`:
```js
{
  "photo_hash": "<...>",
  "photo_src": "<...>",
  "photo_src_big": "<...>",
  "photo_src_small": "<...>",
  "saved": 1,
  "post_id": 1
}
```

Думаю, issue можно закрыть
