### ISSUE TITLE
Какой нужно использовать обработчик ошибочных команд вместо setHearFallbackHandler?

### ISSUE THREAD

**Issue by CatFlucks** [negezor/vk-io#365]
Перешёл на v4.0.3, и тут появилась проблема с обработчиком не существующих команд.
Всегда юзал setHearFallbackHandler, но теперь не знаю какой и как использовать.
![image](https://user-images.githubusercontent.com/73762767/97793131-db4c9280-1bf8-11eb-832d-b42fe1b40bbf.png)
Хотел использовать setHearFallbackHandler, но как сказано в документации "миграция до v4" данный метод удалён.
Что делать?
![image](https://user-images.githubusercontent.com/73762767/97793144-08994080-1bf9-11eb-8c5c-50d9392ab9db.png)

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `v4.0.3` |
| `Node.JS`                             | `v12.18.4` |
| `NPM`                    | `v6.14.6` |

**Comment by MrZillaGold** [comment]
Необходимо ознакомится и использовать модуль [@vk-io/hear](https://github.com/negezor/vk-io/blob/master/packages/hear/README.md), вместо vk.updates

**Comment by CatFlucks** [comment]
> Необходимо ознакомится и использовать модуль [@vk-io/hear](https://github.com/negezor/vk-io/blob/master/packages/hear/README.md), вместо vk.updates.hear

А можете пример показать?

**Comment by MrZillaGold** [comment]
В репозитории, который я указал выше, есть примеры
