### ISSUE TITLE
Как правильно использовать callback кнопки?

### ISSUE THREAD

**Issue by CatFlucks** [negezor/vk-io#366]
При попытке нажатия кнопки на моб. устройстве, в snackbar присылается ответ, но как реализовать с редактированием сообщения?

![image](https://user-images.githubusercontent.com/73762767/97901714-971ed680-1d4d-11eb-8a5b-63d1d3b91fa7.png)

Почитал документацию ВК, не нашёл как редактируется сообщение при событии message_event.

![image](https://user-images.githubusercontent.com/73762767/97901736-9dad4e00-1d4d-11eb-8a70-7cc20ba7d782.png)

Если можете, покажите пример с командой.

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `v4.0.4` |
| `node`                            | `v12.18.4` |
| `npm`                    | `v6.14.6` |

**Comment by negezor** [comment]
У контекста [MessageEvent](https://negezor.github.io/vk-io/references/vk-io/classes/messageeventcontext.html) есть геттеры `conversationMessageId` и `peerId`. Их можно использовать что бы редактировать сообщения.
