### ISSUE TITLE
как использовать новый обработчик капчи?

### ISSUE THREAD

**Issue by notz448** [negezor/vk-io#371]
как использовать новый обработчик капчи?

**Comment by isinkin** [comment]
```js
vk.callbackService.onCaptcha((payload, retry) => {
    // в payload хранится ссылка на капчу-картинку
    // после чего, мы должны вызвать метод retry и передать в него решение капчи
});

**Comment by notz448** [comment]
> ```js
> vk.callbackService.onCaptcha((payload, retry) => {
>     // в payload хранится ссылка на капчу-картинку
>     // после чего, мы должны вызвать метод retry и передать в него решение капчи
> });
> ```

спасибо
