### ISSUE TITLE
APIError: Code №1 - Unknown error occurred при отправке фото.

### ISSUE THREAD

**Issue by PololoR** [negezor/vk-io#372]
При отправке фото в беседу созданную от имени группы появляется ошибка: APIError: Code №1 - Unknown error occurred.
Код которым происходит отправка: `message.sendPhotos({value: canvas.toBuffer()});` 
Скрин ошибки: [https://ibb.co/hKXrq9k](https://ibb.co/hKXrq9k)

**Comment by isinkin** [comment]
Можно более подробный код?

**Comment by negezor** [comment]
Я закрою этот вопрос из-за неактивности.
