### ISSUE TITLE
Тип string, а не any у свойства keyboard в параметрах messages.edit

### ISSUE THREAD

**Issue by ifstream** [negezor/vk-io#374]
#### What did you do?
Редактирую сообщение 

vk.api.messages.edit({
                conversation_message_id: context.conversationMessageId,
                peer_id: context.peerId,
                message: 'message',
                keyboard: builder.callbackButton({
                    label: 'Профиль',
                    payload: {
                        command: 'profile',
                    }
                }).inline()
            });

#### What did you expect to happen?
Все работает

#### What was the actual result?
IDE выдает ошибку "Type 'KeyboardBuilder' is not assignable to type 'string' ", при смене на any в params.d.ts, как указано в методе messages.send все работает

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.4` |
| `node`                             | `12.18.3` |
| `TypeScript`                       | `4.0.3` |
| `yarn` or `npm`                    | `npm` |

**Comment by AlexXanderGrib** [comment]
Так работает ВК, если ты не знал, он воспринимает JSON клавиатуру как строку. Если у тебя возникают проблемы с типами в Typescript, ты можешь в конце объявления своей клавиатуры дописать `.toString()` и `vk-io` сам превратит её в строку.

Вот полный пример (взял как есть из моего бота)
```typescript
await msg.send({
  message: `Привет ${personalClientMention}, вот мои команды:`,
  keyboard: Keyboard.builder()
    .textButton({
      label: "Халява",
      color: Keyboard.POSITIVE_COLOR,
      payload: {
        command: "free"
      }
    })
    .row()
    .textButton({
      label: "Узнать",
      color: Keyboard.SECONDARY_COLOR,
      payload: {
        command: "know"
      }
    })
    .row()
    .textButton({
      label: "Скины",
      color: Keyboard.SECONDARY_COLOR,
      payload: {
        command: "skins"
      }
    })
    .row()
    .textButton({
      label: "Боксы",
      color: Keyboard.SECONDARY_COLOR,
      payload: {
        command: "boxes"
      }
    })
    .row()
    .textButton({
      label: "Тест",
      color: Keyboard.SECONDARY_COLOR,
      payload: {
        command: "test"
      }
    })

    .inline(supportsInlineKB)
    .oneTime(!supportsInlineKB)
    .toString() // <= Вот это явно конвертирует клавиатуру в строку
});
```

**Comment by negezor** [comment]
После кодогенерации типов по схеме было не поправлено вручную, обновитесь до последней версии.
