### ISSUE TITLE
resolveResource чувствителен к регистру

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#376]
#### What did you do?
При использовании resolveResource с символами верхнего регистра мы получаем ошибку о том, что ресурс не существует.

Например: VK.com/mrzillagold

Эта утилита часто используется при пользовательском вводе, думаю чувствительность регистра не так важна.

https://github.com/negezor/vk-io/blob/181b8f1ab4a45c370daf8f40a2eb6fe1e1056bf5/packages/vk-io/src/utils/resource-resolver.ts#L23-L28

#### What was the actual result?
![image](https://user-images.githubusercontent.com/42776347/100378509-fe832a00-305e-11eb-91f0-79a21bfb4666.png)

**Comment by xTCry** [comment]
Скорее всего это избыточно
Лучше в вашем проекте делать доп проверку или приводить домен или всю ссылку в нижний регистр

Или что имелось в виду?

**Comment by MrZillaGold** [comment]
Ничего избыточного в том, чтобы добавить к регулярным выражениям флаг `i` не вижу.
Также метод https://vk.com/dev/utils.resolveScreenName не чувствителен к регистру, что также не мешает передавать ему такие данные.

**Comment by MrZillaGold** [comment]
Конечно, можно приводить вводимые данные в LowerCase и потом передавать их в утилиту, все же хочется услышать мнение автора библиотеки на счёт этого. Как по мне - это баг.

**Comment by negezor** [comment]
Это не баг, но для лучшего UX можно сделать регистронезависимый вариант мета информации.

**Comment by negezor** [comment]
Реализовано https://github.com/negezor/vk-io/commit/3b2ceac4c86e780e739bc49d9802756d3c7491d2
