### ISSUE TITLE
AuthError: invalid_request, Security Error

### ISSUE THREAD

**Issue by npyramid** [negezor/vk-io#38]
Все работало ок. А сегодня ночью как-то резко все сломалось.

```
vk.setOptions({
        app: this.credentials.vkapp,
        login: this.credentials.vklogin,
        pass: this.credentials.vkpass,
        phone: this.credentials.vkphone,
        restartCount: 0,
        longpollCount: 0,
      });

      const vkAuth = vk.auth.standalone();

      vkAuth.run()
        .then((token) => {
          vk.setToken(token);
          resolve();
        })
        .catch((error) => {
          reject(error);
        });
```

Теперь вот это не работает и приходит ошибка, что токен отсутствует
```
ApiError: User authorization failed: no access_token passed.
```

**Comment by negezor** [comment]
А можно узнать что там в теле запроса?

**Comment by npyramid** [comment]
![image](https://user-images.githubusercontent.com/3968529/31651787-acd669a6-b325-11e7-80b8-3812c8265aad.png)

**Comment by npyramid** [comment]
через ключ приложения также не хочет авторизироваться

**Comment by negezor** [comment]
А что в HTML, который в ответе?

**Comment by npyramid** [comment]
![image](https://user-images.githubusercontent.com/3968529/31653231-80cbef34-b32a-11e7-9222-8c40e6c6114f.png)

**Comment by negezor** [comment]
Скорее всего данные входа неправильны.

**Comment by npyramid** [comment]
все работало, а сегодня отвалилось, причем ничего не менял

**Comment by negezor** [comment]
Тогда пока не могу помочь, в 4.0.0 версии будет новая авторизация (она уже есть, но сама библиотека в разработке). Как насчёт испытать авторизацию [4 версии](https://github.com/negezor/vk-io/tree/v4.0.0)?
```javascript
vk.setOptions({
  app: <app>,
  login: <login>,
  phone: <phone>,
  password: <password>
});

vk.auth.implicitFlowUser().run()
.then(console.log)
.catch(console.error);
```

**Comment by npyramid** [comment]
Ок. Попробую ее. Нестабильно в каких местах?

**Comment by negezor** [comment]
Streaming API, Updates (Long Poll + Callback API), Collect, Upload (.video)

**Comment by negezor** [comment]
Можно в принципе получать от туда токен, а использовать пока старую версию.

**Comment by npyramid** [comment]
Хех. Костыль. Ну ладно спасибо. Попробую отпишусь

**Comment by npyramid** [comment]
В общем сейчас запустил проект. Заработало на v3.2. Скорее всего что-то у вк сломалось

**Comment by npyramid** [comment]
Сегодня во время авторизации пишет уже invalid_request, Security Error

**Comment by npyramid** [comment]
при попытке авторизации через server() ключ получает. Но сразу пишет что токен протух. Что за мистика?

**Comment by negezor** [comment]
![image](https://user-images.githubusercontent.com/9392723/31707225-632487bc-b437-11e7-99e0-93d699e4e4fc.png)
