### ISSUE TITLE
Как подключить сессии к БД?

### ISSUE THREAD

**Issue by Zharckov** [negezor/vk-io#380]
### В настройках SessionManager есть свойство storage, что оно принимает и как им пользоваться?
![изображение](https://user-images.githubusercontent.com/48046493/101273522-3bf65e80-37a7-11eb-82b2-5ce1949ea541.png)

**Comment by lunnaholy** [comment]
Насколько я понимаю - объект типа https://negezor.github.io/vk-io/references/session/interfaces/isessionstorage.html, а вот как его юзать - хз

**Comment by negezor** [comment]
Опция `storage` принимает интерфейс [ISessionStorage](https://negezor.github.io/vk-io/references/session/interfaces/isessionstorage.html) который нужно реализовать.
- Метод `get()` - получает сессию из хранилища, должен вернуть объект сессии или `undefined`
- Метод `set()` - обновляет сессию в хранилище, должен вернуть `boolean` как результат об успешности операции
- Метод `delete()` - удаляет сессию в хранилище, должен вернуть `boolean` как результат об успешности операции
- Метод `set()` - обновляет TTL сессии в хранилище

Все методы принимают ключ сессии, который получается из опции `getStorageKey` в `SessionManager`. Сериализация объекта сессии и TTL остаётся на плечах разработчика.
