### ISSUE TITLE
Можно ли повешать vk.updates на url /webhook в fastify

### ISSUE THREAD

**Issue by idev-hub** [negezor/vk-io#381]
Можно ли повешать vk.updates на url /webhook в fastify?
Когда я это делаю мне выдает 500 и res.writeHead is not a function"

Код предельно прост. Я не знаю всех тонкостей getWebhookCallback
Но переписывать всё на express не очень хорошая идея, скажем так ужасная идея. Как это можно решить? 
Помогите пожалуйста

```ts
fastify.post('/webhook', vkGroup.updates.getWebhookCallback())
```

**Comment by negezor** [comment]
Адаптации под `fastify` нет, но её можно сделать самому, достаточно вызвать у библиотеки метод `vk.updates.handleWebhookUpdate(update)`, в переменной `update` находится событие от ВК. В самом обработчике нужно будет только сделать проверку на событие `confirmation` (и по необходимости проверку на секретных ключ).

**Comment by idev-hub** [comment]
Жаль что нет поддержки изначальной. Полазил немного, так и не разобрался, что к чему,  а именно что в переменной update. Сделал костыль большой, пока сойдет.

**Comment by negezor** [comment]
Я не пользовался до этого `fastify`, если есть желание, можно открыть PR и постепенно доработать.
