### ISSUE TITLE
Когда context.reply научится пересылать сообщение не только в лс, но и в беседу?

### ISSUE THREAD

**Issue by tenwiq** [negezor/vk-io#382]
Совсем недавно в vk api [ [тык](https://vk.com/dev/bots_docs_2?f=3.%20%D0%A1%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%BE%D1%82%20%D0%B1%D0%BE%D1%82%D0%B0)  и [тык](https://vk.com/dev/messages.send?params[random_id]=0&params[peer_id]=185014513&params[message]=Test%20message&params[forward]=3333%0A&params[dont_parse_links]=0&params[disable_mentions]=0&params[intent]=default&params[v]=5.126)] вышло обновление, то есть можно уже пересылать сообщение в беседу с помощью  параметр **forward - json объект**. Пытался самому модернизировать context.reply ведя это
```JS
let name = {
    reply: (text, reply, params) => { context.reply(`${text}`, context.conversationMessageId,  params);
    }
}
```
```JS
-------------- vk-io/index.js
    reply(text, reply, params,) {
        return this.send({
                forward: {
                    is_reply: this.id,
                },
            ...(typeof text !== 'object'
                ? {
                    message: text,
                    forward: {
                          is_reply: reply,
                    },
                    ...params
                }
                : text)
        });
```
После этого колхоза выдает ошибку теперь: 

APIError: Code №100 - One of the parameters specified was missing or invalid: forward contains incorrect JSON
    at SequentialWorker.execute (C:\Users\Пользователь\Desktop\xxx\node_modules\vk-io\lib\index.js:1548:39)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  code: 100,
  params: [
    { key: 'method', value: 'messages.send' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.126' },
    { key: 'peer_id', value: 'user_id' },
    { key: 'random_id', value: '7047648433131136' },
    { key: 'forward', value: '[object Object]' }
  ]
}

Я что-то не так делаю?  И да я знаю, что forward содержит неверный JSON

**Comment by nitreojs** [comment]
`context.reply` научится пересылать отправленное сообщение в беседу тогда, когда наконец ВК сделает ID сообщений ботам во всех беседах, сейчас эти ID равны нулю, потому реплай невозможен; можно реплаить от имени бота только в чатах групп, где сама группа является создателем чата, так как уже там ВК сделали возврат айди сообщений

**Comment by DaniilKuchkovCodeGeneration** [comment]
Потому что поле forward должно быть СТРОКОЙ, то есть надо сделать forward: JSON.stringify({ ... })

**Comment by isinkin** [comment]
Потому что поле forward должно быть json строкой, то есть надо сделать forward: JSON.stringify({ ... })
