### ISSUE TITLE
parallel_selected not works

### ISSUE THREAD

**Issue by alexey2baranov** [negezor/vk-io#385]
#### What did you do?
```ts
  const vk = new VK({
    token: process.env.VK_TOKEN,
    apiMode: "parallel_selected", 
    apiRequestMode: 'sequential',
    apiLimit: 1,
    apiExecuteMethods: ['messages.send'],
  })

    const result = await Promise.all([1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(i => vk.api.messages.send({
      peer_id: parseInt(process.env.VK_TEST_USER),
      message: basename(__filename) + ' ' + i,
      random_id: _.random(1000000)
    })))

    console.log(result)
```

#### What did you expect to happen?
I expect 10 messages will be sent in one `execute`

#### What was the actual result?
`APIError: Code №14 - Captcha needed`

#### Additional Info
Looks like `parallel_selected`in combination with `apiExecuteMethods`  don't work 

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.1.1` |
| `node`                             | `15.0.1` |
| `TypeScript`                       | `4.0.5` |
| `yarn` or `npm`                    | `7.0.3` |

**Comment by vitalyavolyn** [comment]
It works.

index.js
```
const { VK } = require('vk-io')
const { basename } = require('path')
const _ = require('lodash')

const vk = new VK({
	      token: process.env.VK_TOKEN,
	      apiMode: "parallel_selected", 
	      apiRequestMode: 'sequential',
	      apiLimit: 1,
	      apiExecuteMethods: ['messages.send'],
	    })

const run = async () => {
    const result = await Promise.all([1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(i => vk.api.messages.send({
	          peer_id: parseInt(process.env.VK_TEST_USER),
	          message: basename(__filename) + ' ' + i,
	          random_id: _.random(1000000)
	        })))

    console.log(result)
}

run()
```

```
$ DEBUG=vk-io:* node index.js

  vk-io:api execute --> +0ms
  vk-io:api execute <-- +674ms
/home/vitalya/dev/test-vk-io-parallel/node_modules/vk-io/lib/index.js:1548
            this.handleError(request, new APIError(response.error));
                                      ^

APIError: Code №14 - Captcha needed
```

VK-IO tries to send all messages in one `execute` request, but VK doesn't allow sending this many messages in short time.
You should:
a) use communities to create chat bots
b) create a delay between sending messages
c) use `callbackService.onCaptcha` to solve captcha
