### ISSUE TITLE
Можно ли использовать на клиенте?

### ISSUE THREAD

**Issue by Fxlr8** [negezor/vk-io#39]
нода жалуется на отсутствие 'fs' и 'net'

**Comment by negezor** [comment]
Electron?

**Comment by Fxlr8** [comment]
@negezor, нет, просто react приложка

**Comment by Fxlr8** [comment]
нашел здесь решение https://github.com/webpack-contrib/css-loader/issues/447

**Comment by Fxlr8** [comment]
Вообще предполагалось использование этой либы не на сервере?

**Comment by negezor** [comment]
Она предназначалась для серверных приложений Node.js
