### ISSUE TITLE
vk pay отслеживание транзакции

### ISSUE THREAD

**Issue by Projoker** [negezor/vk-io#392]
#### What did you do?

Использую payButton для оплаты и обработчик

vk.updates.on('vk_pay_transaction', async (context) => {
    console.log(context);
});

(пробовал vkpay_transaction)

#### What did you expect to happen?

Сообщение в консоль после оплаты

#### What was the actual result?

Сообщений нет

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.1.2` |
| `node`                             | `12.14.1` |
| `npm`                    | `6.14.8` |

**Comment by Antonzlo** [comment]
1. vkpay_transaction
2. Включено ли событие в настройках лонгполл/каллбак?
