### ISSUE TITLE
Cannot read property 'pollingGroupId' of undefined

### ISSUE THREAD

**Issue by sv1007** [negezor/vk-io#393]
Из-за этого кусочка кода, отказывается работать весь код.

if (this.vk.options.pollingGroupId !== this.groupId) {
            this.groupId = this.vk.options.pollingGroupId;
        }
появляется ошибка в консоли, при запуске.
console: TypeError: Cannot read property 'pollingGroupId' of undefined

**Comment by mulfyx** [comment]
Код?

**Comment by Antonzlo** [comment]
Разве не this.vk.api.options?

**Comment by sv1007** [comment]
> Разве не this.vk.api.options?

На старых версиях vk-io работает

**Comment by mulfyx** [comment]
> > Разве не this.vk.api.options?
> 
> На старых версиях vk-io работает

Ну, на новых, значит, нет

**Comment by sv1007** [comment]
> > > Разве не this.vk.api.options?
> > 
> > 
> > На старых версиях vk-io работает
> 
> Ну, на новых, значит, нет

Да
