### ISSUE TITLE
Использование на клиенте

### ISSUE THREAD

**Issue by aleksanderd** [negezor/vk-io#394]
Добрый день!

Можно ли как то использовать на клиенте(iframe приложение)? Может даже в виде обёртки на нативным VK.init/VK.api - только ради типизации параметров и ответов.

Пробовал поисследовать, но в react-app при импорте:
```
Failed to compile.

./node_modules/inspectable/lib/index.mjs
Can't import the named export 'inspect' from non EcmaScript module (only default export is available)
```

Спасибо!

**Comment by mulfyx** [comment]
Нет, эта библиотека только для nodejs

**Comment by negezor** [comment]
На текущий момент это невозможно, так как пришлось бы использовать что-то вроде `cross-fetch`, но возникает проблема с кросс-доменными запросами.
