### ISSUE TITLE
в WallPostContext при subTypes: ['wall_post_new'] isRepost всегда true

### ISSUE THREAD

**Issue by nitreojs** [negezor/vk-io#396]
#### What did you do?
Я отлавливал событие `wall_post_new` и консолил его. В своей группе я создавал тестовый пост без вложений, без репостов, только текст.

#### What did you expect to happen?
Я ожидал увидеть `context.isRepost: false`, так как мой пост не являлся репостом другого поста.

#### What was the actual result?
Я получил `context.isRepost: true`, хотя в посте есть **ТОЛЬКО** текст:

![изображение](https://user-images.githubusercontent.com/40319427/105628931-fd009300-5e50-11eb-8934-3cd614b3e700.png)

#### Additional info
Немного покопавшись коде я понял, что для `wall_post_new` `isRepost` почему-то всегда `true`:

![изображение](https://user-images.githubusercontent.com/40319427/105628952-1dc8e880-5e51-11eb-816a-a31a90ec316b.png)

Вероятно, имелось ввиду `wall_repost`?

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.1.2` |
| `node`                             | `14.13.0` |
| `TypeScript`                       | `4.0.3` |
| `yarn` or `npm`                    | `1.22.10` |

**Comment by negezor** [comment]
Исправлено https://github.com/negezor/vk-io/commit/1a35d25315d78496fe8b635ce9d8e285301e307a
