### ISSUE TITLE
Как получать событие о входе / выходе / кике пользователя из чата? (Чат от имени сообщества)

### ISSUE THREAD

**Issue by Kamillaova** [negezor/vk-io#397]
Как обрабатывать событие о входе / выходе / кике пользователя в чате? (на message_new ничего не поступает, а вроде как должно)

(Example code: 
```
import { VK } from 'vk-io';
import * as config from '../config.json';
const group = new VK({
	token: config.group_token
});

group.updates.on('message_new', (msg) => {msg.send(JSON.stringify(msg))});
group.updates.start().catch(console.error);
```
)

**Comment by kravetsone** [comment]
От имени сообщества насколько я помню только проверять по базе) когда сообщение приходит)))

**Comment by catware1** [comment]
> От имени сообщества насколько я помню только проверять по базе) когда сообщение приходит)))

Не, событие message_new не приходит с полем 'action'

**Comment by artyomova0** [comment]
Решено (Почти). `updates.on("chat_invite_user", ()...` (только от имени другого сообщества)

Но. Если мониторить userlp api **ОТ ИМЕНИ СООБЩЕСТВА** то при вхождении в чат прилетает эвент вида {"ts":ts,"updates":[[51,1],[52,6,200000000chatid,userid],[51,1],[52,3,200000000chatid,userid]]}, тоесть теоритически можно как то реализовать получение chat_invite_user если сообщество является создателем беседы

**Comment by Meqy** [comment]
В типы событий включить чекбокс **Входящие события**, при новом сообщении обрабатывать поле action, либо листнить событие **chat_invite_user**.

p.s судя по всему, у вас получен некорректный токен, потому что прилетают вообще события от лонгполла для юзера

**Comment by Antonzlo** [comment]
group.updates.on('message_new', (msg) => {if(msg.action) msg.send(JSON.stringify(msg.action))});

**Comment by Antonzlo** [comment]
Кстати, события на выход нет. Есть только кик пользователем самого себя

**Comment by artyomova0** [comment]
> group.updates.on('message_new', (msg) => {if(msg.action) msg.send(JSON.stringify(msg.action))});
На message_new вообще не поступает ничего при входе пользователя

**Comment by Antonzlo** [comment]
Какая версия апи?

**Comment by artyomova0** [comment]
> Какая версия апи?

Последняя

**Comment by Antonzlo** [comment]
На юзерлп такой метод не подойдёт. Вам нужен токен группы.

**Comment by artyomova0** [comment]
> На юзерлп такой метод не подойдёт. Вам нужен токен группы.

На userlp от имени сообщества приходит уведомление о входе а на bot api - нет

**Comment by Antonzlo** [comment]
События разные. Все приходит. В юзерлп отдельное событие, в боте поле `action`

**Comment by artyomova0** [comment]
> События разные. Все приходит. В юзерлп отдельное событие, в боте поле `action`

Да, оно приходит. Но только если сообщество не является создателем чата
