### ISSUE TITLE
Как получить именно текст сообщения, когда обращаются в беседе через @?

### ISSUE THREAD

**Issue by bqio** [negezor/vk-io#398]
В качестве текста получаю вот это "[clubID|@NAME] text", а хотелось бы просто "text".

**Comment by artyomova0** [comment]
context.$match[1] вроде

**Comment by bqio** [comment]
> context.$match[1] вроде

Он пустой.

**Comment by bqio** [comment]
Да и попросту мои хеары такого вида не срабатывают на "@user топ":
`headMgr.hear(
  {
    text: "топ",
    senderType: "user",
    isChat: true,
  }, async (ctx) => {});`

**Comment by negezor** [comment]
Нужно просто обрезать первую часть с упоминанием бота в middleware до hearManager. [Регулярное выражение](https://regex101.com/r/yXp151/1), вместо ID поставить идентификатор бота.
```js


const 

vk.updates.on('message_new', (context, next) => {
  
})
```
