### ISSUE TITLE
Обработка сообщений

### ISSUE THREAD

**Issue by kaiqed7** [negezor/vk-io#399]
Я обрабатываю сообщения с помощью регулярных выражений и HearManager.

вот моя команда:
`msg.hear(/^профиль$/i, async (ctx) => {`

так же у меня есть кнопка с label "профиль". При нажатии кнопки в беседе, отправляется такое сообщение: @linktomybot профиль. Бот не видит это сообщение из за @linktomybot, как его можно убрать?

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.1.2` |
| `node`                             | `14.15.4` |
| `yarn` or `npm`                    | `npm` |

**Comment by kaiqed7** [comment]
> Реплейси собаку.
> message.text = message.text.replace(/\[club1\|.+\]/i, "").trim()

я убрал ссылку на группу, сообщение чистое получается. но бот не обрабатывает так же..

**Comment by Antonzlo** [comment]
Если ты на встроенном  Hear, то надо через Middleware делать

**Comment by kaiqed7** [comment]
> Если ты на встроенном  Hear, то надо через Middleware делать
> 

а как? просто message.text = // чистое сообщение

**Comment by kaiqed7** [comment]
все получилось, спасибо всем 😄
