### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by Khuzha** [negezor/vk-io#403]
Привет! Написал такой код:

```
const { API, Upload, Updates } = require('vk-io');

const api = new API({
    token: process.env.VKBOTTOKEN
});

const uploads = new Upload({ api });
const updates = new Updates({ api, uploads});

module.exports = updates.start;

```
И он не работает, не запускается. 
Получаю ошибку:
`TypeError: Cannot read property 'options' of undefined
`
При этом передаю токен сообщества

И подскажите, пожалуйста, у либы есть чатик в телеграме или еще где-нибудь?

**Comment by mulfyx** [comment]
```js
module.exports = updates.start;
```
у вас здесь теряется контекст, надо делать

```js
module.exports = () => updates.start();
// или
module.exports = updates.start.bind(updates);
```
