### ISSUE TITLE
[Q] Should library include methods that used in mobile application?

### ISSUE THREAD

**Issue by InspectorDue** [negezor/vk-io#404]
I reverse engineered [VK mobile app](https://play.google.com/store/apps/details?id=com.vkontakte.android) and found methods by which you can get music. There's like private api. Could it be in vk-io?

**Comment by Antonzlo** [comment]
It is hidden by VK. There is no way to use it, the only way is to contact support asking for a permission

**Comment by Antonzlo** [comment]
You can call any method using 
```js
vk.api.call("method.name", { params })
```

**Comment by Antonzlo** [comment]
And actually, library only holds group names, like "messages" or "groups". "audios" should be there

**Comment by InspectorDue** [comment]
> 
> 
> It is hidden by VK. There is no way to use it, the only way is to contact support asking for a permission

So, I can get [token from the offical VK mobile application](https://vk.com/dev/auth_direct) (appId (client_id) and appHash (client_secret) you can find in gist below)

I found method `catalog.getAudio` that takes 4 parameters (need_blocks, owner_id (optional), url, ref)

[Part of decompiled files](https://gist.github.com/InspectorDue/ea1a822e084eb995a2b22fb8a572904e)

**Comment by Antonzlo** [comment]
> > It is hidden by VK. There is no way to use it, the only way is to contact support asking for a permission
> 
> So, I can get [token from the offical VK mobile application](https://vk.com/dev/auth_direct) (appId (client_id) and appHash (client_secret) you can find in gist below)
> 
> I found method `catalog.getAudio` that takes 4 parameters (need_blocks, owner_id (optional), url, ref)
> 
> [Part of decompiled files](https://gist.github.com/InspectorDue/ea1a822e084eb995a2b22fb8a572904e)

So, create VK with this token and use ```js
vk.api.call("catalog.getAudio", {})
```

**Comment by InspectorDue** [comment]
> 
> 
> > > It is hidden by VK. There is no way to use it, the only way is to contact support asking for a permission
> > 
> > 
> > So, I can get [token from the offical VK mobile application](https://vk.com/dev/auth_direct) (appId (client_id) and appHash (client_secret) you can find in gist below)
> > I found method `catalog.getAudio` that takes 4 parameters (need_blocks, owner_id (optional), url, ref)
> > [Part of decompiled files](https://gist.github.com/InspectorDue/ea1a822e084eb995a2b22fb8a572904e)
> 
> So, create VK with this token and use ```js
> vk.api.call("catalog.getAudio", {})

Ok. But should it be in the library?

**Comment by Antonzlo** [comment]
> > > > It is hidden by VK. There is no way to use it, the only way is to contact support asking for a permission
> > > 
> > > 
> > > So, I can get [token from the offical VK mobile application](https://vk.com/dev/auth_direct) (appId (client_id) and appHash (client_secret) you can find in gist below)
> > > I found method `catalog.getAudio` that takes 4 parameters (need_blocks, owner_id (optional), url, ref)
> > > [Part of decompiled files](https://gist.github.com/InspectorDue/ea1a822e084eb995a2b22fb8a572904e)
> > 
> > 
> > So, create VK with this token and use ```js
> > vk.api.call("catalog.getAudio", {})
> 
> Ok. But should it be in the library?

It may create some confusion, as it isn't documented, so, i think no
