### ISSUE TITLE
Can't import the named export 'inspect' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by SWDevStudio** [negezor/vk-io#405]
#### What did you do?
Пытался получить токен пользователя по примеру, делаю импорт и создаю объект класса
`
import { CallbackService } from 'vk-io'
const callbackService = new CallbackService()
`
в общем делаю все как по примеру и получаю ошибку 

 error  in ./node_modules/inspectable/lib/index.mjs
Can't import the named export 'inspect' from non EcmaScript module (only default export is available)

#### Additional Info
Не знаю влияет ли это, делаю electron приложение

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.1.4` |
| `@vk-io/authorization`             | `1.0.0` |
| `node`                             | `14.15.3` |
| `TypeScript`                       | `3.9.3` |
| `yarn` or `npm`                    | `1.22.10` |

**Comment by MrZillaGold** [comment]
```js
import VKIO from "vk-io";

const { CallbackService } = VKIO;

const callbackService = new CallbackService();
```
