### ISSUE TITLE
Ошибка с updates.hear - TypeError: updates.hear is not a function

### ISSUE THREAD

**Issue by Boniuss** [negezor/vk-io#406]
#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `X.Y.Z` |
| `node`                             | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `X.Y.Z` |

Выдает ошибку на **updates.hear**
TypeError: updates.hear is not a function

Скрипт:

const {updates} = vk;

updates.hear(/!test /i, async (ctx, next) => {
	ctx.send("OK");
});

isOutBox работает нормально, сообщение пишет, но ошибку выдает как только стоит updates.hear

Как исправить?

**Comment by vitalyavolyn** [comment]
Используйте [@vk-io/hear](https://www.npmjs.com/package/@vk-io/hear), в 4 версии его вынесли в отдельный пакет

**Comment by Boniuss** [comment]
> Используйте [@vk-io/hear](https://www.npmjs.com/package/@vk-io/hear), в 4 версии его вынесли в отдельный пакет

Спасибо большое, все работает...
Но как в это - 

vk.updates.on('message_new', hearManager.middleware);

сделать оутбокс?
например у меня стоял такой:

vk.updates.use(async (ctx, next) => {
	if(ctx.type == 'message' && (ctx.isOutBox || ctx.senderId < 0)) return;
	if(ctx.senderId === undefined || ctx.senderType != 'user') return;
});

Он мне нужен для базы данных в JSON формате, а так я не знаю как можно еще базу сделать
