### ISSUE TITLE
сообщение приходит но, выскакивает ошибка (ExecuteError: Code №100 - One of the parameters specified was missing or invalid: random_id is a required parameter)

### ISSUE THREAD

**Issue by DanLudan** [negezor/vk-io#407]
#### What did you do?

`await vk_io.api.messages.send(`
      `   initFunctionality({`
              `   start: true,`
      `   })`
 `   );`
 

 `const initFunctionality = ({ start }) => {`
      `const getFunctionality = () => {`
          `if (start) console.log("старт");`
      `};`
      `return `getFunctionality();`
  `};` 
  
#### What did you expect to happen?
Не получить ошибку

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.1.4` |
| `node`                             | `14.15.3` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `npm` |

**Comment by Antonzlo** [comment]
```await vk_io.api.messages.send({
...(initFunctionality({
start: true,
})), random_id: 0
});```js

**Comment by DanLudan** [comment]
> await vk_io.api.messages.send({ ...(initFunctionality({ start: true, })), random_id: 0 });

Появилась новая ошибка: ExecuteError: Code №100 - One of the parameters specified was missing or invalid: you should specify peer_id, user_id, domain, chat_id or user_ids param

**Comment by Antonzlo** [comment]
Читайте документацию как сообщения отправлять. vk.com/dev

**Comment by DanLudan** [comment]
> Читайте документацию как сообщения отправлять. vk.com/dev

спасибо, я решил свою проблему
