### ISSUE TITLE
MessageContext: баг с peerId в личных сообещениях 

### ISSUE THREAD

**Issue by ronnyevans** [negezor/vk-io#408]
если написать сообщение какому-то человеку в лс, `senderId` будет равен `peerId`
небольшой пример
есть код
```ts
account.updates.on("message_new", async function(ctx,next) {
    console.log(ctx)
})
```
при новом сообщении выводит в консоль MessageContext
я отправил сообщение в лс 
![vk-message](https://i.imgur.com/SyKL5e7.png)
то что у меня словил скрипт
![context](https://i.imgur.com/aOvqEGA.png)
как мы видим `senderId` и `peerId` совпадают

**Comment by Antonzlo** [comment]
Такой баг действительно есть, но это на стороне ВК апи. Вы можете воспользоваться полем `isOutbox`, оно укажет, отправили ли вы или собеседник. ВК не всегда возвращает отправителя, скорее всего потому что самому ВК не нужно отслеживать исходящие сообщения. Или не было нужно, но чтобы не менять все они добавили флаг.

**Comment by ronnyevans** [comment]
понял, спасибо
