### ISSUE TITLE
S.O.S.

### ISSUE THREAD

**Issue by helix-team** [negezor/vk-io#409]
![image](https://user-images.githubusercontent.com/71103071/111930227-74f1df00-8ac9-11eb-8bed-c13dd6453b01.png)
![image](https://user-images.githubusercontent.com/71103071/111930263-8fc45380-8ac9-11eb-8007-8babcf6d2f81.png)
How to use ref and ref_source?

**Comment by helix-team** [comment]
Кароче, я не знаю как сделать сделать передачу произвольных параметров с помощью ссылки vk.me.

**Comment by Antonzlo** [comment]
VK.me/club1?ref=1&ref_source=home

**Comment by helix-team** [comment]
> VK.me/club1?ref=1&ref_source=home

В hear нету ref и ref_source

Я смог сделать через API

**Comment by Antonzlo** [comment]
Закройте пожалуйста ошибку, если решение есть
