### ISSUE TITLE
После обновления до 4 версии при запуске скрипта получаю ошибку.

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#41]
NodeJS - v6.12.0
VK-IO -  4.0.0-alpha.3

```
/vk/node_modules/vk-io/lib/api/index.js:202
    const work = async () => {
                       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vk/node_modules/vk-io/lib/vk.js:12:35)

```

**Comment by negezor** [comment]
Минимальная версия Node.js 8

**Comment by T1MOXA** [comment]
Обновил нод.
Теперь при запуске скрипта получаю сообщения:
```
(node:25471) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AuthError: Unsupported type validation
(node:25471) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by negezor** [comment]
Стоило бы повесить обработчик и узнать в чём ошибка
```javascript
process.on('unhandledRejection', (err) => {
	console.log('Caught unhandledRejection:', err);
});
```

**Comment by T1MOXA** [comment]
```
Caught unhandledRejection: { AuthError: Unsupported type validation
    at DirectAuth.run (/home/bots/vk/node_modules/vk-io/lib/auth/direct.js:226:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'AUTHORIZATION_FAILED', name: 'AuthError' }
```

**Comment by negezor** [comment]
А Promise ошибки кто будет обрабатывать?

**Comment by T1MOXA** [comment]
Хз : ) 
Где и как это нужно делать ? 
(Не очень знаком с промисами)

**Comment by negezor** [comment]
Ну библиотека полностью на них построена. Следует их изучить для работы в Node.js.

**Comment by T1MOXA** [comment]
Я все ещё не совсем понимаю как мне отловить ошибку.
Судя по всему ошибка происходит на этапе авторизации, я сделал следующую конструкцию
```
vk.auth.direct().run().then((response) => {
	BotID = response.user;
}).catch((err) => {
	console.log(err);
});
```
Но ничего не изменилось.

**Comment by negezor** [comment]
Всё дело в том что прямая авторизация только для разрешённых приложений. Как пример vk.auth.androidApp().run()

**Comment by T1MOXA** [comment]
Если использовать vk.auth.windowsApp() - получаю ту-же ошибку

**Comment by T1MOXA** [comment]
Есть еще варианты ?

**Comment by negezor** [comment]
Standalone приложение?

**Comment by T1MOXA** [comment]
+

**Comment by negezor** [comment]
`vk.auth.implicitFlowUser()`

**Comment by T1MOXA** [comment]
`AuthError: Auth form error: Указан неверный логин или пароль.`
Раньше (на старой версии) авторизация работала.
Через `vk.auth.windowsApp()`

**Comment by negezor** [comment]
Можно увидеть код?

**Comment by T1MOXA** [comment]
Да, у меня авторизация по логину\паролю.
Я так понимаю нужен только код авторизации ?

**Comment by T1MOXA** [comment]
```
vk.setOptions({
	app: 0000001, //Пример
	login: '+Телефон',
	pass: 'Пароль',
	phone: '+Телефон'
});

vk.auth.implicitFlowUser().run().catch((err) => {
	console.log(err);
});
```

**Comment by negezor** [comment]
Не `pass`, а `password`

**Comment by T1MOXA** [comment]
А в старой было psss ?

**Comment by negezor** [comment]
В 3.2 было свойство `pass`, теперь `password`

**Comment by T1MOXA** [comment]
Спасибо.

**Comment by T1MOXA** [comment]
Ещё такой вопрос, сайт показывает что бот сидит через мобильное устройство.
Как сделать так чтоб был статус просто "Online"

**Comment by negezor** [comment]
Авторизация через standalone приложение `vk.auth.implicitFlowUser()`

**Comment by T1MOXA** [comment]
Так и сделал, однако все равно показывает что бот сидит с мобилки.

**Comment by negezor** [comment]
Даже не знаю, мои с нормального онлайна сидят.

**Comment by T1MOXA** [comment]
Странно, сейчас обычный статус.
Наверное вк выпендривается ) 
Спасибо за помощь :)

**Comment by T1MOXA** [comment]
Отличная библиотека с которой удобно работать.
Спасибо.

**Comment by negezor** [comment]
Не за что, пользуйся на здоровье)
