### ISSUE TITLE
Не отлавливает все сообщения

### ISSUE THREAD

**Issue by Exle** [negezor/vk-io#410]
Пытаюсь отловить все сообщения ( беседа в группе / лс группы / группа, добавленная в беседу ).
При "группа, добавленная в беседу" (с другими проблем нет) срабатывает только если написать сообщение через `/`.

```js
const { VK } = require('vk-io');

const vk = new VK({
    token: accesToken
});
vk.updates.on('message', async (context) => {
    console.log(context);
    context.send(`Ты написал: ${context.text}`);
});
vk.updates.start().catch(console.error);
```
Отвечает на сообщение начинающееся с `/`
![image](https://user-images.githubusercontent.com/25784007/112683435-9b759880-8e82-11eb-9266-ab890121707b.png)
без `/`
![image](https://user-images.githubusercontent.com/25784007/112683648-f3140400-8e82-11eb-9ec4-aa70c2007c28.png)

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `v4.1.4` |
| `node`                             | `v15.5.0` |
| `TypeScript`                       | `v4.2.3` |
| `yarn` or `npm`                    | `npm` |

**Comment by Antonzlo** [comment]
Выдайте группе доступ ко всей переписке и закройте иссуе

**Comment by Exle** [comment]
> Выдайте группе доступ ко всей переписке и закройте иссуе

Где настройки беседы найти?

**Comment by Exle** [comment]
ВК не пользуюсь, но что он через зад устроен я не знал.
