### ISSUE TITLE
help, import error

### ISSUE THREAD

**Issue by phobiaxyz** [negezor/vk-io#411]
import { VK, MessageContext } from 'vk-io';
^^^^^^

SyntaxError: Cannot use import statement outside a module

example code:
`const {
    TOKEN,
} = require("./config"); // noob

import { VK, MessageContext } from 'vk-io';

import { HearManager } from '@vk-io/hear';

const vk = new VK({
    token: TOKEN
});

const hearManager = new HearManager<MessageContext>();

vk.updates.on('message_new', hearManager.middleware);

hearManager.hear(/^hello$/, async (context) => {
    await context.send('Hello!');
});

vk.updates.start().catch(console.error);
`

**Comment by negezor** [comment]
```js
const { VK, MessageContext } = require('vk-io');
const { HearManager } = require('@vk-io/hear');
```

**Comment by phobiaxyz** [comment]
А теперь:

```
const hearManager = new HearManager<MessageContext>();
                                                    ^

SyntaxError: Unexpected token ')'
```

**Comment by phobiaxyz** [comment]
Ладно, уже пофиксил убрал <MessageContext> это было лишним, закрываю.

Прошу ответ в теме https://github.com/negezor/vk-io/issues/412
