### ISSUE TITLE
context.sendSticker is not a function

### ISSUE THREAD

**Issue by phobiaxyz** [negezor/vk-io#413]
context.sendSticker is not a function

```
hearManager.hear(/^!stick$/, async (context) => {
	context.sendSticker(`9008`);
});
```

**Comment by phobiaxyz** [comment]
И тут тоже самое, как быть?
 context.renameChat is not a function
 
```
hearManager.hear(/^!tit$/, async (context) => {
	await context.renameChat('ftw');
}); 
```

**Comment by Antonzlo** [comment]
В новой версии все эти методы были удалены. Читайте документацию.

**Comment by phobiaxyz** [comment]
Ох, прочитал, спасибо. А есть замены этому? Или как быть?

**Comment by phobiaxyz** [comment]
И хотелось бы на это получить ответ - https://github.com/negezor/vk-io/issues/412

**Comment by phobiaxyz** [comment]
> Ох, прочитал, спасибо. А есть замены этому? Или как быть?

Решено
