### ISSUE TITLE
[object Object]

### ISSUE THREAD

**Issue by phobiaxyz** [negezor/vk-io#414]
Дополнение к https://github.com/negezor/vk-io/issues/412

Теперь "Ты онлайн с - [object Object]"

```
hearManager.hear(/^!инфо$/, async (context) => {
	await context.send(`Ты онлайн с - ${context.clientInfo} \n Твой ID страницы - ${context.senderId}`);
});
```

**Comment by MrSlavik0** [comment]
JSON.stringify

**Comment by phobiaxyz** [comment]
Спасибо, можешь подсказать как его вставить сюда?

**Comment by negezor** [comment]
Мне кажется тут недопонимание, `clientInfo` содержит объект мета информации (поддерживается ли кнопки и т.д.), но там нет информации про устройство с которого сидит пользователь. Для начала стоит смотреть в [API Reference](https://negezor.github.io/vk-io/references/vk-io/classes/messagecontext.html#clientinfo), но видимо вам стоит подучить JavaScript.

**Comment by phobiaxyz** [comment]
> Мне кажется тут недопонимание, `clientInfo` содержит объект мета информации (поддерживается ли кнопки и т.д.), но там нет информации про устройство с которого сидит пользователь. Для начала стоит смотреть в [API Reference](https://negezor.github.io/vk-io/references/vk-io/classes/messagecontext.html#clientinfo), но видимо вам стоит подучить JavaScript.

Да, наверное стоит, спасибо, я уже сделал JSON.Stringify, не смотрел в документацию, думал это содержит нужную информацию про устройство. Уже нашел, что устройство обозначается context.platform, извиняюсь за глупость. Уже вывело всё верно.

На счёт подучить, вы правы, наверное и правда стоит, не так давно я начал писать на Node.JS и уже пытаюсь писать ботов, вроде бы что то получается, но есть и такие глупости, как это. Спасибо за ответ @negezor и @MrSlavik0.
