### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Payz123** [negezor/vk-io#417]
![image](https://user-images.githubusercontent.com/69257098/113473504-4db0ef80-9483-11eb-8ae9-48bab94a25aa.png)
![image](https://user-images.githubusercontent.com/69257098/113473513-5acdde80-9483-11eb-8381-c0649400c582.png)
Раньше данной ошибки не было (год назад)

**Comment by nitreojs** [comment]
Решено: была использована старая версия API `5.93`, в то время как уже давно существует более высокая версия API `5.130`.
