### ISSUE TITLE
Нет данных о сообщении

### ISSUE THREAD

**Issue by DarkNetFox** [negezor/vk-io#425]
При попытке отловить сообщение, получаю неполную информацию.

![image](https://user-images.githubusercontent.com/35868005/116418686-31278d80-a85e-11eb-99a4-1c9fe1046392.png)
![image](https://user-images.githubusercontent.com/35868005/116418826-4c929880-a85e-11eb-9674-2f59af853968.png)

**Comment by Antonzlo** [comment]
Какая версия апи в настройках группы?

**Comment by swedesjs** [comment]
Ставь последнию версию лонгпола и все

**Comment by nitreojs** [comment]
если проблема была решена, закройте issue
