### ISSUE TITLE
Как сделать, чтобы работало сразу несколько ботов в одном скрипте?

### ISSUE THREAD

**Issue by json1c** [negezor/vk-io#426]
Вопрос в шапке

**Comment by Antonzlo** [comment]
Попробуйте создать несколько разных VK

**Comment by json1c** [comment]
> Попробуйте создать несколько разных VK
Вот здесь запускается только один бот

`async function start() {
	valid_tokens = await check_tokens();
	console.log(valid_tokens);

	bots = [];
	for (token of valid_tokens) {
		await Bot(token);
	}
}

async function Bot(token) {
	const vk = new VK({
		token: token
	});
	api = vk.api;

	await vk.updates.startPolling();
	vk.updates.on('message', async (event) => {
		if (event.text == ".") {
			console.log(token);
			await event.send("Хехъ");
		}
	});
}`

**Comment by Antonzlo** [comment]
> > Попробуйте создать несколько разных VK
> 
> Вот здесь запускается только один бот из трех
> 
> ```
> async function start() {
> 	valid_tokens = await check_tokens();
> 	console.log(valid_tokens);
> 
> 	for (token of valid_tokens) {
> 		await Bot(token);
> 	}
> }
> 
> async function Bot(token) {
> 	const vk = new VK({
> 		token: token
> 	});
> 	api = vk.api;
> 
> 	await vk.updates.startPolling();
> 	vk.updates.on('message', async (event) => {
> 		if (event.text == ".") {
> 			console.log(token);
> 			await event.send("Хехъ");
> 		}
> 	});
> }```
> ```

Токен проходит проверку?

**Comment by json1c** [comment]
> Токен проходит проверку?

да, проходит: `valid_tokens = await check_tokens();`

**Comment by Antonzlo** [comment]
> > Токен проходит проверку?
> 
> да, проходит: `valid_tokens = await check_tokens();`

Valid_tokens.length равно 3?

**Comment by json1c** [comment]
> Valid_tokens.length равно 3?

у меня только два аккаунта, из этого следует, что длина этого списка - 2

**Comment by Antonzlo** [comment]
Везде включен ЛП? Есть ли ошибки? Есть ли права у токенов?

**Comment by json1c** [comment]
> Везде включен ЛП? Есть ли ошибки? Есть ли права у токенов?

ошибок нет, права все, стоит уточнить, что это юзеры

**Comment by Markoffka** [comment]
синхронно вызываешь асинхронную функцию?

**Comment by Markoffka** [comment]
попробуй для этого использовать [cluster](https://nodejs.org/api/cluster.html)

**Comment by json1c** [comment]
> синхронно вызываешь асинхронную функцию?
> 
> ```
> for (token of valid_tokens) {
>   await Bot(token);
> }
> ```
> 
> пока в цикле работает **await** следующий цикл не наступит

я и без этого пробовал
