### ISSUE TITLE
Есть у кого чистая структура бота?

### ISSUE THREAD

**Issue by Boniuss** [negezor/vk-io#430]
Дайте пожалуйста голую структуру бота, месяц назад все ок работало, сейчас из-за того что @vk-io/hear вынесли в отдельный пакет, вообще все по п***** пошло... 
скиньте пожалуйста, я уже устал делать тупо структуру, ниче не выходит.......

**Comment by Drauiq** [comment]
Возможно, это то что нужно: #387

И перед тем как обновляться на более свежие версии библиотеки лучше проверять работоспособность бота в тестовом окружении, а не сразу в продакшн.
