### ISSUE TITLE
ImplicitFlowGroups: Could not log in

### ISSUE THREAD

**Issue by liminin** [negezor/vk-io#431]
При попытке получить токен группы вываливает ошибку "Could not log in".

Ошибка дропается на последнем этапе получения, т.е. токен создался, но далее идёт попытка получить переменную locations (707 ст.) на пустой странице с токеном, находящимся в url. 

По сей видимости, процесс получения токена группы немного отличается.

UPD: Проверил с ImplicitFlowUser, выдаёт ту же ошибку без ведомых на то причин, следовательно, проблема в самом ImplicitFlow. При получении же токена через DirectAuthorization, кстати, всё проходит гладко.

**Comment by liminin** [comment]
Проверил с ImplicitFlowUser, выдаёт ту же ошибку без ведомых на то причин, следовательно, проблема в самом ImplicitFlow. При получении же токена через DirectAuthorization, кстати, всё проходит гладко.

**Comment by realnickzero** [comment]
Проблема в регулярном выражении FIND_LOCATION_HREF_RE. Не находит на странице location.href. После исправления всё снова работает

**Comment by negezor** [comment]
Исправлено в 1.2.1.
