### ISSUE TITLE
Проблемы с отправкой сообщения с фото.

### ISSUE THREAD

**Issue by kungermu** [negezor/vk-io#432]
#### What did you do?
![image](https://user-images.githubusercontent.com/42349670/119259154-8e043280-bbd5-11eb-8337-f4841e89bc74.png)

#### What did you expect to happen?
Должно отправиться сообщение с фото. Этого не происходит.

#### What was the actual result?
![image](https://user-images.githubusercontent.com/42349670/119259163-a7a57a00-bbd5-11eb-9728-4fe5f0e01ee3.png)
Сообщение не отправляется + выдает ошибку.

#### Additional Info
Файл создается до того, как происходит отправка, с этим проблемы точно нет. 

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `7.7.6` |
| `node`                             | `15.13.0` |
| `TypeScript`                       | `--` |
| `yarn` or `npm`                    | `npm 7.7.6` |

**Comment by mulfyx** [comment]
По этому куску кода мало чего можно понять

**Comment by kungermu** [comment]
Но больше у меня и не используется vk-io в этом коде.

Но вот в принципе код всей команды:

`      const callback = new VK({ token: 'неважно'  });

       console.log('Инициировано сообщение "test"')
	const start = new Date().getTime();
	const random = (x, y) => { return y ? Math.round(Math.random() * (y - x)) + x : Math.round(Math.random() * x) }
        let repeat = random(4, 14);
        let text = "";

    for (let g = 0; g < repeat; g++) {
      let randomWord = random(0, (db.base.length - 1));
      text += ` ${db.base[[randomWord]]}`

       if(g == repeat - 1) {
        util.sendMessage(peer, text.toLowerCase())
        fnt.load(() => {
          var img = PImage.make(840,360);
          var ctx = img.getContext('2d');
          ctx.fillStyle = '#000000';
          console.log(fnt)
          ctx.font = "18pt Ubuntu";
          ctx.textAlign = 'center';
          ctx.fillText(text, 420, 180);
          PImage.encodePNGToStream(img, fs.createWriteStream(`/var/www/html/storage/images/${start}.png`)).then(() => {
            console.log("фото записано. ждем отправку сообщения с вложением.");
        }).catch((e)=>{
            console.log("there was an error writing");
      }); 
      }); 
      callback.upload.messagePhoto({ 
      peer_id: peer, 
      source: {
         value: `/var/www/html/storage/images/${start}.png`
       }
     }); 
       }
    }
   `

**Comment by mulfyx** [comment]
```js
const callback = new VK({
    token: 'неважно'
});
console.log('Инициировано сообщение "test"')
const start = new Date().getTime();
const random = (x, y) => {
    return y ? Math.round(Math.random() * (y - x)) + x : Math.round(Math.random() * x)
}
let repeat = random(4, 14);
let text = "";

for (let g = 0; g < repeat; g++) {
    let randomWord = random(0, (db.base.length - 1));
    text += ` ${db.base[[randomWord]]}`

    if (g == repeat - 1) {
        util.sendMessage(peer, text.toLowerCase())
        fnt.load(() => {
            var img = PImage.make(840, 360);
            var ctx = img.getContext('2d');
            ctx.fillStyle = '#000000';
            console.log(fnt)
            ctx.font = "18pt Ubuntu";
            ctx.textAlign = 'center';
            ctx.fillText(text, 420, 180);
            PImage.encodePNGToStream(img, fs.createWriteStream(`/var/www/html/storage/images/${start}.png`)).then(() => {
                console.log("фото записано. ждем отправку сообщения с вложением.");

                callback.upload.messagePhoto({
                    peer_id: peer,
                    source: {
                        value: `/var/www/html/storage/images/${start}.png`
                    }
                });
            }).catch((e) => {
                console.log("there was an error writing");
            });
        });

    }
}
```

Я бы вообще сразу стрим отправлял, не записывая картинку на диск

**Comment by kungermu** [comment]
Насчет загрузки из буфера - не получиться. Мне нужно это ещё и на сайт одновременно грузить.

**Comment by kungermu** [comment]
Проблема не решена. Теперь абсолютно нет ошибок, но и фото не отправляется :-(

**Comment by kungermu** [comment]
Проблема решена. Метод не выполняет функцию, которую я думал.

Если кому-то понадобиться:

callback.upload.messagePhoto({ source: { value: `/var/www/html/storage/images/${start}.png`, }  }).then((attachment) =>
callback.api.messages.send({
                           message: text, 
                           attachment,
                           random_id: Math.random() * 0xFFFFFFFFFF,
                           peer_id: peer, 
                       })
                       );

**Comment by Antonzlo** [comment]
> Проблема решена. Метод не выполняет функцию, которую я думал.
> 
> Если кому-то понадобиться:
> 
> callback.upload.messagePhoto({
> source: {
> value: `/var/www/html/storage/images/${start}.png`,
> }
> }).then((attachment) =>
> callback.api.messages.send({
> message: text,
> attachment,
> random_id: Math.random() * 0xFFFFFFFFFF,
> peer_id: peer,
> })
> );

Так же можно указать random_id: 0 если это не нужно

**Comment by kungermu** [comment]
> > Проблема решена. Метод не выполняет функцию, которую я думал.
> > Если кому-то понадобиться:
> > callback.upload.messagePhoto({
> > source: {
> > value: `/var/www/html/storage/images/${start}.png`,
> > }
> > }).then((attachment) =>
> > callback.api.messages.send({
> > message: text,
> > attachment,
> > random_id: Math.random() * 0xFFFFFFFFFF,
> > peer_id: peer,
> > })
> > );
> 
> Так же можно указать random_id: 0 если это не нужно

Спасибо за совет.
