### ISSUE TITLE
Обработка запроса

### ISSUE THREAD

**Issue by Ciferblood** [negezor/vk-io#433]
Допустим, есть команда:

vk.updates.hear(/!Проверка/i, async(context) => {
        await context.reply(`Бот работает`);
    });

Как сделать так, чтобы бот реагировал на отредактированное сообщение?
То есть допустим, пользователь неправильно написал команду "!Прверка", потом отредактировал сообщение на "!Проверка".

**Comment by Antonzlo** [comment]
Для этого нужно ловить событие `message_edit`, но в беседах оно не приходит

**Comment by Ciferblood** [comment]
> Для этого нужно ловить событие `message_edit`, но в беседах оно не приходит

Речь идёт про страничного бота

**Comment by ttempaa** [comment]
Вроде так:

```
vk.updates.on('message_edit' context => {
  console.log(context);
});
```
