### ISSUE TITLE
Можно ли связать vk-io и expressjs в единое целое?

### ISSUE THREAD

**Issue by sm1rnovdev** [negezor/vk-io#434]
Добрый день!
Возможно ли связать вк-ио и экспресс вместе? 
Хочу отправлять и обрабатывать сообщения и не только через vk-io, если есть пример, буду рад!
PS: Использование User Long Pool в expressjs

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.3.0` |
| `node`                             | `16.2.0` |
| `TypeScript`                       | `none` |
| `yarn` or `npm`                    | `7.13.0` |

**Comment by negezor** [comment]
User Long Poll из названия уже указывает что доступен только с помощью опроса сервера. Через вебхук доступны только группы.

**Comment by sm1rnovdev** [comment]
> User Long Poll из названия уже указывает что доступен только с помощью опроса сервера. Через вебхук доступны только группы.

Ну а вообще, возможно ли получать события через вк ио, но отправлять скажем так, определенные действия уже внутри express?
То есть: 
app.get('/vk.send', function (req, res) {
//Код обработчика события new_message
//Отправка сообщения клиенту/чату
})
Пробовал внутри get/post использовать обработчик событий, в принципе работать можно, но слишком муторно, да и в MessageContext если отправляешь несколько сообщений в самом вк, то он повторяется (MessageContext)

**Comment by Antonzlo** [comment]
Так а что не так? Вы сами весь код написали, обработчик событий Callback, и в нём можно `vk.api.messages.send()` например

**Comment by sm1rnovdev** [comment]
> Так а что не так? Вы сами весь код написали, обработчик событий Callback, и в нём можно `vk.api.messages.send()` например

Так с отправкой все понятно, но как мне редактировать сообщения? 
Допустим я создаю сайт для создания дежурных, и мне надо чтобы сообщения которые они отправили, редактировать...

**Comment by Antonzlo** [comment]
Сохраняете айди сообщений в массив, их редактируете через цикл

**Comment by sm1rnovdev** [comment]
> Сохраняете айди сообщений в массив, их редактируете через цикл

Хм... Была конечно такая мысль, а если не только будут события связанные с отправкой/редачем?

**Comment by Antonzlo** [comment]
А вы подумайте: можно по типу события делать разные вещи. Их можно разделить например через `switch`

**Comment by sm1rnovdev** [comment]
> А вы подумайте: можно по типу события делать разные вещи. Их можно разделить например через `switch`

Был ещё один вопрос, как получать message_id если не отлавливать события new_message?

**Comment by sm1rnovdev** [comment]
> А вы подумайте: можно по типу события делать разные вещи. Их можно разделить например через `switch`

Допустим если разделять их через switch, то как сначала отлавливать их без vk-io? (Если я правильно понял Вашу мысль)

**Comment by negezor** [comment]
```js
const messageId = await vk.api.messages.send({
  // ...
});
```

**Comment by sm1rnovdev** [comment]
> ```js
> const messageId = await vk.api.messages.send({
>   // ...
> });
> ```

Прощу прощения, но для того чтобы получить messageId мне необходимо сначала ввести саму команду, чтобы express уже от другого сервера обработал данную команду, и после этого уже получить messageId
То есть код который я использую: https://pastebin.com/AGW9yqum
При этом если ввести 2 разные команды, то в MessageContext text и id будут содержать данные 1-вого сообщения

**Comment by Antonzlo** [comment]
Не понятно зачем создавать этот маршрут при каждом новом сообщении, его нужно один раз создавать

**Comment by sm1rnovdev** [comment]
> Не понятно зачем создавать этот маршрут при каждом новом сообщении, его нужно один раз создавать

Если можете, покажите на "пальцах"
