### ISSUE TITLE
invalid json response body at https://api.vk.com/method/execute reason: Unexpected token E in JSON at position 0

### ISSUE THREAD

**Issue by devled-ui** [negezor/vk-io#436]
Вопрос: что делаю не так?

![image](https://user-images.githubusercontent.com/59190419/122725475-7a102700-d28e-11eb-8c59-db6f689aa759.png)
![image](https://user-images.githubusercontent.com/59190419/122725479-7aa8bd80-d28e-11eb-9fb4-71fc9ada22f2.png)
![image](https://user-images.githubusercontent.com/59190419/122725617-9f049a00-d28e-11eb-8230-05130f865a64.png)

**Comment by Antonzlo** [comment]
Вы можете получать до 200 диалогов одним запросом, но это не суть. Тут проблема или в неправильном запросе от библиотеки или ошибка на стороне ВК. Нужно посмотреть запрос и повторить вне библиотеки

**Comment by negezor** [comment]
Проблема явно на стороне ВКонтакте, так как вернулся с их стороны неправильный JSON.
