### ISSUE TITLE
Event добавление/удаление из друзей

### ISSUE THREAD

**Issue by Oliver-Patterson** [negezor/vk-io#437]
Есть ли event когда добавляется/удаляется друг? Я не нашел в списке доступных. Этого нет в вк или нет в данном package?

**Comment by AlexXanderGrib** [comment]
Такого события действительно нет. 

API User Long Poll подразумевает только сообщения ([Документация](https://vk.com/dev/using_longpoll))

- Для работы с друзьями есть раздел [`friends`](https://vk.com/dev/friends)
- Если хочешь посмотреть заявки есть метод [`friends.getRequests`](https://vk.com/dev/friends.getRequests)
- А теми, кто удалил сложнее, есть вариант сохранить друзей сверять раз в какой-то промежуток врмени
