### ISSUE TITLE
Некорректная работа Snippets

### ISSUE THREAD

**Issue by kkmoskalenko** [negezor/vk-io#44]
**What version of vk-io are you using?**
4.0.0-alpha.6

**What version of Node.js are you using?**
9.2.1

**What did you do?**
```javascript
const url = "https://vk.com/durov?z=photo1_456264771/album1_0/rev";

snippets.resolveResource(url)
        .then(result => {
            console.log(result);
        });
```
**What did you expect to happen?**
```javascript
{ id: 456264771, owner: 1, type: 'photo' }
```

**What was the actual result?**
```javascript
{ id: 456264771, owner: 456264771, type: 'durov??z=photo' }
```

К сожалению, данный пример не единственный. Это случается со многими другими ссылками.

Подскажите, пожалуйста, есть ли ещё какие-либо способы парсинга ссылок vk? В официальной документации полезных советов найти не удалось :(

**Comment by kkmoskalenko** [comment]
Кроме того, если вызвать тот же самый метод для ссылки наподобие `pornhub.com.18mb.ua.xxx`, то вместо ошибки будет возвращено:
```javascript
{ id: 18, type: 'pornhub.com.' }
```

**Comment by kkmoskalenko** [comment]
Первая строка – то, что было подано на вход `snippets.resolveResource()`, вторая строка – полученный объект.
```javascript
"https://vk.com/durov?z=photo1_456264771/album1_0/rev"
{ id: 456264771, owner: 456264771, type: 'durov??z=photo' }

"photo1_456264771"
{ id: 456264771, owner: 456264771, type: 'photo' }

"wall67529365_14477"
{ id: 14477, owner: 14477, type: 'wall' }

"https://vk.com/feed?w=wall67529365_14477"
{ id: 14477, owner: 14477, type: 'feed??w=wall' }

"https://vk.com/i_starikova?w=wall67529365_14477"
{ id: 14477, owner: 14477, type: 'i_starikova??w=wall' }
```

**Comment by negezor** [comment]
[Исправлено](https://github.com/negezor/vk-io/commit/720269f767c5248e42b25682fe64f3758abcae7b)
