### ISSUE TITLE
Ошибка при попытке обновления обложки

### ISSUE THREAD

**Issue by zombieserv** [negezor/vk-io#440]
Добрый день.
С недавних пор при попытке вызвать upload.groupCover появляется ошибка "One of the parameters specified was missing or invalid: min height of crop is 265".
После добавления параметра crop_y2 она пропадает, но появляется другая: AbortError: The user aborted a request.
Полный код обновления:
` const updated = await upload.groupCover({
    source: { value: canvas.toBuffer() },
    group_id: process.env.VK_GROUP_ID,
    crop_x2: 1590,
    crop_y2: 530,
});`

Смена parallel на sequential не помогает, указание прямого пути до картинки вместо буфера не помогает.
В чём может быть проблема?
Заранее спасибо.
#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.3.1` |
| `node`                             | `12.16.1` |

**Comment by nitreojs** [comment]
каковы изначальные размеры картинки? User aborted the request обозначает, что запрос выполнялся слишком долго (в основном, более 30 секунд) и автоматически был отменен

**Comment by zombieserv** [comment]
> каковы изначальные размеры картинки? User aborted the request обозначает, что запрос выполнялся слишком долго (в основном, более 30 секунд) и автоматически был отменен

1590x530, рекомендуемый ВК.
Эксперимента ради попробовал уменьшить до 700x233, не помогло, ошибка та же.

**Comment by negezor** [comment]
Стоит попробовать обновится до [4.5.0](https://github.com/negezor/vk-io/releases/tag/vk-io%404.5.0).
