### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by nutrolsharfik** [negezor/vk-io#441]
Здравствуйте, помогите решить проблему. Весь интернет облазил, решения не нашел.
![image](https://user-images.githubusercontent.com/85965186/124504120-7cff3180-ddcf-11eb-9406-551b295c3de0.png)

**Comment by nitreojs** [comment]
ты, видимо, используешь `const vk = new VK();`
в новых версиях (начиная с 4.0.0) нужно обязательно прокидывать обьект в конструктор, а не использовать `setOptions` (он уже давно устарел и вроде как удален):
`const vk = new VK({ token: ... })`

**Comment by nutrolsharfik** [comment]
const vk = new VK({ token: 'токен' })
Верно?

**Comment by nutrolsharfik** [comment]
Исправил, ошибка осталась

**Comment by negezor** [comment]
Всё как и сказал @nitreojs. В коде остались места где не передаётся объект в конструктор `VK`.
