### ISSUE TITLE
Как сделать несколько аргументов для входящих сообщений и проверить их?

### ISSUE THREAD

**Issue by FutStudio** [negezor/vk-io#443]
![Error](https://user-images.githubusercontent.com/87040527/124659778-ff5e2300-dead-11eb-9ffc-591ad71a0c63.jpg)
Когда пишу проверку нескольких аргументов (if (msg.$match[1/2/3 и т. д.])...), проверка вообще перестаёт проходить. Как мне сделать правильно?

**Comment by nitreojs** [comment]
регулярка очень бредовая, все проблемы в ней. regex101.com в помощь, а у библиотеки все прекрасно — просто выведи `msg.$match` в консоль и увидишь, что там происходит

**Comment by negezor** [comment]
Вопрос не относится к библиотеке, а только к теме регулярных выражений. Для более сложных вещей, используйте что-то сложнее чем абстрактный слушатель, как например [Command Pattern](https://refactoring.guru/ru/design-patterns/command).
