### ISSUE TITLE
getWebhookCallback() возвращает Function, с чем не согласен express

### ISSUE THREAD

**Issue by nitreojs** [negezor/vk-io#444]
#### Что вы сделали?

`app.use('/webhook/vk', vk.updates.getWebhookCallback());`

#### Каков был ожидаемый результат?

`express` принимает и пропускает `getWebhookCallback()`

#### Каков был настоящий результат?

express данный тип не принимает, а typescript, соответственно, выкидывает ошибку:
```
Ни одна перегрузка не соответствует этому вызову.
  Последняя перегрузка возвратила следующую ошибку.
    Аргумент типа "Function" нельзя назначить параметру типа "Application".
      В типе "Function" отсутствуют следующие свойства из типа "Application": init, defaultConfiguration, engine, set и еще 61.
```

#### Дополнительная информация

[ссылка на оригинальное сообщение](https://t.me/vkio_ru/11441) 

#### Версии

| модуль                             | версия  |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.3.1` |

**Comment by negezor** [comment]
Исправлено https://github.com/negezor/vk-io/commit/1bff695b390c7202d9542ef45b9b4adf4da98f88
