### ISSUE TITLE
Ошибка VK API при рассылке

### ISSUE THREAD

**Issue by devled-ui** [negezor/vk-io#447]
у меня есть скрипт рассылки на nodejs, при запуске  ВК отдает ошибку APIError: Code №13 - Runtime error occurred during code invocation: response size is too big, с чем это может быть связано?
![122725475-7a102700-d28e-11eb-8c59-db6f689aa759](https://user-images.githubusercontent.com/59190419/128849908-43e0d626-52a6-40aa-8fa1-bcbdbd377a29.png)
![122725479-7aa8bd80-d28e-11eb-9fb4-71fc9ada22f2](https://user-images.githubusercontent.com/59190419/128849924-334ef79e-cd70-4280-90fa-c34a26a85fe7.png)

**Comment by nitreojs** [comment]
https://qna.habr.com/q/551164
@negezor возможно, `execute` в `collectIterator` превышает 25 запросов в execute code/вызывается более 3 раз в секунду?

**Comment by devled-ui** [comment]
> https://qna.habr.com/q/551164
> @negezor возможно, `execute` в `collectIterator` превышает 25 запросов в execute code/вызывается более 3 раз в секунду?

я думаю, что нет. на vk.com/dev нашел вот это 

Обратите внимание! Существует ограничение на объем ответа. В случае, если данные в ответе занимают больше 5 МБ, вернется ошибка 13 с комментарием "response size is too big".
