### ISSUE TITLE
Аргументы

### ISSUE THREAD

**Issue by Fut-Studio** [negezor/vk-io#448]
Например, я хочу создать команду «Никнейм»:

`vk.updates.hear(/никнейм ?(.+)?/i, async (context) => {
     // ...
}`

И если аргумент context.$match[1] == null - то выводится сообщение, что нужно ввести никнейм.

Казалось бы, всё хорошо, но

Я могу использовать команду с необязательным аргументом без пробела. То есть, могу написать:

НикнеймПривет

И мой никнейм будет равен "Привет". Но мне нужно сделать так, чтобы я мог установить никнейм только тогда, когда стоит пробел.
Как мне это сделать?

**Comment by negezor** [comment]
Решение в лоб:
```ts
vk.updates.hear(/никнейм(?:$|\s(.+))/i, async (context) => { // ... }
```
Как работает регулярное выражение https://regex101.com/r/vrcetx/1

**Comment by Fut-Studio** [comment]
Но в таком случае, когда я пишу, к примеру, «Любое_слово никнейм», у меня выполняется команда.
Что делать?

**Comment by Fut-Studio** [comment]
> ```ts
> vk.updates.hear(/никнейм(?:$|\s(.+))/i, async (context) => { // ... }
> ```
> 
> Как работает регулярное выражение https://regex101.com/r/vrcetx/1
> 
> Модуль `@vk-io/hear` предназначен для очень простых ботов (хотя на нём можно писать сложные вещи, но это труднее). Если планируются сложные валидации или удобство, то я бы порекомендовал уже написать собственный обработчик команд.

Но в таком случае, когда я пишу, к примеру, «Любое_слово никнейм», у меня выполняется команда.
Что делать?

**Comment by Antonzlo** [comment]
/^никнейм\s(.+)/i

**Comment by Fut-Studio** [comment]
> /^никнейм\s(.+)/i

В том случае, при написании этой команды без аргументов, не выводится сообщение, что нужно ввести аргумент.
А мне же нужно, чтобы это выполнялось.

**Comment by Antonzlo** [comment]
> > /^никнейм\s(.+)/i
> 
> В том случае, при написании этой команды без аргументов, не выводится сообщение, что нужно ввести аргумент.
> А мне же нужно, чтобы это выполнялось.

Извиняюсь, плохо прочитал. Если вам нужен необязательный аргумент, после него поставьте ?
/^никнейм\s(.+)?/i

**Comment by Fut-Studio** [comment]
> > > /^никнейм\s(.+)/i
> > 
> > 
> > В том случае, при написании этой команды без аргументов, не выводится сообщение, что нужно ввести аргумент.
> > А мне же нужно, чтобы это выполнялось.
> 
> Извиняюсь, плохо прочитал. Если вам нужен необязательный аргумент, после него поставьте ?
> /^никнейм\s(.+)?/i

В таком случае тоже не работает. Если не трудно - помогите, пожалуйста.

**Comment by Fut-Studio** [comment]
Всё, спасибо, сам исправил проблему.
`/^никнейм(?:$|\s(.+))/i`

**Comment by Fut-Studio** [comment]
Но нужна помощь: как мне сделать такой же второй аргумент?
