### ISSUE TITLE
Can't send messages for users without permission

### ISSUE THREAD

**Issue by Fut-Studio** [negezor/vk-io#449]
Я хочу отправить сообщение пользователю через VK API:
await vk.api.messages.send({message: `🆘 ${nickname(sender)}, [id${user.vk_id}|${administrator.post} #${administrator.id}] ответил на Ваш репорт №${report.id} (${report.answer}):\n${context.$match[2]}`, peer_id: report.sender, chat_id: report.sender, random_id: utils.random(100000, 999999)});

Выдаётся следующая ошибка:
`Can't send messages for users without permission`

**Comment by Antonzlo** [comment]
Это не проблема с библиотекой, а то, что пользователь запретил группе писать ему.

**Comment by Antonzlo** [comment]
И зачем писать параметр chat_id при отправке пользователю?

**Comment by arslanp0** [comment]
> Я хочу отправить сообщение пользователю через VK API:
> await vk.api.messages.send({message: `🆘 ${nickname(sender)}, [id${user.vk_id}|${administrator.post} #${administrator.id}] ответил на Ваш репорт №${report.id} (${report.answer}):\n${context.$match[2]}`, peer_id: report.sender, chat_id: report.sender, random_id: utils.random(100000, 999999)});
> 
> Выдаётся следующая ошибка:
> `Can't send messages for users without permission`

Пользователь не разрешил писать сообщения группе

**Comment by Fut-Studio** [comment]
Но я хочу отправить это сообщение себе от имени группы. А сообщения от группы у меня разрешены.

**Comment by Fut-Studio** [comment]
await vk.api.messages.send({user_id: report.sender, message: `🆘 ${nickname(sender)}, [id${user.vk_id}|${administrator.post} #${administrator.id}] ответил на Ваш репорт №${report.id} (${report.answer}):\n${context.$match[2]}`});

**Comment by Antonzlo** [comment]
> await vk.api.messages.send({user_id: report.sender, message: `🆘 ${nickname(sender)}, [id${user.vk_id}|${administrator.post} #${administrator.id}] ответил на Ваш репорт №${report.id} (${report.answer}):\n${context.$match[2]}`});

Вам нужно указать параметр random_id, но при желании вы можете поставить 0

**Comment by Fut-Studio** [comment]
Спасибо, получилось. А как отправить сообщение в беседу? Ведь для этого нужно узнать её ID.

**Comment by nitreojs** [comment]
и все же, это не относится к библиотеке
