### ISSUE TITLE
Не работает клавиатура

### ISSUE THREAD

**Issue by Fut-Studio** [negezor/vk-io#451]
У меня есть клавиатура:
`Keyboard.builder()
                            .textButton({
                                label: '🛠 Работать',
                                payload: {
                                    command: 'работать'
                                }
                            }).inline()`

И есть команда:
`vk.updates.hear([/^работать/i, /^work/i], async (context) => {  /* ... */  });`

При нажатии на кнопку, ничего не происходит. Как это исправить?

**Comment by Antonzlo** [comment]
У вас текст клавиатуры со смайликом, в регулярном выражении смайликов нет. В payload вы указали текст, но вы его не обрабатываете, обрабатывается именно текст сообщения.

**Comment by Fut-Studio** [comment]
> У вас текст клавиатуры со смайликом, в регулярном выражении смайликов нет. В payload вы указали текст, но вы его не обрабатываете, обрабатывается именно текст сообщения.

Не совсем понимаю.
Можете, пожалуйста, написать, как будет правильно?

**Comment by Antonzlo** [comment]
> > У вас текст клавиатуры со смайликом, в регулярном выражении смайликов нет. В payload вы указали текст, но вы его не обрабатываете, обрабатывается именно текст сообщения.
> 
> Не совсем понимаю.
> Можете, пожалуйста, написать, как будет правильно?

Или сделать текст кнопки без смайлика, или добавить смайлик в регулярное выражение, или написать свой обработчик событий и там обрабатывать именно текст в payload сообщения

**Comment by Fut-Studio** [comment]
> > > У вас текст клавиатуры со смайликом, в регулярном выражении смайликов нет. В payload вы указали текст, но вы его не обрабатываете, обрабатывается именно текст сообщения.
> > 
> > 
> > Не совсем понимаю.
> > Можете, пожалуйста, написать, как будет правильно?
> 
> Или сделать текст кнопки без смайлика, или добавить смайлик в регулярное выражение, или написать свой обработчик событий и там обрабатывать именно текст в payload сообщения

А смысл, в таком случае, объекта payload? Что делает command?

**Comment by Antonzlo** [comment]
> > > > У вас текст клавиатуры со смайликом, в регулярном выражении смайликов нет. В payload вы указали текст, но вы его не обрабатываете, обрабатывается именно текст сообщения.
> > > 
> > > 
> > > Не совсем понимаю.
> > > Можете, пожалуйста, написать, как будет правильно?
> > 
> > Или сделать текст кнопки без смайлика, или добавить смайлик в регулярное выражение, или написать свой обработчик событий и там обрабатывать именно текст в payload сообщения
> 
> А смысл, в таком случае, объекта payload? Что делает command?

Пейлоад это полезная нагрузка. Комманд ничего не сделает пока вы сами это не обработаете. В полезной нагрузке может быть что угодно, но смысла в ней без обработки нет

**Comment by Fut-Studio** [comment]
> > > > > У вас текст клавиатуры со смайликом, в регулярном выражении смайликов нет. В payload вы указали текст, но вы его не обрабатываете, обрабатывается именно текст сообщения.
> > > > 
> > > > 
> > > > Не совсем понимаю.
> > > > Можете, пожалуйста, написать, как будет правильно?
> > > 
> > > 
> > > Или сделать текст кнопки без смайлика, или добавить смайлик в регулярное выражение, или написать свой обработчик событий и там обрабатывать именно текст в payload сообщения
> > 
> > 
> > А смысл, в таком случае, объекта payload? Что делает command?
> 
> Пейлоад это полезная нагрузка. Комманд ничего не сделает пока вы сами это не обработаете. В полезной нагрузке может быть что угодно, но смысла в ней без обработки нет

Как можно сделать, так скажем, обработчик команд? Чтобы текст сообщения не зависил от payload?

**Comment by Antonzlo** [comment]
> > > > > > У вас текст клавиатуры со смайликом, в регулярном выражении смайликов нет. В payload вы указали текст, но вы его не обрабатываете, обрабатывается именно текст сообщения.
> > > > > 
> > > > > 
> > > > > Не совсем понимаю.
> > > > > Можете, пожалуйста, написать, как будет правильно?
> > > > 
> > > > 
> > > > Или сделать текст кнопки без смайлика, или добавить смайлик в регулярное выражение, или написать свой обработчик событий и там обрабатывать именно текст в payload сообщения
> > > 
> > > 
> > > А смысл, в таком случае, объекта payload? Что делает command?
> > 
> > Пейлоад это полезная нагрузка. Комманд ничего не сделает пока вы сами это не обработаете. В полезной нагрузке может быть что угодно, но смысла в ней без обработки нет
> 
> Как можно сделать, так скажем, обработчик команд? Чтобы текст сообщения не зависил от payload?

`vk.updates.on('message_new', async (message) => {
})`
Дальше делайте с данными что хотите
