### ISSUE TITLE
Синтаксис payload-a в конпках и при отправке через vk.api.messages.send разный

### ISSUE THREAD

**Issue by GeneriumMadness** [negezor/vk-io#452]
#### What did you do?
Пытался загрузить payload через vk.api.messages.send рабочим принципом от кнопки, то есть 
```
builder.textButton({
                        label: 'Добавить новую неделю',
                        color: Keyboard.POSITIVE_COLOR,
                        payload: {"command": "add week"}
                    }).row();
```

#### What did you expect to happen?
Загрузка payload-a в сообщение

#### What was the actual result?

`ExecuteError: Code №100 - One of the parameters specified was missing or invalid: payload contains incorrect JSON`

#### Additional Info

Проблема в синтаксисе. Для кнопок `payload: {"command": "add week"}` полностью работает, но в api нужно загонять payload как строку, то есть `payload: '{"command":"new week"}'`
ИМХО это является багом, нежели фичей.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.3.2` |
| `node`                             | `14.17.4` |

**Comment by Antonzlo** [comment]
Это не баг, используйте JSON.stringify
Автоматически это отсутствует, потому что есть возможность сделать слишком длинную строку или передать лишнее значение

**Comment by negezor** [comment]
@GeneriumMadness нет полного примера от создание до отправки клавиатуры.

@Antonzlo автоматический вся клавиатура приводится к JSON
https://github.com/negezor/vk-io/blob/7030d0cd8c8baeefc3b93989f748c7e73574494a/packages/vk-io/src/structures/keyboard/builder.ts#L324-L334
Насчёт длинной строки это не так, сам payload может быть длиной до 255 символов. Так же для кнопка "Начать" в боте используется JSON с видом `{"command":"start"}`.
