### ISSUE TITLE
Тайпинги для запроса messages.getChat

### ISSUE THREAD

**Issue by Loskir** [negezor/vk-io#454]
Насколько я вижу, в https://github.com/negezor/vk-io/blob/master/packages/vk-io/src/api/schemas/methods.ts отсутствует метод [messages.getChat](https://vk.com/dev/messages.getChat), хотя соседний [messages.getChatPreview](https://vk.com/dev/messages.getChatPreview) присутствует

**Comment by nitreojs** [comment]
типы генерируются на основе VK API схемы, которая лежит в `/src/api/schemas/methods.json` (там, где ты указал)
как видно, последнее обновление схемы -- 12 апреля, НО! https://github.com/VKCOM/vk-api-schema/blob/master/methods.json
даже **здесь** на текущий момент нет метода `getChat`, а `getChatPreview `есть
так что насчет типов виновата схема VK API, потому что типы генерируются на ее основе

**Comment by Loskir** [comment]
спасибо, пожаловался туда https://github.com/VKCOM/vk-api-schema/issues/200

**Comment by nitreojs** [comment]
тогда, думаю, проблема неактуальна? я о закрытии issue

**Comment by Loskir** [comment]
Ну, возможно. Хотя можно и вручную добавить недостающие типы, раз официальных нет

**Comment by nitreojs** [comment]
вручную добавлять совершенно не вариант -- при каждой регенерации типов придется их добавлять и добавлять, а еще типы могут не соответствовать настоящим

**Comment by Loskir** [comment]
добавленные вручную типы явно лучше, чем никакие
не уверен, как тут устроен генератор, но, думаю, в нем можно реализовать добавление отдельного файла с кастомными типами в каком-нибудь формате и их вставку в результат
впрочем, это требует значительных усилий, так что я не настаиваю, конечно

а можно ещё спросить совета, как локально в проекте добавить недостающие типы? `declare module` и всё такое. не настолько разбираюсь в ts

**Comment by negezor** [comment]
В зависимости от файла. Но это только переопределение существующего.
```ts
declare module 'vk-io/lib/api/schemas/<file>.ts' {
    interface MessagesMessage {
        mySomeProp: string;
    }
}
```
