### ISSUE TITLE
 createCollectIterator не выполняется.

### ISSUE THREAD

**Issue by sxpph1re** [negezor/vk-io#455]
метод createCollectIterator не работает.
Возвращается ошибка:

> (node:3552) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'execute' of undefined
>     at createCollectIterator (/home/david/drochilo/node_modules/vk-io/lib/index.js:4888:56)
>     at createCollectIterator.next (<anonymous>)
>     at run (/home/david/drochilo/braingeneration.js:19:25)
>     at Object.<anonymous> (/home/david/drochilo/braingeneration.js:63:1)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

Код: 
```
const {API, createCollectIterator} = require("vk-io");
const vk = new API({token:TOKEN, pollingGroupId: ID, apiMode: "parallel"});
let all_conversations;
  const iterator = createCollectIterator({
    // Объект API
    vk,

    method: 'messages.getConversations',
    params: {
      extended: 1,
      parallelCount: 1
    },
    countPerRequest: 25,
    maxCount: 200
  });
  let messages;
  for await(const chunk of iterator) {
    // chunk.received
    // chunk.percent
    // chunk.total

    // chunk.items
    // chunk.profiles
    // chunk.groups
    messages.push(chunk.profiles);
  }
```

**Comment by negezor** [comment]
```diff
let all_conversations;
  const iterator = createCollectIterator({
    // Объект API
-   vk,
+   api: vk
```

**Comment by sxpph1re** [comment]
thx, не увидел.
