### ISSUE TITLE
Code №17 - Validation required: please open redirect_uri in browser

### ISSUE THREAD

**Issue by Mreddi1** [negezor/vk-io#456]
Could you please prompt me how can I handle this code? `Code №17 - Validation required: please open redirect_uri in browser` 
I have `onCaptcha` handler. But this thing does not handle `onCaptcha`.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.3.0` |
| `@vk-io/authorization`             | `1.2.0` |
| `node`                             | `13.9.0` |
| `TypeScript`                       | `4.2.4` |
| `npm`                    | `7.15.1` |

**Comment by Mreddi1** [comment]
It was happening in /vk-io/lib/index.js:1626:39

**Comment by MrZillaGold** [comment]
Вы можете получить url редиректа из объекта ошибки обратившись к полю redirectUri.
