### ISSUE TITLE
Игнорируются параметры методов

### ISSUE THREAD

**Issue by Vahagn1993** [negezor/vk-io#46]
**What version of vk-io are you using?**
4.0.0-alpha.8
**What version of Node.js are you using?**
node -v: 8.1.4
npm -v: 5.2.0
**What did you do?**
```import VK from 'vk-io';
import StorageService from "...";
import {VkAppId} from "...";
export default class VkApiService {
    api: VK;

    constructor() {
        const token = new StorageService().getKey('access_token');
        this.api = new VK({
            app: VkAppId,
            token: token,
        }).api;
    }

    getDocs() {
        this.api.wall.get({owner_id: 1}).then(docs => console.log(docs));
        this.api.doc.search({q: 'Java'}).then(docs => console.log(docs));
    }
}
```
вызов метода `wall.get` для пользователя и `id:1` возвращает посты со стены **текущего** пользователя (аргумент игнорируется)
вызов метода `docs.search` с `q:'Java'` возвращает ошибку `APIError: Code №100 - One of the parameters specified was missing or invalid: q is undefined`
Пробовал использовать `Request`, результат аналогичный, хотя `request.toString()` возвращает валидный объект.
Если в методе `callMethod` передавать аргументы не в теле, а в url, проблема пропадает. Правда не уверен в правильности этого подхода :) 
по аналогии с 
```
url.searchParams.set('access_token', token);
url.searchParams.set('v', _constants.API_VERSION); 
```

**Comment by negezor** [comment]
Разве? В URL существует ограничение на 4096 символов (обычном веб-сервере), а значит может запрос обрезаться.
![image](https://user-images.githubusercontent.com/9392723/34467626-4b21c4b4-ef4b-11e7-8fbd-3b4c53d9da70.png)

**Comment by Vahagn1993** [comment]
@negezor , а библиотека работает в браузере? или только на сервере?

**Comment by negezor** [comment]
Только на сервере, в связи с CORS.
