### ISSUE TITLE
Очень странная ошибка. Node JS / VK API?

### ISSUE THREAD

**Issue by Coder-TheBeJIIHiu** [negezor/vk-io#461]
#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.0.0-rc.30` |
| `node`                             | `14...` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `npm` |

Handle polling update error: TypeError: Cannot read property 'member_id' of undefined

Непонятно почему возникает, ведь member_id взят из метода.

Вот код:
vk.updates.on([ 'chat_invite_user', 'chat_invite_user_by_link' ], async (message, context, bot) => {
if(chats[message.chatId].users[message.payload.action.member_id].isBanned && chats[message.chatId].users[message.payload.action.member_id].permanently) {

vk.api.call("messages.removeChatUser", { chat_id: chatId, user_id: message.payload.action.member_id } );
return message.send('@id' + message.payload.action.member_id + ' - находится в бане, поэтому он был исключен из беседы.'); }
} )

**Comment by negezor** [comment]
В библиотеке присутствует [context.eventMemberId](https://negezor.github.io/vk-io/references/vk-io/classes/MessageContext.html#eventMemberId) для получения ID пользователя связанного с событием. Использование `payload` не рекомендуется, так как его формат может меняться.
