### ISSUE TITLE
Error import node-fetch modules

### ISSUE THREAD

**Issue by DonatEW** [negezor/vk-io#462]
#### What did you do?
Установил vk-io и импортировал в код

#### What did you expect to happen?
Что код заработает и я смогу пользоваться vk-io

#### What was the actual result?
В консоли ошибка связанная с node-fetch
These dependencies were not found:

* node:http in ./node_modules/node-fetch/src/index.js, ./node_modules/node-fetch/src/headers.js
* node:https in ./node_modules/node-fetch/src/index.js
* node:stream in ./node_modules/node-fetch/src/index.js, ./node_modules/node-fetch/src/body.js
* node:url in ./node_modules/node-fetch/src/request.js
* node:util in ./node_modules/node-fetch/src/headers.js, ./node_modules/node-fetch/src/body.js
* node:zlib in ./node_modules/node-fetch/src/index.js

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                              | `4.4.0` |
| `node`                              | `14.17.5` |
| `TypeScript`                    | `нет` |
| `yarn`                               | `1.22.11` |

**Comment by Byeraon** [comment]
Привет, не нашел решение?

**Comment by tailsjs** [comment]
Не пробовал поставить версию постарей?

**Comment by negezor** [comment]
Протокол `node:` поддерживается начиная только с v14.18.0
