### ISSUE TITLE
[Feature] Расширение списка контекстов

### ISSUE THREAD

**Issue by MrZillaGold** [negezor/vk-io#463]
Сейчас библиотека поддерживает только контексты которые реализованы в ней самой, при этом обработка всех остальных происходить не будет. 
При реализации проектов от вк, часто предоставляется доступ к внутренним callback-событиям, что не позволяет использовать библиотеку так как они игнорируются.

**Шаги решения проблемы:**
1. Реализовать отдельный контекст для неподдерживаемых ивентов и задавать их тип (название), то которое приходит в самом ивенте. Поля и их названия сохраняем в том же виде, что приходят в полезной нагрузке.
2. Возможность самостоятельной реализации контекстов и передача их библиотеке.

**Comment by negezor** [comment]
Я думаю первый вариант самый оптимальный 🤔 , можно реализовать контекст в виде:
```ts
UnsupportedEventContext {
  type: 'unsupported_event',
  subTypes: ['название события'],
  eventPayload: <...>
}
```

**Comment by MrZillaGold** [comment]
Так и так, если мы не хотим открывать доступ к payload, то надо реализовывать кастомное поле в неподдерживаемом контексте (eventPayload). 
Возникает одна проблема, если пользователь будет использовать неподдерживаемый контекст, а потом его реализует вк и сама библиотека, то поле с eventPayload пропадет (библиотека будет возвращать контекст с геттерами), это можно фиксировать в истории версии, но будет ли этого достаточно.

**Comment by negezor** [comment]
Изначально сам вариант контекстов строился на изоморфности, код не поломался при добавлении `client_info` в сообщениях. Но это не касается неподдерживаемых типов, так что я считаю что semver будет достаточно для контроля таких случаев.
