### ISSUE TITLE
Метод photos.getMessagesUploadServer вызывает ошибку №15 в upload.messagePhoto

### ISSUE THREAD

**Issue by sm1rnovdev** [negezor/vk-io#468]
#### What did you do?
Создал чистый холст на Canvas
Далее использую upload.messagePhoto и передаю буфер канваса
После отправляю сообщение с текстом "test:" и в параметре attachment передаю полученный результат upload.messagePhoto

#### What did you expect to happen?
Бот отправляет сообщение "test:" с фотографией

#### What was the actual result?
APIError: Code №15 - Access denied: no access to call this method

#### Additional Info
Код:
![image](https://user-images.githubusercontent.com/77857669/152681202-1c7e41d5-3b8d-4b77-a0ea-7f440575543f.png)

Ошибка:
![image](https://user-images.githubusercontent.com/77857669/152681238-c873c344-5e7f-454f-bc59-577c58fb4239.png)

Использую групп-токен, с юзер токеном отправляется только текстовое сообщение, хотя присутствует PhotoAttachment

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.4.0` |
| `node`                             | `17.4.0` |
| `TypeScript`                       | `4.4.5` |
| `yarn` or `npm`                    | `1.22.17` |

**Comment by Antonzlo** [comment]
Права токена, ошибка на стороне ВК. Надо давать права на фотографии если вы работаете с ними

**Comment by sm1rnovdev** [comment]
> Права токена, ошибка на стороне ВК. Надо давать права на фотографии если вы работаете с ними

Ну так у токенов есть все доступные права, в том числе и с фотографиями. Проблема всё также остаётся на стороне вк?

**Comment by Antonzlo** [comment]
15
Доступ запрещён.
Убедитесь, что Вы используете верные идентификаторы, и доступ к контенту для текущего пользователя есть в полной версии сайта.

Попробуйте при загрузке указать chat_id

**Comment by sm1rnovdev** [comment]
> 15 Доступ запрещён. Убедитесь, что Вы используете верные идентификаторы, и доступ к контенту для текущего пользователя есть в полной версии сайта.
> 
> Попробуйте при загрузке указать chat_id

Эм... Ам... А зачем при загрузке указывать chat_id если он относится к чату, а не к чату с пользователем?
К тому же, вот что отвечает TS: 
  Аргумент типа "{ source: { value: Buffer; }; chat_id: number; }" нельзя назначить параметру типа "IUploadParams & { peer_id?: number; }".
  Объектный литерал может использовать только известные свойства. "chat_id" не существует в типе "IUploadParams & { peer_id?: number; }".

**Comment by sm1rnovdev** [comment]
Закрываю issue в пользу перевыпуска токена группы!
