### ISSUE TITLE
Ошибка при использовании createCollectIterator

### ISSUE THREAD

**Issue by 8funtik8** [negezor/vk-io#470]
Добрый день.
Подскажите, что не так делаю.
Запускаю пример с createCollectIterator отсюда https://negezor.github.io/vk-io/ru/guide/collect-iterator.html, получаю ошибку
Code №13 - Runtime error occurred during code invocation: Method splice requires an array
![Screenshot_8](https://user-images.githubusercontent.com/65829942/153454721-62f5560f-5e8f-40ca-aca0-56289ad63d0d.png)

**Comment by MrZillaGold** [comment]
Все так, ошибка библиотеки.

https://github.com/negezor/vk-io/blob/130161507434a2a6441d359b40afd6febc98b3ce/packages/vk-io/src/collect/execute-code.ts#L47

**Comment by MrZillaGold** [comment]
Проверил на группе с большим количеством диалогов, метод работает нестабильно

![image](https://user-images.githubusercontent.com/42776347/154764797-24793ac9-e699-4537-b8ac-07223d3632ab.png)
