### ISSUE TITLE
Попытка вызова wall.get проваливается

### ISSUE THREAD

**Issue by LilyStilson** [negezor/vk-io#474]
#### What did you do?
Скопировала-вставила пример из readme.md в корне репозитория со своим токеном. Токен имеет все права доступа к странице.
```js
import { VK } from 'vk-io';

const vk = new VK({
	token: "my-token-here"
});

async function run() {
	const response = await vk.api.wall.get({
		owner_id: 1
	});

	console.log(response);
}

run().catch(console.log);
```

#### What did you expect to happen?
Ожидалось получить посты со стены пользователя с ID = 1.

#### What was the actual result?
![image](https://user-images.githubusercontent.com/42270214/155190795-b4574e16-d833-48a5-8a02-6154fc223e21.png)
Ошибка - неизвестный метод `wall.get`

#### Additional Info
Проблема происходит и при попытке вызова через `VK.api.call()`
```js
import { VK } from 'vk-io';

const vk = new VK({
	token: "my-token-here"
});

async function run() {
	const response = await vk.api.call("wall.get", {
		owner_id: 1
	});

	console.log(response);
}

run().catch(console.log);
```
Этот код выдаёт ту же самую ошибку.

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.4.0` |
| `node`                             | `16.14.0` |
| `npm`                    | `8.4.1` |

**Comment by MrZillaGold** [comment]
[Сгенерируйте токен](https://vkhost.github.io/) от другого приложения, такая проблема точно наблюдается при генерации токена от vk.com, сгенерировал токен от VK Admin - работает.
