### ISSUE TITLE
Code №100 - One of the parameters specified was missing or invalid: file is undefined

### ISSUE THREAD

**Issue by Epifiev** [negezor/vk-io#475]
![image](https://user-images.githubusercontent.com/72816116/156994950-d674ad73-d127-43ef-bcbb-1e8037459bbf.png)
![image](https://user-images.githubusercontent.com/72816116/156994983-addb8e0c-ea0a-4e63-9ea7-5855c05ea208.png)

| ---------------------------------- | ------- |
| `vk-io`                            | `4.5.0` |
| `node`                             | `16.14.0` |

**Comment by negezor** [comment]
ВКонтакте предпочитает получать `.ogg` вместо `.mp3`. Не знаю насколько корректные файлы на выходе от Google TTS.

**Comment by Epifiev** [comment]
> ВКонтакте предпочитает получать `.ogg` вместо `.mp3`. Не знаю насколько корректные файлы на выходе от Google TTS.

ошибка та же

**Comment by negezor** [comment]
Рекомендую сначала проверить, рабочий файл в итоге или нет (через браузер это делать бессмысленно).
