### ISSUE TITLE
Похоже что context.hasText() работает некорректно.

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#48]
Node - v9.2.0
VK-IO - 4.0.0-alpha.8

Сама проверка:
```
if (!message.hasText() && message.isOutbox() && message.text[0] !== '/' && message.getChatId() != 4) return next();
let command = message.text.split(" ")[0].slice(1).toLowerCase()
```
(Ошибка указывает на последнюю строку)

```
Handle polling update error: TypeError: Cannot read property 'split' of null
at vk.updates.on (/home/bots/vk/vk.js:198:29)
at Array.use (/home/bots/vk/node_modules/vk-io/lib/updates/index.js:136:15)
at next (/home/bots/vk/node_modules/middleware-io/lib/middleware.js:80:22)
at stack.(anonymous function) (/home/bots/vk/node_modules/middleware-io/lib/middleware.js:80:34)
at Array.use (/home/bots/vk/node_modules/vk-io/lib/updates/index.js:140:13)
at next (/home/bots/vk/node_modules/middleware-io/lib/middleware.js:80:22)
at Middleware.run (/home/bots/vk/node_modules/middleware-io/lib/middleware.js:87:10)
at Updates.dispatchMiddleware (/home/bots/vk/node_modules/vk-io/lib/updates/index.js:678:28)
at Updates.handlePollingUpdate (/home/bots/vk/node_modules/vk-io/lib/updates/index.js:213:23)
at Promise.all.response.updates.map (/home/bots/vk/node_modules/vk-io/lib/updates/index.js:660:22)

```

**Comment by negezor** [comment]
```js
if (message.isOutbox() || !message.hasText() || message.getChatId() !== 4 || message.getText()[0] !== '/') {
  await next();
}
```

**Comment by negezor** [comment]
По хорошему на проверки isOutbox вынести отдельно если не нужны исходящие сообщения.
```js
if (message.isOutbox()) {
  return;
}
```

**Comment by negezor** [comment]
Как в целом выглядит код?

**Comment by T1MOXA** [comment]
Вы про 376 строку ? 
Перед ней куча проверок на совпадение различного текста и на 376 строке стоит `else await next();`
Т.Е. Если не найдется ни одного совпадения делать await next()

**Comment by negezor** [comment]
1. Ошибка указывает на то что `next()` вызывается несколько раз.
2. Попытка обратится к split от null. Думаю логично что это из-за того что нет текста.

**Comment by T1MOXA** [comment]
Ок, с первым думаю разберусь, а со второй ошибкой что делать ?

**Comment by negezor** [comment]
Потому что текст отсутствует.

**Comment by T1MOXA** [comment]
А разве функция context.hasText() не должна это проверять ?

**Comment by negezor** [comment]
Метод `hasText()` вернёт `true` если текст есть, а иначе `false`. Как я уже сказал проблема в череде проверок.

**Comment by T1MOXA** [comment]
Ну последовательность проверок я взял вашу, и на ней и была проблема. 
```
if (message.isOutbox() || message.getChatId() !== 4 || !message.hasText() || message.getText()[0] !== '/') {
  await next();
}
```

**Comment by negezor** [comment]
Я не могу видеть всей картины с таким кодом. Ошибка есть потому что условия неправильно расставлены или полное непонимание как работают Promise middleware.

**Comment by T1MOXA** [comment]
переделал структуру кода на более правильную с моей точки зрения, посмотрим может ошибка была как раз из за кривой структуры.

**Comment by T1MOXA** [comment]
Еще заметил что куда-то пропала инфа о прокси.
Вы убрали их поддержку ?

**Comment by negezor** [comment]
Поддержка осталась, только теперь нужно использовать https агенты для проксирования.

**Comment by T1MOXA** [comment]
Где можно найти информацию о том как это использовать? 
И еще...
Похоже в ваших доках нет списка всех эвентов которые можно слушать.
Было бы не плохо если бы вы это добавили )

**Comment by negezor** [comment]
Ну вообще достаточно загуглить `https proxy agent`, думаю позже сделаю.

Нету времени почти совсем на создание документации, но думаю как нибудь получится.

**Comment by T1MOXA** [comment]
Снова появилась нужда в использовании прокси...
Можете показать пример их использования с вашей библиотекой?

**Comment by negezor** [comment]
Нужно передать имплементацию [agent](https://nodejs.org/docs/latest/api/https.html#https_class_https_agent) в опции. Для этого может подойти модуль [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent).

**Comment by negezor** [comment]
vk.setOptions({ agent });

**Comment by T1MOXA** [comment]
Спасибо
