### ISSUE TITLE
vk-io/hear проблема с context.$match

### ISSUE THREAD

**Issue by Kypt3r** [negezor/vk-io#499]
Столкнулся с такой проблемой, что при написании команды context.$match[0] сливается с context.$match[1] и из за этого бот реагирует на слитные команды.
Например есть команда test и 1 параметр который можно написать после команды, например match1
Если написать testmatch1 то бот отреагирует на слитную команду. Решается путём обычной проверки if(context.$match[0].includes(`test${context.$match[1]}`)) return;
Если это возможно, то можно прописать данную проверку сразу в модуль

**Comment by nitreojs** [comment]
а показать регулярное выражение с помощью которого матчишь?
звучит примерно как это: /(test\s*(.+))/
просто тут проблема в регулярке и только

**Comment by negezor** [comment]
Тут неправильное понимание регулярного выражения, в `context.$match[0]` всегда хранится полная строка которая попала под выражение. А в `context.$match[1..]` уже хранятся все другие группы которые указаны в регулярном выражении.
