### ISSUE TITLE
Help me SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by firstgoat** [negezor/vk-io#504]
Помогите, начал только кодить и не понимаю что за проблема, код взял частично у друга, частично писал сам

![image](https://user-images.githubusercontent.com/110966232/183836652-2432c31d-24d1-4906-9872-336d346af90e.png)

Вот сам код:

![image](https://user-images.githubusercontent.com/110966232/183836711-958b43d5-7e16-4844-a6f9-086f46440499.png)

**Comment by negezor** [comment]
Вы пытаетесь использовать ESM импорт в CJS модуле, вам нужно поменять в коде:
```diff
- import { VK } from 'vk-io';
+ const { VK } = require('vk-io');
```
