### ISSUE TITLE
Возможно ли использование либы на клиенте?

### ISSUE THREAD

**Issue by WebKieth** [negezor/vk-io#51]
**What version of vk-io are you using?**
3.2.0
**What version of Node.js are you using?**
8.9.1

Попробовал выкачать данные с сервера из альбома группы:
Основной скрипт галереи:
'use strict'
gallery = ->
	vkGallery = require '../../components/vk-api/vk-gallery/vk-gallery'
	vkGallery.init
		group_id: 39911768
		album_id: 245393954

Компонент работы с vk-api:
'use strict'
const $ = require('jquery');
var VK = require('vk-io');
const vk = new VK;

var vkGallery = {
	init: function (options) {
		var group_id = options.group_id,
		album_id = options.album_id;

		return vk.api.photos.get({
			owner_id: group_id,
			album_id: album_id
		}).then((items) =>{
			console.log(items);
			return items
		}
		).catch((error) =>{
			console.log(error);
		})
	}
}

Запрашиваю локалхост, в консоль ловлю лулзы.
ailed to load https://api.vk.com/method/photos.get?access_token=&lang=&v=5.68: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Помимо прикола с CORS либа отказывается подставлять параметры в запрос, хотя в скрипт vk-gallery они подставляются верно. 

Я сделал вывод, что либа видимо применяется на сервере nodejs, но это же куча лишнего геморроя. 
Выходит, чтоб vk-io зафурычил нужно запиливать на сервере nodejs + express + настраивать роутер и вообще делать полноценный прокси. Неужели никак нельзя использовать либу с клиента? 
Стандартный JavaScript API vk используется от клиента, просто он неудобен запросами через script.src , значит по идее и все инструменты обёртки для работы с javascript API должны работать от клиента

**Comment by negezor** [comment]
Библиотека изначально предназначалась для работы на сервере, потому что где-то больше половины функционала зависит от Node.js модулей. Из-за CORS библиотека от ВКонтакте делает JSONP запросы. Так как использую node-fetch это аналог браузерного fetch возможно можно было бы портировать, но как отключать остальную функциональность остаётся загадкой.

**Comment by WebKieth** [comment]
А если сделать для клиента отдельный модуль, скажем, vk-io-client, сменить в нём node-fetch на fetch API и вырезать неподдерживаемый клиентом функционал?

**Comment by negezor** [comment]
В таком случае придётся поддерживать сразу 2 версии библиотеки.

**Comment by WebKieth** [comment]
Готов взять поддержку второй версии на себя =)
Окда, я покопаюсь в библиотеке и постараюсь реализовать задуманное

**Comment by negezor** [comment]
Я думаю в браузере можно сделать простую обёртку наподобие:
```js
api(method, params) {
  new Promise(() => {
    VK.Api.call(method, params, response => {
       if (!response) {
          return reject();
       }

       resolve(response);
     });
   })
}
```

**Comment by WebKieth** [comment]
Да, я склонировал, немного вник и понял что вырезать там можно почти всё, и писать клиентскую версию легче с нуля. 
Трудность будет в том, что vk после запроса к данным инициализирует функцию, которая находится не в глобальной области видимости, а во вложенных функциях компонентов, а соответственно будет undefined для внешнего script src, куда его не вставь. 
Вообщем буду думать как оформить клиент. Идея с промисами и fetch API понравилась
