### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by leuphoria** [negezor/vk-io#53]
Привет!

Юзаю авторизацию через логин/пароль, просит вводить капчу, хочу показать картинку пользователю и попросить ввести, но при запросе по url из payload.src (в captchaHandler) загружается новая капча и код со старой не подходит.

ЧЯДНТ?

**Comment by negezor** [comment]
Лично я делаю так, получаю капчу в base64 и отправляю пользователям.
```js
vk.setCaptchaHandler(async ({ src }, retry) => {
    const response = await fetch(src);
    const buffer = await response.buffer();

	const base64Captcha = `data:${response.headers.get('content-type')};base64,${buffer.toString('base64')}`;

	const key = await myAwesomeCaptchaHandler(base64Captcha);

	try {
		await retry(key);

		console.log('Капча успешно решена');
	} catch (error) {
		console.log('Капча неверная');
	}
});

```

**Comment by WampirenoK** [comment]
Я почему-то всё равно ошибку получаю: 
`AuthError: Incorrect captcha code
    at ImplicitFlowUser.run`

**Comment by negezor** [comment]
Неверный код с капчи?

**Comment by WampirenoK** [comment]
Верный, я капчу уже даже лупой разглядывал, чтобы ввести коректно.

**Comment by WampirenoK** [comment]
```javascript
fetch(payload.src)
      .then((response) => {
        response.buffer()
          .then(data => {
            console.log(payload.src)
            const src = `data:${response.headers.get('content-type')};base64,${data.toString('base64')}`
            message.info('Необходимо ввести капчу.', 5)
            this.setState(() => {
              return {
                hasCaptcha: true,
                retryCaptcha: retry,
                srcCaptcha: src,
                loading: false
              }
            })
          })
      })
```
Это React, если что.

**Comment by negezor** [comment]
Библиотека серверная.

**Comment by WampirenoK** [comment]
Как-то по другому можно это решить?

**Comment by negezor** [comment]
Авторизовываться на сервере, а на клиент уже просто посылать данные.

**Comment by WampirenoK** [comment]
Я это всё в [Electron](https://electronjs.org/) делаю, если знаете, что это, так вот там всё сервер.

**Comment by negezor** [comment]
Не всё так просто, должна использоваться именно Node.js оболочка.

**Comment by WampirenoK** [comment]
Попробую иной способ авторизации, надеюсь поможет, если что отпишусь.

**Comment by WampirenoK** [comment]
Переделал авторизацию на сервер, всё равно не могу пройти капчу( неверная капча исключена ).
Версия vk-io: 4.0.0-beta.3
Версия node.js: 9.3.0
Доп. библиотека: node-fetch

P.S. Извиняюсь, если надоел :D
```js
vk.setCaptchaHandler((payload, retry) => {
    fetch(payload.src)
      .then((response) => {
        response.buffer()
          .then((data) => {
            const src = `data:${response.headers.get('content-type')};base64,${data.toString('base64')}`
            // Далее отправляется клиенту
          })
      })
  })
```

**Comment by negezor** [comment]
Не могли бы вы записать то что приходит в HTML с авторизации, возможно они изменили вёрстку.

**Comment by WampirenoK** [comment]
Простите, не понял о чём вы.

**Comment by negezor** [comment]
Привести сам контент авторизации, HTML который приходит с ВК. А ещё желательно полный код авторизации.
