### ISSUE TITLE
APIError: Code №5 - User authorization failed: invalid access_token (4)

### ISSUE THREAD

**Issue by JekaSexy** [negezor/vk-io#533]
C:\ChatBot>node bot.js
APIError: Code №5 - User authorization failed: invalid access_token (4).
    at API.callMethod (C:\ChatBot\node_modules\vk-io\lib\index.js:1256:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 5,
  params: [
    { key: 'method', value: 'execute' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.80' },
    {
      key: 'code',
      value: 'return [API.groups.getLongPollServer({"group_id":"218197127"})];'
    }
  ]
}

Как исправить чтоб бот работал ровно? (Извините за тупость но можно по подробнее я начинающий и не совсем понимаю что куда)

**Comment by GirlDev1337** [comment]
Брат, у тебя токен неверный. В ошибке же указано, то есть тебе нужно получить токен и обновить его в скрипте.

**Comment by JekaSexy** [comment]
> Брат, у тебя токен неверный. В ошибке же указано, то есть тебе нужно получить токен и обновить его в скрипте.

Хорошо щас создам новый, но мне кажется причина не в этом, токен создан недавно)

**Comment by GirlDev1337** [comment]
Возможно, ты не там вставляешь его)
И, кстати, чисто рекомендация. Обнови версию Longpoll API до последней.

**Comment by JekaSexy** [comment]
Апи создал новый, но проблема та же, Longpoll API у меня версии 5.131 права выдал на всё
Сказать что проблема в боте НЕТ, потому что я брал многие другие скрипты ботов, и там такая же история, некоторые пишут что бот  запущен но бот ни на что не реагирует.

**Comment by JekaSexy** [comment]
[https://i.yapx.ru/Vvady.png](url)

**Comment by cot20** [comment]
> Апи создал новый, но проблема та же, Longpoll API у меня версии 5.131 права выдал на всё Сказать что проблема в боте НЕТ, потому что я брал многие другие скрипты ботов, и там такая же история, некоторые пишут что бот запущен но бот ни на что не реагирует.

А как именно у тебя происходит подключения бота)

**Comment by JekaSexy** [comment]
В отельную папку вводим токен и ID Сообщества, 

А так оно выглядит в скрипте бота 

const {VK, Keyboard} = require('vk-io');
const vk = new VK();
const {updates} = vk;
const fs = require("fs"); 
const users = require("./base/users.json");
const tokens = require("./base/tokens.json");

**Comment by cot20** [comment]
> 

Ну поздравляю тебя у тебя подключения не под ту версию модуля которая у тебя стоит

**Comment by JekaSexy** [comment]
> > 
> 
> Ну поздравляю тебя у тебя подключения не под ту версию модуля которая у тебя стоит

Можно пожалуйста по подробнее, как исправить эту проблему?

**Comment by cot20** [comment]
> > > 
> > 
> > 
> > Ну поздравляю тебя у тебя подключения не под ту версию модуля которая у тебя стоит
> 
> Можно пожалуйста по подробнее, как исправить эту проблему?

npm install vk-io@4.0.0-rc.8 — по идеи должно подходить

**Comment by negezor** [comment]
В представленном коде токен не передаётся в конструктор VK, должно быть так:
```ts
const vk = new VK({
    token: process.env.TOKEN
});
```
