### ISSUE TITLE
В объекте MessageContext отображаются не все вложения

### ISSUE THREAD

**Issue by fakemancat** [negezor/vk-io#536]
#### What did you do?
При получении сообщения от пользователя я хочу получить все вложения, которые он отправил.

```js
handler: async (context) => {
    console.log(context.attachments);
    console.log(context.getAllAttachments('photo'));
    return context.send('ok');
}
```

#### What did you expect to happen?
Ожидалось получения всех вложений, которые отправил пользователь

#### What was the actual result?
При отправке от 1 до 3 вложений всё хорошо, но при отправке свыше 4-х отображается только одно - первое

#### Additional Info
```js
context.loadMessagePayload()
```
пробовал, результат такой же

заметил такую беду с фото-вложениями, другие не пробовал

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.8.1` |
| `node`                             | `16.17.0` |
| `TypeScript`                       | `4.8.3` |
| `npm` or `yarn`                    | `1.22.19` |

**Comment by negezor** [comment]
У сообщения есть `context.isCropped`, новая фича ВКонтакте, не отправлять больше 5 вложений. По этому свойству можно орентироваться, чтобы перезагрузить полное сообщение, нужно вызвать так:
```ts
if (context.isCropped) {
  await context.loadMessagePayload({ force: true });
}
```

**Comment by fakemancat** [comment]
Помогло, спасибо
