### ISSUE TITLE
Long polling does not work without updates.use being called

### ISSUE THREAD

**Issue by ololoepepe** [negezor/vk-io#54]
**What version of vk-io are you using?**
4.0.0-beta.0

**What version of Node.js are you using?**
8.9.2

**What did you do?**
1. Initialized VK instance.
2. Called `.updates.hear('/test', () => console.log('yay!'))`.
3. Posted a message to group.

**What did you expect to happen?**
Expected `yay!` to be printed.

**What was the actual result?**
Nothing happened.

**What is wrong?**
`this.hears.run` is called only inside `.updates.use` method. That seems to be wrong, one may not need any middlewares.

When I used the `.updates.use` method, my callback was called.

**What is suggested?**
Make it possible to avoid calling `.updates.use` method.

**Comment by negezor** [comment]
[Fixed 4.0.0-beta.1](https://github.com/negezor/vk-io/commit/f9ea380557bd6a54e29843c570039145d9b0527a)

**Comment by ololoepepe** [comment]
Thanks for fast fix!
