### ISSUE TITLE
Attacments are not working properly

### ISSUE THREAD

**Issue by SHCDevelops** [negezor/vk-io#548]
#### What did you do?
I am connecting to my group using the code provided below and trying to retrieve document data (I want to clarify that if I test it with Postman, the data comes through successfully). However, I'm getting incorrect results from the code.

#### What did you expect to happen?
```
[
  DocumentAttachment <doc361652443_663282796> {
    id: 663282796,
    ownerId: 361652443,
    size: 3003494,
    accessKey: "BSZVDviZJzAj9vay927pMD3uka93GPr3Ph6rc1SfSpX",
    title: "images.zip",
    typeId: 2,
    createdAt: 1686878350,
    extension: "zip",
    url: "https://vk.com/doc361652443_663171634?hash=2AHAkz6cNAhCrPUHZSMIXtSjxxCwpRCWD4kLoc6n3Zw&dl=YRYXZ9rLO59aburEMXOSKZWIPzdb6Pf4Qrvkxt3ECsc&api=1&no_preview=1"
  }
]
```

#### What was the actual result?
```
[
  DocumentAttachment <doc361652443_663282796> {
    id: 663282796,
    ownerId: 361652443,
    accessKey: undefined,
    title: undefined,
    typeId: undefined,
    createdAt: undefined,
    extension: undefined,
    url: undefined
  }
]
```

#### Additional Info
Example code:
```
const vk = new VK({ token: process.env.TOKEN });

vk.updates.on('message_new', async (context) => {
  console.log(context.getAttachments('doc'));
});

vk.updates.startPolling().catch(console.error);
```

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.8.3` |
| `node`                             | `18.16.0` |

**Comment by SHCDevelops** [comment]
Проблема решена.

Не получал полные данные, из-за неправильно запуска.

Нужно изменить
`vk.updates.startPolling().catch(console.error);`
на
`vk.updates.start().catch(console.error);`

**Comment by RusAnonym** [comment]
Также хочу отметить что актуально только для групп, у пользователей ([User LongPoll](https://negezor.github.io/vk-io/ru/guide/updates.html#polling-user-long-poll)) события приходят обрезанными
