### ISSUE TITLE
Как отловить сообщение, которого нет в списке команд?

### ISSUE THREAD

**Issue by Verheim** [negezor/vk-io#55]
Есть код:
updates.hear(/^\/getid (.+)/i, async (context) => {

});

updates.hear(/^\/setid (.+)/i, async (context) => {

});

Как создать событие, когда текст в боте вообще не похож ни на одну команду? Чтобы ответом было что-то вроде "Такой команды нет". А то бот просто молчит.

**Comment by negezor** [comment]
Что то я не подумал насчёт fallback'а для hear и ставил его последним в цепочки middleware. К следующему обновлению думаю добавлю fallback для hear.

**Comment by negezor** [comment]
Добавлен метод в `setHearFallbackHandler()` [v4.0.0-beta.2](https://github.com/negezor/vk-io/commit/70b20fb14dd99c240caa9a3adff0ed64bf41f942)
