### ISSUE TITLE
packages/vk-io/src/structures/contexts/message-event.ts

### ISSUE THREAD

**Issue by Jhon-Mosk** [negezor/vk-io#553]
### Discussed in https://github.com/negezor/vk-io/discussions/552

<div type='discussions-op-text'>

<sup>Originally posted by **Jhon-Mosk** October  2, 2023</sup>
Предлагаю добавить в контекст message-event возможность редактировать сообщение и отвечать на него. Как в контексте message.

https://github.com/negezor/vk-io/blob/1604d196327d3c437c4bcb3a526cde7110aaa65f/packages/vk-io/src/structures/contexts/message.ts#L536

https://github.com/negezor/vk-io/blob/1604d196327d3c437c4bcb3a526cde7110aaa65f/packages/vk-io/src/structures/contexts/message.ts#L562</div>

**Comment by negezor** [comment]
Я уже думал реализовать метод `.send()`, однако для `.editMessage()` недостаточно информации в контексте, прикрепления будут теряться.

**Comment by negezor** [comment]
Реализовано https://github.com/negezor/vk-io/commit/e7f4f51f71ca1b646691b86a351f273728988890

**Comment by Jhon-Mosk** [comment]
> Я уже думал реализовать метод `.send()`, однако для `.editMessage()` недостаточно информации в контексте, прикрепления будут теряться.

Я у себя в боте сделал обработчик всех ошибок. И если прилетает MessageEventContext, то редактирую сообщение:

```
/**
   * для редактирования сообщения
   * @param {object} ctx - контекст события message_event
   * @param {string} message - текст сообщения
   * @param {object} [keyboard] - клавиатура
   * @returns {object} объект с результатом
   */
  editEventMessage = async (ctx, message, keyboard) => {
    const { peerId, conversationMessageId } = ctx;

    const params = {
      peer_id: peerId,
      conversation_message_id: conversationMessageId,
      message: message,
    };

    if (keyboard) {
      params.keyboard = keyboard;
    }

    try {
      const response = await this.#vk.api.messages.edit(params);

      if (response.error) {
        const { error_code, error_msg } = response.error;
        throw createError(400, `${error_code}: ${error_msg}`);
      }

      return response;
    } catch (error) {
      this.#logErr(error, "editEventMessage->", {
        responseMsg: `Не удалось отредактировать сообщение события message_event ${conversationMessageId}.`,
        requestMsg: `При попытке отредактировать сообщение события message_event ${conversationMessageId}, запрос был сделан, но ответ не был получен.`,
        paramsMsg: `Ошибка редактирования сообщения события message_event ${conversationMessageId}.`,
      });
    }
  };
```
