### ISSUE TITLE
текст в кнопке

### ISSUE THREAD

**Issue by Jhon-Mosk** [negezor/vk-io#555]
### Discussed in https://github.com/negezor/vk-io/discussions/554

<div type='discussions-op-text'>

<sup>Originally posted by **Jhon-Mosk** October  4, 2023</sup>
При длине лэйбла в кнопке более 40, сделать сокращение его до 40 символов с заменой последних трёх ... Вместо проброса ошибки https://github.com/negezor/vk-io/blob/1604d196327d3c437c4bcb3a526cde7110aaa65f/packages/vk-io/src/structures/keyboard/builder.ts#L72</div>

**Comment by mulfyx** [comment]
не входит в зону ответственности библиотеки, сделайте собственный хелпер, который будет этим промышлять

**Comment by Jhon-Mosk** [comment]
> не входит в зону ответственности библиотеки, сделайте собственный хелпер, который будет этим промышлять

в telegraf.js реализовано так и не нужно постоянно об этом помнить и писать хэлперы. По моему так удобнее.

**Comment by Jhon-Mosk** [comment]
библиотека же реализована для удобства разработки по мне моё предложение этим и является

**Comment by mulfyx** [comment]
> > не входит в зону ответственности библиотеки, сделайте собственный хелпер, который будет этим промышлять
> 
> в telegraf.js реализовано так и не нужно постоянно об этом помнить и писать хэлперы. По моему так удобнее.

телеграф говно, вопросы?

**Comment by mulfyx** [comment]
> библиотека же реализована для удобства разработки по мне моё предложение этим и является

а если мне нужна ошибка, а не чтоб текст обрезался?

**Comment by Jhon-Mosk** [comment]
> > > не входит в зону ответственности библиотеки, сделайте собственный хелпер, который будет этим промышлять
> > 
> > 
> > в telegraf.js реализовано так и не нужно постоянно об этом помнить и писать хэлперы. По моему так удобнее.
> 
> телеграф говно, вопросы?

А что тогда не говно?

**Comment by Jhon-Mosk** [comment]
> > библиотека же реализована для удобства разработки по мне моё предложение этим и является
> 
> а если мне нужна ошибка, а не чтоб текст обрезался?

А можете пример кейса привести?

**Comment by negezor** [comment]
Это плохая идея, как показывает практика, взгляните на то как он MySQL обрезал строки вместо ошибки и сколько данных из-за этого билось. Если в кнопке может быть больше 40 символов, это явно не то что нужно обрезать, вместо этого лучше быть более кратким или вынести описание в текст сообщения.

**Comment by Jhon-Mosk** [comment]
> Это плохая идея, как показывает практика, взгляните на то как он MySQL обрезал строки вместо ошибки и сколько данных из-за этого билось. Если в кнопке может быть больше 40 символов, это явно не то что нужно обрезать, вместо этого лучше быть более кратким или вынести описание в текст сообщения.

В моём кейсе название кнопок это названия сообществ.

Изначально вынес это в дискуссию, но там никто не реагирует. Поэтому создал ишью.
