### ISSUE TITLE
Как читать сообщения из группы ?

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#56]
Как с помощью данной библиотеки читать сообщения которые пишут в группу ?

**Comment by T1MOXA** [comment]
Нагуглил вот это.
https://vk.com/dev/bizmessages_doc
Я так понимаю мне нужно отдельного бота делать с отдельным токеном ?

**Comment by negezor** [comment]
Точно так же как и для пользователя. Если интересует возможность получать полный набор событий из сообщества, то можно указать в опциях параметр [pollingGroupId](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/vk.md#%D0%9E%D0%BF%D1%86%D0%B8%D0%B8-polling-long-poll).

**Comment by T1MOXA** [comment]
Для авторизации также нужна пара логин\пароль ?

**Comment by negezor** [comment]
Только токен сообщества.

**Comment by T1MOXA** [comment]
Я не совсем понимаю как это использовать.

```
const group = new VK();
group.setOptions({ token: 'токен' });
```
Что дальше нужно делать? 
По идеи нужно же отправить запрос на авторизацию...

Как для обычного пользователя, но я сомневаюсь в этом этапе.
`vk.auth.implicitFlowUser().run()`

Где уже делать запрос startPolling для получения обновлений

**Comment by negezor** [comment]
Имея токен авторизация не требуется. `implicitFlowUser` авторизация позволяющая получить токен пользователя из логина и пароля.
```js
const group = new VK();
group.setOptions({ token: 'токен' });

vk.updates.on('message', async (context, next) => {
  // ...
});

vk.updates.startPolling()
.then(() => console.log('Запущено'))
.catch(() => console.log('Не удалось'));
```

**Comment by T1MOXA** [comment]
Спасибо.
Вроде разобрался благодаря [этому](https://github.com/negezor/vk-io/blob/f03cb0900db5a89faba9d6a431e29da13ca57cb1/examples/simple-updates-bot.js) примеру

**Comment by T1MOXA** [comment]
Добрый вечер.
Столкнулся с такой проблемой:

Я почему-то не могу выполнить запрос groups.enableOnline с ключом группы.
Вот права которые есть у ключа:
{ permissions:
[ { setting: 4, name: 'photos' },
{ setting: 131072, name: 'docs' },
{ setting: 4096, name: 'messages' },
{ setting: 262144, name: 'manage' } ] }
(Получил через groups.getTokenPermissions)

При попытке выполнения получаю такую ошибку:
APIError: Code №15 - Access denied
params:
[ { key: 'oauth', value: '1' },
{ key: 'method', value: 'groups.enableOnline' },
{ key: 'v', value: '5.73' },
{ key: 'group_id', value: '85375411' } ]

Вопрос скорее не к вам а к поддержке вк, однако там отвечают несколько дней, и зная меню я мог спокойно где-то накосячить.

**Comment by negezor** [comment]
Я думаю нужно передать group_id в метод или использовать токен пользователя.

**Comment by T1MOXA** [comment]
@negezor в том то и дело что group_id указан как челое число что в общем и написано в документации, также там написано что можно использовать данный метод с ключом сообщества, по какой причине запрос не удается мне пока ре известно.

**Comment by negezor** [comment]
Ну видимо во ВКонтакте снова накосячили, а с токеном пользователя работает?

**Comment by T1MOXA** [comment]
Да, с ним все ок.
