### ISSUE TITLE
пуллинг групп

### ISSUE THREAD

**Issue by NoMoreNap** [negezor/vk-io#564]
столкнулся с проблемой при пуллинге группы, изменил деструктуризацию и все заработало
![1](https://github.com/negezor/vk-io/assets/114310364/822d63e4-7346-485e-8676-aaf69663db6f)
![2](https://github.com/negezor/vk-io/assets/114310364/716ff0fb-dc2f-4ce7-8dd4-f691ab7ca4d0)
![3](https://github.com/negezor/vk-io/assets/114310364/c79e7b96-4e70-4147-b437-0004839c8560)
![4](https://github.com/negezor/vk-io/assets/114310364/57b6f702-31df-4857-bac6-dc8a93750406)
![5](https://github.com/negezor/vk-io/assets/114310364/f298bc28-ff6b-4913-aa2a-cb0e0e9b6e93)

**Comment by negezor** [comment]
Указана вручную `apiVersion`?

**Comment by negezor** [comment]
Нужно убрать или поставить `5.199` или выше.
