### ISSUE TITLE
context.isEvent() == false, когда происходит событие

### ISSUE THREAD

**Issue by WampirenoK** [negezor/vk-io#57]
**What version of vk-io are you using?**
**4.0.0-beta.2**

**What version of Node.js are you using?**
**9.3.0**

**What did you do?**
1. Отлавливаю событие `message` в `updates.on()`.
2. Во время события вывожу в консоль `context.isEvent()`
3. Получаю `false`, когда срабатывает `chat_pin_message`

**What did you expect to happen?**
Вывод в консоли `true`

**What was the actual result?**
Выводит `false`

**Comment by WampirenoK** [comment]
```js
const action = context.getEventType()
  const chatId = context.getChatId()
  console.log('message', context.isEvent(), action, context.getEventText(), chatId)
  switch (action) {
    case 'chat_pin_message': {
      console.log('chat_pin_message', context.action_text)
      mongo.Group.findOneAndUpdate({ id: chatId }, { pinned_message: context.action_text }, () => {
        console.log('pinned')
      })
      break
    }
}
```

**Comment by WampirenoK** [comment]
Ещё заметил, когда отслеживается событие `message`, `updates.hear()` не ловят команды. Или так и должно и мне придётся самому парсить `context.text` на команды?

**Comment by negezor** [comment]
В 4.0.0-beta.3 исправил баг с отсутствием `context.isEvent()` (при обновлении Long Poll API не отредактировал один участок кода). А насчёт `updates.hear()` всё логично, так как используется цепочка middleware и если в обработчике `message` не вызвать `next()` цепочка не пойдёт дальше.

**Comment by WampirenoK** [comment]
Всё работает, спасибо.

**Comment by WampirenoK** [comment]
В каком случае `context.getText()` возвращает "Сообщение не поддерживается Вашим приложением."?

**Comment by negezor** [comment]
В `context.getText()` этого не может вернуться программно, это кто-то написал ну или бот.
А на какие события идёт подписка?

**Comment by WampirenoK** [comment]
`chat_pin_message`

**Comment by negezor** [comment]
Потому что это ВКонтакте и нужно самому запросить сообщение, вот что приходит. Там отсутствует идентификатор сообщения прикрепленного.
```js
vk-io:updates longpoll update [ 4,
  5597657,
  8227,
  2000000105,
  1521557499,
  'Сообщение не поддерживается Вашим приложением.',
  { source_act: 'chat_pin_message',
    source_mid: '195624402',
    source_chat_local_id: '6629',
    source_message: '',
    from: '195624402' },
{} ]
```
