### ISSUE TITLE
Нет возможности идетифицировать группу

### ISSUE THREAD

**Issue by StipJey** [negezor/vk-io#59]
Я обнаружил, хотя https://vk.com/dev/callback_api?f=2.%20Формат%20данных ВК отдает group_id в handleWebhookUpdate, он никуда не сохраняется и соответственно к нему не возможно получить доступ. Есть ли на текущий момент какой-то другой способ идентифицировать группу?

**What version of vk-io are you using?**
4.0.0-beta

**Comment by Markoffka** [comment]
@StipJey чем [этот](https://vk.com/dev/groups.getById) метод не подходит?

**Comment by negezor** [comment]
К следующему обновлению как раз хотел заняться этим.

**Comment by negezor** [comment]
В `4.0.0-beta.4` добавил возможность получить ID группы через `context.$groupId`.
