### ISSUE TITLE
English Documentation?

### ISSUE THREAD

**Issue by sidoshi** [negezor/vk-io#60]
I can see that a link to English documentation is added to the `docs/README.md`. So I assume there are plans to add English documentation. Can you share what is the status on that?

**Comment by doshisid** [comment]
So you plan on writing English documentation once the current (Russian) documentation is complete, is that correct?

I need to use this lib for work but can't start until I understand the docs. Let me know if I could provide any help ☺️.

**Comment by negezor** [comment]
Yes exactly. In the code, I left some comments. If you are interested in how to do something specifically I can tell.

**Comment by doshisid** [comment]
I will go through the code and let you know If I have any questions. Thank you :)

**Comment by negezor** [comment]
Hello! Any updates?

**Comment by negezor** [comment]
I'll close this issue, feel free to reopen 😄
