### ISSUE TITLE
StickerAttachment  не экстендит Attachment 

### ISSUE THREAD

**Issue by StipJey** [negezor/vk-io#61]
Я думаю что из-за того, что в файле https://github.com/negezor/vk-io/blob/master/src/structures/attachments/sticker.mjs
 class StickerAttachment  не экстендит Attachment возникае проблема ниже:

**What was the actual result?**
```
Error: TypeError: attachment.getType is not a function
at attachments.filter.attachment (/var/node/test/node_modules/vk-io/lib/structures/contexts/message.js:397:61)
at Array.filter (native)
at MessageContext.getAttachments (/var/node/test/node_modules/vk-io/lib/structures/contexts/message.js:397:29)
```

**What version of vk-io are you using?**
4.0.0-beta.4

**Comment by StipJey** [comment]
а так же gift, link и WallReplyAttachment

**Comment by negezor** [comment]
Оно не является стандартным прикреплением. По этому я не стал давать класс Attachment, сделаю ExternalAttachment.

**Comment by negezor** [comment]
[Исправлено](https://github.com/negezor/vk-io/commit/7221cde51bebb835a00ff2a99be75c59bab4d71a).
