### ISSUE TITLE
Как отловить события ?

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#62]
VK-IO - 4.0.0-beta.6

Как можно отловить события ?
Раньше работал этот код, но сейчас не работает.

```
vk.updates.on('message', async (message) => {
	if (message.isEvent()) console.log(`Event:\nType - ${message.getEventType()} | Text - ${message.getEventText()}`);
});
```

**Comment by negezor** [comment]
А можно конкретнее? Данные дебага например?

**Comment by T1MOXA** [comment]
Это я так полагаю сам эвент
```
MessageContext { vk: '<VK>',
type: 'message',
subTypes: [ 'new_message' ],
state: {},
payload:
 { id: 169049,
   date: 1525269784,
   body: '',
   flags: 8227,
   geo: null,
   random_id: null,
   out: 1,
   deleted: 0,
   read_state: 1,
   emoji: 0,
   important: 0,
   user_id: *****,
   chat_id: 2,
   title: undefined,
   attachments: [] },
from: { id: 2000000002, type: 'chat' },
text: null,
attachments: [],
filled: false }
```

Похоже я знаю в чем дело...
message.isEvent() возвращает false

Видимо у меня не обновилась либа.

**Comment by negezor** [comment]
В теле объекта нету action по этому всё верно в контексте. Поставь env DEBUG=vk-io:updates

**Comment by T1MOXA** [comment]
Я переустановил либу.
Теперь эвенты заработали, но проверка message.isEvent() все равно false

```
2018-05-02T14:58:57.445Z vk-io:updates longpoll update [ 80, 2, 0 ]
2018-05-02T14:58:57.445Z vk-io:updates Unsupported polling context type 80
2018-05-02T14:58:57.446Z vk-io:updates http -->
2018-05-02T14:58:58.181Z vk-io:updates http <-- 200
2018-05-02T14:58:58.181Z vk-io:updates longpoll update [ 8, -********, 7, 1525273137 ]
2018-05-02T14:58:58.182Z vk-io:updates http -->
2018-05-02T14:58:58.747Z vk-io:updates http <-- 200
2018-05-02T14:58:58.747Z vk-io:updates longpoll update [ 51, 2 ]
2018-05-02T14:58:58.747Z vk-io:updates Unsupported polling context type 51
2018-05-02T14:58:58.747Z vk-io:updates longpoll update [ 52, 6, 2000000002, ******** ]
2018-05-02T14:58:58.747Z vk-io:updates Unsupported polling context type 52
2018-05-02T14:58:58.747Z vk-io:updates longpoll update [ 6, 2000000002, 169080, 0 ]
2018-05-02T14:58:58.747Z vk-io:updates longpoll update [ 4,
  169082,
  8227,
  2000000002,
  1525273138,
  '',
  { source_act: 'chat_invite_user',
    source_mid: '********',
    from: '********' },
  {} ]

```

**Comment by negezor** [comment]
Не трудно было бы продебажить метод? 🤔

**Comment by T1MOXA** [comment]
Не совсем понял что вы имеете в виду.

**Comment by negezor** [comment]
В исходном коде поменять и проверить что возвращают методы в isEvent.

**Comment by T1MOXA** [comment]
Это ? 
```
isEvent() {
	return this.isChat() && Boolean(this.payload.action);
}
```
this.isChat() == true
А ключа payload.action не существует.
При добавлении пользователя и при кике не один объект context не содержал payload.action

**Comment by negezor** [comment]
Явно не в этом проблема, но это очень странно.

**Comment by T1MOXA** [comment]
Проверьте у себя, я чистых тестов не проводил, возможно проблема на моей стороне.

**Comment by negezor** [comment]
Протестировал на основные события и всё работает, скорее ошибка в неправильном использовании.
Я предполагаю что стоит проверка isOutbox раньше события.

**Comment by T1MOXA** [comment]
Вроде нет.
Я ж правильно понимаю что vk.updates.on('message', async (message, next) стоит в начале цепочки midleware ?
И только за тем идут vk.updates.hear

Есть кстати еще предположение что так как в on chat_kick_user и в on chat_invite_user
 я не добавил await и следующую цепочку midleware, как раз эвент кика и входа не отображаются в on message

**Comment by T1MOXA** [comment]
UPD, да, моё предположение оказалось верным.
После добавления await next() я смог отловить в on message эвенты кика и инвайта.
