### ISSUE TITLE
Problem with captcha handler

### ISSUE THREAD

**Issue by iron-cherep** [negezor/vk-io#63]
**What version of vk-io are you using?**
```
vk-io@^4.0.0-beta.6:
  version "4.0.0-beta.6"
  resolved "https://registry.yarnpkg.com/vk-io/-/vk-io-4.0.0-beta.6.tgz#bac0e013ce4ebb0b3f405ba340abc2132a41b489"
  dependencies:
    cheerio "^1.0.0-rc.2"
    debug "^3.1.0"
    middleware-io "^0.0.6"
    node-fetch "^2.1.2"
    sandwich-stream "^1.0.0"
    tough-cookie "^2.3.4"
    ws "^5.1.1"
```

**What version of Node.js are you using?**
v8.11.1

**What did you do?**
Пытаюсь добавить обработчик капчи. Т.к. приложение выполняется в консоли, для обработки капчи оно выдаёт в консоль url изображения и принимает (с помощью prompt) от пользователя строку для капчи.

```
vk.setCaptchaHandler(async ({ src }, retry) => {
  const key = await captchaHandler(src);

  try {
    await retry(key);
    console.log('Капча успешно решена');
  } catch (error) {
    console.log(error);
    console.log('Капча неверная');
  }
});

function captchaHandler(src) {
  console.log('Ввести текст капчи: ');
  console.log(src);
  prompt.start();

  return new Promise((resolve) => {
    prompt.get(['input'], (err, result) => {
      if (err) console.log(err);
      console.log('Введён текст: ' + result.input);

      resolve(result.input);
    });
  });
}
```

**What did you expect to happen?**
Авторизация и получение токена.

**What was the actual result?**
Каждый раз получаю ошибку:

```
{ AuthError: Incorrect captcha code
    at ImplicitFlowUser.run (/home/iron-cherep/PhpstormProjects/vk/node_modules/vk-io/lib/index.js:2583:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'FAILED_PASSED_CAPTCHA', name: 'AuthError' }
```

**Comment by negezor** [comment]
Мне удалось повторить такую ошибку только при неправильно вводимых данных. Я не знаю с чем это связанно. Возможно это очередные фичи ВКонтакте.

**Comment by Orland25565** [comment]
Получаю такие же ошибки, неверный код из капчи, при правильно введённом коде.
Тоже авторизация через Implict Flow User.

Проверку капчи я получаю при тестировании такого логина и пароля.
login: 'f'
password: 'f'
Я ожидаю увидеть ошибку о том что неверный логин или пароль, а не проверку капчи которая каждый раз будет возвращать что код не корректен.

Если использую свой аккаунт то проверки капчи не возникает.

`AuthorizationError: Incorrect captcha code at ImplicitFlowUser.processAuthForm (C:\Users\Larri Page\Documents\Projects\vkeclipse\node_modules\@vk-io\authorization\lib\index.js:706:41) at ImplicitFlowUser.run (C:\Users\Larri Page\Documents\Projects\vkeclipse\node_modules\@vk-io\authorization\lib\index.js:664:39) at async ImplicitFlowUser.run (C:\Users\Larri Page\Documents\Projects\vkeclipse\node_modules\@vk-io\authorization\lib\index.js:858:30) at async Object.asyncLogin (http://localhost:3000/static/js/main.chunk.js:1274:28) at async AppAuth.handleSubmitClick (http://localhost:3000/static/js/main.chunk.js:2341:9) {code: "FAILED_PASSED_CAPTCHA", name: "AuthorizationError", pageHtml: , stack: "AuthorizationError: Incorrect captcha code\n at …://localhost:3000/static/js/main.chunk.js:2341:9)", message: "Incorrect captcha code"}`
