### ISSUE TITLE
make class field for testing Webhook

### ISSUE THREAD

**Issue by shtyr-maxim** [negezor/vk-io#65]
![image](https://user-images.githubusercontent.com/35374061/41192727-d39bc434-6c0a-11e8-9ba6-00468e763f2c.png)
Работаю с вашей библиотекой и возникла такая проблема. Для тестирования приложения необходимо перенаправлять URL с vk на сервер приложения. А в данной интерпретации сделать это невозможно. Отсюда предложение, почему бы не вынести URL api.vk в class field и подавать его в конструктор, дабы в new URL не подавать константы, да и для тестирования приложений отличное решение подавать baseURL в конструкторе

**Comment by negezor** [comment]
Реализовал [baseUrl](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/api.md#baseurl), но требуется только `https`.
