### ISSUE TITLE
клавиатура

### ISSUE THREAD

**Issue by Bobrovskih** [negezor/vk-io#66]
Добрый день,
Поддерживает ли vk-io сейчас отправку клавиатуры в сообщениях?
Если нет - будет ли в будущем?

**Comment by negezor** [comment]
Уже работаю над этим 😅
![image](https://user-images.githubusercontent.com/9392723/41370866-822591c4-6f94-11e8-82dc-7ecf07896a29.png)

**Comment by Bobrovskih** [comment]
отлично!)

**Comment by negezor** [comment]
[Добавлено](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/buttons/keyboard.md)
