### ISSUE TITLE
access_key в прикреплениях

### ISSUE THREAD

**Issue by alienvspredator** [negezor/vk-io#70]
Здравствуйте. Для пересылки прикреплений из личных сообщений необходим, как я понимаю, `access_key`. Вопрос в следующем: должен ли метод `getAttachments` возвращать объект фото с ключом доступа? В данный момент ключ доступа в объекте отсутсвует. Если нет — то как ещё можно получить `access_key`?

> **nodejs**: 10.5.0
> **vk-io**: 4.0.0 beta 11

PS. Куда можно отправить пожертвование на развитие проекта?)

**Comment by negezor** [comment]
Достаточно просто, можно просто перезагрузить контекст сообщения до всех данных (если используется User Polling). А именно это делается так:
```js
vk.updates.on('message', async (context, next) => {
  await next();
});
```

**Comment by alienvspredator** [comment]
Спасибо )
