### ISSUE TITLE
"FetchError: network timeout" when using vk.upload.messageDocument

### ISSUE THREAD

**Issue by boqusi** [negezor/vk-io#90]
**What version of vk-io are you using?**
4.0.0-beta.12

**What version of Node.js are you using?**
v10.5.0

**What did you do?**
```js
const { VK } = require('vk-io')
const vk = new VK({ token: process.env.TOKEN })

vk.updates.hear('/pic', async context => {
  let attachment = await vk.upload.messageDocument({
    peer_id: context.from.id,
    source: {
      value: 'http://owo.sh/50d6b8.png',
      filename: 'Picture.png',
      contentType: 'image/png'
    }
  })

  context.send('Sample text', { attachment })
})

vk.updates.startPolling()
```
Start the bot and flood him with "/pic" messages

**What did you expect to happen?**
The bot replies to every "/pic" message without any errors

**What was the actual result?**
The bot replies to some messages, but some are left unanswered. After a few seconds this error pops out in the console:
```
Handle polling update error: { FetchError: network timeout at: https://pu.vk.com/c848420/upload.php?act=add_doc_new&mid=-xxxxxxxxx&aid=-1&gid=0&type=0&peer_id=xxxxxxxxx&rhash=a2e71e8dc768c24b6ff92a86c143558b&api=1&server=848420&_origin=https%3A%2F%2Fapi.vk.com&_sig=9ca7ac094563bf41724bd53c6bf3f034
    at Timeout.<anonymous> (C:\...\node_modules\node-fetch\lib\index.js:1386:13)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
  message:
   'network timeout at: https://pu.vk.com/c848420/upload.php?act=add_doc_new&mid=-xxxxxxxxx&aid=-1&gid=0&type=0&peer_id=xxxxxxxxx&rhash=a2e71e8dc768c24b6ff92a86c143558b&api=1&server=848420&_origin=https%3A%2F%2Fapi.vk.com&_sig=9ca7ac094563bf41724bd53c6bf3f034',
  type: 'request-timeout' }
```

This error doesn't seem to be related to my network. It happens both on my computer and on the host.
UPD: сейчас заметил, что можно было писать на русском, ну да ладно.

**Comment by negezor** [comment]
Нужно передать свойство timeout в опции загрузки, вот так:
```js
const { VK } = require('vk-io')
const vk = new VK({ token: process.env.TOKEN })

vk.updates.hear('/pic', async context => {
  let attachment = await vk.upload.messageDocument({
    peer_id: context.from.id,
    timeout: 60e3, // 60 sec
    source: {
      value: 'http://owo.sh/50d6b8.png',
      filename: 'Picture.png',
      contentType: 'image/png'
    }
  })

  context.send('Sample text', { attachment })
})

vk.updates.startPolling()
```
Или же передать глобальную опцию uploadTimeout в конструктор:
```js
vk.setOptions({
  uploadTimeout: 60e3
});
```
По умолчанию 20 секунд.

**Comment by boqusi** [comment]
Дело не в том, что таймаут короткий, а в том, что его вообще быть не должно, изображение маленькое же. Выставил я его в 60 секунд, теперь сообщение всё так же не отправляется, только ошибка не через 20, а через 60 секунд появляется. Как я уже писал, проблема не на моей стороне, на хосту так же.

**Comment by negezor** [comment]
Но это со стороны ВКонтакте отваливается timeout. Не знаю связанно это или нет, но:
![image](https://user-images.githubusercontent.com/9392723/42323948-86eb183a-80ad-11e8-97c2-6c098863f671.png)
https://vk.com/dev/health
