### ISSUE TITLE
DialogFlagsContext

### ISSUE THREAD

**Issue by Untartol** [negezor/vk-io#91]
Не могу разобраться, как инициализировать класс DialogFlagsContext и выполнить проверку, является ли диалог помеченным как "Важный" либо "Неотвеченный". Т.е. вызвать методы isImportant или isUnanswered

**Comment by negezor** [comment]
Это для бота группы?

**Comment by Untartol** [comment]
Да

**Comment by negezor** [comment]
Его можно получить только в User Long Poll API. Для группы не получится использовать pollingGroupId для Bots Long Poll API. Как возможное решение запустить 2 Long Poll. Один для отлова данного события (User Long Poll API) другой для основного потока данных (Bots Long Poll API) или Callback API.

**Comment by Untartol** [comment]
Жаль. Хотел отключить бота для диалогов, имеющих пометку "Важный"
