### ISSUE TITLE
Пересланные сообщения

### ISSUE THREAD

**Issue by mikechip** [negezor/vk-io#92]
Привет!

Когда я пытаюсь получить пересланные сообщения из контекста, он возвращает мне странные объекты, у которых from_id равен ID переславшего сообщения (не автора самого пересланного), и плюс пустой объект fwd_messages

Т.е. context.forwards и context.payload.fwd_messages возвращает:

`[ { from_id: (тут мой ID), fwd_messages: [] } ]`

Подскажите, что я делаю не так? Или это баг?

**Comment by negezor** [comment]
Насколько я понял используется Polling (именно User Long Poll API), так вот этот набор данных следует учитывать только как наличие пересланных сообщений. Что бы получить полный набор данных нужно перезагрузить сообщения с сервера с помощью метода [context.loadMessagePayload()](https://github.com/negezor/vk-io/blob/master/docs/ru/api-reference/contexts/message.md#loadmessagepayload)

**Comment by fakemancat** [comment]
Такая же проблема была, но тебе уже ответили)
Кстати, тоже самое будет и с Attachments. Поэтому я просто оставлю то, как у меня решено всё полностью:

```
vk.updates.on(['new_message'], async(context) => {
if (context.hasForwards || context.hasAttachments()) {
context.loadMessagePayload();
}
context.fwds = context.forwards;
context.attachs = context.attachments;

if (/^(айди)$/i.test(context.text)) {
context.send(`Айди того, чьё сообщение переслали: ${context.fwds[0].from_id}`);
}
else if (/^(аттачмент)$/i.test(context.text)) {
context.send(`Прикрепленные аттачменты: ${context.attachs[0]}`);
}
else return;
});
```
