### ISSUE TITLE
TypeError: context.isInbox is not a function

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#93]
После обновления библиотеки до версии v4.0.0-rc.0 появилась ошибка:
`Handle polling update error: TypeError: context.isInbox is not a function`

Код:
```
vk.updates.on('message', async(context, next) => {
	if (context.isInbox() && context.hasText()) //do something
});

```
NodeJS - v8.11.3

**Comment by T1MOXA** [comment]
Я даже кажется знаю в чем проблема.
В директории node_modules/vk-io/lib находится всего 2 файла index.js и index.mjs хотя по идеи должно быть больше.

Как и в https://registry.npmjs.org/vk-io/-/vk-io-4.0.0-rc.0.tgz
Интересно, почему так...

**Comment by T1MOXA** [comment]
Кажется я нашел ответ.
https://github.com/negezor/vk-io/commit/05e0e5ef979a6047730c6e73895fdb526800b21b#diff-058fbe47579fd7f2b16e17261492702c

**Comment by T1MOXA** [comment]
Было бы не плохо писать о подобных изменениях в доках или в ридми.

**Comment by T1MOXA** [comment]
Еще косяк после обновления.
В группе context.conversationMessageId возвращает undefined

**Comment by negezor** [comment]
Хотел в релизной ветки ввести changelog,
