### ISSUE TITLE
Как мне отправить клавиатуру пользователю без текста?

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#94]
Раньше вроде работало `context.send({ keyboard: Keyboard.keyboard([]) });`
Может ошибаюсь и это никогда не работало, но было бы удобно если бы можно было использовать подобную конструкцию, когда ты не хочешь отправлять сообщение а лишь обновить клавиатуру.

В данный момент подобное использование приводит к ошибке `message is empty or invalid`

**Comment by negezor** [comment]
Это ограничение со стороны ВКонтакте, можно попробовать отправлять пустой символ. Если мне не изменяет память у Telegram точно так же.

**Comment by T1MOXA** [comment]
Что за пустой символ ?

**Comment by negezor** [comment]
https://pastebin.com/raw/0LqRL7ex

**Comment by T1MOXA** [comment]
Спасибо.

Кстати, вопрос не по теме.
Заметил что вк почему-то стал подгружать превью ссылки при отправке сообщения от бота.
раньше я подобного не замечал.
Можно ли это отключить ?

**Comment by negezor** [comment]
Думаю не получится, так как это уже отрабатывается на серверах ВКонтакте.

**Comment by T1MOXA** [comment]
Это они такую новую фичу добавили в API, что у ботов теперь ссылки автоматом подгружаются ?
Спрошу у них в поддержке, а то для моего бота это сильно мешает...
