### ISSUE TITLE
Можно ли как то отловить удаление сообщений ? 

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#96]
Появилась нужда в отлавливании удаленных сообщений, но пока не знаю как это можно реализовать.

**Comment by negezor** [comment]
Вроде как нельзя, если в edit_message не приходит то тогда нельзя.

**Comment by T1MOXA** [comment]
Спасибо.
Это в событии message ?

**Comment by negezor** [comment]
Из событий `message` это тип, а `edit_message` это подтип.
