### ISSUE TITLE
Как получить ID бота при авторизации при помощи токена.

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#98]
Решил перейти на авторизацию по токену но столкнулся с проблемой.
Так как теперь при авторизации нет ответа с объектом в котором лежит ID возникает вопрос как же его все таки получить.

**Comment by T1MOXA** [comment]
Пока вижу для себя 2 варианта.
Изначально знать ID и указать его в коде или конфиге.
Выполнить запрос users.get к API при запуске бота и он вернёт ID, имя и фамилию бота.

**Comment by negezor** [comment]
Именно так это и делается.

**Comment by T1MOXA** [comment]
Спасибо.

**Comment by alienvspredator** [comment]
`groups.getById` без параметров для ботов группы
