### ISSUE TITLE
Есть ли пример выполнения wall.post с добавлением фотографии?

### ISSUE THREAD

**Issue by Jengas** [negezor/vk-io#99]
Я уже две недели пытаюсь найти нормальную билбиотеку, которая даст возможность нормально загрузить фотографию в ВК и прикрепить к посту. Сейчас присмотрел данную билбиотеку, а вот примера использования wall.post с фотографией нигде нету

**Comment by negezor** [comment]
Всё достаточно просто :)
```js
async function run() {
	const attachments = await vk.upload.wallPhoto({
		source: <источник> // примеры в examples/upload.js
	});

	const post = await vk.api.wall.post({ attachments });

	// Несколько прикриплений

	const attachments = await Promise.all([
		vk.upload.wallPhoto({
			source: <источник> // примеры в examples/upload.js
		}),
		'photo-1_456264771' // указание вручную
	]);

	const post = await vk.api.wall.post({ attachments });
}
```

**Comment by Jengas** [comment]
Спасибо! Мне также нужно постить картинки в группу. А вот фотографии загружаются с owner_id моей страницей а не страницей группы. Есть решение на мою проблему?
